invertebrate(butterflies).
animal(insects).
geopoliticallocation(home).
stateorprovince(states).
beverage(breastmilk).
animal(baby).
country(bahamas).
city(nassau).
event(result).
agent(ideas).
disease(heart_attacks).
food(junk_food).
city(zurich).
city(hallenstadion).
sportsequipment(apparel).
sport(hunting).
country(argentina).
sport(rugby).
governmentorganization(division).
governmentorganization(office).
country(the_united_states).
sport(ski).
country(holland).
sport(ski).
sportsequipment(racquet).
sport(badminton).
country(japan).
sport(aikido).
sportsteamposition(offensive_guard).
sport(football).
sportsequipment(field).
sport(golf).
sportsequipment(wood).
sport(golf).
sportsequipment(protective_gear).
sport(sports).
sportsequipment(jersey).
sport(soccer).
country(switzerland).
sport(snowboard).
stadiumoreventvenue(united_center).
sport(basketball).
sportsequipment(soccer_accessories).
sport(soccer).
writer(rosamunde_pilcher).
book(the_shell_seekers).
stadiumoreventvenue(fedex_forum).
stadiumoreventvenue(basketball).
stadiumoreventvenue(conseco_fieldhouse).
stadiumoreventvenue(basketball).
stadiumoreventvenue(thomas___mack_center).
stadiumoreventvenue(basketball).
writer(dan_brown).
writer(angels_and_demons).
writer(dan_brown).
book(angels_and_demons).
writer(dan_brown).
book(angels_and_demons).
writer(dan_brown).
writer(da_vinci_code).
writer(tolkien).
writer(the_hobbit).
stadiumoreventvenue(shea_stadium).
sport(baseball).
writer(shakespeare).
book(macbeth).
writer(rushdie).
book(satanic_verses).
sportsequipment(clubs).
sport(hockey).
writer(adolf_hitler).
book(mein_kampf).
person(adolf_hitler).
person(mein_kampf).
writer(h_g__wells).
book(time_machine).
stadiumoreventvenue(oriole_park).
sport(baseball).
writer(shakespeare).
book(romeo_and_juliet).
writer(tolkien).
book(silmarillion).
writer(tolkien).
book(silmarillion).
university(uc_berkeley).
university(computer_science).
university(mit).
academicfield(computer_science).
university(mit).
academicfield(computer_science).
university(auburn_university).
academicfield(engineering).
academicfield(finance).
academicfield(business).
university(institute).
academicfield(accounting).
academicfield(accounting).
academicfield(actuarial_science).
university(institute).
academicfield(applied_mathematics).
academicfield(engineering).
academicfield(applied_science).
academicfield(japanese).
academicfield(linguistics).
university(institute).
academicfield(computer_science).
university(institute).
academicfield(computer_science).
academicfield(marine).
academicfield(biology).
university(mccormick_theological_seminary).
academicfield(divinity).
writer(j_d__salinger).
book(the_catcher_in_the_rye).
writer(sinclair_lewis).
book(babbitt).
writer(h__g__wells).
book(the_war_of_the_worlds).
writer(h_g__wells).
book(the_war_of_the_worlds).
writer(ray_bradbury).
writer(fahrenheit_451).
writer(ray_bradbury).
writer(dandelion_wine).
writer(ray_bradbury).
book(martian_chronicles).
sportsteamposition(hitter).
sport(baseball).
university(institute).
academicfield(architecture).
university(harvard_university_graduate_school_of_design).
academicfield(architecture).
university(cornell_university).
academicfield(architecture).
city(toronto).
language(english).
city(toronto).
language(english).
university(uc_berkeley).
university(engineering).
university(emory_university).
academicfield(law).
country(iran).
language(persian).
writer(j_k_rowling).
book(harry_potter_books).
writer(j_k__rowling).
book(harry_potter_books).
city(pittsburgh).
language(english).
city(pittsburgh).
language(english).
country(uk__ireland).
language(english).
university(emory_university).
language(english).
writer(john_cheever).
book(the_wapshot_chronicles).
writer(tim_lahaye_and_jerry_jenkins).
book(left_behind).
writer(tim_lahaye).
book(left_behind).
writer(mervyn_peake).
book(gormenghast).
writer(vikram_seth).
book(a_suitable_boy).
writer(jl_carr).
book(a_month_in_the_country).
writer(truman_capote).
book(breakfast_at_tiffany_s).
writer(c__j__cherryh).
book(cyteen).
writer(kazuo_ishiguro).
book(remains_of_the_day).
university(dartmouth).
language(english).
university(iowa_state_university).
language(english).
university(victoria_university_of_wellington).
language(english).
university(university_of_florida).
language(english).
university(university_of_florida).
language(english).
university(ohio_university).
language(english).
university(catholic_university).
language(english).
university(carnegie_mellon).
language(english).
university(washington_university).
language(english).
university(indiana_university).
language(english).
university(middlebury).
language(english).
university(university_of_washington).
language(english).
university(loyola_university).
language(english).
city(st__petersburg).
language(russian).
city(freiburg).
language(german_language).
city(regensburg).
language(german_language).
city(adelaide).
city(english_language).
city(vancouver).
language(english_language).
city(vancouver).
language(english_language).
city(dallas).
language(spanish).
city(miami).
language(spanish).
city(boston).
language(english_language).
country(panama).
language(spanish).
city(orlando).
language(spanish).
country(chile).
language(spanish).
country(chile).
language(spanish).
country(indonesia).
language(malay).
city(barcelona).
language(spanish).
country(uruguay).
language(spanish).
country(guatemala).
language(spanish).
disease(asthma).
disease(anxiety).
disease(memory_problems).
emotion(depression).
disease(disorders).
emotion(symptoms).
disease(disorders).
emotion(abuse).
disease(chronic_fatigue).
emotion(depression).
disease(chronic_fatigue).
emotion(depression).
country(portugal).
language(portuguese).
country(brazil).
language(portuguese).
disease(medications).
emotion(depression).
disease(anxiety_disorders).
emotion(anxiety).
city(cairo).
city(arabic).
emotion(love).
emotion(flowers).
emotion(love).
emotion(flowers).
emotion(love).
emotion(orchids).
emotion(love).
emotion(pansies).
emotion(love).
emotion(roses).
emotion(love).
emotion(roses).
emotion(love).
emotion(roses).
plant(coconut_trees).
plant(trees).
disease(disorder).
emotion(phobia).
disease(disorder).
emotion(phobia).
sportsteam(pittsburgh_steelers).
sportsgame(championship).
emotion(beauty).
plant(flowers).
disease(arthritis).
emotion(pain).
disease(disorder).
emotion(clinical_depression).
plant(tree).
plant(foliage).
emotion(purity).
plant(flowers).
emotion(purity).
plant(flowers).
disease(disorder).
emotion(panic_attacks).
plant(carnations).
plant(flowers).
emotion(grace).
plant(gift).
plant(blueberries).
plant(plants).
plant(blueberries).
plant(plants).
sportsteam(houston_astros).
sportsgame(series).
emotion(romance).
plant(roses).
sportsteam(italy).
sportsgame(world_cup).
plant(elderberry).
plant(bushes).
physiologicalcondition(infections).
bacteria(staphylococcus).
sportsteam(pittsburgh_steelers).
sportsgame(playoffs).
emotion(appreciation).
plant(home).
plant(palm).
plant(trees).
plant(hydrangeas).
plant(plants).
sportsteam(houston_rockets).
sportsgame(playoffs).
sportsteam(eagles).
sportsgame(playoffs).
sportsteam(phoenix_suns).
sportsgame(playoffs).
sportsteam(bulls).
sportsgame(playoffs).
sportsteam(yankees).
sportsgame(series).
disease(endocarditis).
disease(s_).
nonneginteger(35).
sportsgame(n2006_sugar_bowl).
disease(ageing).
emotion(fear).
disease(aids).
emotion(fear).
disease(cancer).
emotion(fear).
physiologicalcondition(infection).
bacteria(streptococcus).
physiologicalcondition(infection).
bacteria(streptococcus).
country(australia).
language(english_language).
country(australia).
language(english_language).
stadiumoreventvenue(wembley_stadium).
sport(soccer).
plant(hydrangeas).
plant(flowers).
country(germany).
language(german).
dateliteral(n2008).
sportsgame(world_cup).
dateliteral(n2008).
sportsgame(world_cup).
country(azerbaijan).
language(azerbaijani).
university(stanford).
language(english).
stadiumoreventvenue(new_yankee_stadium).
sport(baseball).
academicfield(engineering).
academicfield(m_s).
writer(george_orwell).
book(animal_farm).
university(long_island_university).
language(english).
writer(nick_hornby).
book(about_a_boy).
writer(nick_hornby).
book(about_a_boy).
academicfield(ecology).
academicfield(biology).
url('//en.wikipedia.org/wiki/Legend%20of%20Mana').
videogame(legend_of_mana).
geopoliticallocation(countries).
country(tonga).
sportsteam(brazil).
sportsgame(world_cup).
sportsteam(france).
sportsgame(world_cup).
sportsteam(croatia).
sportsgame(world_cup).
personus(christopher_paolini).
book(eragon).
writer(paolini).
book(eragon).
sportsequipment(skate).
sport(hockey).
country(brasil).
country(portuguese).
currency(pounds).
currency(united_kingdom).
currency(pounds).
country(united_kingdom).
sport(baseball).
sportsgame(n2000_world_series).
writer(fyodor_dostoevsky).
book(brothers_karamazov).
university(north_carolina_state_university).
language(english).
academicfield(computer_science).
academicfield(electrical_and_computer_engineering).
arthropod(spiders).
arthropod(tarantulas).
food(plants).
invertebrate(larvae).
food(plants).
invertebrate(larvae).
arthropod(spiders).
arthropod(brown_recluse).
arthropod(shellfish).
arthropod(shrimp).
insect(moths).
arthropod(butterflies).
arthropod(seafood).
arthropod(shrimp).
arthropod(brown_recluse_spider).
arthropod(recluse).
animal(invertebrates).
animal(grubs).
arthropod(seafood).
arthropod(lobsters).
arthropod(seafood).
arthropod(scallops).
insect(beetles).
animal(creatures).
arthropod(brown_recluse).
arthropod(recluse_spiders).
arthropod(seafood).
arthropod(lobster).
food(foods).
animal(birds).
animal(animals).
animal(ocelots).
insect(ticks).
animal(parasites).
insect(mosquitoes).
animal(parasites).
invertebrate(widow_spider).
animal(brown_widow).
arachnid(black_widow_spiders).
arachnid(poisonous_arachnids).
arachnid(spiders).
arachnid(black_widow_spiders).
arachnid(black_widow_spiders).
arachnid(spiders).
vegetable(meal).
vegetable(horses).
vegetable(meal).
vegetable(livestock).
agriculturalproduct(horses).
agriculturalproduct(livestock).
agriculturalproduct(poultry).
agriculturalproduct(livestock).
food(dinner).
animal(cows).
food(dinner).
animal(cows).
food(hay).
animal(cows).
food(chocolate).
animal(dogs).
disease(epilepsy).
animal(cats).
disease(acne).
disease(cats).
disease(seizures).
animal(cats).
food(yogurt).
animal(dogs).
disease(allergic_reactions).
animal(cats).
disease(allergy).
mammal(dogs).
disease(breast_feeding).
animal(cats).
disease(alzheimers).
animal(cats).
disease(alzheimers).
animal(cats).
disease(rabies).
animal(wild_animals).
animal(wild_animals).
animal(bats).
animal(rodents).
animal(rabbits).
animal(creatures).
animal(monkeys).
animal(carnivores).
animal(bears).
animal(large_animals).
animal(cattle).
food(horseradish_sauce).
fish(salmon).
insect(silverfish).
animal(pests).
fish(salmon).
animal(endangered_species).
animal(creatures).
amphibian(frogs).
animal(predators).
amphibian(frogs).
disease(problems).
animal(pet).
food(rice_pilaf).
fish(trout).
food(sauce).
fish(tuna).
food(sauce).
fish(trout).
invertebrate(oysters).
animal(filter_feeders).
disease(mumps).
animal(child).
disease(scabies).
animal(child).
invertebrate(worms).
animal(pests).
disease(disability).
animal(child).
city(hpv).
zoo(child).
food(larvae).
amphibian(frogs).
food(french_bread).
fish(salmon).
everypromotedthing(bison).
everypromotedthing(herds).
chemical(chemicals).
chemical(heavy_metals).
chemical(fossil_fuels).
chemical(natural_gas).
chemical(natural_resources).
chemical(gas).
chemical(gas).
chemical(oxygen).
chemical(compound).
chemical(oxygen).
chemical(gas).
chemical(radon).
chemical(pollutants).
chemical(cadmium).
chemical(compound).
chemical(dioxide).
chemical(gas).
chemical(argon).
chemical(gas).
chemical(argon).
chemical(gas).
chemical(nitrogen).
disease(cancer).
disease(cats).
disease(cancer).
disease(rabbits).
food(sauce).
fish(linguine).
animal(marine_animals).
animal(seals).
everypromotedthing(gorillas).
everypromotedthing(great_apes).
food(sauce).
fish(mahimahi).
chemical(emissions).
chemical(mercury).
chemical(fuels).
chemical(petroleum).
country(great_britain).
country(ireland).
sportsteam(germany).
sportsgame(tournament).
sportsteam(brazil).
sportsgame(tournament).
stateorprovince(california).
city(hayward).
river(east).
city(manhattan).
country(romania).
city(bucharest).
country(canada).
city(winnipeg).
country(canada).
city(winnipeg).
stateorprovince(colorado).
city(gunnison).
currency(dollars).
country(bahamas).
city(salt_lake).
stateorprovince(utah).
city(salt_lake).
stateorprovince(utah).
currency(dollars).
country(canada).
currency(dollars).
country(canada).
currency(dollars).
country(canada).
city(montgomery).
stateorprovince(alabama).
city(bucharest).
stateorprovince(romania).
city(bucharest).
stateorprovince(romania).
city(philly).
city(philadelphia).
currency(dollar).
country(jamaica).
city(omaha).
stateorprovince(ne).
city(omaha).
stateorprovince(ne).
currency(dollars).
country(kuwait).
city(seattle).
stateorprovince(wa).
currency(dollars).
country(taiwan).
geopoliticallocation(canada).
stateorprovince(britishcolumbia).
stateorprovince(texas).
city(galveston).
country(japan).
city(tokyo).
stateorprovince(illinois).
city(hinsdale).
stateorprovince(florida).
city(key_biscayne).
country(japan).
city(hiroshima).
country(japan).
city(hiroshima).
city(edmonton).
stateorprovince(alberta).
country(libya).
city(tripoli).
country(libya).
city(tripoli).
geopoliticallocation(europe).
country(portugal).
currency(dollars).
country(liberia).
stateorprovince(california).
city(santa_ana).
country(burma).
city(rangoon).
stateorprovince(california).
city(glendale).
country(syria).
city(damascus).
country(argentina).
country(bahia_blanca).
country(brazil).
country(rio).
country(algeria).
country(algiers).
country(algeria).
country(algiers).
city(bombay).
city(mumbai).
city(mumbai).
city(bombay).
stateorprovince(andhra_pradesh).
stateorprovince(hyderabad).
stateorprovince(andhra_pradesh).
city(hyderabad).
stateorprovince(maharashtra).
stateorprovince(mumbai).
country(eritrea).
country(ethiopia).
country(ethiopia).
country(eritrea).
country(ethiopia).
country(kenya).
country(ethiopia).
country(djibouti).
currency(kuna).
currency(croatia).
currency(lev).
currency(bulgaria).
currency(birr).
currency(ethiopia).
currency(sucre).
currency(ecuador).
currency(kroon).
currency(estonia).
currency(euro).
currency(andorra).
currency(euro).
currency(montenegro).
currency(euros).
currency(france).
currency(euros).
currency(greece).
river(nile).
city(cairo).
country(argentina).
country(puerto_iguazu).
stateorprovince(illinois).
city(north_chicago).
city(l_a_).
city(los_angeles).
country(kenya).
city(nairobi).
country(tajikistan).
country(afghanistan).
country(tajikistan).
country(tadjikistan).
country(afghanistan).
country(tajikistan).
city(belfast).
stateorprovince(northern_ireland).
country(peru).
city(lima).
river(limmat).
city(zurich).
currency(francs).
country(switzerland).
currency(francs).
country(switzerland).
country(switzerland).
country(montreux).
country(switzerland).
country(montreux).
city(aarau).
stateorprovince(aargau).
country(switzerland).
stateorprovince(aargau).
country(venezuela).
city(caracas).
river(mississippi).
city(little_falls).
stateorprovince(california).
city(lake_tahoe).
stateorprovince(colorado).
city(colorado_city).
continent(europe).
continent(austria).
stateorprovince(california).
city(calabasas).
country(bangladesh).
city(dacca).
stateorprovince(countries).
country(brasil).
geopoliticallocation(germany).
stateorprovince(niedersachsen).
country(united_state).
stateorprovince(texas).
stateorprovince(indiana).
city(fishers).
stateorprovince(colorado).
city(montrose).
country(germany).
city(jena).
geopoliticallocation(u_s_a).
stateorprovince(illinois).
river(mohawk).
city(new_york_city).
currency(pounds).
currency(scotland).
stateorprovince(texas).
city(flower_mound).
city(abu_dhabi).
stateorprovince(united_arab_emirates).
river(mississippi).
city(new_orleans).
politicsissue(liberalism).
politicsgroup(democratic_party).
politicsissue(gun_control).
politicsgroup(national_rifle_association).
awardtrophytournament(australian_open).
athlete(kim_clijsters).
movie(fight_club).
movie(david_fincher).
movie(matrix).
movie(keanu_reeves).
movie(die_hard).
movie(john_mctiernan).
movie(die_hard).
movie(john_mctiernan).
person(child).
female(mother).
musicinstrument(guitar).
musician(elvis_presley).
musicinstrument(guitar).
musician(elvis_presley).
politicianus(president_bush).
politicianus(john_mccain).
jobposition(queen).
person(cleopatra).
visualartform(exhibits).
visualartist(warhol).
movie(magnolia).
movie(tom_cruise).
movie(magnolia).
movie(paul_thomas_anderson).
movie(jerry_maguire).
personus(tom_cruise).
movie(jerry_maguire).
personus(tom_cruise).
movie(mission_impossible).
personus(tom_cruise).
movie(mission_impossible).
personus(tom_cruise).
movie(minority_report).
personus(tom_cruise).
movie(minority_report).
personus(tom_cruise).
movie(risky_business).
personus(tom_cruise).
movie(rush_hour).
personasia(jackie_chan).
movie(rush_hour_2).
personasia(jackie_chan).
celebrity(john_denver).
celebrity(artists).
person(son).
female(mother).
person(lord).
female(mother).
musicartist(cult).
musician(ian_astbury).
person(jesus_christ).
person(mary).
movie(seven_samurai).
director(akira_kurosawa).
movie(rashomon).
director(akira_kurosawa).
visualartmovement(italian_renaissance).
visualartist(leonardo_da_vinci).
visualartmovement(italian_renaissance).
visualartist(leonardo_da_vinci).
politicsgroup(senate).
politicianus(tom_daschle).
jobposition(emperor).
person(constantine).
movie(maverick).
actor(mel_gibson).
person(jesus_christ).
female(mary).
male(sean_penn).
person(madona).
male(sean_penn).
person(madona).
person(jesus_christ).
person(blessed_virgin_mary).
movie(crash).
director(paul_haggis).
company(federal_express).
company(frederick_smith).
movie(dracula).
male(bela_lugosi).
visualartmovement(expressionism).
visualartist(vincent_van_gogh).
celebrity(elvis_presley).
celebrity(artists).
movie(doctor_zhivago).
movie(david_lean).
jobposition(foreign_minister).
person(frank_walter_steinmeier).
profession(services).
profession(research).
profession(professionals).
profession(orthopedic_surgeons).
profession(doctors).
profession(specialists).
geometricshape(cubes).
agriculturalproduct(cucumbers).
drug(caffeine).
beverage(coffee).
chemical(antioxidants).
agriculturalproduct(coffee).
chemical(calcium).
agriculturalproduct(yogurt).
country(comoros).
agriculturalproduct(vanilla).
agriculturalproduct(milk).
agriculturalproduct(cream).
mammal(cows).
meat(beef).
drug(cholesterol).
meat(beef).
country(kenya).
agriculturalproduct(tea).
disease(skin_cancer).
food(green_tea).
agriculturalproduct(sugarcane).
agriculturalproduct(crops).
stateorprovince(florida).
vegetable(tomato).
agriculturalproduct(onions).
agriculturalproduct(beans).
agriculturalproduct(sugar_cane).
agriculturalproduct(crops).
chemical(antioxidant).
agriculturalproduct(tea).
beverage(juice).
beverage(mango_juice).
stateorprovince(mauritius).
agriculturalproduct(sugar).
stateorprovince(new_mexico).
vegetable(spinach).
agriculturalproduct(potatoes).
agriculturalproduct(leek).
geometricshape(squares).
geometricshape(onions).
room(smoking_room).
room(beds).
room(bunk_bed).
furniture(beds).
room(porch).
furniture(beds).
room(apartment).
furniture(beds).
disease(asthma).
disease(serevent).
beverage(juice).
bakedgood(bagels).
beverage(coffee).
bakedgood(bagels).
product(computers).
product(apple_macintosh).
beverage(coffee).
bakedgood(breakfast).
beverage(tea).
bakedgood(breakfast).
beverage(tea).
bakedgood(biscuit).
beverage(cream).
bakedgood(cakes).
beverage(cream).
bakedgood(honey).
beverage(cream).
bakedgood(honey).
buildingmaterial(vinyl).
buildingfeature(doors).
beverage(chocolate).
bakedgood(pie).
beverage(chocolate).
bakedgood(pie).
stateorprovince(north_dakota).
vegetable(bean).
beverage(coffee).
bakedgood(marmalade).
disease(alzheimer).
food(antioxidants).
beverage(coffee).
bakedgood(bun).
beverage(coffee).
bakedgood(bun).
beverage(banana).
bakedgood(bread).
physiologicalcondition(sleeping).
drug(ambien).
beverage(coffee).
bakedgood(fresh_fruit).
disease(diabetes).
food(sugars).
beverage(butter).
bakedgood(toast).
beverage(tea).
bakedgood(sandwich).
buildingmaterial(cement).
buildingfeature(wall).
beverage(tea).
bakedgood(sandwiches).
beverage(tea).
bakedgood(sandwiches).
beverage(juice).
beverage(cilantro).
beverage(coffee).
bakedgood(fruits).
buildingmaterial(veneers).
buildingfeature(veneered_doors).
room(living_room).
furniture(home_bar).
humanagent(bristol_myers_squibb).
drug(metformin).
item(applications).
product(microsoft_windows).
beverage(yoghurt).
bakedgood(bread).
physiologicalcondition(pain).
drug(medications).
buildingmaterial(steel).
buildingfeature(cabinet).
buildingmaterial(vinyl).
buildingfeature(windows).
room(villa).
item(beds).
room(living_room).
furniture(bookcase).
humanagent(glaxosmithkline).
drug(paxil).
beverage(red_wine).
bakedgood(bread).
beverage(coffee).
bakedgood(goodies).
beverage(coffee).
bakedgood(goodies).
buildingmaterial(screen).
buildingfeature(door).
room(studio_rooms).
furniture(beds).
room(dorm_room).
furniture(beds).
beverage(white_chocolate).
bakedgood(cookies).
beverage(cream).
bakedgood(preserves).
protein(enzyme).
protein(breast_milk).
chemical(acids).
chemical(tea).
stateorprovince(andhra_pradesh).
stateorprovince(tobacco).
protein(fatty_acid).
beverage(milk).
vertebrate(cattle).
agriculturalproduct(dairy_products).
beverage(cream).
bakedgood(raspberries).
beverage(beverages).
beverage(cookies).
chemical(chemicals).
agriculturalproduct(tea).
stateorprovince(texas).
vegetable(onion).
plant(palmtrees).
clothing(skirts).
clothing(jackets).
clothing(shirts).
clothing(shirt).
clothing(hoodie).
clothing(shirt).
clothing(sleeve).
clothing(jeans).
clothing(leather_jacket).
clothing(cotton_shirts).
clothing(shorts).
room(private_bathroom).
bathroomitem(hairdryer).
room(bathroom).
bathroomitem(hairdryer).
room(bath).
item(spa_tub).
room(smoking_room).
room(bed).
room(living_room).
furniture(accent_chair).
url('//en.wikipedia.org/wiki/World%20clock').
wallitem(world_clock).
clothing(shirt).
clothing(black_suit).
clothing(shirt).
clothing(black_suit).
room(bedroom).
furniture(headboard).
room(living_room).
furniture(ottoman).
room(living_room).
furniture(sectional_sofa).
room(property).
furniture(bed).
clothing(polo_shirts).
clothing(pants).
clothing(pants).
clothing(polo_shirts).
clothing(pants).
clothing(sport_coat).
clothing(pants).
clothing(jersey).
clothing(pants).
clothing(jersey).
clothing(long_skirt).
clothing(top).
clothing(shorts).
clothing(jersey).
clothing(shoes).
clothing(shorts).
room(bathroom).
item(shower).
room(adjacent_bathroom).
item(shower).
room(one_bathroom).
item(shower).
room(one_bathroom).
item(shower).
room(bathrooms).
item(shower).
room(large_bathrooms).
item(shower).
url('//en.wikipedia.org/wiki/Enemy%20Engaged%202').
software(enemy_engaged_2).
disease(diabetes).
food(blood_sugar).
room(luxury_bathroom).
item(shower).
agriculturalproduct(sorghum).
agriculturalproduct(plants).
agriculturalproduct(chicken).
agriculturalproduct(seasonings).
agriculturalproduct(parsley).
agriculturalproduct(fresh_herbs).
agriculturalproduct(parsley).
agriculturalproduct(herbs).
disease(cancer).
food(natural).
country(nepal).
agriculturalproduct(silk).
clothing(pants).
clothing(sweaters).
clothing(linen_pants).
clothing(shirt).
clothing(bermuda_shorts).
clothing(shirt).
clothing(shirts).
clothing(golf_shirts).
clothing(shirts).
clothing(long_sleeves).
clothing(tops).
clothing(dresses).
clothing(tops).
clothing(dresses).
clothing(shirts).
clothing(sweat_shirts).
country(u_s).
weapon(bombs).
female(pakistan).
person(bombs).
agriculturalproduct(onions).
agriculturalproduct(potato_soup).
clothing(shorts).
clothing(red_shirt).
country(iran).
weapon(nuclear_bombs).
agriculturalproduct(oat).
agriculturalproduct(products).
agriculturalproduct(salt).
agriculturalproduct(products).
agriculturalproduct(barley).
agriculturalproduct(products).
agriculturalproduct(cocoa).
agriculturalproduct(products).
agriculturalproduct(citrus_fruits).
agriculturalproduct(products).
food(margarine).
food(products).
country(brazil).
weapon(bows).
clothing(pants).
clothing(sweat_shirt).
room(master_bath).
item(shower).
city(memphis).
person(martin_luther_king_jr__).
insect(honey_bees).
grain(alfalfa).
grain(alfalfa).
grain(crops).
protein(proteins).
protein(breast_milk).
protein(proteins).
protein(dairy_foods).
protein(proteins).
beverage(beer).
movie(star_wars).
movie(mark_hamill).
url('//en.wikipedia.org/wiki/2001%20British%20Grand%20Prix').
grandprix(n2001_british_grand_prix).
movie(the_prestige).
director(christopher_nolan).
movie(borat).
actor(sacha_baron_cohen).
company(microsoft).
ceo(steven_ballmer).
celebrity(angelina_jolie).
celebrity(film_stars).
male(esau).
female(basemath).
url('//en.wikipedia.org/wiki/Basemath').
female(basemath).
physiologicalcondition(genital_herpes).
drug(valtrex).
chemical(amino_acid).
agriculturalproduct(tea_leaves).
stateorprovince(kansas).
vegetable(corn).
vertebrate(farms).
agriculturalproduct(milk).
company(pfizer).
ceo(hank_mckinnell).
musicinstrument(piano).
musicinstrument(franz_liszt).
politicianus(clinton).
politicianus(gore).
politicsgroup(senate).
politicianus(harry_reid).
politicianus(clinton).
politicianus(joe_biden).
musicinstrument(guitar).
musician(bono).
musicartist(u2).
musician(bono).
musicartist(u2).
musicartist(bono).
politicaloffice(senator).
politician(kennedy).
politicianus(cheney).
politicianus(w___bush).
politicianus(clinton).
politicianus(presidential_candidate_barack_obama).
stateorprovince(california).
person(monica).
geopoliticallocation(california).
person(arnold_schwarzenegger).
governmentorganization(supreme_court).
governmentorganization(antonin_scalia).
politicaloffice(president).
politician(barak_obama).
politicaloffice(senator).
politician(barak_obama).
profession(senators).
politician(barak_obama).
geopoliticallocation(countries).
country(egypt).
movie(jaws).
personafrica(steven_spielberg).
movie(jurassic_park).
personafrica(steven_spielberg).
country(india).
city(new_dehli).
movie(goodfellas).
movie(martin_scorsese).
movie(goodfellas).
movie(martin_scorscese).
movie(goodfellas).
movie(joe_pesci).
movie(goodfellas).
movie(ray_liotta).
movie(pulp_fiction).
movie(quentin_tarantino).
movie(pulp_fiction).
movie(john_travolta).
city(chicago).
skyscraper(sears_tower).
city(chicago).
building(sears_tower).
city(chicago).
building(sears_tower).
city(rome).
attraction(circus_maximus).
city(toronto).
hotel(quality_suites).
city(seattle).
newspaper(the_stranger).
city(seattle).
newspaper(the_stranger).
stateorprovince(california).
mountain(mount_whitney).
stateorprovince(california).
mountain(castro_peak).
city(vancouver).
aquarium(vancouver_aquarium).
religion(catholicism).
placeofworship(westminster_abbey).
city(dallas).
aquarium(dallas_aquarium).
city(istanbul).
city(istanbul_airport).
city(montreal).
transportation(metro_system).
city(vancouver).
hospital(the_vancouver_clinic).
city(vancouver).
hospital(the_vancouver_clinic).
city(chicago).
hotel(omni_chicago_hotel).
city(atlanta).
hotel(georgia_tech_hotel_and_conference_center).
religion(buddhism).
placeofworship(zen_mountain_monastery).
religion(buddhism).
placeofworship(zen_mountain_monastery).
stateorprovince(california).
mountain(calico_mountains).
city(rome).
attraction(colosseum).
city(rome).
attraction(colosseum).
city(toronto).
museum(toronto_s_historic_museums).
city(toronto).
zoo(toronto_zoo).
city(toronto).
hospital(toronto_general).
stateorprovince(california).
lake(lake_tahoe).
stateorprovince(california).
lake(lake_tahoe).
stateorprovince(california).
lake(lake_tahoe).
stateorprovince(california).
mountain(death_valley).
city(portland).
aquarium(gulf_of_maine_research_institute).
stateorprovince(hawaii).
mountain(mauna_kea).
city(vancouver).
hospital(vancouver_general_hospital).
religion(judaism).
placeofworship(the_hurva_synagogue).
city(miami).
building(miami_international_airport).
city(memphis).
stadiumoreventvenue(fedex_forum).
religion(baptist).
placeofworship(east_ham_baptist_church).
organization(sea).
organization(seal).
city(mumbai).
city(mumbai_airport).
religion(hinduism).
placeofworship(muktinath).
religion(hinduism).
placeofworship(banteay_srei).
url('//en.wikipedia.org/wiki/Lindstrom%20Peak').
everypromotedthing(lindstrom_peak).
city(london).
park(south_kensington).
city(cairo).
city(cairo_international_airport).
stateorprovince(colorado).
mountain(capitol_peak).
city(london).
park(covent_garden).
stateorprovince(maryland).
lake(deep_creek_lake).
city(london).
newspaper(evening_standard).
city(los_angeles).
hotel(courtyard_by_marriott_lax).
religion(presbyterianism).
placeofworship(sleepy_hollow_presbyterian_church).
url('//en.wikipedia.org/wiki/Boswell%20Bay%20Airport').
everypromotedthing(boswell_bay_airport).
stateorprovince(hawaii).
mountain(kilauea_volcano).
city(toronto).
newspaper(toronto_star).
religion(islam).
placeofworship(the_great_mosque_of_taza).
religion(islam).
religion(the_great_mosque_of_taza).
city(pittsburgh).
building(three_rivers_stadium).
city(toronto).
airport(lester_b__pearson_international_airport).
city(baltimore).
airport(bwi).
stateorprovince(nepal).
mountain(everest).
everypromotedthing(board).
everypromotedthing(executive_officers).
city(memphis).
city(memphis_international).
city(memphis).
city(memphis_international).
city(miami).
airport(miami_international_airport).
city(bristol).
airport(bristol_airport).
city(london).
park(greenwich).
city(austin).
museum(austin_children_museum).
city(new_york_city).
hotel(hotel_57).
url('//en.wikipedia.org/wiki/Hollywood%20Wax%20Museum').
museum(hollywood_wax_museum).
city(los_angeles).
museum(hollywood_wax_museum).
city(detroit).
stadiumoreventvenue(ford_field).
city(new_york_city).
transportation(airtrain_light_rail).
city(new_york_city).
hotel(the_lombardy).
city(new_york_city).
museum(bethesda_fountain).
city(seattle).
attraction(kingdome).
city(houston).
hospital(m_d__anderson).
city(cleveland).
city(quicken_loans_arena).
city(cleveland).
city(quicken_loans_arena).
religion(buddhism).
placeofworship(san_francisco_zen_center).
organization(warner_music).
person(edgar_bronfman_jr_).
grain(alfalfa).
grain(legumes).
agriculturalproduct(milk).
agriculturalproduct(beverages).
beverage(juice).
beverage(grapefruit_juice).
item(systems).
product(android).
organization(cnn).
person(jeff_greenfield).
company(yahoo_local).
company(google).
sport(tennis).
athlete(john_mcenroe).
athlete(john_mcenroe).
athlete(ivan_lendl).
awardtrophytournament(us_open).
athlete(john_mcenroe).
stadiumoreventvenue(soldier_field).
sportsleague(nfl).
stateorprovince(arkansas).
politicianus(bill_clinton).
sport(cricket).
athlete(sachin_tendulkar).
musicgenre(pop).
musicartist(jewel).
musicgenre(rock).
musicartist(roy_orbison).
school(oxford).
writer(tolkien).
musicgenre(rock).
musicartist(lou_reed).
musicgenre(pop).
musicartist(ricky_martin).
musicgenre(pop).
musicartist(wham).
musicinstrument(piano).
musicinstrument(bach).
musicinstrument(piano).
musicinstrument(beethoven).
musicinstrument(piano).
musician(beethoven).
musicinstrument(piano).
musicinstrument(emerson_lake_palmer).
politicaloffice(speaker).
politicianus(nancy_pelosi).
sportsleague(national_basketball_association).
sportsleague(nba).
sport(tennis).
sport(anna_kournikova).
sport(tennis).
athlete(dinara_safina).
sport(tennis).
athlete(lleyton_hewitt).
awardtrophytournament(us_open).
athlete(lleyton_hewitt).
sport(tennis).
athlete(marat_safin).
awardtrophytournament(australian_open).
athlete(marat_safin).
person(shem).
person(noah).
actor(clint_eastwood).
actor(western_movie_actors).
politicianus(dick_cheney).
politicianus(bush).
politicsgroup(senate).
politicianus(bob_dole).
sportsleague(nba).
sportsleague(doc_rivers).
movie(vacation).
actor(chevy_chase).
politicaloffice(presidents).
politicianus(clinton).
musicgenre(black_metal).
musicartist(immortal).
politicianus(clinton).
politicianus(sen___barack_obama).
musicgenre(hard_rock).
musicartist(alice_cooper).
politicianus(michael_moore).
politicianus(clinton).
politicianus(jimmy_carter).
politicianus(clinton).
athlete(williams).
athlete(svetlana_kuznetsova).
musicgenre(pop).
musicartist(kylie).
sport(golf).
athlete(annika_sorenstam).
stadiumoreventvenue(camden_yards).
sportsleague(mlb).
sport(golf).
athlete(john_daly).
politicianus(bush).
politicianus(cheney).
politicianus(clinton).
politicianus(lieberman).
sport(tennis).
athlete(tommy_haas).
city(atlanta).
politician(andrew_young).
mlsoftware(mallet).
mlauthor(andrew_mccallum).
musicinstrument(violin).
musicinstrument(itzhak_perlman).
musicinstrument(violin).
musicinstrument(joshua_bell).
politicaloffice(president).
politician(president_chirac).
country(brazil).
country(leonardo_boff).
musicinstrument(guitar).
musician(james_hetfield).
stadiumoreventvenue(fedex_forum).
stadiumoreventvenue(nba).
organization(microsoft).
person(balmer).
stadiumoreventvenue(conseco_fieldhouse).
stadiumoreventvenue(nba).
stadiumoreventvenue(thomas___mack_center).
stadiumoreventvenue(nba).
sport(golf).
athlete(phil_mickelson).
musicartist(cream).
musician(jack_bruce).
sport(nascar).
sport(adam_petty).
hobby(car_racing).
athlete(ryan_newman).
stadiumoreventvenue(bristol_motor_speedway).
sportsleague(nascar).
stadiumoreventvenue(bowman_gray_stadium).
sportsleague(nascar).
stadiumoreventvenue(auto_club_speedway).
sportsleague(nascar).
hobby(car_racing).
athlete(carl_edwards).
sportsleague(nfl).
sportsteam(san_francisco_49ers).
city(newark).
politician(cory_booker).
musicgenre(blues).
musicartist(elvis).
musicgenre(blues).
musicartist(elvis).
politicaloffice(senator).
politician(governor_mitt_romney).
governmentorganization(supreme_court).
governmentorganization(john_g___roberts).
musicartist(u2).
musicartist(the_edge).
musicinstrument(guitar).
musician(b_b__king).
musicartist(pussycat_dolls).
musician(nicole_scherzinger).
sport(triathlon).
sport(mark_allen).
year(n1956).
person(david_selden).
geopoliticallocation(mexico).
person(goffredo_marcaccini).
city(miami).
sportsteam(miami_heat).
sportsleague(nba).
sportsteam(sixers).
sportsleague(nba).
sportsteam(dallas_mavericks).
city(denver).
sportsteam(broncos).
city(denver).
sportsteam(broncos).
city(denver).
sportsteam(broncos).
city(dallas).
sportsteam(dallas_mavericks).
stadiumoreventvenue(conseco_fieldhouse).
stadiumoreventvenue(indiana_pacers).
stadiumoreventvenue(camp_nou).
stadiumoreventvenue(fc_barcelona).
city(houston).
sportsteam(astros).
sport(games).
sportsteam(sooners).
sport(boxing).
athlete(george_foreman).
sport(boxing).
athlete(george_foreman).
sport(boxing).
athlete(george_foreman).
sport(boxing).
athlete(george_foreman).
sportsleague(nfl).
athlete(kurt_warner).
stadiumoreventvenue(busch_stadium).
sportsteam(st___louis_cardinals).
writer(e_b__white).
book(charlotte_s_web).
sportsleague(nfl).
sportsteam(pittsburgh_steelers).
sportsteam(minnesota_vikings).
sportsteam(pittsburgh_steelers).
city(cleveland).
sportsteam(indians).
company(sysco_corp).
company(sysco).
city(seattle).
televisionstation(kiro).
economicsector(energy).
company(british_gas).
economicsector(energy).
company(exxonmobil).
economicsector(telecom).
company(china_mobile).
automobilemodel(jeep_wrangler_unlimited).
automobilemaker(jeep).
automobilemodel(jeep_grand_cherokee).
automobilemaker(jeep).
automobilemodel(tundra).
automobilemaker(toyota).
automobilemodel(camry).
automobilemaker(toyota).
product(corolla).
company(toyota).
product(camry).
company(toyota).
automobilemodel(camry_hybrid).
automobilemaker(toyota).
product(toyota_matrix).
company(toyota).
country(japan).
automobilemaker(toyota).
product(bonneville).
company(pontiac).
product(insight).
company(honda).
product(insight).
company(honda).
automobilemodel(fit).
automobilemaker(honda).
automobilemodel(fit).
automobilemaker(honda).
automobilemodel(honda_civic).
automobilemaker(honda).
automobilemodel(honda_civic).
automobilemaker(honda).
automobilemodel(navigator).
automobilemaker(lincoln).
economicsector(auto).
company(audi).
stateorprovince(missouri).
automobilemaker(kia).
economicsector(oil).
company(british_petroleum).
product(element).
company(honda).
automobilemodel(eos).
automobilemodel(volkswagen).
automobilemodel(eos).
automobilemodel(volkswagen).
city(london).
automobilemaker(peugeot).
automobilemodel(odyssey).
automobilemaker(honda).
product(xbox).
company(microsoft).
product(xbox).
company(microsoft).
televisionnetwork(fox).
televisionstation(kcit).
economicsector(insurance).
company(geico).
city(denver).
televisionstation(kcnc).
product(microsoft_excel).
company(microsoft).
product(microsoft_excel).
company(microsoft).
automobilemodel(prelude).
automobilemaker(honda).
country(australia).
bank(citibank).
economicsector(automobile).
company(honda).
economicsector(energy).
company(shell).
automobilemodel(pilot).
automobilemodel(honda).
automobilemodel(pilot).
automobilemodel(honda).
room(bathroom).
item(toilette).
politicaloffice(committee).
politicaloffice(board).
everypromotedthing(eiffel_tower).
everypromotedthing(great_pyramid_of_giza).
event(injury).
agent(impact).
economicsector(oil).
company(citgo).
room(bathrooms).
item(bath_tub).
everypromotedthing(apple_computer).
everypromotedthing(mac).
everypromotedthing(learning).
everypromotedthing(vice).
url('//en.wikipedia.org/wiki/Super%20Ninja%20Boy').
everypromotedthing(super_ninja_boy).
company(at_t).
company(att).
politicaloffice(board).
politicaloffice(committee).
organization(national_science_foundation).
organization(nsf).
room(kitchen).
item(fridge).
room(kitchenette).
item(fridge).
organization(national_security_council).
organization(nsc).
disease(cancer).
food(fibre).
organization(postal_service).
organization(usps).
organization(congressional_budget_office).
organization(cbo).
everypromotedthing(board).
everypromotedthing(management_team).
organization(farm_credit_administration).
organization(fca).
room(bath).
item(tub).
room(home).
item(tub).
room(home).
item(tub).
room(ensuite_bathroom).
item(tub).
room(full_bath).
item(tub).
room(private_bath).
item(tub).
monument(washington_monument).
monument(eiffel_tower).
event(injury).
agent(evidence).
creativework(adventures_of_tom_sawyer).
agent(mark_twain).
creativework(adventures_of_huckleberry_finn).
agent(mark_twain).
organization(food_and_drug_administration).
organization(fda).
everypromotedthing(ministry).
everypromotedthing(department).
disease(cancer).
food(laxative).
everypromotedthing(air).
everypromotedthing(point).
everypromotedthing(ohio).
everypromotedthing(cleveland).
everypromotedthing(chicago).
everypromotedthing(windy_city).
event(part).
agent(changes).
mammal(marsupials).
mammal(kangaroo).
university(princeton_university).
person(michelle).
room(modern_kitchen).
item(oven).
creativework(a_tale_of_two_cities).
agent(charles_dickens).
creativework(pride_and_prejudice).
agent(jane_austen).
everypromotedthing(apple_computer).
everypromotedthing(macintosh).
company(advanced_micro_devices).
company(amd).
sportsteam(indians).
sportsteam(florida_marlins).
automobilemodel(edge).
automobilemaker(ford).
product(explorer).
company(microsoft).
product(explorer).
company(microsoft).
televisionnetwork(fox).
televisionstation(wlov).
everypromotedthing(bolivia).
everypromotedthing(la_paz).
city(chicago).
radiostation(wfmt).
url('//en.wikipedia.org/wiki/Arkalyk').
everypromotedthing(arkalyk).
url('//en.wikipedia.org/wiki/MapReduce').
recordlabel(mapreduce).
city(new_york_city).
company(air_jamaica).
city(new_york_city).
company(verizon).
sportsteamposition(running_back).
athlete(warrick_dunn).
company(honda).
company(nissan).
female(basemath).
female(esau).
country(singapore).
bank(hsbc).
stadiumoreventvenue(invesco_field_at_mile_high).
sportsleague(nfl).
country(egypt).
person(king_ptolemy).
politicaloffice(president).
politicianus(president_obama).
musicgenre(rock).
musicartist(gentle_giant).
movie(pulp_fiction).
movie(jackson).
movie(the_godfather).
movie(mario_puzo).
jobposition(king).
person(william_the_conqueror).
disease(adhd_).
color(red).
religion(jehovah__s_witnesses).
musicfestival(south_by_southwest_music_festival).
currency(dollar_currency).
buildingmaterial(ceramic_tile).
buildingmaterial(ceramic_tile).
televisionshow(blackadder).
televisionshow(blackadder).
televisionshow(blackadder).
televisionshow(blackadder).
televisionshow(blackadder).
mountain(half_dome).
currency(renminbi).
militaryeventtype(terrorists_attacks).
movie(nell).
movie(nell).
academicfield(business_administration___economics).
movie(movie_home_alone_2).
musicsong(god_bless_america).
musicsong(god_bless_america).
awardtrophytournament(bosnian_women_s_cup).
economicsector(cache_advertising).
magazine(womans_health_magazine).
bedroomitem(road_radio).
personasia(zhang_chong).
personasia(zhang_chong).
musicfestival(glastonbury_festival).
candy(hershey_milk_chocolate_with_almonds_nuggets).
videogame(theft_auto_3).
hospital(jenkins_county_hospital).
militaryconflict(korean_war_era).
musicartist(thousand_foot_krutch).
sportsequipment(soccer_ball).
movie(movie_matrix).
movie(movie_matrix).
crustacean(cherry_striped_porcelain_crab).
recipe(vegetarian_pasta_sauce_recipe).
year(n1689).
dateliteral(august_1939).
automobilemaker(cadillac).
kitchenitem(small_plastic_bottle).
date(n25_may).
physicalaction(tugging).
book(les_miserables).
profession(hospital_administrators).
school(waterville_police__state_university).
clothing(wool_stockings).
insect(long_tailed_mealy_bug).
recipe(easy_shrimp_pasta_recipe).
physicalaction(continuous_grasping).
movie(movie_shrek).
movie(tron).
movie(tron).
movie(tron).
videogame(final_fantasy_ix).
buildingmaterial(iron).
buildingmaterial(iron).
city(athens).
movie(movie_shrek_1).
monument(national_mall).
visualartform(art_painting).
musicartist(fred_hammond).
tool(pliers).
vehicle(cadillac_cars).
currency(dollars).
currency(dollars).
currency(dollars).
currency(dollars).
book(jude_the_obscure).
book(brave_new_world).
book(brave_new_world).
book(brave_new_world).
book(brave_new_world).
book(brave_new_world).
book(brave_new_world).
book(brave_new_world).
book(the_adventures_of_huckleberry_finn).
book(the_brothers_karamazov).
book(the_brothers_karamazov).
book(animal_farm).
book(animal_farm).
book(emma).
book(nineteen_eighty_four).
book(tess_of_the_d_urbervilles).
book(dune).
book(dune).
book(a_farewell_to_arms).
book(a_farewell_to_arms).
book(the_davinci_code).
book(the_davinci_code).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(alice_in_wonderland).
book(catch_22).
book(artemis_fowl).
book(harry_potter_and_the_goblet_of_fire).
book(harry_potter_and_the_goblet_of_fire).
book(harry_potter_and_the_goblet_of_fire).
movie(movie_die_hard_2).
movie(matrix).
movie(matrix).
movie(matrix).
movie(matrix).
movie(matrix).
movie(matrix).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(aliens).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(big_lebowski).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(fight_club).
movie(movie___you_only_live_once).
movie(movie_2012).
movie(movie_pirates_of_the_caribbean__dead_man_s_chest).
movie(godzilla).
movie(godzilla).
movie(godzilla).
movie(movie_harry_potter_and_the_prisoner_of_azkaban).
movie(beowulf).
movie(beowulf).
movie(beowulf).
movie(beowulf).
movie(beowulf).
movie(beowulf).
movie(beowulf).
visualartform(acrylic_painting).
visualartform(art_nude_photography).
visualartform(art_nude_photography).
visualartform(art_nude_photography).
militaryeventtype(bombardments).
weatherphenomenon(air).
weatherphenomenon(heatwaves).
eventoutcome(successful_execution).
sportsgame(world_cup).
sportsevent(n1995_world_championships_in_athletics).
geometricshape(isosceles).
economicsector(sea_advertising).
date(oct_7).
date(aug__7).
date(february_2003).
date(march_18).
date(april_4th).
buildingmaterial(brass).
buildingmaterial(brass).
religion(umbanda).
chemical(sodium_orthosilicate).
chemical(argon).
chemical(argon).
chemical(argon).
chemical(germanium_tetrafluoride).
chemical(acetone).
chemical(acetone).
chemical(acetone).
chemical(acetone).
chemical(acetone).
chemical(carbon_dioxide).
currency(gbp).
currency(gbp).
currency(pesetas).
currency(pesetas).
currency(euros).
currency(euros).
currency(euros).
emotion(acceptance).
emotion(acceptance).
emotion(acceptance).
emotion(acceptance).
emotion(acceptance).
emotion(love).
emotion(love).
emotion(love).
emotion(love).
emotion(love).
emotion(love).
emotion(love).
emotion(love).
emotion(anger).
emotion(anger).
emotion(anger).
emotion(anger).
emotion(anger).
physicalaction(mail_post_cards).
academicfield(religious_studies).
academicfield(life_sciences).
academicfield(life_sciences).
academicfield(cognitive_science).
academicfield(cognitive_science).
academicfield(digital_forensics).
fungus(micromycetes).
plant(pines).
celltype(blood_cells__the_mononuclear_cells).
celltype(wall_cells).
profession(septic_tank_servicers_and_sewer_pipe_cleaners).
physicalcharacteristic(greatness).
musicgenre(punk_rock).
musicgenre(british_rock).
charactertrait(frankness).
charactertrait(frankness).
charactertrait(courage).
charactertrait(courage).
charactertrait(courage).
charactertrait(courage).
charactertrait(courage).
charactertrait(kindness).
cognitiveactions(thinking_about_you_thinking_about_me).
cognitiveactions(critical_thinking_skills).
videogame(shenmue).
videogame(killzone).
videogame(left_4_dead).
videogame(gran_turismo).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
videogame(call_of_duty).
boardgame(power_grid).
monument(arc_de_triomphe).
restaurant(seymour_restaurant).
restaurant(hidalgos_restaurant).
hotel(omni_hotels).
hotel(disney_s_all_star_sports_resort).
city(brasilia).
city(brasilia).
city(bydgoszcz).
city(lorient).
city(belgrade).
city(klagenfurt).
city(klagenfurt).
city(klagenfurt).
city(klagenfurt).
city(klagenfurt).
city(klagenfurt).
city(maringa).
musicartist(matthew_good_band).
musicartist(newsboys).
musicartist(descendents).
musicartist(switchfoot).
musicartist(abba).
musicartist(abba).
musicartist(darkness).
musicartist(dead_kennedys).
musicartist(sex_pistols).
musicartist(the_beautiful_girls).
recordlabel(heron_recordings).
university(amirkabir_university_of_technology).
university(tehran_university).
university(sharif_university_of_technology).
ceo(hiroshi_okuda).
mlauthor(maria_m__klawe).
chef(jeff_garvin).
musician(iceland_symphony_orchestra).
musician(johnny_rotten).
bodypart(stomach_lining).
tool(drilling_machines).
clothing(salsa_shoes).
clothing(flirtyshoes).
clothing(outdoor_shoes).
clothing(keen_outdoor_shoes).
clothing(pjs).
sportsequipment(glove).
sportsequipment(birth_certificate).
sportsequipment(balls).
sportsequipment(skis).
software(ghc).
product(commodore_amiga).
product(nokia_6680i).
product(adobe_reader).
product(microsoft_excel).
candy(chewing_gum).
condiment(chipotle_pepper_sauce).
condiment(victory_berry_sauce).
condiment(buffalo_sauce).
vegetable(pobtatoes).
bakedgood(chocolate_raspberry_muffins).
scientist(gilbert_stork).
militaryeventtype(terrorist_raids).
militaryeventtype(raids).
musicalbum(in_the_wee_small_hours).
emotion(depression).
emotion(depression).
charactertrait(generosity).
charactertrait(generosity).
currency(dinar).
currency(francs).
restaurant(bonaparte_restaurant).
visualartform(etching).
chemical(cadium).
videogame(team_fortess_2).
book(how_to_eat_fried_worms).
book(black_beauty).
book(black_beauty).
book(black_beauty).
book(black_beauty).
book(tristram_shandy).
musicalbum(the_joshua_tree).
book(ulysses).
book(ulysses).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(abbey_road).
musicalbum(jagged_little_pill).
musicalbum(jagged_little_pill).
musicartist(u2).
book(the_grapes_of_wrath).
consumerelectronicitem(psp_2k10).
physicsterm(n44_5_percent).
mlauthor(xia_wang).
restaurant(zur_letzten_instanz_restaurant).
date(april_03).
movie(forrest_gump).
movie(forrest_gump).
movie(forrest_gump).
movie(forrest_gump).
movie(forrest_gump).
movie(forrest_gump).
movie(forrest_gump).
chemical(iron_fluoride).
book(the_master_and_margarita).
currency(euro).
currency(euro).
currency(euro).
currency(euro).
currency(euro).
city(krakow).
fungus(wv_hallucinogenic_mushrooms).
chef(auguste_escoffier).
city(maastricht).
buildingfeature(internal_oak_doors).
date(jul_85).
consumerelectronicitem(psp_playstation_portable_2).
date(may_88).
movie(movie_happy_gilmore).
movie(movie_pulp_fiction).
book(chronicles_of_narnia).
academicfield(software_engineering).
bakedgood(lemon_nut_bread).
cognitiveactions(abstract_problem).
cognitiveactions(abstract_problem).
cognitiveactions(abstract_problem).
professionalorganization(association_for_women_in_computing).
physicalaction(mail_puppy).
physicalaction(mail_post).
bakedgood(bacon_cheddar_muffins).
videogame(super_mario_advance).
sociopolitical(conversation_process).
hotel(golden_key_hotel).
perceptionaction(neighboring).
celltype(unilocular_fat_cells).
date(sep_31).
mediatype(top_journals).
musicgenre(ragga).
condiment(porcini_mushroom_sauce).
cognitiveactions(thinking_outside_the_block_pattern).
movie(movie_batman_forever).
movie(the_court_jester).
religion(buddhism).
religion(buddhism).
boardgame(scrabble_crossword_game).
currency(us_dollars).
tool(asphalt_tools).
tool(asphalt_hand_tools).
beverage(coke).
product(ibm_pc).
musicartist(beatles).
musicartist(beatles).
city(fortaleza).
city(fortaleza).
city(fortaleza).
city(fortaleza).
city(fortaleza).
videogame(final_fantasy_fables__chocobo_tales).
book(a_confederacy_of_dunces).
book(harry_potter).
mlarea(neural_networks).
book(the_lord_of_the_rings).
book(acts).
fungus(mushrooms_michigan).
clothing(endless_shoes).
condiment(gud_sauce).
officeitem(continuous_printing_paper).
musicartist(the_noisettes).
amphibian(african_split_skin_toad).
awardtrophytournament(n2008_algarve_cup).
musicgenre(gypsy_punk_rock).
stadiumoreventvenue(daejeon_world_cup_stadium).
currency(yuan).
ceo(shantanu_narayen).
musicalbum(appetite_for_destruction).
musicalbum(appetite_for_destruction).
musicalbum(appetite_for_destruction).
musicalbum(appetite_for_destruction).
musicgenre(emo_rock_metal).
medicalprocedure(cordectomy_corectomy).
profession(court_reporters).
sport(taekwondobari).
female(kathleen_sgambati).
vegetable(photatoes).
physiologicalcondition(shoulder_osteoarthritis).
kitchenitem(sandwich_pot).
city(thun).
date(sept_2009).
movie(movie_the_bridge_on_the_river_kwai).
academicfield(information_sciences).
visualartform(colour_printing).
buildingmaterial(fiberglass).
conference(aaai).
conference(aaai).
movie(doctor_zhivago).
movie(doctor_zhivago).
movie(doctor_zhivago).
celltype(astrocytes).
vertebrate(varmints).
boardgame(go).
boardgame(go).
boardgame(go).
boardgame(go).
buildingmaterial(stainless_steel).
musicgenre(screamo).
musicartist(nirvana).
city(szczecin).
clothing(men_prada_shoes).
medicalprocedure(urinoscopy).
plant(high_grass).
bodypart(scalp_skin).
householditem(osullivan_office_furniture).
charactertrait(quality_talent).
consumerelectronicitem(psp_magic_memory_stick).
restaurant(jade_cafe).
conference(pycon).
conference(pycon).
movie(movie_minority_report).
videogame(mario_64).
writer(shakespeare).
writer(shakespeare).
academicfield(literature).
consumerelectronicitem(psp_red_alert).
reptile(pignose_turtle).
clothing(mens_comfort_shoes).
city(montreal).
boardgame(chess).
boardgame(chess).
boardgame(chess).
boardgame(chess).
boardgame(chess).
boardgame(chess).
boardgame(chess).
boardgame(chess).
city(linkoping).
election(n2004_presidential_election).
election(n2004_presidential_election).
election(n2004_presidential_election).
musicalbum(hybrid_theory).
bird(australian_red_tailed_cockatoo).
clothing(jogging_pants).
mediatype(e_zines).
mediatype(prestigious_medical_journals).
professionalorganization(american_college_of_sofia).
currency(peso).
book(jane_eyre).
book(jane_eyre).
reptile(southeastern_crown_snake).
videogame(morrowind).
videogame(ultima_vii).
female(katie_lohann).
restaurant(cumin_indian_restaurant).
recordlabel(tpk_records).
book(eragon).
book(eragon).
book(eragon).
book(romeo_and_juliet).
book(romeo_and_juliet).
book(romeo_and_juliet).
bird(african_marsh_warbler).
boardgame(ticket_to_ride_board_game).
election(elections_next_year).
buildingfeature(shower_sliding_door).
musicgenre(easy_listening).
date(fev_24).
academicfield(accounting).
academicfield(accounting).
academicfield(accounting).
academicfield(accounting).
academicfield(accounting).
awardtrophytournament(singapore_league_cup).
movie(movie_ghost).
date(dec_30).
reptile(san_felipe_ground_snake).
ceo(howard_stringer).
restaurant(bruno_s_pizza___restaurant).
restaurant(andy_s_chinese_restaurant).
event(potato_famine).
organization(china_hydropower_engineering_society).
weapon(swords).
weapon(swords).
condiment(lemon_thyme_barbecue_sauce).
jobposition(product_development_engineer).
movie(pirates_of_the_carribean).
movie(pirates_of_the_carribean).
movie(pirates_of_the_carribean).
weapon(smoke_grenade).
weapon(smoke_grenade).
weapon(smoke_grenade).
weapon(smoke_grenade).
emotion(terror).
televisionshow(x_files).
televisionshow(x_files).
televisionshow(x_files).
programminglanguage(lisp).
programminglanguage(lisp).
programminglanguage(lisp).
mediatype(internationaljournals).
landscapefeatures(mountains_rivers).
candy(reeses_mini_peanut_butter_cups).
creativework(doujinshi).
creativework(doujinshi).
creativework(doujinshi).
creativework(doujinshi).
creativework(doujinshi).
year(n1595).
furniture(dog_furniture).
sportsevent(n1993_world_championships_in_athletics).
kitchenitem(electric_tea_pot).
date(feb_1870).
bakedgood(cranberry_fruit_nut_bread).
programminglanguage(vb_script).
date(aug__94).
book(canterbury_tales).
academicfield(biology).
academicfield(biology).
academicfield(biology).
book(a_handful_of_dust).
celltype(vascular_smooth_muscle_cells).
televisionshow(the_magician).
professionalorganization(society_of_american_magicians).
academicfield(business_administration___accounting).
race(tour_de_nouvelle_caledonie).
academicfield(immunology).
museum(amador_county_museum).
food(greek_meatballs_with_egg___lemon_sauce).
musicfestival(long_beach_blues_festival).
year(year_1967).
filmfestival(lucid_underground_media_arts_festival).
professionalorganization(american_college_of_oncology_administrators).
profession(correctional_institution_administrators).
date(feb__87).
date(jan_81).
creditunion(tlc_federal_credit_union).
geometricshape(octagons).
geopoliticallocation(central_asia).
academicfield(astronomy).
academicfield(astronomy).
academicfield(astronomy).
academicfield(astronomy).
academicfield(astronomy).
date(january_1_1996).
amphibian(albino_red_eyed_tree_frog).
bacteria(streptomyces_aureoversilis).
vehicle(ford_focus_zta).
year(n1545).
cognitiveactions(thinking_outside_of_the_box).
recipe(easy_chicken_pasta_recipe).
amphibian(blue_tailed_fire_belly_newt).
date(may_1892).
crustacean(bay_ghost_shrimp).
cave(grotte_san_francisco).
cheese(edam_gouda_cheese).
language(farsi_language).
city(londrina).
winery(york_updates).
food(soft_food).
event(congressional_elections).
videogame(advance_wars).
city(gijon).
politicsbill(middle_class_energy_initiative_act).
museum(fick_fossil_and_history_museum).
invertebrate(name__cutworm).
academicfield(computational_linguistics).
book(a_knight_of_the_word).
book(a_knight_of_the_word).
book(a_knight_of_the_word).
videogame(final_fantasy_x).
videogame(final_fantasy_x).
videogame(final_fantasy_x).
automobilemodel(ford_gt40_concept).
airport(pudong_international_airport).
chemical(chromium_dioxychloride).
governmentorganization(delaware_police_department).
mlauthor(manuela_m__veloso).
mlauthor(manuela_m__veloso).
recordlabel(cherrytree_records).
food(swedish_meatballs_with_creamy_dill_sauce).
food(swedish_meatballs_with_creamy_dill_sauce).
software(guitar_hero_4).
software(guitar_hero_4).
musicartist(buckcherry).
county(chatooga_county).
governmentorganization(arizona_game_and_fish_department).
movie(hamlet).
movie(hamlet).
book(iliad).
book(iliad).
book(iliad).
televisionshow(doctor_who).
televisionshow(doctor_who).
televisionshow(doctor_who).
televisionshow(doctor_who).
televisionshow(doctor_who).
reptile(colombian_rattlesnake).
amphibian(lesser_swamp_frog).
hospital(howard_a_rusk_rehab_center).
televisionshow(the_beverly_hillbillies).
televisionshow(the_beverly_hillbillies).
awardtrophytournament(stanley_cup).
filmfestival(cannes_film_festival).
filmfestival(cannes_film_festival).
creditunion(hospital_system_credit_union).
parlourgame(two_queen).
hotel(new_haven_hotel).
creditunion(cambridge_teacher_federal_credit_union).
televisionshow(the_wonder_years).
vehicle(hot_rods).
book(lord_of_the_flies).
legume(lentil_beans).
cognitiveactions(learning).
amphibian(pearson_s_tree_frog).
weatherphenomenon(cold_winds).
conference(icag).
jobposition(senior_sw_engineer).
recordlabel(discomate_records).
politicsbill(violenceagainst_women_act).
celltype(adipocytes).
female(katia_alens).
book(black_boy).
perceptionaction(beholding).
militaryeventtype(assaults).
currency(boliviano).
musicgenre(skapunk).
programminglanguage(c_programming_language).
programminglanguage(c_programming_language).
programminglanguage(c_programming_language).
programminglanguage(c_programming_language).
programminglanguage(c_programming_language).
programminglanguage(c_programming_language).
visualartform(art_digital_photography).
bodypart(adam_s_apple).
product(acrobat_reader).
filmfestival(da_vinci_days_film_festival).
movie(an_american_in_paris).
movie(an_american_in_paris).
movie(an_american_in_paris).
movie(an_american_in_paris).
celltype(blood_cell).
celltype(blood_cell).
celltype(blood_cell).
celltype(blood_cell).
clothing(docksider_boat_shoes).
recipe(potato_topping_recipe).
port(port_of_torre_annunziata).
software(death_crimson_2).
bridge(finland_railway_bridge).
amphibian(midland_chorus_frog).
mountainrange(rocky_mountains).
movie(movie_gladiator).
geometricshape(lines_problem).
scientist(peter_higgs).
bedroomitem(alarm).
fish(black_spotted_porcupinefish).
book(brideshead_revisited).
book(bleak_house).
muscle(vastuslateralis).
televisionshow(queer_as_folk).
physicalaction(kissing).
physicalaction(boring).
physicalaction(just_kissing).
plant(camellias).
hotel(hyatt_regency_pier_66).
academicfield(international_studies).
tableitem(phone_type_pieces).
date(jul_34).
politicsbill(internet_freedom_preservation_act).
kitchenitem(arabic_teapot).
movie(the_water_horse).
movie(spirited_away).
movie(spirited_away).
movie(sky_high).
movie(sky_high).
movie(mulan).
movie(incredible_hulk).
movie(bambi).
automobileengine(w8_engine).
currency(czech_koruna).
currency(czech_koruna).
condiment(breast_sauce).
parlourgame(two_dobermans).
geometricshape(cubes).
geometricshape(cubes).
militaryeventtype(attack).
hotel(south_beach_plaza_hotel).
protein(alpha_enolase).
bird(european_warbler).
recipe(low_fat_chicken_breast_recipes).
creditunion(seven_seventeen_credit_union).
airport(pampulha_airport).
date(jan__98).
academicfield(theoretical_and_mathematical_physics).
museum(musee_d_art_et_d_histoire___metz).
programminglanguage(python).
programminglanguage(python).
programminglanguage(python).
programminglanguage(python).
bacteria(streptococcus_halichoeri).
flooritem(victorian_sofa).
language(tamil_language).
animal(kitten).
bathroomitem(toilet_base).
bridge(cape_fear_memorial_bridge).
wine(cabernet_blanc).
male(alex_roberts).
bank(tochigi_bank).
condiment(almond_fudge_sauce).
mlconference(aid_response).
condiment(bacardi_cream_sauce).
weatherphenomenon(hot_summer_breeze).
restaurant(the_white_barn_inn_restaurant).
terroristorganization(islamic_studies).
city(lebanon).
legume(french_cut_green_bean).
meat(products_include_beef).
fish(poached_salmon).
politicsissue(science_need).
beach(clermont_beach).
zoo(phoenix_zoo).
room(beautiful_bedrooms).
university(brandeis).
profession(office_machine_technicians).
museum(bigfoot_museum).
olympics(of_ancient_greek_olympics).
politicsissue(rights).
mammal(impalas).
meat(fillet_steak).
fish(jellyfish).
consumerelectronicitem(dvd_to_pocket_pc_ripper).
creditunion(united_employees_credit_union).
creditunion(united_employees_credit_union).
color(dodgerblue).
room(laundry_and_workroom).
automobilemodel(daimler_xj12).
personnorthamerica(diane_finley).
sport(speedcubing).
hobby(speedcubing).
tableitem(mug).
company(dhl).
recipe(nutella_recipe).
politicalparty(industrial_socialist_labor_party).
arthropod(ear_mites).
university(indiana_university).
mlauthor(douglas_r__hofstadter).
traditionalgame(sex_hand_job_strip_poker).
condiment(basic_new_mexican_red_chile_sauce).
jobposition(product_assistant).
wallitem(seek_alarm_clock).
jobposition(child_development_consultant).
beach(rotonda_beach).
weapon(marlin_gun).
nut(dry_roasted_hazelnut).
emotion(rage).
agriculturalproduct(bees).
academicfield(physical_cosmology).
bodypart(brain_cavity).
reptile(korean_rat_snake).
profession(biopsychologist).
flooritem(camel_back_sofa).
mlalgorithm(poisson_hidden_markov_model).
reptile(american_ornate_wood_turtle).
flooritem(sectional_club_chair).
furniture(coffee_table_set).
language(hebrew).
kitchenitem(plates).
politicsissue(labour_rights).
bedroomitem(pc_desktop_clock).
geometricshape(squares).
boardgame(puzzle_game).
musicartist(mars_volta).
bodypart(glia).
televisionshow(the_next_generation).
color(black).
country(uae).
food(pizza).
airport(washington_national__dca_).
mlsoftware(weka).
insect(caterpillar_worm).
mlauthor(john_updike).
dayofweek(friday).
dayofweek(friday).
charactertrait(hypocrisy).
personalcareitem(anti_aging_cream).
transportation(amtrack_train).
nondiseasecondition(pregnancy_begin_to_show).
zoo(nashville_zoo_and_wildlife_park).
hotel(courtyard_marriott_hotel).
sportsteam(ac_milan).
householditem(cleanroom_furniture).
color(dark_grey).
agriculturalproduct(thyme).
emotion(unrelentless).
jobposition(product_management_engineer).
website(sundaytimes).
jobposition(associate_dentist).
trail(bald_bluff_trail).
academicfield(archaeology).
book(babbitt).
male(andrew_mccallum).
ceo(alain_belda).
cheese(parmesan).
female(lil_kim).
personnorthamerica(lil_kim).
country(argentina).
country(argentina).
museum(art_museum).
park(vondelpark).
cardgame(poker_texas_hold_em_2004).
clothing(kimonos).
amphibian(frogs).
filmfestival(stockholm_french_film_festival).
programminglanguage(c__).
programminglanguage(c__).
book(the_war_of_the_worlds).
writer(ray_bradbury).
scientist(ray_bradbury).
book(martian_chronicles).
politician(president_chirac).
candy(jelly_beans_cappuccino).
boardgame(carcassonne_game).
boardgame(catchphrase).
boardgame(mouse_trap).
academicfield(other_physics).
videogame(final_fantasy_6).
physicalaction(fucking).
street(i_405_freeway).
street(i_405_freeway).
hospital(colorado_orthopaedic___surgical_hospital).
musicfestival(gold_coast_jazz_festival).
currency(krone_american_dollar).
tradeunion(tobacco_workers_international_union).
street(seventh_street).
food(baked_apple_doughnuts).
island(sunken_rock_island).
physiologicalcondition(dystonias).
country(solomon_islands).
braintissue(cerebral_ganglia).
island(samoa).
bodypart(eustachian_tube).
city(madrid).
politicianus(adam_smith).
medicalprocedure(dental_procedure).
physicsterm(line_speed).
room(reception_rooms).
hospital(u_s__air_force_academy_hospital).
food(coconutmilk).
food(meat_pies).
food(almost_perfect_cheesecake).
charactertrait(sageness).
currency(australia_dollars).
currency(canadian_gold_maple_leaf).
placeofworship(my_cathedral).
braintissue(pituatary_gland).
braintissue(brodmann_area).
beverage(cherry_coke).
beverage(iced_lemonade_tea).
nut(cashew_nut).
agriculturalproduct(cashew_nut).
grain(rolled_oats).
planet(earth).
bodypart(earlobe).
beverage(whole_milk).
criminal(michael_eugene_elkins).
language(persian).
aquarium(marine_palace___oita_sea_life_aquarium).
food(leeks).
chemical(copper_ii_carbonate_dihydroxide).
race(gp_international_costa_azul).
weapon(four_car_bombs).
furniture(elliott_s_antique_reproduction_beds).
aquarium(aquarium_crikvenica).
programminglanguage(assembler_code).
highway(i_405_freeway).
visualartform(portraiture_photography).
clothing(cashmere_sweater).
musicfestival(hiawatha_tradtional_music_festival).
jobposition(petty_officer).
country(brazil).
profession(sociocultural_anthropologists).
profession(sociocultural_anthropologists).
videogame(final_fantasy_12).
filmfestival(golden_apricot_international_film_festival).
videogame(doom).
videogame(doom).
year(c__1888).
vertebrate(pernambuco_pygmy_owl).
programminglanguage(turbo_pascal).
jobposition(lawyer).
movie(movie_highlander).
stadiumoreventvenue(fedex_forum).
radiostation(weoz).
emotion(anxiety).
company(federal_express).
color(cyan).
condiment(barbecue_sauce).
condiment(horseradish).
academicfield(architecture).
furniture(leather_sofas).
clothing(athletic_shoe_discounted_women_s_athletic_shoes).
publication(rutland_herald).
musicsong(a_day_in_the_life).
musicsong(a_day_in_the_life).
musicsong(a_day_in_the_life).
bakedgood(heavenly_chocolate_cheesecake).
weapon(atomic_bomb).
publication(glamour).
country(iran).
country(algeria).
governmentorganization(mt_kisco_police_department).
governmentorganization(mt_kisco_police_department).
governmentorganization(mt_kisco_police_department).
physicalaction(fedex_shipping).
religion(christianity).
religion(christianity).
protein(enzyme).
sport(basketball).
hobby(basketball).
city(rio).
city(rio).
insect(ant).
insect(ant).
fish(bass).
fish(scorpididae).
creditunion(reserve_federal_credit_union).
island(howland_island).
medicalprocedure(gastric_band_procedure).
nondiseasecondition(pregnancy_first_trimester).
female(kate_moss).
celebrity(kate_moss).
model(kate_moss).
plant(mistflower).
medicalprocedure(special_head_surgery).
chemical(benzylic_alcohol).
person(linda).
meat(steak).
meat(steak).
agriculturalproduct(steak).
agriculturalproduct(steak).
weatherphenomenon(little_breeze).
personsouthamerica(jorge_luis_borges).
museum(brooklyn_museum).
building(brooklyn_museum).
professionalorganization(ieee_society).
city(kanpur).
city(mumbai).
city(vishakhapatnam).
stateorprovince(andhra_pradesh).
city(hyderabad).
stateorprovince(maharashtra).
city(vijayawada).
airport(vijayawada_airport).
automobilemodel(honda___civic).
country(ethiopia).
celebrity(bela_lugosi).
male(bela_lugosi).
actor(bela_lugosi).
traditionalgame(n5_card_draw_poker).
musicinstrument(voice___bass).
book(harry_potter_books).
website(facebook).
website(facebook).
company(facebook).
company(facebook).
attraction(madam_tussauds).
attraction(madam_tussauds).
jobposition(insurance_company_executive_manager).
event(extermination_of_native_americans).
placeofworship(muktinath).
placeofworship(banteay_srei).
bacteria(lactobacilli_and_bifidobacteria).
convention(creative_commons_attribution_noncommercial_noderivs).
celltype(cell_determinants).
visualartform(photoprocess).
governmentorganization(swartswood_police_department).
muscle(ulnaris).
protein(acetyl_coa_acp_transacylase).
color(gold_celtic_wedding).
director(jonathan_rattay).
zoo(busch_gardens_tampa_bay).
park(busch_gardens_tampa_bay).
videogame(resident_evil_6).
videogame(persona_4).
musicsong(it_s_raining_again).
month(october).
bone(femur).
election(election_day_1853).
dayofweek(wednesday).
dayofweek(monday).
dayofweek(tuesday).
dayofweek(saturday).
dayofweek(sunday).
dayofweek(thursday).
ethnicgroup(germans).
museum(kunst_haus_wien).
airport(klagenfurt_airport).
university(klagenfurt_university).
jobposition(executive_vicepresident).
hospital(saint_mary_s_mercy_medical_center).
mlauthor(christopher_m__gifford).
landscapefeatures(riverbend).
beverage(la_colombe_coffee).
movie(the_godfather).
movie(the_godfather).
professionalorganization(louisiana_state_bar_association).
ethnicgroup(bulgarian).
jobposition(health_care_administrator).
furniture(hardwood_tables).
writer(pete_mccarthy).
medicalprocedure(nasal_turbinate_surgery).
bakedgood(christmas_cookie).
food(italian_roast_beef).
terroristorganization(palestinian_terrorist_organization_hamas).
politicaloffice(deputy_chief).
beverage(breakfast_blend_coffee).
food(chicken_dumpling_soup).
restaurant(baskin_robbins).
race(gp_de_l_industrie_du_marbre).
olympics(in_the_1952_winter_olympics).
olympics(in_the_1952_winter_olympics).
cardgame(holdemtexas).
chemical(calcium_stearoyl_2_lactylate).
country(u_s_a____new_mexico).
candy(hershey_s_kiss).
attraction(maine_state_aquarium).
athlete(rafa_nadal).
buildingfeature(decorative_glass_windows).
recipe(sugar_cookies_recipe).
musicinstrument(seven_string_guitar).
musicfestival(cowboys_musicfest).
disease(endocarditis).
school(racing_school).
island(cunningham_island).
jobposition(editor).
medicalprocedure(hemipylorectomy).
food(orzo).
currency(kuna).
currency(lev).
currency(birr).
currency(kroon).
currency(sheqels).
currency(rupees).
book(the_wapshot_chronicles).
book(left_behind).
book(gormenghast).
book(breakfast_at_tiffany_s).
book(death_in_venice).
stadiumoreventvenue(conseco_fieldhouse).
stadiumoreventvenue(bankers_life_fieldhouse).
politicianus(barack_obama).
male(barack_obama).
book(about_a_boy).
book(about_a_boy).
book(about_a_boy).
book(about_a_boy).
buildingfeature(door_toilet).
bird(rufous_turtle_dove).
programminglanguage(code_writers).
visualartist(francia).
personus(peter_rummell).
stadiumoreventvenue(camp_nou).
city(cairo).
currency(peseta).
musicartist(lmfao).
buildingmaterial(carbon_fiber).
vegetable(cabbage).
musicinstrument(yamaha_piano).
wallitem(pine_clock).
boardgame(puerto_rico_board_game).
personalcareitem(pet_care_products).
filmfestival(vancouver_international_film_festival).
emotion(awe).
emotion(fear).
officeitem(pencil).
mammal(dogs).
profession(web_programmers).
profession(web_programmers).
color(gold_emerald).
animal(mink).
invertebrate(junebug).
physicalaction(needle_injecting).
food(margarine).
food(margarine).
chemical(diphenylphosphoryl_azide).
musicinstrument(sax_horn).
book(all_quiet_on_the_western_front).
food(chicken___tenderloins).
food(chicken___tenderloins).
boardgame(game_monopoly).
food(apple_slices).
celebrity(katja_schuurman).
female(katja_schuurman).
personalcareitem(moisturising_creams).
personnorthamerica(natalie_merchant).
fish(damselfish).
date(circa_1792).
food(leaf_lettuce).
kitchenitem(bottle_cooler).
arthropod(yellowjacket).
furniture(contemporary_glass_coffee_tables).
island(caribbean_island).
hospital(rockcastle_hospital).
item(laptop).
braintissue(human_frontal_cortex).
physicalaction(jumping).
weapon(flame_thrower).
weapon(colt_45).
weapon(colt_45).
hotel(hilton_dublin_airport).
currency(dutch_guilder).
officeitem(pencil_sharpeners).
everypromotedthing(hamster).
food(beef___steak___rib_eye).
awardtrophytournament(u_s__open).
sportsevent(n1966_fifa_world_cup).
weatherphenomenon(intense_wind).
fungus(fly_agaric).
fungus(mycelium).
vegetable(sawi).
personasia(zhong_zhiwen).
female(martha_stewart).
musicinstrument(martin_acoustic_guitar).
person(ronnie_l__coleman).
shoppingmall(dufferin_grove_park).
hospital(jml_care_center).
officeitem(paper_card).
olympics(olympic_games).
mountain(capitol_peak).
weatherphenomenon(tremendous_winds).
stadiumoreventvenue(gladiator_stadium).
vertebrate(summer_flounder).
company(bell_laboratories).
sportsteam(baltimore_colts).
writer(jk_rowlings).
personeurope(jk_rowlings).
race(gp_1_maja).
drug(imipramine_tablet).
stateorprovince(maharashtra_state).
date(september_14___15).
company(escape_magazine).
furniture(bench_seats).
mammal(ground_sloth).
clothing(addidas_golf_shoes_clarks_discount_shoes).
beverage(watermelon_juice).
agriculturalproduct(tea_leaf).
amphibian(narrow_headed_soft_shelled_turtle).
mlauthor(herman_e__daly).
fish(valdivia_black_dragon_fish).
governmentorganization(middlesex__borough_police_department).
televisionstation(kurs).
highway(st__joseph_valley_parkway).
animal(orca_whales).
personalcareitem(anti_perspirant).
politicsblog(timewe).
mediatype(trade_books).
eventoutcome(experience).
videogame(quake_2).
protein(periplasmic_binding_protein).
sportsgame(national_league).
reptile(titanosaurs).
fruit(sesame_seeds_sesame_seeds).
chemical(gallium_arsenide).
park(disneyland).
tableitem(phone_number_courtesy_listings).
beverage(honey_water).
academicfield(general_physics).
videogame(starcraft_2).
protein(cathepsin_d_preproprotein).
software(battlefield__bad_co__2).
physicalaction(quickly_resuming).
building(shenyang_international_finance_center).
creditunion(workers__credit_union).
shoppingmall(triangle_center).
boardgame(game_of_life).
hospital(the_cheshire_medical_center).
mammal(brown_bear).
mammal(gorillas).
musician(jack_bruce).
jobposition(mechanical_estimator).
automobileengine(mustang_engine).
landscapefeatures(peak_forms).
hobby(freeboard_skateboarding).
televisionstation(kppc).
bird(red_chested_buttonquail).
male(alice_cooper).
animal(bumble_bees).
physicsterm(differential_air_pressure).
physicsterm(differential_air_pressure).
filmfestival(cincinnati_film_festival).
politicalparty(people_s_communist_party_of_kazakhstan).
weatherphenomenon(monstrous_wind).
religion(religious_daoism).
jobposition(claims_administrator).
country(australia).
country(australia).
continent(australia).
continent(australia).
continent(australia).
island(australia).
island(australia).
medicalprocedure(morbid_obesity_surgery).
jobposition(compliance_administrator).
bakedgood(large_chocolate_cake).
bird(penguin).
vegetable(onion).
sportsequipment(rubber_playground_balls).
date(september_23___28).
plant(flower_petals).
mediatype(disk__pc).
mediatype(disk__pc).
director(jonathan_akande).
building(marriott_boulder_hotel).
product(huawei_u120).
sport(football).
vehicle(mazda_ford_laser_coupe).
building(uc_santa_barbara_events_center).
airport(royal_brunei).
hospital(taft_medical_center).
personsouthamerica(escuela_nro__848_san_rafael).
everypromotedthing(syrah_grapes).
beverage(carrot_juice).
beverage(carrot_juice).
furniture(armoire).
male(mitt_romney).
male(mitt_romney).
politicianus(mitt_romney).
politicianus(mitt_romney).
physicalaction(ice_blasting).
company(aps_credit_union).
academicfield(gentics).
vertebrate(cat).
product(chevrolet_el_camino_series_ii).
sportsequipment(spalding_basketballs).
televisionshow(the_black_adder).
language(welsh_language).
winery(miramont_estate_vineyard_and_winery).
person(barbara).
chemical(indium_arsenide).
magazine(professional_carwashing___detailing_magazine).
musicinstrument(uprightbass).
sportsteam(montana_grizzlies).
hobby(snow_skiing_and_surfing).
sociopolitical(war).
weatherphenomenon(terrible_storm).
sport(nascar).
athlete(ryan_newman).
sportsleague(nascar).
stadiumoreventvenue(dover_downs).
athlete(carl_edwards).
race(gp_correios).
televisionshow(the_21st_century).
book(artemis_fowl_the_eternity_code).
automobilemodel(infiniti__i35).
creditunion(alberta_credit_union).
fish(freshwater_angel_fish).
fish(freshwater_angel_fish).
bodypart(internal_ear).
profession(obstetrician_gynecologist).
beverage(chianti_wine).
medicalprocedure(radiography).
profession(physician__s_assistant).
room(soundproof_rooms).
bird(robin).
bird(woodpecker).
person(andrew_stevenson).
stateorprovince(szczecinskie).
cheese(grated_parmesan_cheese).
jobposition(helpdesk_coordinator).
country(viet_nam).
winery(york_risk).
date(september_27___28).
journalist(scully_anderson).
vehicle(chevrolet_denali).
academicfield(social_economics).
tool(scrapers).
clothing(kids_clothes_and_shoes_womens_discount_shoes).
island(wood_island).
male(john_neville).
buildingfeature(heaters).
book(the_waste_land_and_other_poems).
airport(salt_lake_city_international_airport).
jobposition(computer_control_operator).
personalcareitem(anti_stretch_mark_removal_cream).
fish(carnivorous_fish).
geopoliticallocation(raipur).
weatherphenomenon(soft_evening_breeze).
drug(zinviroxime).
plant(locoweed).
jobposition(computer_database_administrator).
jobposition(computer_database_administrator).
automobilemaker(mercedes_lgs).
judge(chief_justice_john_roberts).
river(lower_south_fork_little_river).
bird(salvadori_s_antwren).
medicalprocedure(third_molar_surgery).
product(panasonic_eb_x800).
recipe(recipe_bon_bon_chicken).
videogame(civilization_2).
videogame(civilization_2).
officeitem(high_quality_paper).
date(september_10___14).
flooritem(sofa_system).
publication(purdue_university_football_vault_magazine).
chemical(benzyl_isobutyrate).
publication(alabama_employment_law_letter_magazine).
female(anne_bancroft).
weapon(gun_ammunition).
hobby(australian_kayaking).
plant(mango_tree).
book(the_wide_window).
software(colony_wars_3).
vehicle(chevrolet_apache).
beverage(peppermint_hot_chocolate).
clothing(short_sleeve_t_shirt).
park(liberty_park).
book(couples).
company(sam__s_club).
recipe(recipes_for_eggs).
language(non_chinese_language).
book(the_hostile_hospital).
product(nokia_7310c).
wine(cabernet_sauvigno).
chemical(dicyclanil).
politician(president_g_w__bush).
insect(screw_worm_fly).
bakedgood(chocolate_walnut_cake_brownies).
female(karen_simpson).
software(phantasy_star_online_3).
buildingmaterial(iron_stuff).
food(fiber).
date(january_10___14).
city(savannah).
musician(eric_clapton).
product(nokia_1110i_blue).
male(ben_harper).
sportsevent(beijing_games).
jobposition(computer_network_administrator).
director(david_kaplan).
sportsgame(national_championship).
clothing(adidas_sport_shoes_discounted_basketball_shoes).
musician(phil_collins).
date(january_12___14).
conference(sigcaph).
jobposition(founder_and_coordinator).
profession(paper_goods_machine_setters_and_set_up_operators).
householditem(heavy_duty_baking_pan).
tradeunion(health_care_workers_union).
beverage(oregon_pinot_noir).
recipe(recipe_for_popcorn_balls).
programminglanguage(java).
programminglanguage(java).
city(zurich).
visualartform(photograps).
product(nokia_6750).
profession(web_page_creators).
hotel(hotel_eden).
beverage(vegetable_broth).
physicalaction(mailing_letters).
airport(carl_keller_field_airport).
automobilemodel(accord).
videogamesystem(ps2).
kitchenitem(glass_dish).
country(switzerland).
country(switzerland).
stateorprovince(aargau).
clothing(wool_suit).
automobilemodel(hyundai_hcd10_hellion).
astronaut(vladim_r_ljachov).
weatherphenomenon(balmy_sea_breeze).
insect(eastern_pine_shoot_borer).
date(january_25___28).
sport(street_racing).
cognitiveactions(healthy_thinking).
musicsong(it_s_all_in_the_game).
profession(maintenance_workers).
fruit(mulberry).
election(mayoral_election).
election(u_s__presidential_election).
physicalaction(mailing).
physicalaction(cleaning).
physicalaction(pointing).
physicalaction(running).
city(boston).
planet(mercury).
chemical(acetaldehyde).
politician(governor_mitt_romney).
male(governor_mitt_romney).
personus(governor_mitt_romney).
videogame(sacred_2).
insect(bumblebee).
bridge(brooklyn_bridge).
weapon(ak_47).
weapon(ak_47).
newspaper(the_san_jose_mercury_news).
newspaper(the_san_jose_mercury_news).
website(the_san_jose_mercury_news).
date(december_march).
terroristorganization(taleban).
celebrity(paula_abdul).
wine(granache).
cardgame(blackjack).
bakedgood(apple_streusel_muffins).
vertebrate(giant_hummingbirds).
automobilemodel(mazda_618).
governmentorganization(supreme_court).
university(swiss_federal_institute_of_technology).
recipe(apples_recipes).
academicfield(computer_science).
academicfield(computer_science).
academicfield(computer_science).
invertebrate(japanese_white_birch_woolly_aphid).
celltype(glial_cells).
city(zagreb).
weatherphenomenon(snow).
chemical(oxygen).
fish(shark).
hobby(gardening).
profession(procurement_coordinator).
academicfield(american_history).
academicfield(ecology).
televisionshow(the_ascent_of_man).
person(frank_walter_steinmeier).
politicalparty(social_democratic_party_or_spd).
male(john_russell).
videogame(legend_of_mana).
mountain(everest).
stateorprovince(new_york).
stateorprovince(asturias).
airport(asturias_airport).
mediatype(harddrive).
scientist(georges_lemaitre).
country(canada).
musician(b_b__king).
automobilemodel(porsche_cayman).
election(election_of_1900).
person(jack).
person(martin_luther_king_jr__).
city(memphis).
politician(barak_obama).
male(barak_obama).
personus(barak_obama).
placeofworship(tourism_issues_notre_dame_cathedral).
agriculturalproduct(alfalfa).
grain(alfalfa).
celltype(cells).
protein(proteins).
academicfield(computer_and_information_sciences).
month(april).
furniture(corner_cabinet).
academicfield(finance_economics).
actor(emmy_rossum).
meat(tender_beef).
bakedgood(portuguese_coffee_buttercake).
currency(swiss_franc).
currency(swiss_franc).
sport(paintball).
hobby(paintball).
school(columbia_college).
athlete(george_foreman).
athlete(george_foreman).
athlete(george_foreman).
athlete(george_foreman).
automobilemodel(chevrolet___tahoe).
filmfestival(dublin_underground_film_festival).
filmfestival(dublin_underground_film_festival).
agriculturalproduct(beer).
beverage(beer).
beverage(beer).
bakedgood(bread).
nondiseasecondition(yawning).
tool(knowledge_base).
jobposition(president).
politicaloffice(president).
race(tour_de_georgia).
hobby(triathlon).
sport(triathlon).
hobby(triathlons).
sport(triathlons).
movie(empire_strikes_back).
biotechcompany(amarincorp).
videogame(hell__a_cyberpunk_thriller_take_2).
movie(star_wars).
musicsong(lucy_in_the_sky_with_diamonds).
charactertrait(rightousness).
automobilemodel(mercedes_500sl).
musicinstrument(bugle).
olympics(n2000_sydney_olympics).
televisionshow(the_daly_show).
terroristorganization(hizbllah).
city(mendocino).
recipe(crab_dip_recipe).
musicinstrument(banduria).
charactertrait(overimpressionableness).
disease(cancer).
bakedgood(classic_cupcake).
country(germany).
agriculturalproduct(paprika).
boardgame(battleship).
academicfield(computer_electronics).
personeurope(john_la_farge).
island(trim_island).
governmentorganization(beccaria_police_department).
chemical(sodium_carboxy_methylcellulose).
currency(indian_rupee).
actor(movie_actors).
grandprix(n2001_british_grand_prix).
election(presidential_elections).
programminglanguage(php).
automobileengine(lexus_engines).
software(apache_http_server).
physicalaction(sewing).
city(york).
agriculturalproduct(maize).
programminglanguage(scala).
televisionshow(ally_mcbeal).
politicianus(james_russell).
animal(red_bellied_lemur).
country(brasil).
plant(catholicus).
university(world_dine_college).
eventoutcome(severe_negative_impact).
buildingfeature(door_knob_set_fit_any_door).
museum(hollywood_wax_museum).
male(jose_masegosa).
filmfestival(paris_international_underground_film_festival).
actor(john_leigh).
color(varley_s_green).
arachnid(black_widow_spiders).
musicinstrument(gibson_electric_guitar).
radiostation(krhv).
river(agujitas_river).
vehicle(gmc_sierra_3500_hd).
chemical(caproamphoglycinate).
politicalparty(progressive_conservative_party).
airport(luxembourg_findel_airport).
attraction(musee_national_du_chateau_de_compiegne).
publication(the_lincoln_sentinel).
bone(vertebral_body).
muscle(pectoralis_major_pars_clavicularis).
room(charming_room).
buildingfeature(floor_access_doors).
politicalparty(sanjak_democratic_party).
airport(oslo_sandefjord_torp_airport).
condiment(basic_tomato_and_basil_sauce).
date(november_12_14).
disease(diabetes).
politicalparty(democratic_party_of_armenia).
jobposition(business_travel_assistant).
product(nokia_5210e).
televisionshow(the_big_bang_theory).
televisionshow(friends).
religion(islam).
religion(islam).
televisionshow(the_scooby_doo_show).
city(fishers).
mlconference(www_malepornstarsexposed_com).
sportsteam(david_gilliland).
musicsong(your_body_is_a_wonderland).
food(milkshakes).
musicgenre(progressive_trance).
terroristorganization(islamic_jihad_for_the_liberation_of_palestine).
condiment(caramel_sauce).
politicalparty(wyoming_republican_party).
automobilemodel(mazda_mx_5).
musicinstrument(tub_bass).
beverage(syrup).
reptile(beach_turtle).
mlconference(icml).
bird(barn_owl).
olympics(n1924_summer_olympics).
movie(die_hard).
movie(pulp_fiction).
movie(pulp_fiction).
city(jena).
personasia(chang_tseng).
bodypart(nerves_to_vagina).
chemical(n1_bromo_3_iodobenzene).
item(plastic_wrap).
chemical(ammonium_cupric_sulphate).
hotel(palomar_hotel).
bacteria(pichia_fabianii).
chemical(ammonium_mercuric_thiocynate).
physicalaction(assumes_sitting).
food(fruit_pizza).
muscle(jaw_muscles).
tool(machine_evaluation).
university(dundee_university).
currency(pounds).
filmfestival(toronto_international_film_festival).
election(n1840_presidential_election).
month(july).
personeurope(ken_clarke).
drug(reparil).
date(october_21_and_23).
kitchenitem(dish_pan).
hobby(kayak_paddling).
householditem(sectional_sleeper_sofas).
book(the_holy_bible).
disease(rheumatoid_arthritis).
televisionshow(anime).
food(easy_zucchini_bread).
boardgame(backgammon).
radiostation(kkan).
beverage(dark_coffee).
stadiumoreventvenue(mckenzie_arena).
lake(langholen_reservoir).
insect(lightning_beetles).
blog(the_breast_blog).
plant(mallow).
transportation(art_arlington_transit).
city(stone_mountain).
governmentorganization(tully_police_department).
female(basemath).
geopoliticallocation(nikolsburg).
city(kansas).
island(east_brother_island).
hobby(scrap_quilting).
university(auburn_university).
politicalparty(nagaland_democratic_party).
charactertrait(sweet_reasonableness).
profession(desigers).
recipe(green_bean_casserole_recipe).
geopoliticallocation(khong_island).
charactertrait(purity).
academicfield(financial_forensics).
automobileengine(sho_engine).
female(kristina_springer).
bacteria(genus_rhabdochromatium).
plant(trees).
criminal(ted_bundy).
boardgame(settlers_of_catan).
sociopolitical(terrorism).
chemical(petroleum).
city(cleveland).
weapon(roadside_bombs).
color(med_foliage_green).
stateorprovince(delhi).
clothing(costume_glasses).
academicfield(active_learning).
medicalprocedure(complications_of_gastric_bypass_surgery).
currency(china_yuan_renminbi).
academicfield(electrical_and_computer_engineering).
disease(calcinosis).
jobposition(it_systems_administrator).
religion(orthodox_faith).
geopoliticallocation(parish).
animal(beavers).
televisionshow(person_of_interest).
male(steven_spielberg).
director(steven_spielberg).
officeitem(paper_fasteners).
bakedgood(pie).
book(contact).
agriculturalproduct(sheep).
mammal(sheep).
celebrity(alec_guinness).
actor(alec_guinness).
journalist(sam_donaldson).
visualartmovement(conceptual_art).
musicsong(aurora).
militaryconflict(vietnam_war_era).
book(adventures_of_tom_sawyer).
movie(goodfellas).
city(new_york_city).
personnorthamerica(gregory_r__schultz).
room(large_single_bedroom).
beverage(moscato_d_asti_o_asti_spumante).
city(new_york_city).
hotel(holiday_inn_midtown_57th_street).
reptile(western_ratsnake).
female(kate_middleton).
celebrity(kate_middleton).
female(kate_middleton).
female(prince_william).
movie(k_pax).
actor(kevin_spacey).
physicsterm(gravities).
hobby(photo_collecting).
country(great_britain).
language(english).
musicgenre(rock).
musicartist(arctic_monkeys).
medicalprocedure(preparing_for_spine_surgery).
nondiseasecondition(postpartum_depression).
everypromotedthing(people).
everypromotedthing(lebanon).
amphibian(malayan_painted_toad).
