animalsuchasinvertebrate(insects,butterflies).
statelocatedingeopoliticallocation(states,home).
animaleatfood(baby,breastmilk).
citycapitalofcountry(nassau,bahamas).
agentparticipatedinevent(ideas,result).
foodcancausedisease(junk_food,heart_attacks).
attractionofcity(hallenstadion,zurich).
sportusesequipment(hunting,apparel).
sportfansincountry(rugby,argentina).
synonymfor(office,division).
sportschoolincountry(ski,the_united_states).
sportschoolincountry(ski,holland).
sportusesequipment(badminton,racquet).
sportschoolincountry(aikido,japan).
sporthassportsteamposition(football,offensive_guard).
sportusesequipment(golf,field).
sportusesequipment(golf,wood).
sportusesequipment(sports,protective_gear).
sportusesequipment(soccer,jersey).
sportschoolincountry(snowboard,switzerland).
sportusesstadium(basketball,united_center).
sportusesequipment(soccer,soccer_accessories).
bookwriter(the_shell_seekers,rosamunde_pilcher).
sportusesstadium(basketball,fedex_forum).
sportusesstadium(basketball,conseco_fieldhouse).
sportusesstadium(basketball,thomas___mack_center).
bookwriter(angels_and_demons,dan_brown).
bookwriter(angels_and_demons,dan_brown).
bookwriter(angels_and_demons,dan_brown).
bookwriter(da_vinci_code,dan_brown).
bookwriter(the_hobbit,tolkien).
sportusesstadium(baseball,shea_stadium).
bookwriter(macbeth,shakespeare).
bookwriter(satanic_verses,rushdie).
sportusesequipment(hockey,clubs).
bookwriter(mein_kampf,adolf_hitler).
bookwriter(mein_kampf,adolf_hitler).
bookwriter(time_machine,h_g__wells).
sportusesstadium(baseball,oriole_park).
bookwriter(romeo_and_juliet,shakespeare).
bookwriter(silmarillion,tolkien).
bookwriter(silmarillion,tolkien).
academicprogramatuniversity(computer_science,uc_berkeley).
academicprogramatuniversity(computer_science,mit).
academicprogramatuniversity(computer_science,mit).
academicprogramatuniversity(engineering,auburn_university).
academicfieldsuchasacademicfield(business,finance).
academicprogramatuniversity(accounting,institute).
academicfieldsuchasacademicfield(actuarial_science,accounting).
academicprogramatuniversity(applied_mathematics,institute).
academicfieldsuchasacademicfield(applied_science,engineering).
academicfieldsuchasacademicfield(linguistics,japanese).
academicprogramatuniversity(computer_science,institute).
academicprogramatuniversity(computer_science,institute).
academicfieldsuchasacademicfield(biology,marine).
academicprogramatuniversity(divinity,mccormick_theological_seminary).
bookwriter(the_catcher_in_the_rye,j_d__salinger).
bookwriter(babbitt,sinclair_lewis).
bookwriter(the_war_of_the_worlds,h__g__wells).
bookwriter(the_war_of_the_worlds,h_g__wells).
bookwriter(fahrenheit_451,ray_bradbury).
bookwriter(dandelion_wine,ray_bradbury).
bookwriter(martian_chronicles,ray_bradbury).
sporthassportsteamposition(baseball,hitter).
academicprogramatuniversity(architecture,institute).
academicprogramatuniversity(architecture,harvard_university_graduate_school_of_design).
academicprogramatuniversity(architecture,cornell_university).
languageofcity(english,toronto).
languageofcity(english,toronto).
academicprogramatuniversity(engineering,uc_berkeley).
academicprogramatuniversity(law,emory_university).
languageofcountry(persian,iran).
bookwriter(harry_potter_books,j_k_rowling).
bookwriter(harry_potter_books,j_k__rowling).
languageofcity(english,pittsburgh).
languageofcity(english,pittsburgh).
languageofcountry(english,uk__ireland).
languageofuniversity(english,emory_university).
bookwriter(the_wapshot_chronicles,john_cheever).
bookwriter(left_behind,tim_lahaye_and_jerry_jenkins).
bookwriter(left_behind,tim_lahaye).
bookwriter(gormenghast,mervyn_peake).
bookwriter(a_suitable_boy,vikram_seth).
bookwriter(a_month_in_the_country,jl_carr).
bookwriter(breakfast_at_tiffany_s,truman_capote).
bookwriter(cyteen,c__j__cherryh).
bookwriter(remains_of_the_day,kazuo_ishiguro).
languageofuniversity(english,dartmouth).
languageofuniversity(english,iowa_state_university).
languageofuniversity(english,victoria_university_of_wellington).
languageofuniversity(english,university_of_florida).
languageofuniversity(english,university_of_florida).
languageofuniversity(english,ohio_university).
languageofuniversity(english,catholic_university).
languageofuniversity(english,carnegie_mellon).
languageofuniversity(english,washington_university).
languageofuniversity(english,indiana_university).
languageofuniversity(english,middlebury).
languageofuniversity(english,university_of_washington).
languageofuniversity(english,loyola_university).
languageofcity(russian,st__petersburg).
languageschoolincity(german_language,freiburg).
languageschoolincity(german_language,regensburg).
languageschoolincity(english_language,adelaide).
languageschoolincity(english_language,vancouver).
languageschoolincity(english_language,vancouver).
languageofcity(spanish,dallas).
languageofcity(spanish,miami).
languageschoolincity(english_language,boston).
languageofcountry(spanish,panama).
languageofcity(spanish,orlando).
languageofcountry(spanish,chile).
languageofcountry(spanish,chile).
languageofcountry(malay,indonesia).
languageofcity(spanish,barcelona).
languageofcountry(spanish,uruguay).
languageofcountry(spanish,guatemala).
emotionassociatedwithdisease(anxiety,asthma).
emotionassociatedwithdisease(depression,memory_problems).
emotionassociatedwithdisease(symptoms,disorders).
emotionassociatedwithdisease(abuse,disorders).
emotionassociatedwithdisease(depression,chronic_fatigue).
emotionassociatedwithdisease(depression,chronic_fatigue).
languageofcountry(portuguese,portugal).
languageofcountry(portuguese,brazil).
emotionassociatedwithdisease(depression,medications).
emotionassociatedwithdisease(anxiety,anxiety_disorders).
languageofcity(arabic,cairo).
plantrepresentemotion(flowers,love).
plantrepresentemotion(flowers,love).
plantrepresentemotion(orchids,love).
plantrepresentemotion(pansies,love).
plantrepresentemotion(roses,love).
plantrepresentemotion(roses,love).
plantrepresentemotion(roses,love).
plantincludeplant(trees,coconut_trees).
emotionassociatedwithdisease(phobia,disorder).
emotionassociatedwithdisease(phobia,disorder).
sportsgameteam(championship,pittsburgh_steelers).
plantrepresentemotion(flowers,beauty).
emotionassociatedwithdisease(pain,arthritis).
emotionassociatedwithdisease(clinical_depression,disorder).
plantgrowinginplant(foliage,tree).
plantrepresentemotion(flowers,purity).
plantrepresentemotion(flowers,purity).
emotionassociatedwithdisease(panic_attacks,disorder).
plantincludeplant(flowers,carnations).
plantrepresentemotion(gift,grace).
plantincludeplant(plants,blueberries).
plantincludeplant(plants,blueberries).
sportsgameteam(series,houston_astros).
plantrepresentemotion(roses,romance).
sportsgamewinner(world_cup,italy).
plantincludeplant(bushes,elderberry).
bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,infections).
sportsgameteam(playoffs,pittsburgh_steelers).
plantrepresentemotion(home,appreciation).
plantincludeplant(trees,palm).
plantincludeplant(plants,hydrangeas).
sportsgameteam(playoffs,houston_rockets).
sportsgameteam(playoffs,eagles).
sportsgameteam(playoffs,phoenix_suns).
sportsgameteam(playoffs,bulls).
sportsgameteam(series,yankees).
bacteriaisthecausativeagentofphysiologicalcondition(s_,endocarditis).
sportsgameloserscore(n2006_sugar_bowl,35).
emotionassociatedwithdisease(fear,ageing).
emotionassociatedwithdisease(fear,aids).
emotionassociatedwithdisease(fear,cancer).
bacteriaisthecausativeagentofphysiologicalcondition(streptococcus,infection).
bacteriaisthecausativeagentofphysiologicalcondition(streptococcus,infection).
languageofcountry(english_language,australia).
languageofcountry(english_language,australia).
sportusesstadium(soccer,wembley_stadium).
plantincludeplant(flowers,hydrangeas).
languageofcountry(german,germany).
sportsgamedate(world_cup,n2008).
sportsgamedate(world_cup,n2008).
languageofcountry(azerbaijani,azerbaijan).
languageofuniversity(english,stanford).
sportusesstadium(baseball,new_yankee_stadium).
academicfieldsuchasacademicfield(m_s,engineering).
bookwriter(animal_farm,george_orwell).
languageofuniversity(english,long_island_university).
bookwriter(about_a_boy,nick_hornby).
bookwriter(about_a_boy,nick_hornby).
academicfieldsuchasacademicfield(biology,ecology).
haswikipediaurl(legend_of_mana,'//en.wikipedia.org/wiki/Legend%20of%20Mana').
countrylocatedingeopoliticallocation(tonga,countries).
sportsgameteam(world_cup,brazil).
sportsgameteam(world_cup,france).
sportsgameteam(world_cup,croatia).
bookwriter(eragon,christopher_paolini).
bookwriter(eragon,paolini).
sportusesequipment(hockey,skate).
languageofcountry(portuguese,brasil).
countrycurrency(united_kingdom,pounds).
countrycurrency(united_kingdom,pounds).
sportsgamesport(n2000_world_series,baseball).
bookwriter(brothers_karamazov,fyodor_dostoevsky).
languageofuniversity(english,north_carolina_state_university).
academicfieldsuchasacademicfield(electrical_and_computer_engineering,computer_science).
arthropodcalledarthropod(tarantulas,spiders).
invertebratefeedonfood(larvae,plants).
invertebratefeedonfood(larvae,plants).
arthropodandotherarthropod(brown_recluse,spiders).
arthropodcalledarthropod(shrimp,shellfish).
arthropodlookslikeinsect(butterflies,moths).
arthropodcalledarthropod(shrimp,seafood).
arthropodandotherarthropod(recluse,brown_recluse_spider).
animalistypeofanimal(grubs,invertebrates).
arthropodcalledarthropod(lobsters,seafood).
arthropodcalledarthropod(scallops,seafood).
animalthatfeedoninsect(creatures,beetles).
arthropodandotherarthropod(recluse_spiders,brown_recluse).
arthropodcalledarthropod(lobster,seafood).
animaleatfood(birds,foods).
animalistypeofanimal(ocelots,animals).
animalsuchasinsect(parasites,ticks).
animalsuchasinsect(parasites,mosquitoes).
animalsuchasinvertebrate(brown_widow,widow_spider).
arachnidssuchasarachnids(poisonous_arachnids,black_widow_spiders).
arthropodcalledarthropod(black_widow_spiders,spiders).
arthropodandotherarthropod(spiders,black_widow_spiders).
animaleatfood(horses,meal).
animaleatvegetable(livestock,meal).
agriculturalproductincludingagriculturalproduct(livestock,horses).
agriculturalproductincludingagriculturalproduct(livestock,poultry).
animaleatfood(cows,dinner).
animaleatfood(cows,dinner).
animaleatfood(cows,hay).
animaleatfood(dogs,chocolate).
animaldevelopdisease(cats,epilepsy).
animaldevelopdisease(cats,acne).
animaldevelopdisease(cats,seizures).
animaleatfood(dogs,yogurt).
animaldevelopdisease(cats,allergic_reactions).
animaldevelopdisease(dogs,allergy).
animaldevelopdisease(cats,breast_feeding).
animaldevelopdisease(cats,alzheimers).
animaldevelopdisease(cats,alzheimers).
animaldevelopdisease(wild_animals,rabies).
animalistypeofanimal(bats,wild_animals).
animalistypeofanimal(rabbits,rodents).
animalistypeofanimal(monkeys,creatures).
animalistypeofanimal(bears,carnivores).
animalistypeofanimal(cattle,large_animals).
fishservedwithfood(salmon,horseradish_sauce).
animalthatfeedoninsect(pests,silverfish).
animalsuchasfish(endangered_species,salmon).
animalistypeofanimal(frogs,creatures).
animalistypeofanimal(frogs,predators).
animaldevelopdisease(pet,problems).
fishservedwithfood(trout,rice_pilaf).
fishservedwithfood(tuna,sauce).
fishservedwithfood(trout,sauce).
animalsuchasinvertebrate(filter_feeders,oysters).
animaldevelopdisease(child,mumps).
animaldevelopdisease(child,scabies).
animalsuchasinvertebrate(pests,worms).
animaldevelopdisease(child,disability).
animaldevelopdisease(child,hpv).
animaleatfood(frogs,larvae).
fishservedwithfood(salmon,french_bread).
ismultipleof(herds,bison).
chemicalistypeofchemical(heavy_metals,chemicals).
chemicalistypeofchemical(natural_gas,fossil_fuels).
chemicalistypeofchemical(gas,natural_resources).
chemicalistypeofchemical(oxygen,gas).
chemicalistypeofchemical(oxygen,compound).
chemicalistypeofchemical(radon,gas).
chemicalistypeofchemical(cadmium,pollutants).
chemicalistypeofchemical(dioxide,compound).
chemicalistypeofchemical(argon,gas).
chemicalistypeofchemical(argon,gas).
chemicalistypeofchemical(nitrogen,gas).
animaldevelopdisease(cats,cancer).
animaldevelopdisease(rabbits,cancer).
fishservedwithfood(linguine,sauce).
animalistypeofanimal(seals,marine_animals).
synonymfor(great_apes,gorillas).
fishservedwithfood(mahimahi,sauce).
chemicalistypeofchemical(mercury,emissions).
chemicalistypeofchemical(petroleum,fuels).
countryalsoknownas(ireland,great_britain).
sportsgameteam(tournament,germany).
sportsgameteam(tournament,brazil).
citylocatedinstate(hayward,california).
cityliesonriver(manhattan,east).
citycapitalofcountry(bucharest,romania).
citylocatedincountry(winnipeg,canada).
citylocatedincountry(winnipeg,canada).
citylocatedinstate(gunnison,colorado).
countrycurrency(bahamas,dollars).
statehascapital(utah,salt_lake).
statehascapital(utah,salt_lake).
countrycurrency(canada,dollars).
countrycurrency(canada,dollars).
countrycurrency(canada,dollars).
statehascapital(alabama,montgomery).
statehascapital(romania,bucharest).
statehascapital(romania,bucharest).
cityalsoknownas(philadelphia,philly).
countrycurrency(jamaica,dollar).
statehascapital(ne,omaha).
statehascapital(ne,omaha).
countrycurrency(kuwait,dollars).
statehascapital(wa,seattle).
countrycurrency(taiwan,dollars).
statelocatedingeopoliticallocation(britishcolumbia,canada).
citylocatedinstate(galveston,texas).
citylocatedincountry(tokyo,japan).
citylocatedinstate(hinsdale,illinois).
citylocatedinstate(key_biscayne,florida).
citylocatedincountry(hiroshima,japan).
citylocatedincountry(hiroshima,japan).
statehascapital(alberta,edmonton).
citycapitalofcountry(tripoli,libya).
citycapitalofcountry(tripoli,libya).
countrylocatedingeopoliticallocation(portugal,europe).
countrycurrency(liberia,dollars).
citylocatedinstate(santa_ana,california).
citycapitalofcountry(rangoon,burma).
citylocatedinstate(glendale,california).
citycapitalofcountry(damascus,syria).
citylocatedincountry(bahia_blanca,argentina).
citylocatedincountry(rio,brazil).
citycapitalofcountry(algiers,algeria).
citylocatedincountry(algiers,algeria).
cityalsoknownas(mumbai,bombay).
cityalsoknownas(bombay,mumbai).
citylocatedinstate(hyderabad,andhra_pradesh).
citylocatedinstate(hyderabad,andhra_pradesh).
citylocatedinstate(mumbai,maharashtra).
countryalsoknownas(ethiopia,eritrea).
countryalsoknownas(eritrea,ethiopia).
countryalsoknownas(kenya,ethiopia).
countryalsoknownas(djibouti,ethiopia).
countrycurrency(croatia,kuna).
countrycurrency(bulgaria,lev).
countrycurrency(ethiopia,birr).
countrycurrency(ecuador,sucre).
countrycurrency(estonia,kroon).
countrycurrency(andorra,euro).
countrycurrency(montenegro,euro).
countrycurrency(france,euros).
countrycurrency(greece,euros).
cityliesonriver(cairo,nile).
citylocatedincountry(puerto_iguazu,argentina).
citylocatedinstate(north_chicago,illinois).
cityalsoknownas(los_angeles,l_a_).
citycapitalofcountry(nairobi,kenya).
countryalsoknownas(afghanistan,tajikistan).
countryalsoknownas(tadjikistan,tajikistan).
countryalsoknownas(tajikistan,afghanistan).
statehascapital(northern_ireland,belfast).
citycapitalofcountry(lima,peru).
cityliesonriver(zurich,limmat).
countrycurrency(switzerland,francs).
countrycurrency(switzerland,francs).
citylocatedincountry(montreux,switzerland).
citylocatedincountry(montreux,switzerland).
statehascapital(aargau,aarau).
statelocatedincountry(aargau,switzerland).
citycapitalofcountry(caracas,venezuela).
cityliesonriver(little_falls,mississippi).
citylocatedinstate(lake_tahoe,california).
citylocatedinstate(colorado_city,colorado).
countrylocatedingeopoliticallocation(austria,europe).
citylocatedinstate(calabasas,california).
citycapitalofcountry(dacca,bangladesh).
countrylocatedingeopoliticallocation(brasil,countries).
statelocatedingeopoliticallocation(niedersachsen,germany).
statelocatedincountry(texas,united_state).
subpartof(fishers,indiana).
citylocatedinstate(montrose,colorado).
citylocatedincountry(jena,germany).
statelocatedingeopoliticallocation(illinois,u_s_a).
cityliesonriver(new_york_city,mohawk).
countrycurrency(scotland,pounds).
citylocatedinstate(flower_mound,texas).
statehascapital(united_arab_emirates,abu_dhabi).
cityliesonriver(new_orleans,mississippi).
politicsgroupconcernsissue(democratic_party,liberalism).
politicsgroupconcernsissue(national_rifle_association,gun_control).
athletewinsawardtrophytournament(kim_clijsters,australian_open).
directordirectedmovie(david_fincher,fight_club).
actorstarredinmovie(keanu_reeves,matrix).
directordirectedmovie(john_mctiernan,die_hard).
directordirectedmovie(john_mctiernan,die_hard).
motherofperson(mother,child).
musicianplaysinstrument(elvis_presley,guitar).
musicianplaysinstrument(elvis_presley,guitar).
politicianusendorsedbypoliticianus(john_mccain,president_bush).
personhasjobposition(cleopatra,queen).
visualartistartform(warhol,exhibits).
actorstarredinmovie(tom_cruise,magnolia).
directordirectedmovie(paul_thomas_anderson,magnolia).
actorstarredinmovie(tom_cruise,jerry_maguire).
actorstarredinmovie(tom_cruise,jerry_maguire).
actorstarredinmovie(tom_cruise,mission_impossible).
actorstarredinmovie(tom_cruise,mission_impossible).
actorstarredinmovie(tom_cruise,minority_report).
actorstarredinmovie(tom_cruise,minority_report).
actorstarredinmovie(tom_cruise,risky_business).
actorstarredinmovie(jackie_chan,rush_hour).
actorstarredinmovie(jackie_chan,rush_hour_2).
celebritysuchascelebrity(artists,john_denver).
motherofperson(mother,son).
motherofperson(mother,lord).
musicianinmusicartist(ian_astbury,cult).
parentofperson(mary,jesus_christ).
directordirectedmovie(akira_kurosawa,seven_samurai).
directordirectedmovie(akira_kurosawa,rashomon).
visualartistartmovement(leonardo_da_vinci,italian_renaissance).
visualartistartmovement(leonardo_da_vinci,italian_renaissance).
politicianusmemberofpoliticalgroup(tom_daschle,senate).
personhasjobposition(constantine,emperor).
actorstarredinmovie(mel_gibson,maverick).
motherofperson(mary,jesus_christ).
hashusband(madona,sean_penn).
hashusband(madona,sean_penn).
parentofperson(blessed_virgin_mary,jesus_christ).
directordirectedmovie(paul_haggis,crash).
ceoof(frederick_smith,federal_express).
actorstarredinmovie(bela_lugosi,dracula).
visualartistartmovement(vincent_van_gogh,expressionism).
celebritysuchascelebrity(artists,elvis_presley).
directordirectedmovie(david_lean,doctor_zhivago).
personhasjobposition(frank_walter_steinmeier,foreign_minister).
professionistypeofprofession(research,services).
professionistypeofprofession(orthopedic_surgeons,professionals).
professionistypeofprofession(specialists,doctors).
agriculturalproductcutintogeometricshape(cucumbers,cubes).
agriculturalproductcontainchemical(coffee,caffeine).
agriculturalproductcontainchemical(coffee,antioxidants).
agriculturalproductcontainchemical(yogurt,calcium).
agriculturalproductcamefromcountry(vanilla,comoros).
agriculturalproductcookedwithagriculturalproduct(cream,milk).
agriculturalproductcomingfromvertebrate(beef,cows).
agriculturalproductcontainchemical(beef,cholesterol).
agriculturalproductcamefromcountry(tea,kenya).
fooddecreasestheriskofdisease(green_tea,skin_cancer).
agriculturalproductincludingagriculturalproduct(crops,sugarcane).
vegetableproductioninstateorprovince(tomato,florida).
agriculturalproductcookedwithagriculturalproduct(beans,onions).
agriculturalproductincludingagriculturalproduct(crops,sugar_cane).
agriculturalproductcontainchemical(tea,antioxidant).
beveragemadefrombeverage(mango_juice,juice).
agriculturalproductgrowinginstateorprovince(sugar,mauritius).
vegetableproductioninstateorprovince(spinach,new_mexico).
agriculturalproductcookedwithagriculturalproduct(leek,potatoes).
agriculturalproductcutintogeometricshape(onions,squares).
furniturefoundinroom(beds,smoking_room).
furniturefoundinroom(beds,bunk_bed).
furniturefoundinroom(beds,porch).
furniturefoundinroom(beds,apartment).
drugpossiblytreatsphysiologicalcondition(serevent,asthma).
bakedgoodservedwithbeverage(bagels,juice).
bakedgoodservedwithbeverage(bagels,coffee).
productinstanceof(apple_macintosh,computers).
bakedgoodservedwithbeverage(breakfast,coffee).
bakedgoodservedwithbeverage(breakfast,tea).
bakedgoodservedwithbeverage(biscuit,tea).
bakedgoodservedwithbeverage(cakes,cream).
bakedgoodservedwithbeverage(honey,cream).
bakedgoodservedwithbeverage(honey,cream).
buildingfeaturemadefrombuildingmaterial(doors,vinyl).
bakedgoodservedwithbeverage(pie,chocolate).
bakedgoodservedwithbeverage(pie,chocolate).
vegetableproductioninstateorprovince(bean,north_dakota).
bakedgoodservedwithbeverage(marmalade,coffee).
fooddecreasestheriskofdisease(antioxidants,alzheimer).
bakedgoodservedwithbeverage(bun,coffee).
bakedgoodservedwithbeverage(bun,coffee).
bakedgoodservedwithbeverage(bread,banana).
drugpossiblytreatsphysiologicalcondition(ambien,sleeping).
bakedgoodservedwithbeverage(fresh_fruit,coffee).
foodcancausedisease(sugars,diabetes).
bakedgoodservedwithbeverage(toast,butter).
bakedgoodservedwithbeverage(sandwich,tea).
buildingfeaturemadefrombuildingmaterial(wall,cement).
bakedgoodservedwithbeverage(sandwiches,tea).
bakedgoodservedwithbeverage(sandwiches,tea).
beveragemadefrombeverage(cilantro,juice).
bakedgoodservedwithbeverage(fruits,coffee).
buildingfeaturemadefrombuildingmaterial(veneered_doors,veneers).
furniturefoundinroom(home_bar,living_room).
drugworkedonbyagent(metformin,bristol_myers_squibb).
productinstanceof(microsoft_windows,applications).
bakedgoodservedwithbeverage(bread,yoghurt).
drugpossiblytreatsphysiologicalcondition(medications,pain).
buildingfeaturemadefrombuildingmaterial(cabinet,steel).
buildingfeaturemadefrombuildingmaterial(windows,vinyl).
itemfoundinroom(beds,villa).
furniturefoundinroom(bookcase,living_room).
drugworkedonbyagent(paxil,glaxosmithkline).
bakedgoodservedwithbeverage(bread,red_wine).
bakedgoodservedwithbeverage(goodies,coffee).
bakedgoodservedwithbeverage(goodies,coffee).
buildingfeaturemadefrombuildingmaterial(door,screen).
furniturefoundinroom(beds,studio_rooms).
furniturefoundinroom(beds,dorm_room).
bakedgoodservedwithbeverage(cookies,white_chocolate).
bakedgoodservedwithbeverage(preserves,cream).
beveragecontainsprotein(breast_milk,enzyme).
agriculturalproductcontainchemical(tea,acids).
agriculturalproductgrowinginstateorprovince(tobacco,andhra_pradesh).
beveragecontainsprotein(milk,fatty_acid).
agriculturalproductcomingfromvertebrate(dairy_products,cattle).
bakedgoodservedwithbeverage(raspberries,cream).
bakedgoodservedwithbeverage(cookies,beverages).
agriculturalproductcontainchemical(tea,chemicals).
vegetableproductioninstateorprovince(onion,texas).
clothingmadefromplant(skirts,palmtrees).
clothingtogowithclothing(shirts,jackets).
clothingtogowithclothing(hoodie,shirt).
clothingtogowithclothing(sleeve,shirt).
clothingtogowithclothing(leather_jacket,jeans).
clothingtogowithclothing(shorts,cotton_shirts).
itemfoundinroom(hairdryer,private_bathroom).
itemfoundinroom(hairdryer,bathroom).
itemfoundinroom(spa_tub,bath).
furniturefoundinroom(bed,smoking_room).
furniturefoundinroom(accent_chair,living_room).
haswikipediaurl(world_clock,'//en.wikipedia.org/wiki/World%20clock').
clothingtogowithclothing(black_suit,shirt).
clothingtogowithclothing(black_suit,shirt).
furniturefoundinroom(headboard,bedroom).
furniturefoundinroom(ottoman,living_room).
furniturefoundinroom(sectional_sofa,living_room).
furniturefoundinroom(bed,property).
clothingtogowithclothing(pants,polo_shirts).
clothingtogowithclothing(polo_shirts,pants).
clothingtogowithclothing(sport_coat,pants).
clothingtogowithclothing(jersey,pants).
clothingtogowithclothing(jersey,pants).
clothingtogowithclothing(top,long_skirt).
clothingtogowithclothing(jersey,shorts).
clothingtogowithclothing(shorts,shoes).
itemfoundinroom(shower,bathroom).
itemfoundinroom(shower,adjacent_bathroom).
itemfoundinroom(shower,one_bathroom).
itemfoundinroom(shower,one_bathroom).
itemfoundinroom(shower,bathrooms).
itemfoundinroom(shower,large_bathrooms).
haswikipediaurl(enemy_engaged_2,'//en.wikipedia.org/wiki/Enemy%20Engaged%202').
foodcancausedisease(blood_sugar,diabetes).
itemfoundinroom(shower,luxury_bathroom).
agriculturalproductincludingagriculturalproduct(plants,sorghum).
agriculturalproductcookedwithagriculturalproduct(seasonings,chicken).
agriculturalproductincludingagriculturalproduct(fresh_herbs,parsley).
agriculturalproductincludingagriculturalproduct(herbs,parsley).
fooddecreasestheriskofdisease(natural,cancer).
agriculturalproductcamefromcountry(silk,nepal).
clothingtogowithclothing(sweaters,pants).
clothingtogowithclothing(shirt,linen_pants).
clothingtogowithclothing(shirt,bermuda_shorts).
clothingtogowithclothing(golf_shirts,shirts).
clothingtogowithclothing(long_sleeves,shirts).
clothingtogowithclothing(dresses,tops).
clothingtogowithclothing(dresses,tops).
clothingtogowithclothing(sweat_shirts,shirts).
weaponmadeincountry(bombs,u_s).
weaponmadeincountry(bombs,pakistan).
agriculturalproductcookedwithagriculturalproduct(potato_soup,onions).
clothingtogowithclothing(red_shirt,shorts).
weaponmadeincountry(nuclear_bombs,iran).
agriculturalproductincludingagriculturalproduct(products,oat).
agriculturalproductincludingagriculturalproduct(products,salt).
agriculturalproductincludingagriculturalproduct(products,barley).
agriculturalproductincludingagriculturalproduct(products,cocoa).
agriculturalproductincludingagriculturalproduct(products,citrus_fruits).
agriculturalproductincludingagriculturalproduct(products,margarine).
weaponmadeincountry(bows,brazil).
clothingtogowithclothing(sweat_shirt,pants).
itemfoundinroom(shower,master_bath).
writerwasbornincity(martin_luther_king_jr__,memphis).
agriculturalproducttoattractinsect(alfalfa,honey_bees).
agriculturalproductincludingagriculturalproduct(crops,alfalfa).
beveragecontainsprotein(breast_milk,proteins).
beveragecontainsprotein(dairy_foods,proteins).
beveragecontainsprotein(beer,proteins).
actorstarredinmovie(mark_hamill,star_wars).
haswikipediaurl(n2001_british_grand_prix,'//en.wikipedia.org/wiki/2001%20British%20Grand%20Prix').
directordirectedmovie(christopher_nolan,the_prestige).
actorstarredinmovie(sacha_baron_cohen,borat).
ceoof(steven_ballmer,microsoft).
celebritysuchascelebrity(film_stars,angelina_jolie).
hashusband(basemath,esau).
haswikipediaurl(basemath,'//en.wikipedia.org/wiki/Basemath').
drugpossiblytreatsphysiologicalcondition(valtrex,genital_herpes).
agriculturalproductcontainchemical(tea_leaves,amino_acid).
vegetableproductioninstateorprovince(corn,kansas).
agriculturalproductcomingfromvertebrate(milk,farms).
ceoof(hank_mckinnell,pfizer).
musicianplaysinstrument(franz_liszt,piano).
politicianusendorsedbypoliticianus(gore,clinton).
politicianusmemberofpoliticalgroup(harry_reid,senate).
politicianusendorsedbypoliticianus(joe_biden,clinton).
musicianplaysinstrument(bono,guitar).
musicianinmusicartist(bono,u2).
musicianinmusicartist(bono,u2).
politicianholdsoffice(kennedy,senator).
politicianusendorsedbypoliticianus(w___bush,cheney).
politicianusendorsedbypoliticianus(presidential_candidate_barack_obama,clinton).
personwasborninstateorprovince(monica,california).
personhasresidenceingeopoliticallocation(arnold_schwarzenegger,california).
politicianusmemberofpoliticalgroup(antonin_scalia,supreme_court).
politicianholdsoffice(barak_obama,president).
politicianholdsoffice(barak_obama,senator).
politicianholdsoffice(barak_obama,senators).
countrylocatedingeopoliticallocation(egypt,countries).
directordirectedmovie(steven_spielberg,jaws).
directordirectedmovie(steven_spielberg,jurassic_park).
citylocatedincountry(new_dehli,india).
directordirectedmovie(martin_scorsese,goodfellas).
directordirectedmovie(martin_scorscese,goodfellas).
actorstarredinmovie(joe_pesci,goodfellas).
actorstarredinmovie(ray_liotta,goodfellas).
directordirectedmovie(quentin_tarantino,pulp_fiction).
actorstarredinmovie(john_travolta,pulp_fiction).
buildinglocatedincity(sears_tower,chicago).
buildinglocatedincity(sears_tower,chicago).
buildinglocatedincity(sears_tower,chicago).
attractionofcity(circus_maximus,rome).
hotelincity(quality_suites,toronto).
newspaperincity(the_stranger,seattle).
newspaperincity(the_stranger,seattle).
mountaininstate(mount_whitney,california).
mountaininstate(castro_peak,california).
aquariumincity(vancouver_aquarium,vancouver).
placeofworshippracticesreligion(westminster_abbey,catholicism).
aquariumincity(dallas_aquarium,dallas).
airportincity(istanbul_airport,istanbul).
transportationincity(metro_system,montreal).
hospitalincity(the_vancouver_clinic,vancouver).
hospitalincity(the_vancouver_clinic,vancouver).
hotelincity(omni_chicago_hotel,chicago).
hotelincity(georgia_tech_hotel_and_conference_center,atlanta).
placeofworshippracticesreligion(zen_mountain_monastery,buddhism).
placeofworshippracticesreligion(zen_mountain_monastery,buddhism).
mountaininstate(calico_mountains,california).
attractionofcity(colosseum,rome).
attractionofcity(colosseum,rome).
museumincity(toronto_s_historic_museums,toronto).
zooincity(toronto_zoo,toronto).
hospitalincity(toronto_general,toronto).
lakeinstate(lake_tahoe,california).
lakeinstate(lake_tahoe,california).
lakeinstate(lake_tahoe,california).
mountaininstate(death_valley,california).
aquariumincity(gulf_of_maine_research_institute,portland).
mountaininstate(mauna_kea,hawaii).
hospitalincity(vancouver_general_hospital,vancouver).
placeofworshippracticesreligion(the_hurva_synagogue,judaism).
buildinglocatedincity(miami_international_airport,miami).
stadiumlocatedincity(fedex_forum,memphis).
placeofworshippracticesreligion(east_ham_baptist_church,baptist).
organizationacronymhasname(seal,sea).
airportincity(mumbai_airport,mumbai).
placeofworshippracticesreligion(muktinath,hinduism).
placeofworshippracticesreligion(banteay_srei,hinduism).
haswikipediaurl(lindstrom_peak,'//en.wikipedia.org/wiki/Lindstrom%20Peak').
parkincity(south_kensington,london).
airportincity(cairo_international_airport,cairo).
mountaininstate(capitol_peak,colorado).
parkincity(covent_garden,london).
lakeinstate(deep_creek_lake,maryland).
newspaperincity(evening_standard,london).
hotelincity(courtyard_by_marriott_lax,los_angeles).
placeofworshippracticesreligion(sleepy_hollow_presbyterian_church,presbyterianism).
haswikipediaurl(boswell_bay_airport,'//en.wikipedia.org/wiki/Boswell%20Bay%20Airport').
mountaininstate(kilauea_volcano,hawaii).
newspaperincity(toronto_star,toronto).
placeofworshippracticesreligion(the_great_mosque_of_taza,islam).
placeofworshippracticesreligion(the_great_mosque_of_taza,islam).
buildinglocatedincity(three_rivers_stadium,pittsburgh).
airportincity(lester_b__pearson_international_airport,toronto).
airportincity(bwi,baltimore).
mountaininstate(everest,nepal).
synonymfor(executive_officers,board).
buildinglocatedincity(memphis_international,memphis).
airportincity(memphis_international,memphis).
airportincity(miami_international_airport,miami).
airportincity(bristol_airport,bristol).
parkincity(greenwich,london).
museumincity(austin_children_museum,austin).
hotelincity(hotel_57,new_york_city).
haswikipediaurl(hollywood_wax_museum,'//en.wikipedia.org/wiki/Hollywood%20Wax%20Museum').
museumincity(hollywood_wax_museum,los_angeles).
stadiumlocatedincity(ford_field,detroit).
transportationincity(airtrain_light_rail,new_york_city).
hotelincity(the_lombardy,new_york_city).
museumincity(bethesda_fountain,new_york_city).
attractionofcity(kingdome,seattle).
hospitalincity(m_d__anderson,houston).
attractionofcity(quicken_loans_arena,cleveland).
buildinglocatedincity(quicken_loans_arena,cleveland).
placeofworshippracticesreligion(san_francisco_zen_center,buddhism).
personbelongstoorganization(edgar_bronfman_jr_,warner_music).
agriculturalproductincludingagriculturalproduct(legumes,alfalfa).
agriculturalproductincludingagriculturalproduct(beverages,milk).
beveragemadefrombeverage(grapefruit_juice,juice).
productinstanceof(android,systems).
personbelongstoorganization(jeff_greenfield,cnn).
competeswith(google,yahoo_local).
athleteplayssport(john_mcenroe,tennis).
athletebeatathlete(ivan_lendl,john_mcenroe).
athletewinsawardtrophytournament(john_mcenroe,us_open).
leaguestadiums(nfl,soldier_field).
personhasresidenceingeopoliticallocation(bill_clinton,arkansas).
athleteplayssport(sachin_tendulkar,cricket).
musicartistgenre(jewel,pop).
musicartistgenre(roy_orbison,rock).
personattendsschool(tolkien,oxford).
musicartistgenre(lou_reed,rock).
musicartistgenre(ricky_martin,pop).
musicartistgenre(wham,pop).
musicianplaysinstrument(bach,piano).
musicianplaysinstrument(beethoven,piano).
musicianplaysinstrument(beethoven,piano).
musicianplaysinstrument(emerson_lake_palmer,piano).
politicianusholdsoffice(nancy_pelosi,speaker).
organizationacronymhasname(nba,national_basketball_association).
athleteplayssport(anna_kournikova,tennis).
athleteplayssport(dinara_safina,tennis).
athleteplayssport(lleyton_hewitt,tennis).
athletewinsawardtrophytournament(lleyton_hewitt,us_open).
athleteplayssport(marat_safin,tennis).
athletewinsawardtrophytournament(marat_safin,australian_open).
parentofperson(noah,shem).
actorsuchasactor(western_movie_actors,clint_eastwood).
politicianusendorsedbypoliticianus(bush,dick_cheney).
politicianusmemberofpoliticalgroup(bob_dole,senate).
coachesinleague(doc_rivers,nba).
actorstarredinmovie(chevy_chase,vacation).
politicianusholdsoffice(clinton,presidents).
musicartistgenre(immortal,black_metal).
politicianusendorsedbypoliticianus(sen___barack_obama,clinton).
musicartistgenre(alice_cooper,hard_rock).
politicianusendorsedbypoliticianus(clinton,michael_moore).
politicianusendorsedbypoliticianus(clinton,jimmy_carter).
athletebeatathlete(svetlana_kuznetsova,williams).
musicartistgenre(kylie,pop).
athleteplayssport(annika_sorenstam,golf).
leaguestadiums(mlb,camden_yards).
athleteplayssport(john_daly,golf).
politicianusendorsedbypoliticianus(cheney,bush).
politicianusendorsedbypoliticianus(lieberman,clinton).
athleteplayssport(tommy_haas,tennis).
personleadscity(andrew_young,atlanta).
mlauthorofsoftware(andrew_mccallum,mallet).
musicianplaysinstrument(itzhak_perlman,violin).
musicianplaysinstrument(joshua_bell,violin).
politicianholdsoffice(president_chirac,president).
personhascitizenship(leonardo_boff,brazil).
musicianplaysinstrument(james_hetfield,guitar).
leaguestadiums(nba,fedex_forum).
worksfor(balmer,microsoft).
leaguestadiums(nba,conseco_fieldhouse).
leaguestadiums(nba,thomas___mack_center).
athleteplayssport(phil_mickelson,golf).
musicianinmusicartist(jack_bruce,cream).
athleteplayssport(adam_petty,nascar).
athleteplayssport(ryan_newman,car_racing).
leaguestadiums(nascar,bristol_motor_speedway).
leaguestadiums(nascar,bowman_gray_stadium).
leaguestadiums(nascar,auto_club_speedway).
athleteplayssport(carl_edwards,car_racing).
teamplaysinleague(san_francisco_49ers,nfl).
personleadscity(cory_booker,newark).
musicartistgenre(elvis,blues).
musicartistgenre(elvis,blues).
politicianholdsoffice(governor_mitt_romney,senator).
politicianusmemberofpoliticalgroup(john_g___roberts,supreme_court).
musicianinmusicartist(the_edge,u2).
musicianplaysinstrument(b_b__king,guitar).
musicianinmusicartist(nicole_scherzinger,pussycat_dolls).
athleteplayssport(mark_allen,triathlon).
marriedinyear(david_selden,n1956).
personhasresidenceingeopoliticallocation(goffredo_marcaccini,mexico).
teamplaysincity(miami_heat,miami).
teamplaysinleague(sixers,nba).
teamplaysinleague(dallas_mavericks,nba).
teamplaysincity(broncos,denver).
teamplaysincity(broncos,denver).
teamplaysincity(broncos,denver).
teamplaysincity(dallas_mavericks,dallas).
teamhomestadium(indiana_pacers,conseco_fieldhouse).
teamhomestadium(fc_barcelona,camp_nou).
teamplaysincity(astros,houston).
teamplayssport(sooners,games).
athleteplayssport(george_foreman,boxing).
athleteplayssport(george_foreman,boxing).
athleteplayssport(george_foreman,boxing).
athleteplayssport(george_foreman,boxing).
athleteplaysinleague(kurt_warner,nfl).
teamhomestadium(st___louis_cardinals,busch_stadium).
bookwriter(charlotte_s_web,e_b__white).
teamplaysinleague(pittsburgh_steelers,nfl).
teamplaysagainstteam(pittsburgh_steelers,minnesota_vikings).
teamplaysincity(indians,cleveland).
companyalsoknownas(sysco,sysco_corp).
televisionstationincity(kiro,seattle).
companyeconomicsector(british_gas,energy).
companyeconomicsector(exxonmobil,energy).
companyeconomicsector(china_mobile,telecom).
automakerproducesmodel(jeep,jeep_wrangler_unlimited).
automakerproducesmodel(jeep,jeep_grand_cherokee).
automakerproducesmodel(toyota,tundra).
automakerproducesmodel(toyota,camry).
producesproduct(toyota,corolla).
producesproduct(toyota,camry).
automakerproducesmodel(toyota,camry_hybrid).
producesproduct(toyota,toyota_matrix).
automobilemakerdealersincountry(toyota,japan).
producesproduct(pontiac,bonneville).
producesproduct(honda,insight).
producesproduct(honda,insight).
automakerproducesmodel(honda,fit).
automakerproducesmodel(honda,fit).
automakerproducesmodel(honda,honda_civic).
automakerproducesmodel(honda,honda_civic).
automakerproducesmodel(lincoln,navigator).
companyeconomicsector(audi,auto).
automobilemakercardealersinstateorprovince(kia,missouri).
companyeconomicsector(british_petroleum,oil).
producesproduct(honda,element).
producesproduct(volkswagen,eos).
automakerproducesmodel(volkswagen,eos).
automobilemakerdealersincity(peugeot,london).
automakerproducesmodel(honda,odyssey).
producesproduct(microsoft,xbox).
producesproduct(microsoft,xbox).
televisionstationaffiliatedwith(kcit,fox).
companyeconomicsector(geico,insurance).
televisionstationincity(kcnc,denver).
producesproduct(microsoft,microsoft_excel).
producesproduct(microsoft,microsoft_excel).
automakerproducesmodel(honda,prelude).
bankbankincountry(citibank,australia).
companyeconomicsector(honda,automobile).
companyeconomicsector(shell,energy).
automakerproducesmodel(honda,pilot).
producesproduct(honda,pilot).
itemfoundinroom(toilette,bathroom).
synonymfor(board,committee).
istallerthan(great_pyramid_of_giza,eiffel_tower).
agentparticipatedinevent(impact,injury).
companyeconomicsector(citgo,oil).
itemfoundinroom(bath_tub,bathrooms).
synonymfor(mac,apple_computer).
synonymfor(vice,learning).
haswikipediaurl(super_ninja_boy,'//en.wikipedia.org/wiki/Super%20Ninja%20Boy').
companyalsoknownas(att,at_t).
synonymfor(committee,board).
organizationacronymhasname(nsf,national_science_foundation).
itemfoundinroom(fridge,kitchen).
itemfoundinroom(fridge,kitchenette).
organizationacronymhasname(nsc,national_security_council).
fooddecreasestheriskofdisease(fibre,cancer).
organizationacronymhasname(usps,postal_service).
organizationacronymhasname(cbo,congressional_budget_office).
synonymfor(management_team,board).
organizationacronymhasname(fca,farm_credit_administration).
itemfoundinroom(tub,bath).
itemfoundinroom(tub,home).
itemfoundinroom(tub,home).
itemfoundinroom(tub,ensuite_bathroom).
itemfoundinroom(tub,full_bath).
itemfoundinroom(tub,private_bath).
istallerthan(eiffel_tower,washington_monument).
agentparticipatedinevent(evidence,injury).
agentcontributedtocreativework(mark_twain,adventures_of_tom_sawyer).
agentcontributedtocreativework(mark_twain,adventures_of_huckleberry_finn).
organizationacronymhasname(fda,food_and_drug_administration).
synonymfor(department,ministry).
fooddecreasestheriskofdisease(laxative,cancer).
subpartof(point,air).
subpartof(cleveland,ohio).
synonymfor(windy_city,chicago).
agentparticipatedinevent(changes,part).
animalistypeofanimal(kangaroo,marsupials).
persongraduatedfromuniversity(michelle,princeton_university).
itemfoundinroom(oven,modern_kitchen).
agentcontributedtocreativework(charles_dickens,a_tale_of_two_cities).
agentcontributedtocreativework(jane_austen,pride_and_prejudice).
synonymfor(macintosh,apple_computer).
companyalsoknownas(amd,advanced_micro_devices).
teamplaysagainstteam(florida_marlins,indians).
automakerproducesmodel(ford,edge).
producesproduct(microsoft,explorer).
producesproduct(microsoft,explorer).
televisionstationaffiliatedwith(wlov,fox).
subpartof(la_paz,bolivia).
radiostationincity(wfmt,chicago).
haswikipediaurl(arkalyk,'//en.wikipedia.org/wiki/Arkalyk').
haswikipediaurl(mapreduce,'//en.wikipedia.org/wiki/MapReduce').
hasofficeincity(air_jamaica,new_york_city).
headquarteredin(verizon,new_york_city).
athleteplayssportsteamposition(warrick_dunn,running_back).
competeswith(nissan,honda).
haswife(esau,basemath).
bankbankincountry(hsbc,singapore).
leaguestadiums(nfl,invesco_field_at_mile_high).
personhascitizenship(king_ptolemy,egypt).
politicianusholdsoffice(president_obama,president).
musicartistgenre(gentle_giant,rock).
actorstarredinmovie(jackson,pulp_fiction).
agentcontributedtocreativework(mario_puzo,the_godfather).
personhasjobposition(william_the_conqueror,king).
hotelincity(holiday_inn_midtown_57th_street,new_york_city).
haswife(prince_william,kate_middleton).
actorstarredinmovie(kevin_spacey,k_pax).
languageofcountry(english,great_britain).
musicartistgenre(arctic_monkeys,rock).
istallerthan(lebanon,people).
