rel(rio_de_janeiro, possui, assalto).
rel(sao_gonçalo, possui, assalto).
rel(niteroi, possui, qualidade).
rel(niteroi, possui, UFF).
rel(UFF, oferece, computacao).
rel(UFF, possui, comunista).
rel(comunista, gostade, daropopo).
rel(pedra, ficaem, niteroi).
rel(pedra, faz, comidamerda).