:- \+musicalbum(comfortably_numb).
:- \+mlarea(linear_algebra).
:- \+street(highway_824).
:- \+language(sauria_paharia_language).
:- \+reptile(san_diego_nightsnake).
:- \+museum(museums_in_chicago).
:- \+date(sep_58).
:- \+visualartmovement(post_gender).
:- \+filmfestival(alberta_student_film_festival).
:- \+geometricshape(two_vertical_lines).
:- \+movie(aliens).
:- \+weatherphenomenon(air).
:- \+sportsgame(world_cup).
:- \+buildingmaterial(brass).
:- \+buildingmaterial(brass).
:- \+currency(pesetas).
:- \+emotion(acceptance).
:- \+fungus(chitin).
:- \+physicalcharacteristic(greatness).
:- \+everypromotedthing(doctor_death).
:- \+bodypart(specific_area).
:- \+book(the_member_of_the_wedding).
:- \+academicfield(biotechnology_laboratory_technology).
:- \+boardgame(life_and_monopoly).
:- \+consumerelectronicitem(psp_memory_8gb).
:- \+eventoutcome(control).
:- \+physicsterm(n72_percent).
:- \+book(titus_andronicus).
:- \+geometricshape(radial_lines).
:- \+geometricshape(line_segments_lines_and_rays).
:- \+product(rockstar_games).
:- \+date(oct_43).
:- \+museum(museum_im_amtshaussch_pfla).
:- \+charactertrait(ambagiousness).
:- \+musicalbum(appetite_for_destruction).
:- \+sportsgame(finals).
:- \+book(purgatorio).
:- \+politician(luiz_inacio_lula_da_calendar_silva).
:- \+sportsgame(first_playoff).
:- \+vegetable(cherry_leaves).
:- \+radiostation(wyut).
:- \+sportsteam(italy).
:- \+county(logan_township_cuming_county).
:- \+date(feb_55).
:- \+boardgame(traditional_chinese_game).
:- \+condiment(popular_sauce).
:- \+chemical(greenhouse_gases).
:- \+weatherphenomenon(strong_headwind).
:- \+mlarea(artificial_intelligence).
:- \+mlarea(artificial_intelligence).
:- \+visualartform(photo_copier).
:- \+plant(cut_flowers).
:- \+cheese(somerset_brie_cheese).
:- \+bank(h_r_block_bank).
:- \+company(air_niugini).
:- \+date(jul_35).
:- \+park(sim_s_themepark).
:- \+flooritem(garden_rattan_sofa).
:- \+skyscraper(the_aam_tower).
:- \+city(pest).
:- \+airport(flybalaton_airport).
:- \+beach(grand_palladium_resort_beach).
:- \+magazine(singer_and_musician_magazine).
:- \+organization(kremlin).
:- \+clothing(women__s_athletic_shoes).
:- \+bank(swiss_national_bank).
:- \+male(alex_donnelly).
:- \+nut(pumpkinseed).
:- \+artery(surface_blood_vessels).
:- \+city(purchase).
:- \+militaryconflict(battle_of_domb__s).
:- \+mediatype(disk_driver).
:- \+kitchenitem(cookware_stockpot).
:- \+clothing(stola).
:- \+location(central_intelligence_agency).
:- \+clothing(cuff).
:- \+artery(left_coronary_atery).
:- \+insect(moths_and_wasp_moths).
:- \+vertebrate(two_goats).
:- \+recipe(receipes).
:- \+furniture(accenttables).
:- \+zoo(zoos_in_switzerland).
:- \+vein(valve).
:- \+bank(morgan_stanley___company).
:- \+emotion(inheritress).
:- \+country(caribbean_island).
:- \+musician(barber).
:- \+protein(simvastatin).
:- \+filmfestival(shortmoves_international_filmfestival).
:- \+website(google__yahoo).
:- \+company(google__yahoo).
:- \+condiment(salad).
:- \+plant(floral_arrangements).
:- \+color(goldilocks).
:- \+color(red_gold).
:- \+artery(neck_software).
:- \+kitchenitem(cookie_sheets_bake).
:- \+buildingmaterial(steel_development).
:- \+buildingmaterial(steel_development).
:- \+nongovorganization(creator_s_rights_party).
:- \+politicsissue(george_w__bush).
:- \+bakedgood(the_vegetarian_restaurant_s_lemon_poppyseed_cake).
:- \+charactertrait(quality_web_design).
:- \+charactertrait(quality_resources).
:- \+charactertrait(misconduct).
:- \+charactertrait(quality_leads).
:- \+charactertrait(quality_legal_representation).
:- \+charactertrait(quality_baby_products).
:- \+charactertrait(quality_digital_photographs).
:- \+charactertrait(quality_vacation_homes).
:- \+charactertrait(quality_outputs).
:- \+currency(four_different_currencies).
:- \+condiment(fry_s_chocolate_sauce).
:- \+food(caterpillars).
:- \+politicianus(michal_cjakovsky).
:- \+year(c__1888).
:- \+sportsteam(university_of_georgia).
:- \+politicsissue(architecture).
:- \+buildingmaterial(filigree).
:- \+ethnicgroup(german___english).
:- \+nut(nutritious_dry_fruits).
:- \+weatherphenomenon(luxurious_air).
:- \+fish(scorpididae).
:- \+emotion(summer_doldrums).
:- \+date(abr_29).
:- \+weapon(space_station).
:- \+musicsong(willkommen).
:- \+braintissue(ventral_cord_deformity).
:- \+blog(the_gazette_telegraph).
:- \+blog(the_gazette_telegraph).
:- \+race(gp_du_1er_mai___hoboken).
:- \+sportsgame(playoffs).
:- \+agriculturalproduct(steak).
:- \+automobilemodel(honda_mc_rc212v).
:- \+recipe(best_of_british_recipes).
:- \+city(le).
:- \+zoo(busch_gardens_tampa_bay).
:- \+park(busch_gardens_tampa_bay).
:- \+profession(gifted_artists).
:- \+profession(gifted_artists).
:- \+fruit(two_coconuts).
:- \+election(elections_and_referendums).
:- \+gamescore(n0_1).
:- \+color(lt__foliage_green).
:- \+kitchenitem(paper_towel).
:- \+musicgenre(atmospheric_funeral_doom_metal).
:- \+food(beef_porterhouse_and_vegetables).
:- \+ethnicgroup(waigali).
:- \+fruit(speckled_red_kidney_beans).
:- \+nongovorganization(american_tradition_party).
:- \+musicartist(the_all_stars).
:- \+televisionshow(the_human_face).
:- \+braintissue(a_space_odyssey_rostral_anterior_cingulate_cortex).
:- \+sportsteamposition(def_interior).
:- \+highway(county_street).
:- \+protein(sushi_repeat_containing_protein).
:- \+perceptionaction(garden_grove_engineering).
:- \+musicinstrument(country_blues_guitar).
:- \+mediatype(several_literary_journals).
:- \+bakedgood(_cookies).
:- \+currency(currancy).
:- \+currency(currancy).
:- \+recipe(insecure_recipes).
:- \+room(n88_bedrooms).
:- \+sportsgame(n1939_major_league_baseball_season).
:- \+food(leaf).
:- \+highway(north_donnelly_street).
:- \+vegetable(small_leaves).
:- \+artery(modest_vessels).
:- \+sportsgame(n1960_nba_finals).
:- \+tool(cordless_reciprocating_saws).
:- \+everypromotedthing(armistice_day).
:- \+mlconference(www_freewebsitetemplates_com).
:- \+mlconference(www_freewebsitetemplates_com).
:- \+protein(autoantibodies).
:- \+politicaloffice(attorney_f).
:- \+politicaloffice(attorney_f).
:- \+politicaloffice(estimator).
:- \+bedroomitem(atomic_clock).
:- \+wallitem(atomic_clock).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+braintissue(current_research_regarding_the_human_brain).
:- \+wallitem(astronomical_clock).
:- \+bedroomitem(astronomical_clock).
:- \+musicinstrument(percussion).
:- \+convention(united_kingdom___motherwell_cactus_comicon).
:- \+currency(pound_service).
:- \+food(romaine).
:- \+recipe(recipes_oil).
:- \+university(god_s_bible_school_and_college).
:- \+wine(synergistic_blend).
:- \+wine(synergistic_blend).
:- \+fruit(theseed).
:- \+fruit(theseed).
:- \+recipe(recipe_people).
:- \+celebrity(joan_gerber).
:- \+furniture(bench_seats).
:- \+mammal(ground_sloth).
:- \+vein(vena_dorsalis_clitoridis_profunda).
:- \+clothing(sneaks).
:- \+sportsteam(ohio_university_chillicothe).
:- \+mammal(mousedeers).
:- \+vegetable(tomatoes_stuffed_potatoes_cheese).
:- \+museum(museum_massing).
:- \+ethnicgroup(wapanese).
:- \+politicianus(kevin_powell).
:- \+eventoutcome(free_access).
:- \+tool(tools_program).
:- \+mammal(seven_animals).
:- \+female(jorja_fox).
:- \+celebrity(jorja_fox).
:- \+agriculturalproduct(organ_meats).
:- \+emotion(unhumorousness).
:- \+highway(right_of_way).
:- \+sportsgame(draft).
:- \+date(september_15___16).
:- \+furniture(bed_benches).
:- \+sportsteam(santa_barbara_college_of_oriental_medicine).
:- \+personalcareitem(fda_approved_prescription_drugs).
:- \+awardtrophytournament(n2009_super_bowl).
:- \+householditem(phonelines).
:- \+clothing(kids_clothes_and_shoes_womens_discount_shoes).
:- \+bank(bank_of_america_online_banking).
:- \+geopoliticallocation(orange).
:- \+bakedgood(bread_computer).
:- \+ethnicgroup(americanese).
:- \+sportsequipment(possible_balls).
:- \+personsouthamerica(jesus_love).
:- \+country(united_state).
:- \+bedroomitem(radio_interviews_of_wwii_airmen).
:- \+bedroomitem(radio_interviews_of_wwii_airmen).
:- \+fungus(list_of_deadly_fungi).
:- \+hallwayitem(there_are_a_variety_of_different_kits_for_window).
:- \+amphibian(choco_toad).
:- \+country(bassas_da_india).
:- \+personeurope(gogol).
:- \+tool(quality_tools).
:- \+programminglanguage(web_page_source_code).
:- \+mediatype(several_publications).
:- \+sportsgame(ball).
:- \+county(berwickshire).
:- \+drug(oxygen).
:- \+year(n1950___1957).
:- \+biotechcompany(adaptive_broadband_corp).
:- \+nut(feeds).
:- \+year(n1917___1919).
:- \+mlconference(www_nationalcreditfixers_com).
:- \+agriculturalproduct(cat).
:- \+monarch(alarming).
:- \+personsouthamerica(prophet_mohamed).
:- \+boardgame(chess_books).
:- \+physicalaction(flat_plate_comprising_a_bonding).
:- \+emotion(unreproductiveness).
:- \+musicinstrument(giutar).
:- \+country(uk__netherlands).
:- \+sportsevent(picnic_games).
:- \+insect(stink_bugs_and_shield_bugs).
:- \+musicartist(zep).
:- \+sportsgame(n1950_st__louis_cardinals_season).
:- \+visualartmovement(dogmatism).
:- \+visualartmovement(post_colonialism).
:- \+chef(jerome_david_selby_reddick).
:- \+coach(willis_otanez).
:- \+fungus(dipping_sauce).
:- \+physicalaction(product_packaging).
:- \+charactertrait(quality_futon).
:- \+blog(the_conway_log_cabin_democrat).
:- \+airport(three_rivers_municipal_dr__haines_airport).
:- \+mlconference(www_porntube_com).
:- \+visualartmovement(polyomavirus).
:- \+weatherphenomenon(play_northern_winds).
:- \+farm(grocery_store).
:- \+boardgame(game_and).
:- \+bedroomitem(radio_technician).
:- \+fruit(how_to_cook_pumpkin_seeds).
:- \+wallitem(coffee_table_clock).
:- \+biotechcompany(verizon).
:- \+terroristorganization(gaza_land).
:- \+personafrica(richard_m__stallman).
:- \+terroristorganization(islamic_calendar).
:- \+city(fishers).
:- \+bodypart(lymph_node_neck_cancer).
:- \+trainstation(arkansas_state_university).
:- \+fungus(caramel_sauce).
:- \+scientist(j_k__rowling).
:- \+scientist(j_k__rowling).
:- \+monarch(aleutian_range).
:- \+sportsevent(n1997_grand_prix_performance_numbers).
:- \+trainstation(terra_state_community_college).
:- \+mlalgorithm(earning_model).
:- \+mlarea(earning_model).
:- \+religion(portland_church).
:- \+nut(he_was_the_first_to_find_the_nut).
:- \+mlconference(www_nationalrail_co_uk).
:- \+sport(diving_lessons).
:- \+personcanada(robert_hickson).
:- \+politicalparty(partidos_pol_ticos_en_italia).
:- \+terroristorganization(islamic_republic_of_iran).
:- \+year(s_1839).
:- \+mlarea(boyfriend_model).
:- \+mlalgorithm(boyfriend_model).
:- \+musician(plymouth_canton_symphony_orchestra).
:- \+county(lancastershire).
:- \+race(edit).
:- \+boardgame(edit).
:- \+agriculturalproduct(machine).
:- \+conference(www_t_mobile_co_uk).
:- \+charactertrait(quality_rental_apartments).
:- \+bedroomitem(radio_staion_from_byu).
:- \+emotion(popeless).
:- \+coach(steve).
:- \+everypromotedthing(salvation_army_new).
:- \+transportation(metro_call_a_ride).
:- \+sportsgame(n1986_st__louis_cardinals_season).
:- \+disease(hyperlipidema).
:- \+monarch(alfred_taylor).
:- \+beverage(chips).
:- \+fish(appetizer).
:- \+astronaut(united_states_senate).
:- \+automobilemaker(motorized).
:- \+stateorprovince(delta).
:- \+medicalprocedure(risks_of_vascular_surgery).
:- \+beverage(milk_chocolate).
:- \+bedroomitem(radio_interface_specification_layer_1).
:- \+country(pa).
:- \+recordlabel(recordings).
:- \+charactertrait(quality_vapor).
:- \+mlconference(www_thepensionservice).
:- \+weapon(gun_products).
:- \+conference(www_206_108_49_36).
:- \+sportsgame(tournament).
:- \+sportsgame(n2007_postseason).
:- \+chef(jerome_chlorine_dioxide_debra).
:- \+chef(jerome_chlorine_dioxide_debra).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+grain(n1_4_cup_breadcrumbs).
:- \+personafrica(steven_spielberg).
:- \+bedroomitem(traditional_clock).
:- \+meat(pork_barbecue_recipe).
:- \+legume(using_3_kinds_of_canned_beans).
:- \+emotion(unpopularness).
:- \+placeofworship(scripps_institute_of_oceanography).
:- \+placeofworship(scripps_institute_of_oceanography).
:- \+aquarium(scripps_institute_of_oceanography).
:- \+aquarium(scripps_institute_of_oceanography).
:- \+trainstation(university_of_virginia_law_school).
:- \+recordlabel(pennsylvania_marriage_records).
:- \+recordlabel(pennsylvania_marriage_records).
:- \+blog(the_st__louis_post_dispatch).
:- \+musicgenre(progressive_rock_metal_mathcore).
:- \+year(may_2000).
:- \+nondiseasecondition(fourteen_day_period).
:- \+nondiseasecondition(fourteen_day_period).
:- \+planet(earth_moving_equipments).
:- \+planet(earth_moving_equipments).
:- \+trainstation(university_of_michigan_business_school).
:- \+trainstation(university_of_michigan_business_school).
:- \+trainstation(university_of_michigan_business_school).
:- \+monument(penn_museum).
:- \+person(about_wikipedia).
:- \+animal(pademelons).
:- \+terroristorganization(army).
:- \+model(kathy_najimy).
:- \+actor(kate_middleton).
:- \+country(austria___vienna).
:- \+buildingmaterial(machined).
:- \+physicsterm(n4_9_percent_last_month).
:- \+musicartist(vibrators).
