:- \+fungus(banana_peppers).
:- \+planet(work_from_home).
:- \+televisionshow(real_life).
:- \+televisionshow(real_life).
:- \+musicalbum(the_holy_bible).
:- \+disease(smoking).
:- \+disease(abnormalities).
:- \+nondiseasecondition(prggnancy).
:- \+ethnicgroup(mam).
:- \+weatherphenomenon(air).
:- \+musicfestival(summer_music_festivals_illinois).
:- \+sportsgame(world_cup).
:- \+race(sparkassen_m_nsterland_giro).
:- \+sportsevent(n2000_in_india).
:- \+hobby(boxing).
:- \+sport(scouting).
:- \+sport(cheerleading).
:- \+year(n1958_1969).
:- \+year(n1_601).
:- \+year(n1901_03).
:- \+buildingmaterial(brass).
:- \+currency(pesetas).
:- \+perceptionevent(extra_light).
:- \+fungus(chitin).
:- \+fungus(mushrooms_eugene_oregon_2009).
:- \+bird(garden_birds).
:- \+vertebrate(baillon_s_crake).
:- \+color(leprechaun).
:- \+cognitiveactions(tactics_for_thinking).
:- \+traditionalgame(poker_game_room).
:- \+monument(christopher_columbus_memorial_fountain).
:- \+museum(centre_culturel_suisse_e_paris).
:- \+zipcode(n98102).
:- \+room(breakfast_nook_and_a_2nd_floor_laundry_room).
:- \+country(austalia).
:- \+trainstation(european_university).
:- \+farm(trp_farm).
:- \+city(leek).
:- \+city(warsaw_ghetto).
:- \+planet(discovery_channel_blue_planet).
:- \+planet(mercury_closest_planet).
:- \+university(academy).
:- \+actor(bush).
:- \+actor(bush).
:- \+actor(bush).
:- \+comedian(willem_dafoe).
:- \+personcanada(gisele_bundchen).
:- \+female(anthony_quinn).
:- \+female(colin_firth).
:- \+personeurope(michael_jackson).
:- \+personeurope(michael_jackson).
:- \+visualartist(ricardo_bofill).
:- \+male(bush_41).
:- \+personasia(ashley_benson).
:- \+criminal(william_o_dwyer).
:- \+personasia(zhang_meng_2).
:- \+bone(foot).
:- \+lymphnode(swollen_abdominal_lymph_nodes_in_children).
:- \+kitchenitem(large_piece).
:- \+tableitem(expensive_computer).
:- \+tableitem(tremendous_computer).
:- \+householditem(ovens).
:- \+consumerelectronicitem(avatar_psp).
:- \+candy(oreos).
:- \+fungus(chili_sauce).
:- \+vegetable(popatoes).
:- \+fruit(dried_mixed_peppers).
:- \+fruit(flour_for_bread).
:- \+meat(easy_chicken).
:- \+everypromotedthing(doctor_death).
:- \+mediatype(drive_data_recovery_services).
:- \+governmentorganization(us_food).
:- \+celltype(cell_phone_use).
:- \+book(jesus).
:- \+nondiseasecondition(pregnancy_food).
:- \+mlconference(aid_offerings).
:- \+politicaloffice(music_director).
:- \+bodypart(specific_area).
:- \+tableitem(important_computer).
:- \+book(the_member_of_the_wedding).
:- \+charactertrait(administrative_responsibility).
:- \+country(foundation).
:- \+ethnicgroup(african_american_english).
:- \+religion(mount_olive_church).
:- \+mlconference(aid_provision).
:- \+muscle(muscle_pain).
:- \+currency(reals).
:- \+physicalaction(initial_shipping_costs).
:- \+date(died_sept_1).
:- \+personasia(ayrton_senna).
:- \+planet(planet_hollywood_casino_grand_opening).
:- \+nondiseasecondition(development_conference).
:- \+nondiseasecondition(development_conference).
:- \+nut(recipe_hazelnut).
:- \+currency(dollar_businesses).
:- \+nut(egg_shaped_fruits).
:- \+placeofworship(cathedral_city_fraud).
:- \+terroristorganization(national_democratic_party).
:- \+agriculturalproduct(party_organisations).
:- \+householditem(bar_tray).
:- \+televisionshow(real_life).
:- \+televisionshow(real_life).
:- \+musicalbum(the_holy_bible).
:- \+disease(smoking).
:- \+disease(abnormalities).
:- \+ethnicgroup(mam).
:- \+weatherphenomenon(air).
:- \+musicfestival(summer_music_festivals_illinois).
:- \+sportsgame(world_cup).
:- \+race(sparkassen_m_nsterland_giro).
:- \+sportsevent(n2000_in_india).
:- \+hobby(boxing).
:- \+sport(scouting).
:- \+sport(cheerleading).
:- \+year(n1958_1969).
:- \+year(n1_601).
:- \+year(n1901_03).
:- \+buildingmaterial(brass).
:- \+currency(pesetas).
:- \+perceptionevent(extra_light).
:- \+fungus(chitin).
:- \+fungus(mushrooms_eugene_oregon_2009).
:- \+bird(garden_birds).
:- \+vertebrate(baillon_s_crake).
:- \+color(leprechaun).
:- \+traditionalgame(poker_game_room).
:- \+monument(christopher_columbus_memorial_fountain).
:- \+museum(centre_culturel_suisse_e_paris).
:- \+zipcode(n98102).
:- \+country(austalia).
:- \+farm(trp_farm).
:- \+city(leek).
:- \+city(warsaw_ghetto).
:- \+university(academy).
:- \+actor(bush).
:- \+actor(bush).
:- \+actor(bush).
:- \+comedian(willem_dafoe).
:- \+personcanada(gisele_bundchen).
:- \+male(bush_41).
:- \+personasia(ashley_benson).
:- \+criminal(william_o_dwyer).
:- \+personasia(zhang_meng_2).
:- \+bone(foot).
:- \+lymphnode(swollen_abdominal_lymph_nodes_in_children).
:- \+kitchenitem(large_piece).
:- \+tableitem(expensive_computer).
:- \+tableitem(tremendous_computer).
:- \+householditem(ovens).
:- \+consumerelectronicitem(avatar_psp).
:- \+candy(oreos).
:- \+vegetable(popatoes).
:- \+fruit(dried_mixed_peppers).
:- \+fruit(flour_for_bread).
:- \+meat(easy_chicken).
:- \+everypromotedthing(doctor_death).
:- \+mediatype(drive_data_recovery_services).
:- \+governmentorganization(us_food).
:- \+celltype(cell_phone_use).
:- \+book(jesus).
:- \+mlconference(aid_offerings).
:- \+bodypart(specific_area).
:- \+tableitem(important_computer).
:- \+book(the_member_of_the_wedding).
:- \+charactertrait(administrative_responsibility).
:- \+country(foundation).
:- \+ethnicgroup(african_american_english).
:- \+currency(reals).
:- \+academicfield(biotechnology_laboratory_technology).
:- \+boardgame(life_and_monopoly).
:- \+sportsgame(world_title).
:- \+bodypart(grey_matter).
:- \+consumerelectronicitem(psp_memory_8gb).
:- \+year(n1910___1920).
:- \+animal(pests).
:- \+date(october_may).
:- \+eventoutcome(control).
:- \+physicsterm(n72_percent).
:- \+disease(heart_disease_caused_by_lung_disease).
:- \+book(titus_andronicus).
:- \+televisionshow(the_wedding_how_i_met_your_mother_episode).
:- \+country(catholic_poland).
:- \+celebrity(jennifer_lee).
:- \+tableitem(fast_computer).
:- \+color(special_yellow).
:- \+sport(taekwondo_europe).
:- \+year(n1970_1978).
:- \+software(sengoku_basara_2_heroes).
:- \+year(n1982_1992).
:- \+eventoutcome(appreciable_impact).
:- \+geometricshape(radial_lines).
:- \+personeurope(daniel_silva).
:- \+emotion(firmness).
:- \+trainstation(moscow_state_university).
:- \+trainstation(air_force_academy).
:- \+country(member_states).
:- \+trainstation(messiah_college).
:- \+flooritem(garden_sofa_set).
:- \+trainstation(simon_fraser_university).
:- \+sportsteam(simon_fraser_university).
:- \+fungus(curry).
:- \+skyscraper(george_medal).
:- \+recipe(recipes_editor).
:- \+bank(visa_logo).
:- \+consumerelectronicitem(psp_what_can_they_do).
:- \+color(gold_mind).
:- \+bodypart(in_the_same_vein).
:- \+braintissue(frontal_cortex_in_autism_might_be).
:- \+mlmetric(power_and).
:- \+bone(massive_hand).
:- \+drug(amiodarone_tablet).
:- \+nondiseasecondition(pregnqancy).
:- \+physicalcharacteristic(tempestuousness).
:- \+geometricshape(line_segments_lines_and_rays).
:- \+geometricshape(philosophical_lines).
:- \+airport(easyjet).
:- \+product(rockstar_games).
:- \+musicalbum(comfortably_numb).
:- \+mlarea(linear_algebra).
:- \+street(highway_824).
:- \+language(sauria_paharia_language).
:- \+reptile(san_diego_nightsnake).
:- \+museum(museums_in_chicago).
:- \+date(sep_58).
:- \+visualartmovement(post_gender).
:- \+filmfestival(alberta_student_film_festival).
:- \+geometricshape(two_vertical_lines).
:- \+movie(aliens).
:- \+weatherphenomenon(air).
:- \+sportsgame(world_cup).
:- \+buildingmaterial(brass).
:- \+buildingmaterial(brass).
:- \+currency(pesetas).
:- \+emotion(acceptance).
:- \+fungus(chitin).
:- \+physicalcharacteristic(greatness).
:- \+everypromotedthing(doctor_death).
:- \+bodypart(specific_area).
:- \+book(the_member_of_the_wedding).
:- \+academicfield(biotechnology_laboratory_technology).
:- \+boardgame(life_and_monopoly).
:- \+consumerelectronicitem(psp_memory_8gb).
:- \+eventoutcome(control).
:- \+physicsterm(n72_percent).
:- \+book(titus_andronicus).
:- \+geometricshape(radial_lines).
:- \+geometricshape(line_segments_lines_and_rays).
:- \+product(rockstar_games).
:- \+date(oct_43).
:- \+museum(museum_im_amtshaussch_pfla).
:- \+charactertrait(ambagiousness).
:- \+musicalbum(appetite_for_destruction).
:- \+sportsgame(finals).
:- \+book(purgatorio).
:- \+politician(luiz_inacio_lula_da_calendar_silva).
:- \+sportsgame(first_playoff).
:- \+vegetable(cherry_leaves).
:- \+radiostation(wyut).
:- \+sportsteam(italy).
:- \+county(logan_township_cuming_county).
:- \+date(feb_55).
:- \+boardgame(traditional_chinese_game).
:- \+condiment(popular_sauce).
:- \+chemical(greenhouse_gases).
:- \+weatherphenomenon(strong_headwind).
:- \+mlarea(artificial_intelligence).
:- \+mlarea(artificial_intelligence).
:- \+visualartform(photo_copier).
:- \+plant(cut_flowers).
:- \+cheese(somerset_brie_cheese).
:- \+bank(h_r_block_bank).
:- \+company(air_niugini).
:- \+date(jul_35).
:- \+park(sim_s_themepark).
:- \+flooritem(garden_rattan_sofa).
:- \+skyscraper(the_aam_tower).
:- \+city(pest).
:- \+airport(flybalaton_airport).
:- \+beach(grand_palladium_resort_beach).
:- \+magazine(singer_and_musician_magazine).
:- \+organization(kremlin).
:- \+clothing(women__s_athletic_shoes).
:- \+bank(swiss_national_bank).
:- \+male(alex_donnelly).
:- \+nut(pumpkinseed).
:- \+artery(surface_blood_vessels).
:- \+city(purchase).
:- \+militaryconflict(battle_of_domb__s).
:- \+mediatype(disk_driver).
:- \+kitchenitem(cookware_stockpot).
:- \+clothing(stola).
:- \+location(central_intelligence_agency).
:- \+clothing(cuff).
:- \+artery(left_coronary_atery).
:- \+insect(moths_and_wasp_moths).
:- \+vertebrate(two_goats).
:- \+recipe(receipes).
:- \+furniture(accenttables).
:- \+zoo(zoos_in_switzerland).
:- \+vein(valve).
:- \+bank(morgan_stanley___company).
:- \+emotion(inheritress).
:- \+country(caribbean_island).
:- \+musician(barber).
:- \+protein(simvastatin).
:- \+filmfestival(shortmoves_international_filmfestival).
:- \+website(google__yahoo).
:- \+company(google__yahoo).
:- \+condiment(salad).
:- \+plant(floral_arrangements).
:- \+color(goldilocks).
:- \+color(red_gold).
:- \+artery(neck_software).
:- \+kitchenitem(cookie_sheets_bake).
:- \+buildingmaterial(steel_development).
:- \+buildingmaterial(steel_development).
:- \+nongovorganization(creator_s_rights_party).
:- \+politicsissue(george_w__bush).
:- \+bakedgood(the_vegetarian_restaurant_s_lemon_poppyseed_cake).
:- \+charactertrait(quality_web_design).
:- \+charactertrait(quality_resources).
:- \+charactertrait(misconduct).
:- \+charactertrait(quality_leads).
:- \+charactertrait(quality_legal_representation).
:- \+charactertrait(quality_baby_products).
:- \+charactertrait(quality_digital_photographs).
:- \+charactertrait(quality_vacation_homes).
:- \+charactertrait(quality_outputs).
:- \+currency(four_different_currencies).
:- \+condiment(fry_s_chocolate_sauce).
:- \+food(caterpillars).
:- \+politicianus(michal_cjakovsky).
:- \+year(c__1888).
:- \+sportsteam(university_of_georgia).
:- \+politicsissue(architecture).
:- \+buildingmaterial(filigree).
:- \+ethnicgroup(german___english).
:- \+nut(nutritious_dry_fruits).
:- \+weatherphenomenon(luxurious_air).
:- \+fish(scorpididae).
:- \+emotion(summer_doldrums).
:- \+date(abr_29).
:- \+weapon(space_station).
:- \+musicsong(willkommen).
:- \+braintissue(ventral_cord_deformity).
:- \+blog(the_gazette_telegraph).
:- \+blog(the_gazette_telegraph).
:- \+race(gp_du_1er_mai___hoboken).
:- \+sportsgame(playoffs).
:- \+agriculturalproduct(steak).
:- \+automobilemodel(honda_mc_rc212v).
:- \+recipe(best_of_british_recipes).
:- \+city(le).
:- \+zoo(busch_gardens_tampa_bay).
:- \+park(busch_gardens_tampa_bay).
:- \+profession(gifted_artists).
:- \+profession(gifted_artists).
:- \+fruit(two_coconuts).
:- \+election(elections_and_referendums).
:- \+gamescore(n0_1).
:- \+color(lt__foliage_green).
:- \+kitchenitem(paper_towel).
:- \+musicgenre(atmospheric_funeral_doom_metal).
:- \+food(beef_porterhouse_and_vegetables).
:- \+ethnicgroup(waigali).
:- \+fruit(speckled_red_kidney_beans).
:- \+nongovorganization(american_tradition_party).
:- \+musicartist(the_all_stars).
:- \+televisionshow(the_human_face).
:- \+braintissue(a_space_odyssey_rostral_anterior_cingulate_cortex).
:- \+sportsteamposition(def_interior).
:- \+highway(county_street).
:- \+protein(sushi_repeat_containing_protein).
:- \+perceptionaction(garden_grove_engineering).
:- \+musicinstrument(country_blues_guitar).
:- \+mediatype(several_literary_journals).
:- \+bakedgood(_cookies).
:- \+currency(currancy).
:- \+currency(currancy).
:- \+recipe(insecure_recipes).
:- \+room(n88_bedrooms).
:- \+sportsgame(n1939_major_league_baseball_season).
:- \+food(leaf).
:- \+highway(north_donnelly_street).
:- \+vegetable(small_leaves).
:- \+artery(modest_vessels).
:- \+sportsgame(n1960_nba_finals).
:- \+tool(cordless_reciprocating_saws).
:- \+everypromotedthing(armistice_day).
:- \+mlconference(www_freewebsitetemplates_com).
:- \+mlconference(www_freewebsitetemplates_com).
:- \+protein(autoantibodies).
:- \+politicaloffice(attorney_f).
:- \+politicaloffice(attorney_f).
:- \+politicaloffice(estimator).
:- \+bedroomitem(atomic_clock).
:- \+wallitem(atomic_clock).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+nut(cannabis_seeds_cannabis_seeds).
:- \+braintissue(current_research_regarding_the_human_brain).
:- \+wallitem(astronomical_clock).
:- \+bedroomitem(astronomical_clock).
:- \+musicinstrument(percussion).
:- \+convention(united_kingdom___motherwell_cactus_comicon).
:- \+currency(pound_service).
:- \+food(romaine).
:- \+recipe(recipes_oil).
:- \+university(god_s_bible_school_and_college).
:- \+wine(synergistic_blend).
:- \+wine(synergistic_blend).
:- \+fruit(theseed).
:- \+fruit(theseed).
:- \+recipe(recipe_people).
:- \+celebrity(joan_gerber).
:- \+furniture(bench_seats).
:- \+mammal(ground_sloth).
:- \+vein(vena_dorsalis_clitoridis_profunda).
:- \+clothing(sneaks).
:- \+sportsteam(ohio_university_chillicothe).
:- \+mammal(mousedeers).
:- \+vegetable(tomatoes_stuffed_potatoes_cheese).
:- \+museum(museum_massing).
:- \+ethnicgroup(wapanese).
:- \+politicianus(kevin_powell).
:- \+eventoutcome(free_access).
:- \+tool(tools_program).
:- \+mammal(seven_animals).
:- \+female(jorja_fox).
:- \+celebrity(jorja_fox).
:- \+agriculturalproduct(organ_meats).
:- \+emotion(unhumorousness).
:- \+highway(right_of_way).
:- \+sportsgame(draft).
:- \+date(september_15___16).
:- \+furniture(bed_benches).
:- \+sportsteam(santa_barbara_college_of_oriental_medicine).
:- \+personalcareitem(fda_approved_prescription_drugs).
:- \+awardtrophytournament(n2009_super_bowl).
:- \+householditem(phonelines).
:- \+clothing(kids_clothes_and_shoes_womens_discount_shoes).
:- \+bank(bank_of_america_online_banking).
:- \+geopoliticallocation(orange).
:- \+bakedgood(bread_computer).
:- \+ethnicgroup(americanese).
:- \+sportsequipment(possible_balls).
:- \+personsouthamerica(jesus_love).
:- \+country(united_state).
:- \+bedroomitem(radio_interviews_of_wwii_airmen).
:- \+bedroomitem(radio_interviews_of_wwii_airmen).
:- \+fungus(list_of_deadly_fungi).
:- \+hallwayitem(there_are_a_variety_of_different_kits_for_window).
:- \+amphibian(choco_toad).
:- \+country(bassas_da_india).
:- \+personeurope(gogol).
:- \+tool(quality_tools).
:- \+programminglanguage(web_page_source_code).
:- \+mediatype(several_publications).
:- \+sportsgame(ball).
:- \+county(berwickshire).
:- \+drug(oxygen).
:- \+year(n1950___1957).
:- \+biotechcompany(adaptive_broadband_corp).
:- \+nut(feeds).
:- \+year(n1917___1919).
:- \+mlconference(www_nationalcreditfixers_com).
:- \+agriculturalproduct(cat).
:- \+monarch(alarming).
:- \+personsouthamerica(prophet_mohamed).
:- \+boardgame(chess_books).
:- \+physicalaction(flat_plate_comprising_a_bonding).
:- \+emotion(unreproductiveness).
:- \+musicinstrument(giutar).
:- \+country(uk__netherlands).
:- \+sportsevent(picnic_games).
:- \+insect(stink_bugs_and_shield_bugs).
:- \+musicartist(zep).
:- \+sportsgame(n1950_st__louis_cardinals_season).
:- \+visualartmovement(dogmatism).
:- \+visualartmovement(post_colonialism).
:- \+chef(jerome_david_selby_reddick).
:- \+coach(willis_otanez).
:- \+fungus(dipping_sauce).
:- \+physicalaction(product_packaging).
:- \+charactertrait(quality_futon).
:- \+blog(the_conway_log_cabin_democrat).
:- \+airport(three_rivers_municipal_dr__haines_airport).
:- \+mlconference(www_porntube_com).
:- \+visualartmovement(polyomavirus).
:- \+weatherphenomenon(play_northern_winds).
:- \+farm(grocery_store).
:- \+boardgame(game_and).
:- \+bedroomitem(radio_technician).
:- \+fruit(how_to_cook_pumpkin_seeds).
:- \+wallitem(coffee_table_clock).
:- \+biotechcompany(verizon).
:- \+terroristorganization(gaza_land).
:- \+personafrica(richard_m__stallman).
:- \+terroristorganization(islamic_calendar).
:- \+city(fishers).
:- \+bodypart(lymph_node_neck_cancer).
:- \+trainstation(arkansas_state_university).
:- \+fungus(caramel_sauce).
:- \+scientist(j_k__rowling).
:- \+scientist(j_k__rowling).
:- \+monarch(aleutian_range).
:- \+sportsevent(n1997_grand_prix_performance_numbers).
:- \+trainstation(terra_state_community_college).
:- \+mlalgorithm(earning_model).
:- \+mlarea(earning_model).
:- \+religion(portland_church).
:- \+nut(he_was_the_first_to_find_the_nut).
:- \+mlconference(www_nationalrail_co_uk).
:- \+sport(diving_lessons).
:- \+personcanada(robert_hickson).
:- \+politicalparty(partidos_pol_ticos_en_italia).
:- \+terroristorganization(islamic_republic_of_iran).
:- \+year(s_1839).
:- \+mlarea(boyfriend_model).
:- \+mlalgorithm(boyfriend_model).
:- \+musician(plymouth_canton_symphony_orchestra).
:- \+county(lancastershire).
:- \+race(edit).
:- \+boardgame(edit).
:- \+agriculturalproduct(machine).
:- \+conference(www_t_mobile_co_uk).
:- \+charactertrait(quality_rental_apartments).
:- \+bedroomitem(radio_staion_from_byu).
:- \+emotion(popeless).
:- \+coach(steve).
:- \+everypromotedthing(salvation_army_new).
:- \+transportation(metro_call_a_ride).
:- \+sportsgame(n1986_st__louis_cardinals_season).
:- \+disease(hyperlipidema).
:- \+monarch(alfred_taylor).
:- \+beverage(chips).
:- \+fish(appetizer).
:- \+astronaut(united_states_senate).
:- \+automobilemaker(motorized).
:- \+stateorprovince(delta).
:- \+medicalprocedure(risks_of_vascular_surgery).
:- \+beverage(milk_chocolate).
:- \+bedroomitem(radio_interface_specification_layer_1).
:- \+country(pa).
:- \+recordlabel(recordings).
:- \+charactertrait(quality_vapor).
:- \+mlconference(www_thepensionservice).
:- \+weapon(gun_products).
:- \+conference(www_206_108_49_36).
:- \+sportsgame(tournament).
:- \+sportsgame(n2007_postseason).
:- \+chef(jerome_chlorine_dioxide_debra).
:- \+chef(jerome_chlorine_dioxide_debra).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+emotion(wilderness).
:- \+grain(n1_4_cup_breadcrumbs).
:- \+personafrica(steven_spielberg).
:- \+bedroomitem(traditional_clock).
:- \+meat(pork_barbecue_recipe).
:- \+legume(using_3_kinds_of_canned_beans).
:- \+emotion(unpopularness).
:- \+placeofworship(scripps_institute_of_oceanography).
:- \+placeofworship(scripps_institute_of_oceanography).
:- \+aquarium(scripps_institute_of_oceanography).
:- \+aquarium(scripps_institute_of_oceanography).
:- \+trainstation(university_of_virginia_law_school).
:- \+recordlabel(pennsylvania_marriage_records).
:- \+recordlabel(pennsylvania_marriage_records).
:- \+blog(the_st__louis_post_dispatch).
:- \+musicgenre(progressive_rock_metal_mathcore).
:- \+year(may_2000).
:- \+nondiseasecondition(fourteen_day_period).
:- \+nondiseasecondition(fourteen_day_period).
:- \+planet(earth_moving_equipments).
:- \+planet(earth_moving_equipments).
:- \+trainstation(university_of_michigan_business_school).
:- \+trainstation(university_of_michigan_business_school).
:- \+trainstation(university_of_michigan_business_school).
:- \+monument(penn_museum).
:- \+person(about_wikipedia).
:- \+animal(pademelons).
:- \+terroristorganization(army).
:- \+model(kathy_najimy).
:- \+actor(kate_middleton).
:- \+country(austria___vienna).
:- \+buildingmaterial(machined).
:- \+physicsterm(n4_9_percent_last_month).
:- \+musicartist(vibrators).
:- \+city(purchase).
:- \+programminglanguage(internet).
:- \+programminglanguage(to_rewrite_the_code).
:- \+programminglanguage(regedit).
:- \+programminglanguage(javasript).
:- \+tableitem(phone_ringtones).
:- \+tableitem(phone_ringtones).
:- \+tableitem(phone_ringtones).
:- \+tableitem(phone_ringtones).
:- \+tableitem(phone_ringtones).
:- \+room(eat_in_breakfast_room).
:- \+emotion(unconcreteness).
:- \+everypromotedthing(adult_contacts_in).
:- \+book(payback).
:- \+televisionshow(rolling_thunder).
:- \+televisionshow(the_explorers).
:- \+televisionshow(the_moor_murderers).
:- \+televisionshow(the_dubliners).
:- \+televisionshow(the_test_dream).
:- \+televisionshow(the_banana_bunch).
:- \+televisionshow(the_distillers).
:- \+televisionshow(the_story).
:- \+televisionshow(the_doors).
:- \+televisionshow(the_chemical_brothers).
:- \+televisionshow(the_super_gwobetrotters).
:- \+televisionshow(the_pretenders).
:- \+televisionshow(the_good_german).
:- \+televisionshow(the_black_seal).
:- \+televisionshow(the_young_marauders).
:- \+televisionshow(the_sullivan_family_singers).
:- \+televisionshow(main).
:- \+televisionshow(oprah).
:- \+televisionshow(tonight_show).
:- \+televisionshow(non_profit_organization).
:- \+boardgame(games_rss).
:- \+vertebrate(dogs_version).
:- \+parlourgame(two_useful_sites).
:- \+politicsissue(environmental_studies).
:- \+musicinstrument(nylon_string).
:- \+olympics(word_games).
:- \+building(famous_restaurant).
:- \+geometricshape(line_title).
:- \+politicaloffice(financial_planning_officer).
:- \+invertebrate(porche_transmission_in_a_vw_beetle).
:- \+politicaloffice(attorney_abuse).
:- \+nut(fruit_servings).
:- \+nut(fruit_servings).
:- \+nut(fruit_servings).
:- \+charactertrait(quality_quartz_engineering).
:- \+tool(machine_government).
:- \+programminglanguage(budget_code).
:- \+programminglanguage(budget_code).
:- \+programminglanguage(budget_code).
:- \+programminglanguage(budget_code).
:- \+celltype(cell_agents).
:- \+drug(proroxane).
:- \+weapon(weapons_worth).
:- \+programminglanguage(codes_news).
:- \+language(bill_clinton__hillary_lole_clinton_language).
:- \+consumerelectronicitem(hebrew_speakers).
:- \+automobilemaker(mercedes_bentz_dealers).
:- \+mlmetric(power_food).
:- \+automobilemaker(mercedes_350).
:- \+animal(cuckoos_and_allies).
:- \+braintissue(brain_synchronization).
:- \+fungus(dangers_of_psychedelic_mushrooms).
:- \+nut(sea_weed).
:- \+archaea(amino_acid).
:- \+legume(bean_preparation).
:- \+biotechcompany(nike_inc).
:- \+fruit(power_sugar).
:- \+fruit(hex_nuts).
:- \+invertebrate(beetles_music_downloader).
:- \+fungus(mushrooms_and_artichokes_in_cdkitchen).
:- \+personsouthamerica(jesus_of_nazareth).
:- \+criminal(joseph_lawrence).
:- \+vegetable(tomato_pizza).
:- \+mlconference(www_crisismanagement_org).
:- \+programminglanguage(javasript).
:- \+book(payback).
:- \+televisionshow(the_test_dream).
:- \+televisionshow(the_banana_bunch).
:- \+televisionshow(the_super_gwobetrotters).
:- \+televisionshow(the_pretenders).
:- \+televisionshow(the_black_seal).
:- \+televisionshow(oprah).
:- \+televisionshow(tonight_show).
:- \+politicsissue(environmental_studies).
:- \+musicinstrument(nylon_string).
:- \+drug(proroxane).
:- \+criminal(joseph_lawrence).
:- \+personalcareitem(n23_products).
:- \+physicsterm(outstanding_pace).
:- \+grain(hardened_sugar).
:- \+grain(hardened_sugar).
:- \+nerve(nerves_or_structures_relevant_in_this_review).
:- \+bone(bone_rings).
:- \+tableitem(extreme_computer).
:- \+personalcareitem(likely_products).
:- \+sportsteam(state_university).
:- \+charactertrait(quality_scientific_papers).
:- \+mammal(big_cats).
:- \+consumerelectronicitem(video_converter_tool).
:- \+consumerelectronicitem(video_converter_tool).
:- \+museum(famous_prado_museum).
:- \+vegetable(fern_leaves).
:- \+musicinstrument(guitar_packages).
:- \+sportsteam(ohio_state_university).
:- \+zoo(the_park).
:- \+braintissue(one_hemisphere).
:- \+weatherphenomenon(dark_smoke).
:- \+amphibian(croaking_frogs).
:- \+mlarea(statistical_analyses_all_statistical_analyses).
:- \+wine(cagninadiromagna).
:- \+muscle(powerful_muscles).
:- \+sportsgame(n1905_st__louis_cardinals_season).
:- \+tool(machine_group).
:- \+weatherphenomenon(weather_wind).
:- \+animal(beetles_on_my_roses).
:- \+programminglanguage(shell_commands).
:- \+programminglanguage(pseudo_code).
:- \+fish(larger_carnivorous_fish).
:- \+year(_54).
:- \+year(_54).
:- \+televisionshow(the_fwintstones).
:- \+mammal(n10_000_animals).
:- \+year(_06).
:- \+televisionshow(the_sorcerer_s_apprentice).
:- \+perceptionevent(beautiful_natural_light).
:- \+aquarium(aqua_food).
:- \+sportsteam(bethel_college).
:- \+nongovorganization(badly_drawn_boy_tickets).
:- \+nongovorganization(badly_drawn_boy_tickets).
:- \+vegetable(basil).
:- \+food(plant_species).
:- \+archaea(property_rights).
:- \+year(circa_1868).
:- \+year(unknown).
:- \+scientist(plotinus).
:- \+nut(cashew_nut_cholesterol).
:- \+religion(witnesses).
:- \+physicsterm(specific_body_weight).
:- \+date(october_11_and_12).
:- \+kitchenitem(steamkettle).
:- \+buildingfeature(wonderful_doors).
:- \+blog(the_appeal_democrat).
:- \+male(alex_flatner___lopazz).
:- \+street(inclusive_road).
:- \+vegetable(willow_like_leaves).
:- \+academicfield(biology_ecology).
:- \+chef(jerome_hemsath).
:- \+nondiseasecondition(development_web_sites).
:- \+bridge(pont_weygand).
:- \+mlauthor(david_p__clements).
:- \+sportsteam(santa_barbara_college_of_oriental_medicine).
:- \+fish(sandsucker).
:- \+academicfield(business_related).
:- \+sportsequipment(driving_school_course).
:- \+date(november_5___19).
:- \+country(middle_east_countries).
:- \+bodypart(stronger_hand).
:- \+beverage(how_to_make_white_tea).
:- \+politician(presidential_candidate_sen__barack_obama).
:- \+awardtrophytournament(n1968_69_european_cup).
:- \+transportation(car).
:- \+emotion(unclementness).
:- \+reptile(amazing_dinosaurs).
:- \+meat(beef_powder).
:- \+country(republic).
:- \+meat(ranchero_chicken).
:- \+transportation(john_f_kennedy_international_airport).
:- \+monarch(allaah).
:- \+charactertrait(quality_fabrics).
:- \+sportsgame(interview_series).
:- \+lymphnode(destination_address).
:- \+charactertrait(quality_training_material).
:- \+fruit(seed_pods).
:- \+weatherphenomenon(n7_30).
:- \+plant(arcadia_flowers).
:- \+perceptionevent(light_photography).
:- \+personsouthamerica(lordalmighty).
:- \+physicsterm(n10_7).
:- \+plant(jackson_flowers).
:- \+personmexico(nick_hundley).
:- \+geometricshape(line_coffee).
:- \+country(iraq_need).
:- \+grain(sugarbeets).
:- \+kitchenitem(plastic_atomizer).
:- \+plant(darmstadt_flowers).
:- \+terroristorganization(gaza_city).
:- \+consumerelectronicitem(small_video_conversion_tool).
:- \+charactertrait(quality_adult_learning).
:- \+physicalcharacteristic(strandline).
:- \+geometricshape(line_jack).
:- \+nerve(mouth_marketing).
:- \+publication(time_nobody).
:- \+terroristorganization(african_national_congress).
:- \+politicalparty(african_national_congress).
:- \+cognitiveactions(thinknig).
:- \+buildingfeature(distributors_of_entrance_doors).
:- \+geometricshape(line_interview).
:- \+buildingfeature(behind_the_green_door).
:- \+automobilemaker(mercedes_benz_sacramento).
:- \+filmfestival(film_snow_white).
:- \+weatherphenomenon(wind_gods).
:- \+religion(cornerstone_church).
:- \+vegetable(baby_clams).
:- \+arthropod(site_fly).
:- \+mlmetric(power_storage_small_compressed).
:- \+museum(museum_of_modern_art_holiday_cards).
:- \+museum(museum_of_modern_art_holiday_cards).
:- \+museum(museum_of_modern_art_holiday_cards).
:- \+mlalgorithm(worm_model).
:- \+mlarea(worm_model).
:- \+nut(cashew_nut_wholesale).
:- \+geopoliticalorganization(six_degrees_of_separation_tickets).
:- \+transportation(metrocard_machines__subway_debut).
:- \+musicsong(comprehensive_frequently).
:- \+country(thailand_thailand).
:- \+vehicle(explosives_laden_truck).
:- \+mlauthor(donald_f__towsley).
:- \+fungus(sauce_software).
:- \+politicianus(act).
:- \+chef(kevin_bacon).
:- \+arthropod(scale_websites).
:- \+emotion(superradicalness).
:- \+mlconference(www_myfloridalicense__com).
:- \+economicsector(insurance_consultant).
:- \+householditem(queen_zize_beds).
:- \+householditem(watches).
:- \+householditem(wholesale_hon_office_furniture).
:- \+householditem(cottage_sofas).
:- \+householditem(display_sign_stands).
:- \+musicalbum(i_died_for_you).
:- \+conference(conferences).
:- \+crimeorcharge(last_charge).
:- \+hobby(poolside_dining).
:- \+everypromotedthing(bus_train).
:- \+hobby(pedaphilia).
:- \+software(prince_of_persia___rival_swords).
:- \+hobby(talks).
:- \+terroristorganization(islamic_action_front).
:- \+mlauthor(m__w__du).
:- \+terroristorganization(diocese_that_offers_prayers_of_liberation).
:- \+company(hdr).
:- \+automobilemodel(ferrari_456_m).
:- \+cardgame(hi_lo).
:- \+medicalprocedure(isolation).
:- \+person(princess).
:- \+invertebrate(night_crawler).
:- \+protestevent(indonesian_invasion_of_east_timor).
:- \+currency(escolas).
:- \+victim(undergraduate_students).
:- \+color(sky).
:- \+victim(graduates_students).
:- \+profession(support_officers).
:- \+insect(small_insects).
:- \+programminglanguage(web_programming_language).
:- \+programminglanguage(general_purpose_programming_language).
:- \+year(n1871_1990).
:- \+year(n1871_1990).
:- \+automobileengine(thomas_tank_engine).
:- \+bakedgood(breakfast).
:- \+beverage(dairy_foods).
:- \+beverage(meal).
:- \+beverage(avocado).
:- \+agriculturalproduct(blood).
:- \+beverage(blood).
:- \+beverage(oil).
:- \+beverage(mix).
:- \+beverage(peaches).
:- \+beverage(strawberry).
:- \+country(israeli).
:- \+country(isreal).
:- \+country(republics).
:- \+country(republic).
:- \+country(republic).
:- \+country(republic).
:- \+country(saudis).
:- \+country(nation).
:- \+vegetable(meal).
:- \+agriculturalproduct(meal).
:- \+vegetable(potatoeas).
:- \+weapon(weaopns).
:- \+bone(finger_joint).
:- \+bone(diseased_joint).
:- \+bone(immovable_joint).
:- \+weapon(gas_natural_gas).
:- \+weapon(tankless_gas).
:- \+physicsterm(n1_217).
:- \+beverage(apricot).
:- \+everypromotedthing(domestic_animals__all_animals_are_included_there).
:- \+year(n1918_1932).
:- \+grain(rice_plants).
:- \+room(cottage_style_kitchen).
:- \+televisionshow(your_new_house).
:- \+jobposition(head_costume_designer).
:- \+mammal(western_black_rhinoceros).
:- \+officebuildingroom(oversized_bathroom).
:- \+year(n1930___1970).
:- \+date(n1861___1938).
:- \+language(varieties_of_chinese).
:- \+mlarea(probably_approximately_correct_learning).
:- \+terroristorganization(fundamentalist_islamists).
:- \+meat(salmon_hash).
:- \+weapon(uk_coal).
:- \+bodypart(fourth_stomach).
:- \+politicsissue(economical_energy).
:- \+politician(president_josiah_bartlet).
:- \+company(internal_revenue_service).
:- \+mountainrange(northern_mountain_range).
:- \+beach(washington_oregon).
:- \+religion(sikh_religion).
:- \+animal(baby).
:- \+language(fictional_language).
:- \+animal(child).
:- \+victim(kinesiology_students).
:- \+bank(apple).
:- \+emotion(nausea).
:- \+sportsteam(golden_gate_university).
:- \+victim(second_language_students).
:- \+shoppingmall(the_fashion_show).
:- \+sportsteam(jacobs_university_bremen).
:- \+sportsteam(jacksonville_university).
:- \+sportsteam(jacksonville_university).
:- \+victim(first_nations_students).
:- \+victim(wsu_students).
:- \+museum(oregon_art_museums).
:- \+bathroomitem(marble_mosaic_floors).
:- \+product(pheromones).
:- \+awardtrophytournament(challenge_cup_final).
:- \+weapon(non_coal).
:- \+mammal(bear_cats).
:- \+profession(owner_directors).
:- \+agent(deutsche_lufthansa_ag).
:- \+weatherphenomenon(distance_wind).
:- \+bone(pasterns).
:- \+celebrity(arielle_dombasle).
:- \+hallwayitem(door_slides).
:- \+archaea(deadly_organism).
:- \+blog(lelectronique_com).
:- \+visualizableobject(groundnut_oil).
:- \+mammal(balaenopteridae).
:- \+date(b__14_dec_1900_d__1983).
:- \+furniture(treasure_island_outdoor_furniture).
:- \+politicaloffice(ecowas_executive_secretary).
:- \+fish(saddled_grenadier).
:- \+politicaloffice(iaea_director_general).
:- \+emotion(overassess).
:- \+sportsteam(france).
:- \+sportsteam(france).
:- \+bird(wattled_broadbill).
:- \+nondiseasecondition(n10_hour_period).
:- \+emotion(acceptance).
:- \+emotion(personal_joy).
:- \+hallwayitem(shiny_wooden_floor).
:- \+sportsevent(disney_channel_games).
:- \+book(amelia).
:- \+bone(a_joint).
:- \+bone(knee_area).
:- \+officebuildingroom(economical_rooms).
:- \+visualizablescene(downtown_dallas).
:- \+software(the_king_of_fighters_98_ultimate_match).
:- \+terroristorganization(labor_movement).
:- \+drug(glycopine).
:- \+vertebrate(bar_tailed_desert_lark).
:- \+agriculturalproduct(anchovies).
:- \+fruit(cream_style_corn).
:- \+fruit(cream_style_corn).
:- \+fruit(cream_style_corn).
:- \+recipe(recipe_representations).
:- \+emotion(unrevealedness).
:- \+academicfield(art_education).
:- \+city(gotham_city).
:- \+militaryconflict(battle_25_december).
:- \+braintissue(dlpfc_).
:- \+weapon(gas_transmission).
:- \+mlarea(logistic_regression).
:- \+academicfield(crop_and_soil_sciences).
:- \+language(macedonian).
:- \+victim(n90_students).
:- \+hospital(university_of_louisville_school_of_medicine).
:- \+bedroomitem(lake_city_radio).
:- \+software(tomb_raider___anniversary).
:- \+personsouthamerica(jesus_).
:- \+braintissue(human_brain_is_about_85_percent_cerebrum).
:- \+amphibian(gray_crowned_prinia).
:- \+wine(igiene).
:- \+geopoliticalorganization(moxico).
:- \+boardgame(monitor_game).
:- \+weapon(basic_gas).
:- \+parlourgame(forty_days).
:- \+sportsevent(forty_days).
:- \+victim(business_school_students).
:- \+politicalparty(community_party).
:- \+terroristorganization(community_party).
:- \+visualizableobject(internet_cookies).
:- \+crimeorcharge(serious_faux_pas).
:- \+year(n1934___1943).
:- \+invertebrate(same_bugs).
:- \+aquarium(vogelpark_heiligenkirchen).
:- \+furniture(consignment_furniture).
:- \+researchproject(major_internet_search_engines).
:- \+consumerelectronicitem(youtube_downloader).
:- \+tableitem(mystery_computer).
:- \+country(people_republic).
:- \+householditem(potterybarn_furniture).
:- \+politicaloffice(poetry_editor).
:- \+personsouthamerica(military_of_paraguay).
:- \+language(chinantec).
:- \+year(n1917_1997).
:- \+programminglanguage(html_page).
:- \+sportsteam(brookwood_high_school).
:- \+website(the_globe).
:- \+musicalbum(book_of_life).
:- \+hospital(university_of_miami).
:- \+cognitiveactions(societal_problem).
:- \+monarch(maternal_grandmother).
:- \+year(n1861__1956).
:- \+sportsteam(wofford_college).
:- \+aquarium(build_world).
:- \+kitchenitem(carving_fork).
:- \+restaurant(addar_hotel).
:- \+aquarium(sea_world_adventure_parks).
:- \+nut(blackbutt).
:- \+year(n1945_1978).
:- \+geometricshape(holiday_shapes).
:- \+bombingevent(beirut_bombing__thurs__blast_in_hezbollah_run_area_of_beirut_claimed_5_lives).
:- \+monarch(patricks).
:- \+drug(drocinonide).
:- \+musician(david_coburn).
:- \+nut(pin_oaks).
:- \+ethnicgroup(href___farms__________badaga).
:- \+musicfestival(annual_meet).
:- \+zoo(zion_park).
:- \+grandprix(n1937_czechoslovakian_grand_prix).
:- \+terroristorganization(of_liberation_museum).
:- \+protestevent(stuha).
:- \+buildingfeature(brown_bridge_road).
:- \+meat(quorn).
:- \+victim(mathematics_majors).
:- \+trainstation(louisiana_state_univ).
:- \+monarch(russian_grandmother).
:- \+bedroomitem(radio_inffluence_during_elction_years).
:- \+year(n1915_1945).
:- \+hospital(stanford_university_medical_school).
:- \+consumerelectronicitem(free_youtube_downloader).
:- \+vegetable(potadoes).
:- \+visualizableattribute(geraldine_green).
:- \+book(sherlock_holmes).
:- \+person(two_people).
:- \+sportsgame(hollywood_bowl).
:- \+book(all_american_girl).
:- \+company(kpcc_fm).
:- \+city(house).
:- \+researchproject(internet_search_results).
:- \+musicgenre(fusion_genres_of_black_metal).
:- \+victim(n125_000_students).
:- \+religion(new_bethel_chr_the_living_god).
:- \+economicsector(cryptology).
:- \+arthropod(crabs_and_lobsters).
:- \+insect(primary_pest).
:- \+building(west_chester_university_of_pennsylvania).
:- \+academicfield(naturopathic_medicine_naturopathic_medicine).
:- \+professor(anonymous).
:- \+musician(anonymous).
:- \+personafrica(anonymous).
:- \+consumerelectronicitem(aimersoft_3gp_converter_suite).
:- \+personsouthamerica(oklahoma_city_university_school_of_law).
:- \+personsouthamerica(oklahoma_city_university_school_of_law).
:- \+mlalgorithm(memory_device).
:- \+software(texas_hold_em_poker).
:- \+personafrica(carol_burnett).
:- \+personalcareitem(addicted_drugs).
:- \+mlconference(aid_the_us).
:- \+airport(california_asset_search_investigator).
:- \+currency(pobres).
:- \+mlmetric(n43_12).
:- \+wallitem(xterm_window).
:- \+videogamesystem(avcware_wii_video_converter).
:- \+shoppingmall(starbucks_central_mall_texarkana).
:- \+boardgame(em_poker_odds).
:- \+cognitiveactions(poems_to_someone_thinking_about_suicide).
:- \+cognitiveactions(poems_to_someone_thinking_about_suicide).
:- \+crimeorcharge(very_crimes).
:- \+emotion(vibrationless).
:- \+videogamesystem(nidesoft_dvd_to_creative_zen_converter).
:- \+geometricshape(intermediate_mass_stars).
:- \+biotechcompany(intel_chipset).
:- \+scientist(william_burroughs).
:- \+personeurope(william_burroughs).
:- \+professor(william_burroughs).
:- \+meat(chicken_tortellini_soup).
:- \+cardgame(em_poker_party).
:- \+sportsevent(em_poker_party).
:- \+musicfestival(commerce_meetings).
:- \+wine(clarita_software).
:- \+sportsgame(em_and_poker).
:- \+conference(iclique).
:- \+cheese(null_string).
:- \+county(cambridge_university).
:- \+election(privacy_policy_policy).
:- \+street(n104r_lakeview_avenue).
:- \+parlourgame(n12_3).
:- \+musicfestival(academy_meeting).
:- \+mountain(double_point).
:- \+personafrica(brent_barrett).
:- \+personaustralia(chad_johnson).
:- \+coach(chad_johnson).
:- \+celebrity(jon_stewart_and_stephen_colbert).
:- \+sportsgame(em_poker_download_game).
:- \+agriculturalproduct(beef_products).
:- \+model(james_moffat).
:- \+publication(linked_in_).
:- \+animal(learn_how_to_catch_fish).
:- \+sport(downhill).
:- \+sport(sale_rentals).
:- \+county(arizona_college).
:- \+videogamesystem(wondershare_dvd_to_3gp_ripper).
:- \+weapon(gas_project).
:- \+sportsteamposition(center_thermodynamics).
:- \+aquarium(botanical_garden).
:- \+zoo(botanical_garden).
:- \+website(contact_the_food_bank).
:- \+filmfestival(ivor_novello_award).
:- \+charactertrait(showeriness).
:- \+arthropod(cost_home_equity_loans).
:- \+physicalcharacteristic(infrastructure_business).
:- \+stadiumoreventvenue(stadiums).
:- \+mlmetric(n61_09).
:- \+radiostation(wcqu).
:- \+householditem(queen_zize_beds).
:- \+householditem(watches).
:- \+householditem(wholesale_hon_office_furniture).
:- \+householditem(cottage_sofas).
:- \+householditem(display_sign_stands).
:- \+musicalbum(i_died_for_you).
:- \+conference(conferences).
:- \+crimeorcharge(last_charge).
:- \+hobby(poolside_dining).
:- \+hobby(poolside_dining).
:- \+everypromotedthing(bus_train).
:- \+hobby(pedaphilia).
:- \+hobby(pedaphilia).
:- \+software(prince_of_persia___rival_swords).
:- \+hobby(talks).
:- \+terroristorganization(islamic_action_front).
:- \+mlauthor(m__w__du).
:- \+terroristorganization(diocese_that_offers_prayers_of_liberation).
:- \+company(hdr).
:- \+automobilemodel(ferrari_456_m).
:- \+cardgame(hi_lo).
:- \+medicalprocedure(isolation).
:- \+person(princess).
:- \+invertebrate(night_crawler).
:- \+mlalgorithm(chi_square_test).
:- \+protestevent(indonesian_invasion_of_east_timor).
:- \+currency(escolas).
:- \+victim(undergraduate_students).
:- \+color(sky).
:- \+victim(graduates_students).
:- \+profession(support_officers).
:- \+insect(small_insects).
:- \+programminglanguage(web_programming_language).
:- \+programminglanguage(general_purpose_programming_language).
:- \+year(n1871_1990).
:- \+year(n1871_1990).
:- \+mammal(dog).
:- \+automobileengine(thomas_tank_engine).
:- \+bakedgood(breakfast).
:- \+beverage(dairy_foods).
:- \+beverage(avocado).
:- \+agriculturalproduct(blood).
:- \+beverage(blood).
:- \+beverage(oil).
:- \+beverage(mix).
:- \+beverage(peaches).
:- \+beverage(strawberry).
:- \+country(israeli).
:- \+country(isreal).
:- \+country(republic).
:- \+country(republic).
:- \+country(republic).
:- \+country(saudis).
:- \+country(nation).
:- \+country(nation).
:- \+vegetable(potatoeas).
:- \+weapon(weaopns).
:- \+bone(finger_joint).
:- \+bone(diseased_joint).
:- \+bone(immovable_joint).
:- \+weapon(gas_natural_gas).
:- \+weapon(tankless_gas).
:- \+beverage(apricot).
:- \+everypromotedthing(domestic_animals__all_animals_are_included_there).
:- \+year(n1918_1932).
:- \+grain(rice_plants).
:- \+room(cottage_style_kitchen).
:- \+televisionshow(your_new_house).
:- \+jobposition(head_costume_designer).
:- \+mammal(western_black_rhinoceros).
:- \+officebuildingroom(oversized_bathroom).
:- \+year(n1930___1970).
:- \+date(n1861___1938).
:- \+language(varieties_of_chinese).
:- \+mlarea(probably_approximately_correct_learning).
:- \+terroristorganization(fundamentalist_islamists).
:- \+meat(salmon_hash).
:- \+weapon(uk_coal).
:- \+bodypart(fourth_stomach).
:- \+politicsissue(economical_energy).
:- \+politician(president_josiah_bartlet).
:- \+company(internal_revenue_service).
:- \+mountainrange(northern_mountain_range).
:- \+beach(washington_oregon).
:- \+religion(sikh_religion).
:- \+animal(baby).
:- \+language(fictional_language).
:- \+animal(child).
:- \+victim(kinesiology_students).
:- \+bank(apple).
:- \+emotion(nausea).
:- \+sportsteam(golden_gate_university).
:- \+victim(second_language_students).
:- \+shoppingmall(the_fashion_show).
:- \+sportsteam(jacobs_university_bremen).
:- \+sportsteam(jacksonville_university).
:- \+sportsteam(jacksonville_university).
:- \+victim(first_nations_students).
:- \+victim(wsu_students).
:- \+museum(oregon_art_museums).
:- \+bathroomitem(marble_mosaic_floors).
:- \+product(pheromones).
:- \+awardtrophytournament(challenge_cup_final).
:- \+mammal(bear_cats).
:- \+profession(owner_directors).
:- \+agent(deutsche_lufthansa_ag).
:- \+weatherphenomenon(distance_wind).
:- \+bone(pasterns).
:- \+celebrity(arielle_dombasle).
:- \+hallwayitem(door_slides).
:- \+archaea(deadly_organism).
:- \+blog(lelectronique_com).
:- \+mammal(balaenopteridae).
:- \+date(b__14_dec_1900_d__1983).
:- \+furniture(treasure_island_outdoor_furniture).
:- \+politicaloffice(ecowas_executive_secretary).
:- \+fish(saddled_grenadier).
:- \+politicaloffice(iaea_director_general).
:- \+emotion(overassess).
:- \+sportsteam(france).
:- \+sportsteam(france).
:- \+bird(wattled_broadbill).
:- \+nondiseasecondition(n10_hour_period).
:- \+emotion(acceptance).
:- \+emotion(personal_joy).
:- \+hallwayitem(shiny_wooden_floor).
:- \+sportsevent(disney_channel_games).
:- \+book(amelia).
:- \+bone(a_joint).
:- \+bone(knee_area).
:- \+officebuildingroom(economical_rooms).
:- \+visualizablescene(downtown_dallas).
:- \+software(the_king_of_fighters_98_ultimate_match).
:- \+drug(glycopine).
:- \+vertebrate(bar_tailed_desert_lark).
:- \+agriculturalproduct(anchovies).
:- \+fruit(cream_style_corn).
:- \+fruit(cream_style_corn).
:- \+fruit(cream_style_corn).
:- \+recipe(recipe_representations).
:- \+emotion(unrevealedness).
:- \+academicfield(art_education).
:- \+city(gotham_city).
:- \+militaryconflict(battle_25_december).
:- \+braintissue(dlpfc_).
:- \+weapon(gas_transmission).
:- \+mlarea(logistic_regression).
:- \+academicfield(crop_and_soil_sciences).
:- \+language(macedonian).
:- \+victim(n90_students).
:- \+hospital(university_of_louisville_school_of_medicine).
:- \+bedroomitem(lake_city_radio).
:- \+software(tomb_raider___anniversary).
:- \+braintissue(human_brain_is_about_85_percent_cerebrum).
:- \+amphibian(gray_crowned_prinia).
:- \+wine(igiene).
:- \+geopoliticalorganization(moxico).
:- \+boardgame(monitor_game).
:- \+parlourgame(forty_days).
:- \+sportsevent(forty_days).
:- \+victim(business_school_students).
:- \+politicalparty(community_party).
:- \+terroristorganization(community_party).
:- \+visualizableobject(internet_cookies).
:- \+crimeorcharge(serious_faux_pas).
:- \+year(n1934___1943).
:- \+invertebrate(same_bugs).
:- \+aquarium(vogelpark_heiligenkirchen).
:- \+furniture(consignment_furniture).
:- \+researchproject(major_internet_search_engines).
:- \+consumerelectronicitem(youtube_downloader).
:- \+tableitem(mystery_computer).
:- \+householditem(potterybarn_furniture).
:- \+politicaloffice(poetry_editor).
:- \+personsouthamerica(military_of_paraguay).
:- \+language(chinantec).
:- \+year(n1917_1997).
:- \+programminglanguage(html_page).
:- \+sportsteam(brookwood_high_school).
:- \+website(the_globe).
:- \+musicalbum(book_of_life).
:- \+hospital(university_of_miami).
:- \+cognitiveactions(societal_problem).
:- \+monarch(maternal_grandmother).
:- \+year(n1861__1956).
:- \+sportsteam(wofford_college).
:- \+aquarium(build_world).
:- \+kitchenitem(carving_fork).
:- \+restaurant(addar_hotel).
:- \+aquarium(sea_world_adventure_parks).
:- \+nut(blackbutt).
:- \+year(n1945_1978).
:- \+geometricshape(holiday_shapes).
:- \+bombingevent(beirut_bombing__thurs__blast_in_hezbollah_run_area_of_beirut_claimed_5_lives).
:- \+monarch(patricks).
:- \+drug(drocinonide).
:- \+musician(david_coburn).
:- \+ethnicgroup(href___farms__________badaga).
:- \+musicfestival(annual_meet).
:- \+zoo(zion_park).
:- \+grandprix(n1937_czechoslovakian_grand_prix).
:- \+terroristorganization(of_liberation_museum).
:- \+protestevent(stuha).
:- \+buildingfeature(brown_bridge_road).
:- \+meat(quorn).
:- \+victim(mathematics_majors).
:- \+recordlabel(emi_music_japan).
:- \+trainstation(louisiana_state_univ).
:- \+monarch(russian_grandmother).
:- \+bedroomitem(radio_inffluence_during_elction_years).
:- \+year(n1915_1945).
:- \+hospital(stanford_university_medical_school).
:- \+consumerelectronicitem(free_youtube_downloader).
:- \+vegetable(potadoes).
:- \+visualizableattribute(geraldine_green).
:- \+book(sherlock_holmes).
:- \+person(two_people).
:- \+sportsgame(hollywood_bowl).
:- \+book(all_american_girl).
:- \+city(house).
:- \+researchproject(internet_search_results).
:- \+musicgenre(fusion_genres_of_black_metal).
:- \+victim(n125_000_students).
:- \+religion(new_bethel_chr_the_living_god).
:- \+economicsector(cryptology).
:- \+arthropod(crabs_and_lobsters).
:- \+insect(primary_pest).
:- \+building(west_chester_university_of_pennsylvania).
:- \+academicfield(naturopathic_medicine_naturopathic_medicine).
:- \+cognitiveactions(poems_to_someone_thinking_about_suicide).
:- \+cognitiveactions(poems_to_someone_thinking_about_suicide).
:- \+videogamesystem(nidesoft_dvd_to_creative_zen_converter).
:- \+geometricshape(intermediate_mass_stars).
:- \+street(n104r_lakeview_avenue).
:- \+agriculturalproduct(beef_products).
:- \+weapon(gas_project).
:- \+nondiseasecondition(early_postmenopause).
:- \+mlalgorithm(one_way_test).
:- \+hallwayitem(window_overlooking_the_garden).
:- \+animal(boring_beetles).
:- \+officeitem(cards_credit_cards).
:- \+visualizablething(pastry_crusts).
:- \+victim(student_athlete).
:- \+website(gogle).
:- \+religion(orange_grove_church).
:- \+criminal(michael_contaro).
:- \+movie(metal_jacket_movie).
:- \+book(collected_stories).
:- \+writer(tolstoy_and_dostoyevsky).
:- \+cave(hole).
:- \+geopoliticallocation(central_michigan).
:- \+cheese(_ness_br___grafton_village______br____cheddar_cheese).
:- \+city(borivli).
:- \+officeitem(prepaid_phone_cards).
:- \+jobposition(future_driver).
:- \+mlauthor(dimitris_p__kraniotis).
:- \+arachnid(tickets_las_vegas).
:- \+blog(wordpress__org).
:- \+country(texas_republic).
:- \+economicsector(loan_search).
:- \+food(fats_and_sugars).
:- \+filmfestival(berlin_competition).
:- \+monarch(precious_father).
:- \+lymphnode(firetide_nodes_review).
:- \+mountain(pocono_mountains_of_northeastern_pennsylvania).
:- \+everypromotedthing(golf_club_bag).
:- \+hallwayitem(shuttle_window).
:- \+drug(buspirone_buspirone).
:- \+room(modern_office).
:- \+conference(acm).
:- \+lymphnode(where_are_supraclavicular_lymph_nodes).
:- \+bird(white_tighed_swallow).
:- \+sportsequipment(football_goal_posts).
:- \+furniture(large_teak_table).
:- \+sportsteam(university_of_indonesia).
:- \+physicsterm(n53_cents).
:- \+publication(mothering).
:- \+musicalbum(something_with_vaseline_in_the_name).
:- \+nongovorganization(health_committee).
:- \+braintissue(political_system).
:- \+lymphnode(burning_pain_and_swollen_lymph_nodes).
:- \+director(late_heath_ledger).
:- \+cheese(absolute_value).
:- \+consumerelectronicitem(cod2_game_servers).
:- \+tableitem(phone_device).
:- \+musicfestival(july_2003_meeting).
:- \+visualizablething(cum).
:- \+victim(ph_d__candidates).
:- \+insect(are_fast_moving_insect).
:- \+researchproject(scientific_studies).
:- \+street(north).
:- \+cognitiveactions(i_cant_stop_thinking_about_her).
:- \+room(twin_bedroom).
:- \+nondiseasecondition(early_growth_stages).
:- \+buildingmaterial(iron_sulfur_cluster).
:- \+reptile(kimberly_rock_monitor).
:- \+river(unnamed_trib_of_mary_s_creek).
:- \+sportsevent(olympic_season).
:- \+bedroomitem(radio_italiana_on_line).
:- \+victim(three_undergraduate_students).
:- \+weapon(gas_substitutes).
:- \+invertebrate(scale_financing).
:- \+politicsissue(service_management).
:- \+visualartform(minute_engineering).
:- \+condiment(coca_cola_barbecue_sauce___2).
:- \+year(n1931_1992).
:- \+politicalparty(republican_majorities).
:- \+farm(tulelake_farm_advisor).
:- \+university(central_carolina_community_college_sanford).
:- \+victim(developmental_students).
:- \+victim(guest_students).
:- \+flooritem(product_table).
:- \+geopoliticallocation(kiri).
:- \+musicartist(fort_collins_wind_symphony).
:- \+geopoliticalorganization(n20794_city_hereford).
:- \+book(leave_it_to_cleavage).
:- \+attraction(city_center).
:- \+year(n1850_1924).
:- \+crimeorcharge(three_mistakes).
:- \+artery(breathing_tubes).
:- \+cheese(cached_value).
:- \+year(n1872_1926).
:- \+currency(flores).
:- \+tradeunion(american_postal_wrks_union).
:- \+hobby(music__violin).
:- \+hobby(local_music).
:- \+geopoliticalorganization(dadiangas).
:- \+highway(church_street).
:- \+bone(human_knee).
:- \+city(alaska).
:- \+nondiseasecondition(incubation_phase).
:- \+food(charcoal).
:- \+ethnicgroup(sranang_tongo).
:- \+militaryeventtype(cyber_attacks).
:- \+videogame(tales_of_the_world___radiant_mythology).
:- \+animal(scavengers).
:- \+wallitem(courseinfo).
:- \+food(fresh_torilla_chips).
:- \+medicalprocedure(high_quality_treatments).
:- \+island(easdale).
:- \+musicinstrument(contents_eagle).
:- \+recipe(chicken_recipe_sites).
:- \+researchproject(several_recent_studies).
:- \+recipe(easy_to_make_chili_recipes).
:- \+terroristorganization(democratic_party).
:- \+nongovorganization(planned_parenthood).
:- \+condiment(an_uncommon_pasta_sauce).
:- \+election(n2007_school_boards_election).
:- \+mlarea(other_challenges).
:- \+hobby(bmx).
:- \+personasia(mike_mackenzie).
:- \+insect(codling_moths).
:- \+terroristorganization(free_democratic_party).
:- \+terroristorganization(social_democratic_party).
:- \+terroristorganization(german_social_democratic_party).
:- \+wine(texas_wine).
:- \+bacteria(r__salmoninarum).
:- \+athlete(baseball_players).
:- \+sportsgame(eastern_conference).
:- \+cognitiveactions(education_higher_level_thinking_strategies).
:- \+academicfield(urban_affairs_and_public_policy).
:- \+sportsteam(central_high_school).
:- \+academicfield(handwriting_analysis).
:- \+country(switzerlandswitzerland_switzerland).
:- \+terroristorganization(jamiya_nuriya_islamia).
:- \+conference(proc__21st_acm_sigplan_conference).
:- \+airport(tri_cities).
:- \+mountain(mount_washington_cog_railway).
:- \+software(super_mario_collections).
:- \+victim(jewish_students).
:- \+victim(jewish_students).
:- \+terroristorganization(democrat_party).
:- \+terroristorganization(french_communist_party).
:- \+weatherphenomenon(asteroid_bombardment).
:- \+recordlabel(sony_music_entertainment_netherlands_b_v).
:- \+language(___span_style__color____ibilo_language).
:- \+athlete(chelsea).
:- \+musicsong(about_us).
:- \+mlconference(aamas).
:- \+food(chipotle_beef_burrito).
:- \+attraction(direct_sales_home).
:- \+stadiumoreventvenue(american_airlines_center).
:- \+race(berner_rundfahrt).
:- \+race(pennsylvania_sales_tax).
:- \+mlarea(actor_model).
:- \+country(eastern_european_countries).
:- \+weapon(uranium_fuel).
:- \+trainstation(new_hampshire_community_technical_college).
:- \+professor(edward_hallowell).
:- \+fruit(whole_plants).
:- \+plant(whole_plants).
:- \+arachnid(rates_nine_times).
:- \+householditem(wide_frying_pan_over_medium_heat).
:- \+bedroomitem(omaha_nebraska_radio_station).
:- \+automobilemaker(acura).
:- \+mlconference(time_buyer_financing).
:- \+boardgame(em_poker_casino_game_free_download).
:- \+trainstation(oregon_state_university).
:- \+musicinstrument(trombula).
:- \+hallwayitem(i_need_opaque_window).
:- \+videogame(maturation_inhibitors).
:- \+sportsequipment(trade_show_bags).
:- \+sportsequipment(trade_show_bags).
:- \+officebuildingroom(luxurious_master_suite).
:- \+traditionalgame(n5_3).
:- \+householditem(try_not_to_come_home_with_a_couch).
:- \+videogame(calcium_need).
:- \+videogame(potassium_content).
:- \+videogame(neuraminidase_inhibitor).
:- \+videogame(calcium_layer).
:- \+videogame(powerful_anti_oxidants).
:- \+videogame(beneficial_antioxidants).
:- \+consumerelectronicitem(daniusoft_video_to_3gp_converter).
:- \+videogame(ten_essential_amino_acids).
:- \+videogame(magnesium_rich_foods).
:- \+videogame(lutein___zeaxanthin).
:- \+videogame(motor_exercises).
:- \+videogame(other_ingredients).
:- \+videogame(calcium_phosphorus).
:- \+videogame(glucosamine_and_chondroitin).
:- \+videogame(oleic).
