:- \+countrylocatedingeopoliticallocation(the_philippines,states).
:- \+animaleatfood(baby,chunkier_foods).
:- \+animaleatfood(baby,finger_foods).
:- \+haswikipediaurl(river_dart,'//en.wikipedia.org/wiki/River%20Dart').
:- \+synonymfor(armistice_day,remembrance_day).
:- \+sportusesequipment(tennis,performance).
:- \+sportusesequipment(tennis,performance).
:- \+synonymfor(office,division).
:- \+sportschoolincountry(ski,turkey).
:- \+sportusesequipment(ski,packages).
:- \+sportusesequipment(sports,jewelry).
:- \+sportusesequipment(football,apparel).
:- \+sportusesequipment(pool,field).
:- \+sportusesequipment(sports,racquetball).
:- \+sportusesequipment(swimming,accessories).
:- \+sportusesequipment(basketball,clubs).
:- \+sportusesequipment(basketball,field).
:- \+sportusesequipment(basketball,children).
:- \+sportusesequipment(softball,football).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(championships,baseball).
:- \+sportusesequipment(baseball,photos).
:- \+bookwriter(king_john,shakespeare).
:- \+academicfieldsuchasacademicfield(biology,history).
:- \+academicfieldsuchasacademicfield(biology,history).
:- \+academicfieldsuchasacademicfield(biology,environment).
:- \+academicfieldsuchasacademicfield(astronomy,business).
:- \+academicfieldsuchasacademicfield(astronomy,history).
:- \+academicfieldsuchasacademicfield(astronomy,history).
:- \+academicfieldsuchasacademicfield(business,planning).
:- \+academicprogramatuniversity(business,graduate_school).
:- \+academicprogramatuniversity(business,babson_college).
:- \+academicfieldsuchasacademicfield(actuarial_science,accounting).
:- \+academicfieldsuchasacademicfield(computer_science,civil_engineering).
:- \+academicfieldsuchasacademicfield(exercise_sciences,environmental_science).
:- \+academicfieldsuchasacademicfield(mechanical_engineering,mathematics).
:- \+academicfieldsuchasacademicfield(genetics,medical).
:- \+academicfieldsuchasacademicfield(chemical_engineering,business_management).
:- \+languageofcountry(persian,bahrain).
:- \+languageofcountry(english,slovenia).
:- \+languageofcountry(english,croatia).
:- \+sportschoolincountry(golf,thailand).
:- \+languageofcountry(russian,malaysia).
:- \+languageofcountry(russian,singapore).
:- \+languageofcity(spanish,baltimore).
:- \+languageofcity(spanish,toronto).
:- \+languageofcity(spanish,portland).
:- \+languageofuniversity(french,indiana_university).
:- \+languageofcity(spanish,minneapolis).
:- \+languageofcity(spanish,milwaukee).
:- \+languageofcity(spanish,milwaukee).
:- \+languageofcity(spanish,tucson).
:- \+emotionassociatedwithdisease(mental_illness,disorders).
:- \+emotionassociatedwithdisease(type,disorder).
:- \+emotionassociatedwithdisease(type,disorder).
:- \+emotionassociatedwithdisease(disorder,dysthymic_disorder).
:- \+emotionassociatedwithdisease(disorder,disorder).
:- \+emotionassociatedwithdisease(disorder,premenstrual_dysphoric_disorder).
:- \+emotionassociatedwithdisease(disorder,syndrome).
:- \+emotionassociatedwithdisease(disorder,personality_disorders).
:- \+emotionassociatedwithdisease(abuse,disorder).
:- \+emotionassociatedwithdisease(disorder,paranoid_schizophrenia).
:- \+emotionassociatedwithdisease(disorder,fibromyalgia).
:- \+plantrepresentemotion(orchids,love).
:- \+plantrepresentemotion(pansies,love).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(escherichia_coli,infections).
:- \+plantincludeplant(mahogany,trees).
:- \+plantincludeplant(mahogany,trees).
:- \+plantincludeplant(hazelnut,trees).
:- \+plantincludeplant(magnolia,tree).
:- \+plantincludeplant(magnolia,tree).
:- \+plantincludeplant(pecan,trees).
:- \+plantincludeplant(hardwood,trees).
:- \+plantincludeplant(hardwood,trees).
:- \+sportsgameteam(fifa_world_cup,brazil).
:- \+plantincludeplant(maple,hardwood).
:- \+plantincludeplant(balsam,trees).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(s_,system).
:- \+plantincludeplant(eucalyptus,trees).
:- \+sportsgameteam(finals,jazz).
:- \+sportsgameteam(fa_cup,spurs).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,children).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,endocarditis).
:- \+emotionassociatedwithdisease(fear,addiction).
:- \+languageofcity(spanish,albany).
:- \+languageofuniversity(spanish,ucla).
:- \+languageofcountry(russian,australia).
:- \+languageofcountry(russian,australia).
:- \+bookwriter(evil_under_the_sun,agatha_christie).
:- \+sportschoolincountry(bjj,brazil).
:- \+sportschoolincountry(golf,japan).
:- \+plantincludeplant(lime,trees).
:- \+sportsgamedate(first_playoff,n2002).
:- \+bookwriter(alice_in_wonderland,lewis_carrol).
:- \+sportsgamescore(first_game,4-2).
:- \+animalsuchasinsect(midges,insects).
:- \+persondiedatage(dad,10).
:- \+languageofcity(liberal_arts,new_york_city).
:- \+plantincludeplant(douglas_fir,trees).
:- \+sportusesequipment(basketball,collectible).
:- \+academicfieldsuchasacademicfield(information_technology,engineering).
:- \+sportsgamewinner(world,world_champion_boston_red_sox).
:- \+plantincludeplant(gingko,trees).
:- \+plantincludeplant(citrus,trees).
:- \+academicfieldsuchasacademicfield(electrical_and_computer_engineering,educational_leadership).
:- \+academicfieldsuchasacademicfield(exercise_sciences,electrical_and_computer_engineering).
:- \+animaleatfood(ants,plants).
:- \+arthropodcalledarthropod(spiders,black_widow_spiders).
:- \+animalsuchasinvertebrate(ants,pests).
:- \+animalpreyson(livestock,man).
:- \+animaleatfood(cows,dinner).
:- \+animaleatfood(dogs,chocolate).
:- \+animaldevelopdisease(cats,acne).
:- \+animaldevelopdisease(cats,acne).
:- \+animalpreyson(mammals,monkeys).
:- \+animaleatfood(dogs,hamsters).
:- \+agriculturalproductincludingagriculturalproduct(cows,chickens).
:- \+animaleatfood(animals,flower).
:- \+animaldevelopdisease(cats,respiratory_infection).
:- \+animalpreyson(animals,alpacas).
:- \+animalistypeofanimal(animals,pheasants).
:- \+animalistypeofanimal(animals,pheasants).
:- \+agriculturalproductincludingagriculturalproduct(cattle,beef).
:- \+animalpreyson(dog,animals).
:- \+animalpreyson(rabbits,wild_animals).
:- \+animalpreyson(boars,birds).
:- \+animaleatvegetable(turkey,sauerkraut).
:- \+animalistypeofanimal(snakes,animals).
:- \+animalsuchasfish(endangered_species,salmon).
:- \+animaldevelopdisease(child,hepatitis_b).
:- \+ismultipleof(herds,goats).
:- \+animalthatfeedoninsect(cow,flies).
:- \+chemicalistypeofchemical(sulfur,coal).
:- \+chemicalistypeofchemical(water,vinegar).
:- \+chemicalistypeofchemical(water,pollutants).
:- \+chemicalistypeofchemical(carbon,ash).
:- \+chemicalistypeofchemical(water,pollutant).
:- \+chemicalistypeofchemical(gas,non_renewable_resources).
:- \+chemicalistypeofchemical(carbon,help).
:- \+chemicalistypeofchemical(gases,mercury).
:- \+chemicalistypeofchemical(gas,carbon).
:- \+chemicalistypeofchemical(gases,carbon).
:- \+chemicalistypeofchemical(oxygen,hydrogen).
:- \+chemicalistypeofchemical(oxygen,nitrogen).
:- \+chemicalistypeofchemical(liquid,vinegar).
:- \+chemicalistypeofchemical(cadmium,water).
:- \+chemicalistypeofchemical(metal,materials).
:- \+chemicalistypeofchemical(metal,materials).
:- \+chemicalistypeofchemical(chemicals,mercury).
:- \+chemicalistypeofchemical(trichloroethylene,water).
:- \+fishservedwithfood(appetizer,sauce).
:- \+chemicalistypeofchemical(fuels,petroleum).
:- \+chemicalistypeofchemical(water,petroleum).
:- \+chemicalistypeofchemical(petroleum,gas).
:- \+countrylocatedingeopoliticallocation(united_state,countries).
:- \+sportsgamedate(tournament,n2002).
:- \+sporthassportsteamposition(baseball,home).
:- \+statehascapital(illinois,elgin).
:- \+citylocatedinstate(dublin,georgia).
:- \+countryalsoknownas(uganda,sudan).
:- \+citylocatedinstate(alexandria,louisiana).
:- \+statelocatedingeopoliticallocation(states,state).
:- \+countrycurrency(uss,dollars).
:- \+countryalsoknownas(austria,prussia).
:- \+countryalsoknownas(prussia,austria).
:- \+statehascapital(wa,seattle).
:- \+countrylocatedingeopoliticallocation(monaco,states).
:- \+cityalsoknownas(district,columbia).
:- \+cityliesonriver(tours,loire).
:- \+cityalsoknownas(rio,buenos_aires).
:- \+cityalsoknownas(rio,uruguay).
:- \+statehascapital(maharashtra,ratnagiri).
:- \+statehascapital(andra_pradesh,vijayawada).
:- \+citylocatedinstate(gardena,california).
:- \+cityliesonriver(cairo,mississippi).
:- \+cityalsoknownas(rio,rio_grande).
:- \+statehascapital(state,jerusalem).
:- \+countrylocatedingeopoliticallocation(republic,eastern_european_countries).
:- \+countryalsoknownas(germany,switzerland).
:- \+statelocatedingeopoliticallocation(bajacalifornia,mexico).
:- \+countryalsoknownas(mexico,canada).
:- \+countrycurrency(pa,dollars).
:- \+countrycurrency(pa,dollars).
:- \+countrylocatedingeopoliticallocation(afghanistan,countries).
:- \+countrylocatedingeopoliticallocation(algeria,countries).
:- \+countrylocatedingeopoliticallocation(argentina,countries).
:- \+countrylocatedingeopoliticallocation(burkina,countries).
:- \+cityalsoknownas(york,atlantic).
:- \+statehascapital(minnesota,bloomington).
:- \+statehascapital(delta,cleveland).
:- \+statehascapital(delta,cleveland).
:- \+motherofperson(mother,jesus_christ).
:- \+visualartistartform(leonardo,sketches).
:- \+visualartistartform(van_gogh,style).
:- \+visualartistartform(vermeer,collection).
:- \+hashusband(maat,thoth).
:- \+writerwasbornincity(pope,milan).
:- \+parentofperson(mary,isis).
:- \+professionusestool(caregivers,tools).
:- \+professionusestool(caregivers,tools).
:- \+professionusestool(caregivers,tools).
:- \+professionistypeofprofession(workers,teachers).
:- \+professionusestool(home,tools).
:- \+professionistypeofprofession(nurses,aides).
:- \+professionusestool(professionals,materials).
:- \+agriculturalproductincludingagriculturalproduct(cereals,rye).
:- \+agriculturalproductcutintogeometricshape(bacon,dice).
:- \+agriculturalproductcontainchemical(tea,cream).
:- \+agriculturalproductcutintogeometricshape(bacon,squares).
:- \+agriculturalproductcutintogeometricshape(bacon,cubes).
:- \+beveragecontainsprotein(milk,igg).
:- \+agriculturalproductcookedwithagriculturalproduct(sunflower_seeds,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(sunflower_seeds,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(tomatoes,cream).
:- \+agriculturalproductincludingagriculturalproduct(cereals,corn).
:- \+agriculturalproductcookedwithagriculturalproduct(beef,sour_cream).
:- \+agriculturalproductcookedwithagriculturalproduct(spinach,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(sunflower_seeds,wheat).
:- \+beveragecontainsprotein(milk,hydrocortisone).
:- \+agriculturalproductcookedwithagriculturalproduct(chicken,onions).
:- \+agriculturalproductincludingagriculturalproduct(beef,dairy_products).
:- \+agriculturalproductcookedwithagriculturalproduct(tomatoes,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(chicken,milk).
:- \+agriculturalproductcookedwithagriculturalproduct(corn,garlic).
:- \+agriculturalproductincludingagriculturalproduct(crops,grapes).
:- \+agriculturalproductcookedwithagriculturalproduct(onions,brown_sugar).
:- \+agriculturalproductcookedwithagriculturalproduct(onions,whey).
:- \+agriculturalproductcookedwithagriculturalproduct(cucumber,onions).
:- \+beveragemadefrombeverage(red_wine,petite_sirah).
:- \+agriculturalproductcookedwithagriculturalproduct(pumpkin,onions).
:- \+beveragemadefrombeverage(red_wine,zinfandel).
:- \+beveragemadefrombeverage(red_wine,vermentino).
:- \+agriculturalproductcookedwithagriculturalproduct(garlic,bell_peppers).
:- \+itemfoundinroom(beds,area).
:- \+drughassideeffect(cilostazol,side_effects).
:- \+buildingfeaturemadefrombuildingmaterial(doors,vinyl).
:- \+buildingfeaturemadefrombuildingmaterial(doors,aluminium).
:- \+beveragemadefrombeverage(cocktail,absinthe).
:- \+furniturefoundinroom(double_bed,area).
:- \+beveragemadefrombeverage(cocktail,espresso).
:- \+beveragemadefrombeverage(wines,zinfandel).
:- \+beveragemadefrombeverage(wines,zinfandel).
:- \+beveragemadefrombeverage(cocktail,chocolate).
:- \+buildingfeaturemadefrombuildingmaterial(walls,stained_glass).
:- \+productinstanceof(linux,applications).
:- \+beveragemadefrombeverage(cocktail,apricot_brandy).
:- \+beveragemadefrombeverage(cocktail,cherry).
:- \+beveragemadefrombeverage(cocktail,ice_cubes).
:- \+beveragemadefrombeverage(wines,syrah).
:- \+agriculturalproductincludingagriculturalproduct(crops,pulse).
:- \+beveragemadefrombeverage(red_wine_vinegar,juice).
:- \+fooddecreasestheriskofdisease(strength,cancer).
:- \+buildingfeaturemadefrombuildingmaterial(knob,cabinet).
:- \+furniturefoundinroom(beds,baths).
:- \+drughassideeffect(microzide,side_effects).
:- \+buildingfeaturemadefrombuildingmaterial(floor,vinyl).
:- \+buildingfeaturemadefrombuildingmaterial(doors,cabinet).
:- \+agriculturalproductincludingagriculturalproduct(crops,christmas_trees).
:- \+beveragemadefrombeverage(orange,juice).
:- \+agriculturalproductcookedwithagriculturalproduct(milk,pepper).
:- \+agriculturalproductcookedwithagriculturalproduct(milk,pepper).
:- \+agriculturalproductcookedwithagriculturalproduct(sesame_seeds,pepper).
:- \+eventdate(world_war_ii,december_1941).
:- \+arterycalledartery(aorta,arteries).
:- \+arterycalledartery(posterior_cerebral,arteries).
:- \+arterycalledartery(vertebral,arteries).
:- \+arterycalledartery(carotid,arteries).
:- \+arterycalledartery(arteries,carotid).
:- \+clothingmadefromplant(gifts,flower).
:- \+clothingmadefromplant(socks,bamboo).
:- \+clothingtogowithclothing(pants,collar).
:- \+clothingtogowithclothing(tee,shirt).
:- \+clothingtogowithclothing(tee,shirt).
:- \+clothingmadefromplant(products,flower).
:- \+itemfoundinroom(sofa,area).
:- \+furniturefoundinroom(sleeper_sofa,area).
:- \+furniturefoundinroom(size_sofa_bed,area).
:- \+furniturefoundinroom(bed,porch).
:- \+furniturefoundinroom(bed,front_room).
:- \+furniturefoundinroom(bed,master).
:- \+furniturefoundinroom(bed,master).
:- \+clothingtogowithclothing(rugby_shirts,shirts).
:- \+clothingtogowithclothing(shirts,rugby_shirts).
:- \+clothingtogowithclothing(apron,shirt).
:- \+furniturefoundinroom(size,guest_room).
:- \+furniturefoundinroom(nesting_table,living_room).
:- \+arteryarisesfromartery(pulmonary_artery,right_pulmonary_artery).
:- \+clothingtogowithclothing(top,long_skirt).
:- \+clothingtogowithclothing(jersey,shorts).
:- \+agriculturalproductcookedwithagriculturalproduct(green_peas,spices).
:- \+agriculturalproductcookedwithagriculturalproduct(green_peas,onions).
:- \+clothingtogowithclothing(jersey,tights).
:- \+arterycalledartery(arteries,subclavian).
:- \+agriculturalproductincludingagriculturalproduct(products,meal).
:- \+agriculturalproductcookedwithagriculturalproduct(spices,green_peas).
:- \+agriculturalproductincludingagriculturalproduct(substitutes,milk).
:- \+agriculturalproductcookedwithagriculturalproduct(whey,apples).
:- \+agriculturalproductcontainchemical(cow,calcium).
:- \+agriculturalproductcontainchemical(seeds,caffeine).
:- \+agriculturalproductincludingagriculturalproduct(allergies,milk).
:- \+agriculturalproductcomingfromvertebrate(stock,cows).
:- \+agriculturalproductincludingagriculturalproduct(allergies,wheat).
:- \+agriculturalproductcookedwithagriculturalproduct(whey,sour_cream).
:- \+clothingmadefromplant(dress,flower).
:- \+clothingmadefromplant(dresses,flower).
:- \+clothingtogowithclothing(shirt,tuxedo).
:- \+clothingmadefromplant(robes,bamboo).
:- \+clothingmadefromplant(robes,bamboo).
:- \+clothingtogowithclothing(tops,sleeve).
:- \+clothingmadefromplant(clothes,bamboo).
:- \+clothingmadefromplant(shoes,bamboo).
:- \+clothingtogowithclothing(long_sleeves,shirts).
:- \+clothingmadefromplant(t_shirts,bamboo).
:- \+weaponmadeincountry(devices,pakistan).
:- \+weaponmadeincountry(technologies,iran).
:- \+agriculturalproductcomingfromvertebrate(medicines,animals).
:- \+clothingtogowithclothing(shirt,pencil_skirt).
:- \+weaponmadeincountry(weapons,dprk).
:- \+agriculturalproductcomingfromvertebrate(egg_masses,females).
:- \+agriculturalproductcookedwithagriculturalproduct(brown_sugar,chicken).
:- \+agriculturalproductincludingagriculturalproduct(products,margarine).
:- \+professionistypeofprofession(workers,doctor).
:- \+haswikipediaurl(colt_45,'//en.wikipedia.org/wiki/Colt%2045%20(malt%20liquor)').
:- \+beveragecontainsprotein(juice,proteins).
:- \+personhasjobposition(charles,king).
:- \+agriculturalproductgrowinginstateorprovince(orange,kansas).
:- \+agriculturalproductgrowinginstateorprovince(orange,nebraska).
:- \+agriculturalproductcontainchemical(coffee,sweeteners).
:- \+buildingfeaturemadefrombuildingmaterial(heating,wood).
:- \+clothingmadefromplant(underwear,trees).
:- \+visualartistartform(picasso,sculptures).
:- \+persondiedatage(adam,930).
:- \+politicianusendorsedbypoliticianus(tipper_gore,clinton).
:- \+politicianusendorsedbypoliticianus(george_w___bush,clinton).
:- \+musicianinmusicartist(jimmy_page,zep).
:- \+athleteplayssportsteamposition(steve,player).
:- \+athleteplayssportsteamposition(steve,player).
:- \+athleteinjuredhisbodypart(steve,hand).
:- \+athleteinjuredhisbodypart(steve,shoulder).
:- \+athleteinjuredhisbodypart(steve,knee).
:- \+politicianrepresentslocation(norm_coleman,republican).
:- \+directordirectedmovie(steven_spielberg,close_encounters).
:- \+directordirectedmovie(steven_spielberg,hook).
:- \+cityalsoknownas(london,york).
:- \+beveragemadefrombeverage(egg,peel).
:- \+hospitalincity(presbyterian,charlotte).
:- \+buildinglocatedincity(detroit_metropolitan_wayne_county,detroit).
:- \+haswikipediaurl(tuntutuliak_airport,'//en.wikipedia.org/wiki/Tuntutuliak%20Airport').
:- \+parkincity(leicester_square,london).
:- \+riveremptiesintoriver(mississippi,arkansas_river).
:- \+sportusesequipment(adventure,equipment).
:- \+hasofficeincity(daily_news,los_angeles).
:- \+riveremptiesintoriver(columbia,lake_chelan).
:- \+bookwriter(east,john_steinbeck).
:- \+synonymfor(economic_development_council,board).
:- \+agriculturalproductincludingagriculturalproduct(legumes,alfalfa).
:- \+agriculturalproducttoattractinsect(oils,insects).
:- \+drugpossiblytreatsphysiologicalcondition(nexium,heartburn).
:- \+musicianinmusicartist(robert_plant,zep).
:- \+animalsuchasinvertebrate(roaches,insects).
:- \+teamplayssport(cornhuskers,games).
:- \+fatherofperson(abraham,jesus_christ).
:- \+politicianholdsoffice(bill_clinton,office).
:- \+politicianrepresentslocation(bill_clinton,states).
:- \+politicianusendorsedbypoliticianus(bush,hillary_clinton).
:- \+musicianplaysinstrument(charlie,fiddle).
:- \+musicianplaysinstrument(pat,fiddle).
:- \+politicianusendorsedbypoliticianus(bush_90__,john_mccain).
:- \+politicianusendorsedbypoliticianus(bush_90__,john_mccain).
:- \+musicianinmusicartist(van_halen,sammy_hagar).
:- \+politicianusendorsedbypoliticianus(bush,rush_limbaugh).
:- \+parentofperson(abraham,lord).
:- \+athleteplaysforteam(robinho,brazil).
:- \+politicianusendorsedbypoliticianus(clinton,bush).
:- \+politicianholdsoffice(secretary,vice_president).
:- \+persongraduatedschool(he,auburn_university).
:- \+musicartistgenre(bob_dylan,protest).
:- \+musicartistgenre(the_grateful_dead,jam).
:- \+politicianusendorsedbypoliticianus(clinton,bill).
:- \+musicianinmusicartist(black_sabbath,tony_iommi).
:- \+persongraduatedfromuniversity(president,yale).
:- \+politicianusendorsedbypoliticianus(mitt_romney,clinton).
:- \+politicianusendorsedbypoliticianus(mitt_romney,clinton).
:- \+personhasresidenceingeopoliticallocation(governor,massachusetts).
:- \+fatherofperson(noah,lord).
:- \+musicianplaysinstrument(barber,violin).
:- \+musicianinmusicartist(john,joan_baez).
:- \+athletehomestadium(ronaldinho,camp_nou).
:- \+actorsuchasactor(theater_actors,raul_julia).
:- \+malemovedtostateorprovince(edwards,new_york).
:- \+subpartof(good_air,system).
:- \+teamwontrophy(dallas_cowboys,three_super_bowls).
:- \+teamplayssport(washington_nationals,games).
:- \+fatherofperson(laban,pharaoh).
:- \+fatherofperson(abraham,yahweh).
:- \+teamplayssport(pittsburgh_steelers,games).
:- \+companyeconomicsector(suez,water).
:- \+bankboughtbank(citi,countrywide).
:- \+producesproduct(toyota,suv).
:- \+acquired(gm,chevrolet).
:- \+acquired(gm,chevrolet).
:- \+producesproduct(honda,toyota_prius).
:- \+automobilemakerdealersincountry(mitsubishi,canada).
:- \+automakerproducesmodel(lincoln,navigator).
:- \+automakerproducesmodel(lincoln,mark_lt).
:- \+teamplaysagainstteam(baltimore_orioles,indians).
:- \+automobilemakerdealersincountry(toyota,deutschland).
:- \+automobilemakerdealersincity(honda,seattle).
:- \+automobilemakercardealersinstateorprovince(honda,arizona).
:- \+itemfoundinroom(sleeper,area).
:- \+agentparticipatedinevent(benefits,result).
:- \+persondiedatage(michael_crichton,66).
:- \+persondiedatage(bernie_mac,50).
:- \+synonymfor(three,executive).
:- \+synonymfor(vice,analysis).
:- \+subpartof(improvements,air).
:- \+subpartof(home,good_air).
:- \+subpartof(center,air).
:- \+producesproduct(sony,nintendo_wii).
:- \+itemfoundinroom(tv,bathroom).
:- \+synonymfor(committee,directors).
:- \+synonymfor(four,residence).
:- \+synonymfor(four,council).
:- \+subpartof(treatment_plant,water).
:- \+itemfoundinroom(private_bathroom,separate_shower).
:- \+itemfoundinroom(tub,bedroom).
:- \+itemfoundinroom(tub,bedroom).
:- \+synonymfor(excel,microsoft).
:- \+fooddecreasestheriskofdisease(drops,cancer).
:- \+itemfoundinroom(tub,one_bath).
:- \+agentparticipatedinevent(patient,result).
:- \+companyeconomicsector(discount,insurance).
:- \+agentparticipatedinevent(place,turn).
:- \+persondiedatage(mark,10).
:- \+synonymfor(microsoft,entourage).
:- \+persondiedatage(alex002,3).
:- \+personhasage(barack_obama,47).
:- \+headquarteredin(small_business,london).
:- \+persondiedatage(lord,14).
:- \+hasofficeincity(post,los_angeles).
:- \+athleteinjuredhisbodypart(roy_smith,foot).
:- \+coachesinleague(joey_graham,nba).
:- \+parentofperson(steve_trout,dizzy_trout).
:- \+professionusestool(email,tools).
:- \+professionusestool(email,tools).
:- \+agriculturalproductcontainchemical(lactobacillus,caffeine).
:- \+aquariumincity(the_natural_history_museum,london).
:- \+beveragecontainsprotein(family,factor).
:- \+cityliesonriver(jamaica,east).
:- \+sportusesequipment(volleyball,basketball_court).
:- \+musicartistgenre(vibrators,punk).
