:- \+chemicalistypeofchemical(chlorine,chlorine).
:- \+chemicalistypeofchemical(sulfur,oxide).
:- \+animalistypeofanimal(predators,animals).
:- \+latitudelongitude(hamster,51.5166700000000,10.6500000000000).
:- \+animalistypeofanimal(stray_dogs,animals).
:- \+animalpreyson(farm_animals,horses).
:- \+agentcompeteswithagent(birds,eagles).
:- \+animalistypeofanimal(animals,pets).
:- \+animalpreyson(pets,cats).
:- \+specializationof(host,animals).
:- \+professionistypeofprofession(staff,teachers).
:- \+statelocatedincountry(wy,usa).
:- \+citylocatedinstate(belgrade,montana).
:- \+cityalsoknownas(paris,beirut).
:- \+cityliesonriver(warsaw_ghetto,vistula).
:- \+cityalsoknownas(beirut,paris).
:- \+latitudelongitude(bow_street,52.4333300000000,-4.0333300000000).
:- \+latitudelongitude(beatles,31.1093550000000,-83.7973950000000).
:- \+locationlocatedwithinlocation(new,games).
:- \+hasofficeincity(national,warsaw_ghetto).
:- \+atdate(academy,n2005).
:- \+synonymfor(academy,board).
:- \+agentcreated(ernest_hemingway,a_farewell_to_arms).
:- \+politicianusholdsoffice(barack,vice_president).
:- \+politicianusholdsoffice(palin,vice_president).
:- \+agentcreated(stanislaw_lem,solaris).
:- \+bodypartcontainsbodypart(system,whole_body).
:- \+itemfoundinroom(bed,floor_master_bedroom).
:- \+productinstanceof(windows_ce,systems).
:- \+productinstanceof(windows_95,system).
:- \+synonymfor(doctor_death,jack_kevorkian).
:- \+subpartof(community,air).
:- \+agentcreated(anonymous,beowulf).
:- \+agentinvolvedwithitem(default,windows).
:- \+mutualproxyfor(mobile,alabama).
:- \+atdate(staff,n2006).
:- \+subpartof(needs,air).
:- \+subpartof(space,air).
:- \+itemfoundinroom(bed,library).
:- \+politicianholdsoffice(barrack_obama,office).
:- \+subpartof(system,air).
:- \+animalistypeofanimal(chipmunks,animals).
:- \+animalistypeofanimal(animals,predators).
:- \+synonymfor(department,energy).
:- \+animalistypeofanimal(animals,animals).
:- \+latitudelongitude(windex,43.1025000000000,-75.5002800000000).
:- \+professionistypeofprofession(professionals,professionals).
:- \+atdate(foundation,n2006).
:- \+itemfoundinroom(bed,main_area).
:- \+animalpreyson(pit_bull,dogs).
:- \+animalpreyson(turkeys,birds).
:- \+politicianusendorsedbypoliticianus(house,administration).
:- \+specializationof(home,cat).
:- \+persondiedatage(dad,10).
:- \+organizationacronymhasname(front_page,microsoft).
:- \+subpartof(industry,water).
:- \+atdate(home,wednesday_night).
:- \+agentcompeteswithagent(web,yahoo).
:- \+competeswith(yahoo,skype).
:- \+atdate(life,n2007).
:- \+countryalsoknownas(indonesia,china).
:- \+synonymfor(executive_director,board).
:- \+animalistypeofanimal(horse,animals).
:- \+specializationof(cattle,vertebrates).
:- \+animalistypeofanimal(pests,insects).
:- \+animalpreyson(rabbits,pests).
:- \+animalpreyson(insects,pests).
:- \+atdate(control,n2006).
:- \+animalpreyson(pets,animals).
:- \+agentinvolvedwithitem(paypal,window).
:- \+latitudelongitude(educational_counseling,41.8855900000000,-87.6261600000000).
:- \+agentcreated(site,contact).
:- \+professionistypeofprofession(professional,doctors).
:- \+academicprogramatuniversity(speech,college).
:- \+agentcreated(today,contact).
:- \+atdate(residence,saturday).
:- \+animalistypeofanimal(horses,horses).
:- \+hasofficeincity(national,beijing).
:- \+animalistypeofanimal(polar_bear,animals).
:- \+atdate(beijing,n2007).
:- \+chemicalistypeofchemical(hydrogen,carbon).
:- \+hasofficeincity(kgb,moscow).
:- \+personleadsorganization(steve,today).
:- \+atdate(japan,n2007).
:- \+countryalsoknownas(albania,greece).
:- \+companyeconomicsector(life,insurance).
:- \+chemicalistypeofchemical(water,carbon_dioxide).
:- \+persondiedatage(william,19).
:- \+teamwontrophy(mavs,championship).
:- \+chemicalistypeofchemical(carbon,dioxide).
:- \+agentcompeteswithagent(image,search).
:- \+agentcontrols(david,world).
:- \+politicianusholdsoffice(hugo_chavez,president).
:- \+agentcontrols(michael,world).
:- \+politicianrepresentslocation(rutherford_b___hayes,states).
:- \+personleadsorganization(adam,world).
:- \+productinstanceof(windows,machines).
:- \+subpartof(car,air).
:- \+atdate(board,n2005).
:- \+atdate(board,n2006).
:- \+itemfoundinroom(tub,balcony).
:- \+drugpossiblytreatsphysiologicalcondition(tamiflu,flu).
:- \+organizationacronymhasname(mit_engineers,massachusetts_institute_of_technology).
:- \+atdate(board,n1999).
:- \+atdate(board,n1998).
:- \+subpartof(information,water).
:- \+subpartof(hand,blood).
:- \+companyeconomicsector(easyjet,cost).
:- \+companyeconomicsector(easyjet,budget).
:- \+acquired(ford,lincoln).
:- \+mutualproxyfor(lincoln,nebraska).
:- \+atdate(life,n1996).
:- \+atdate(home,n1998).
:- \+latitudelongitude(mana_mana,-2.7333300000000,132.3000000000000).
:- \+atlocation(american,portsmouth).
:- \+synonymfor(eight,committee).
:- \+synonymfor(contact,committee).
:- \+agentbelongstoorganization(mike,world).
:- \+specializationof(home,life).
:- \+agentbelongstoorganization(george,world).
:- \+subpartof(market,water).
:- \+countrylocatedingeopoliticallocation(the_philippines,states).
:- \+animaleatfood(baby,chunkier_foods).
:- \+animaleatfood(baby,finger_foods).
:- \+haswikipediaurl(river_dart,'//en.wikipedia.org/wiki/River%20Dart').
:- \+synonymfor(armistice_day,remembrance_day).
:- \+sportusesequipment(tennis,performance).
:- \+synonymfor(office,division).
:- \+sportschoolincountry(ski,turkey).
:- \+sportusesequipment(ski,packages).
:- \+sportusesequipment(sports,jewelry).
:- \+sportusesequipment(football,apparel).
:- \+sportusesequipment(pool,field).
:- \+sportusesequipment(sports,racquetball).
:- \+sportusesequipment(swimming,accessories).
:- \+sportusesequipment(basketball,clubs).
:- \+sportusesequipment(basketball,field).
:- \+sportusesequipment(basketball,children).
:- \+sportusesequipment(softball,football).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(championships,baseball).
:- \+sportusesequipment(baseball,photos).
:- \+bookwriter(king_john,shakespeare).
:- \+academicfieldsuchasacademicfield(biology,history).
:- \+academicfieldsuchasacademicfield(biology,environment).
:- \+academicfieldsuchasacademicfield(astronomy,business).
:- \+academicfieldsuchasacademicfield(astronomy,history).
:- \+academicfieldsuchasacademicfield(business,planning).
:- \+academicprogramatuniversity(business,graduate_school).
:- \+academicprogramatuniversity(business,babson_college).
:- \+academicfieldsuchasacademicfield(actuarial_science,accounting).
:- \+academicfieldsuchasacademicfield(computer_science,civil_engineering).
:- \+academicfieldsuchasacademicfield(exercise_sciences,environmental_science).
:- \+academicfieldsuchasacademicfield(mechanical_engineering,mathematics).
:- \+academicfieldsuchasacademicfield(genetics,medical).
:- \+academicfieldsuchasacademicfield(chemical_engineering,business_management).
:- \+languageofcountry(persian,bahrain).
:- \+languageofcountry(english,slovenia).
:- \+languageofcountry(english,croatia).
:- \+sportschoolincountry(golf,thailand).
:- \+languageofcountry(russian,malaysia).
:- \+languageofcountry(russian,singapore).
:- \+languageofcity(spanish,baltimore).
:- \+languageofcity(spanish,toronto).
:- \+languageofcity(spanish,portland).
:- \+languageofuniversity(french,indiana_university).
:- \+languageofcity(spanish,minneapolis).
:- \+languageofcity(spanish,milwaukee).
:- \+languageofcity(spanish,tucson).
:- \+emotionassociatedwithdisease(mental_illness,disorders).
:- \+emotionassociatedwithdisease(type,disorder).
:- \+emotionassociatedwithdisease(disorder,dysthymic_disorder).
:- \+emotionassociatedwithdisease(disorder,disorder).
:- \+emotionassociatedwithdisease(disorder,premenstrual_dysphoric_disorder).
:- \+emotionassociatedwithdisease(disorder,syndrome).
:- \+emotionassociatedwithdisease(disorder,personality_disorders).
:- \+emotionassociatedwithdisease(abuse,disorder).
:- \+emotionassociatedwithdisease(disorder,paranoid_schizophrenia).
:- \+emotionassociatedwithdisease(disorder,fibromyalgia).
:- \+plantrepresentemotion(orchids,love).
:- \+plantrepresentemotion(pansies,love).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(escherichia_coli,infections).
:- \+plantincludeplant(mahogany,trees).
:- \+plantincludeplant(hazelnut,trees).
:- \+plantincludeplant(magnolia,tree).
:- \+plantincludeplant(pecan,trees).
:- \+plantincludeplant(hardwood,trees).
:- \+sportsgameteam(fifa_world_cup,brazil).
:- \+plantincludeplant(maple,hardwood).
:- \+plantincludeplant(balsam,trees).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(s_,system).
:- \+plantincludeplant(eucalyptus,trees).
:- \+sportsgameteam(finals,jazz).
:- \+sportsgameteam(fa_cup,spurs).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,children).
:- \+bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,endocarditis).
:- \+emotionassociatedwithdisease(fear,addiction).
:- \+languageofcity(spanish,albany).
:- \+languageofuniversity(spanish,ucla).
:- \+languageofcountry(russian,australia).
:- \+bookwriter(evil_under_the_sun,agatha_christie).
:- \+sportschoolincountry(bjj,brazil).
:- \+sportschoolincountry(golf,japan).
:- \+plantincludeplant(lime,trees).
:- \+sportsgamedate(first_playoff,n2002).
:- \+bookwriter(alice_in_wonderland,lewis_carrol).
:- \+sportsgamescore(first_game,4-2).
:- \+animalsuchasinsect(midges,insects).
:- \+languageofcity(liberal_arts,new_york_city).
:- \+plantincludeplant(douglas_fir,trees).
:- \+sportusesequipment(basketball,collectible).
:- \+academicfieldsuchasacademicfield(information_technology,engineering).
:- \+sportsgamewinner(world,world_champion_boston_red_sox).
:- \+plantincludeplant(gingko,trees).
:- \+plantincludeplant(citrus,trees).
:- \+academicfieldsuchasacademicfield(electrical_and_computer_engineering,educational_leadership).
:- \+academicfieldsuchasacademicfield(exercise_sciences,electrical_and_computer_engineering).
:- \+animaleatfood(ants,plants).
:- \+arthropodcalledarthropod(spiders,black_widow_spiders).
:- \+animalsuchasinvertebrate(ants,pests).
:- \+animalpreyson(livestock,man).
:- \+animaleatfood(cows,dinner).
:- \+animaleatfood(dogs,chocolate).
:- \+animaldevelopdisease(cats,acne).
:- \+animalpreyson(mammals,monkeys).
:- \+animaleatfood(dogs,hamsters).
:- \+agriculturalproductincludingagriculturalproduct(cows,chickens).
:- \+animaleatfood(animals,flower).
:- \+animaldevelopdisease(cats,respiratory_infection).
:- \+animalpreyson(animals,alpacas).
:- \+animalistypeofanimal(animals,pheasants).
:- \+agriculturalproductincludingagriculturalproduct(cattle,beef).
:- \+animalpreyson(dog,animals).
:- \+animalpreyson(rabbits,wild_animals).
:- \+animalpreyson(boars,birds).
:- \+animaleatvegetable(turkey,sauerkraut).
:- \+animalistypeofanimal(snakes,animals).
:- \+animalsuchasfish(endangered_species,salmon).
:- \+animaldevelopdisease(child,hepatitis_b).
:- \+ismultipleof(herds,goats).
:- \+animalthatfeedoninsect(cow,flies).
:- \+chemicalistypeofchemical(sulfur,coal).
:- \+chemicalistypeofchemical(water,vinegar).
:- \+chemicalistypeofchemical(water,pollutants).
:- \+chemicalistypeofchemical(carbon,ash).
:- \+chemicalistypeofchemical(water,pollutant).
:- \+chemicalistypeofchemical(gas,non_renewable_resources).
:- \+chemicalistypeofchemical(carbon,help).
:- \+chemicalistypeofchemical(gases,mercury).
:- \+chemicalistypeofchemical(gas,carbon).
:- \+chemicalistypeofchemical(gases,carbon).
:- \+chemicalistypeofchemical(oxygen,hydrogen).
:- \+chemicalistypeofchemical(oxygen,nitrogen).
:- \+chemicalistypeofchemical(liquid,vinegar).
:- \+chemicalistypeofchemical(cadmium,water).
:- \+chemicalistypeofchemical(metal,materials).
:- \+chemicalistypeofchemical(chemicals,mercury).
:- \+chemicalistypeofchemical(trichloroethylene,water).
:- \+fishservedwithfood(appetizer,sauce).
:- \+chemicalistypeofchemical(fuels,petroleum).
:- \+chemicalistypeofchemical(water,petroleum).
:- \+chemicalistypeofchemical(petroleum,gas).
:- \+countrylocatedingeopoliticallocation(united_state,countries).
:- \+sportsgamedate(tournament,n2002).
:- \+sporthassportsteamposition(baseball,home).
:- \+statehascapital(illinois,elgin).
:- \+citylocatedinstate(dublin,georgia).
:- \+countryalsoknownas(uganda,sudan).
:- \+citylocatedinstate(alexandria,louisiana).
:- \+statelocatedingeopoliticallocation(states,state).
:- \+countrycurrency(uss,dollars).
:- \+countryalsoknownas(austria,prussia).
:- \+countryalsoknownas(prussia,austria).
:- \+statehascapital(wa,seattle).
:- \+countrylocatedingeopoliticallocation(monaco,states).
:- \+cityalsoknownas(district,columbia).
:- \+cityliesonriver(tours,loire).
:- \+cityalsoknownas(rio,buenos_aires).
:- \+cityalsoknownas(rio,uruguay).
:- \+statehascapital(maharashtra,ratnagiri).
:- \+statehascapital(andra_pradesh,vijayawada).
:- \+citylocatedinstate(gardena,california).
:- \+cityliesonriver(cairo,mississippi).
:- \+cityalsoknownas(rio,rio_grande).
:- \+statehascapital(state,jerusalem).
:- \+countrylocatedingeopoliticallocation(republic,eastern_european_countries).
:- \+countryalsoknownas(germany,switzerland).
:- \+statelocatedingeopoliticallocation(bajacalifornia,mexico).
:- \+countryalsoknownas(mexico,canada).
:- \+countrycurrency(pa,dollars).
:- \+countrylocatedingeopoliticallocation(afghanistan,countries).
:- \+countrylocatedingeopoliticallocation(algeria,countries).
:- \+countrylocatedingeopoliticallocation(argentina,countries).
:- \+countrylocatedingeopoliticallocation(burkina,countries).
:- \+cityalsoknownas(york,atlantic).
:- \+statehascapital(minnesota,bloomington).
:- \+statehascapital(delta,cleveland).
:- \+motherofperson(mother,jesus_christ).
:- \+visualartistartform(leonardo,sketches).
:- \+visualartistartform(van_gogh,style).
:- \+visualartistartform(vermeer,collection).
:- \+hashusband(maat,thoth).
:- \+writerwasbornincity(pope,milan).
:- \+parentofperson(mary,isis).
:- \+professionusestool(caregivers,tools).
:- \+professionistypeofprofession(workers,teachers).
:- \+professionusestool(home,tools).
:- \+professionistypeofprofession(nurses,aides).
:- \+professionusestool(professionals,materials).
:- \+agriculturalproductincludingagriculturalproduct(cereals,rye).
:- \+agriculturalproductcutintogeometricshape(bacon,dice).
:- \+agriculturalproductcontainchemical(tea,cream).
:- \+agriculturalproductcutintogeometricshape(bacon,squares).
:- \+agriculturalproductcutintogeometricshape(bacon,cubes).
:- \+beveragecontainsprotein(milk,igg).
:- \+agriculturalproductcookedwithagriculturalproduct(sunflower_seeds,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(tomatoes,cream).
:- \+agriculturalproductincludingagriculturalproduct(cereals,corn).
:- \+agriculturalproductcookedwithagriculturalproduct(beef,sour_cream).
:- \+agriculturalproductcookedwithagriculturalproduct(spinach,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(sunflower_seeds,wheat).
:- \+beveragecontainsprotein(milk,hydrocortisone).
:- \+agriculturalproductcookedwithagriculturalproduct(chicken,onions).
:- \+agriculturalproductincludingagriculturalproduct(beef,dairy_products).
:- \+agriculturalproductcookedwithagriculturalproduct(tomatoes,chicken).
:- \+agriculturalproductcookedwithagriculturalproduct(chicken,milk).
:- \+agriculturalproductcookedwithagriculturalproduct(corn,garlic).
:- \+agriculturalproductincludingagriculturalproduct(crops,grapes).
:- \+agriculturalproductcookedwithagriculturalproduct(onions,brown_sugar).
:- \+agriculturalproductcookedwithagriculturalproduct(onions,whey).
:- \+agriculturalproductcookedwithagriculturalproduct(cucumber,onions).
:- \+beveragemadefrombeverage(red_wine,petite_sirah).
:- \+agriculturalproductcookedwithagriculturalproduct(pumpkin,onions).
:- \+beveragemadefrombeverage(red_wine,zinfandel).
:- \+beveragemadefrombeverage(red_wine,vermentino).
:- \+agriculturalproductcookedwithagriculturalproduct(garlic,bell_peppers).
:- \+itemfoundinroom(beds,area).
:- \+drughassideeffect(cilostazol,side_effects).
:- \+buildingfeaturemadefrombuildingmaterial(doors,vinyl).
:- \+buildingfeaturemadefrombuildingmaterial(doors,aluminium).
:- \+beveragemadefrombeverage(cocktail,absinthe).
:- \+furniturefoundinroom(double_bed,area).
:- \+beveragemadefrombeverage(cocktail,espresso).
:- \+beveragemadefrombeverage(wines,zinfandel).
:- \+beveragemadefrombeverage(cocktail,chocolate).
:- \+buildingfeaturemadefrombuildingmaterial(walls,stained_glass).
:- \+productinstanceof(linux,applications).
:- \+beveragemadefrombeverage(cocktail,apricot_brandy).
:- \+beveragemadefrombeverage(cocktail,cherry).
:- \+beveragemadefrombeverage(cocktail,ice_cubes).
:- \+beveragemadefrombeverage(wines,syrah).
:- \+agriculturalproductincludingagriculturalproduct(crops,pulse).
:- \+beveragemadefrombeverage(red_wine_vinegar,juice).
:- \+fooddecreasestheriskofdisease(strength,cancer).
:- \+buildingfeaturemadefrombuildingmaterial(knob,cabinet).
:- \+furniturefoundinroom(beds,baths).
:- \+drughassideeffect(microzide,side_effects).
:- \+buildingfeaturemadefrombuildingmaterial(floor,vinyl).
:- \+buildingfeaturemadefrombuildingmaterial(doors,cabinet).
:- \+agriculturalproductincludingagriculturalproduct(crops,christmas_trees).
:- \+beveragemadefrombeverage(orange,juice).
:- \+agriculturalproductcookedwithagriculturalproduct(milk,pepper).
:- \+agriculturalproductcookedwithagriculturalproduct(sesame_seeds,pepper).
:- \+eventdate(world_war_ii,december_1941).
:- \+arterycalledartery(aorta,arteries).
:- \+arterycalledartery(posterior_cerebral,arteries).
:- \+arterycalledartery(vertebral,arteries).
:- \+arterycalledartery(carotid,arteries).
:- \+arterycalledartery(arteries,carotid).
:- \+clothingmadefromplant(gifts,flower).
:- \+clothingmadefromplant(socks,bamboo).
:- \+clothingtogowithclothing(pants,collar).
:- \+clothingtogowithclothing(tee,shirt).
:- \+clothingmadefromplant(products,flower).
:- \+itemfoundinroom(sofa,area).
:- \+furniturefoundinroom(sleeper_sofa,area).
:- \+furniturefoundinroom(size_sofa_bed,area).
:- \+furniturefoundinroom(bed,porch).
:- \+furniturefoundinroom(bed,front_room).
:- \+furniturefoundinroom(bed,master).
:- \+clothingtogowithclothing(rugby_shirts,shirts).
:- \+clothingtogowithclothing(shirts,rugby_shirts).
:- \+clothingtogowithclothing(apron,shirt).
:- \+furniturefoundinroom(size,guest_room).
:- \+furniturefoundinroom(nesting_table,living_room).
:- \+arteryarisesfromartery(pulmonary_artery,right_pulmonary_artery).
:- \+clothingtogowithclothing(top,long_skirt).
:- \+clothingtogowithclothing(jersey,shorts).
:- \+agriculturalproductcookedwithagriculturalproduct(green_peas,spices).
:- \+agriculturalproductcookedwithagriculturalproduct(green_peas,onions).
:- \+clothingtogowithclothing(jersey,tights).
:- \+arterycalledartery(arteries,subclavian).
:- \+agriculturalproductincludingagriculturalproduct(products,meal).
:- \+agriculturalproductcookedwithagriculturalproduct(spices,green_peas).
:- \+agriculturalproductincludingagriculturalproduct(substitutes,milk).
:- \+agriculturalproductcookedwithagriculturalproduct(whey,apples).
:- \+agriculturalproductcontainchemical(cow,calcium).
:- \+agriculturalproductcontainchemical(seeds,caffeine).
:- \+agriculturalproductincludingagriculturalproduct(allergies,milk).
:- \+agriculturalproductcomingfromvertebrate(stock,cows).
:- \+agriculturalproductincludingagriculturalproduct(allergies,wheat).
:- \+agriculturalproductcookedwithagriculturalproduct(whey,sour_cream).
:- \+clothingmadefromplant(dress,flower).
:- \+clothingmadefromplant(dresses,flower).
:- \+clothingtogowithclothing(shirt,tuxedo).
:- \+clothingmadefromplant(robes,bamboo).
:- \+clothingtogowithclothing(tops,sleeve).
:- \+clothingmadefromplant(clothes,bamboo).
:- \+clothingmadefromplant(shoes,bamboo).
:- \+clothingtogowithclothing(long_sleeves,shirts).
:- \+clothingmadefromplant(t_shirts,bamboo).
:- \+weaponmadeincountry(devices,pakistan).
:- \+weaponmadeincountry(technologies,iran).
:- \+agriculturalproductcomingfromvertebrate(medicines,animals).
:- \+clothingtogowithclothing(shirt,pencil_skirt).
:- \+weaponmadeincountry(weapons,dprk).
:- \+agriculturalproductcomingfromvertebrate(egg_masses,females).
:- \+agriculturalproductcookedwithagriculturalproduct(brown_sugar,chicken).
:- \+agriculturalproductincludingagriculturalproduct(products,margarine).
:- \+professionistypeofprofession(workers,doctor).
:- \+haswikipediaurl(colt_45,'//en.wikipedia.org/wiki/Colt%2045%20(malt%20liquor)').
:- \+beveragecontainsprotein(juice,proteins).
:- \+personhasjobposition(charles,king).
:- \+agriculturalproductgrowinginstateorprovince(orange,kansas).
:- \+agriculturalproductgrowinginstateorprovince(orange,nebraska).
:- \+agriculturalproductcontainchemical(coffee,sweeteners).
:- \+buildingfeaturemadefrombuildingmaterial(heating,wood).
:- \+clothingmadefromplant(underwear,trees).
:- \+visualartistartform(picasso,sculptures).
:- \+persondiedatage(adam,930).
:- \+politicianusendorsedbypoliticianus(tipper_gore,clinton).
:- \+politicianusendorsedbypoliticianus(george_w___bush,clinton).
:- \+musicianinmusicartist(jimmy_page,zep).
:- \+athleteplayssportsteamposition(steve,player).
:- \+athleteinjuredhisbodypart(steve,hand).
:- \+athleteinjuredhisbodypart(steve,shoulder).
:- \+athleteinjuredhisbodypart(steve,knee).
:- \+politicianrepresentslocation(norm_coleman,republican).
:- \+directordirectedmovie(steven_spielberg,close_encounters).
:- \+directordirectedmovie(steven_spielberg,hook).
:- \+cityalsoknownas(london,york).
:- \+beveragemadefrombeverage(egg,peel).
:- \+hospitalincity(presbyterian,charlotte).
:- \+buildinglocatedincity(detroit_metropolitan_wayne_county,detroit).
:- \+haswikipediaurl(tuntutuliak_airport,'//en.wikipedia.org/wiki/Tuntutuliak%20Airport').
:- \+parkincity(leicester_square,london).
:- \+riveremptiesintoriver(mississippi,arkansas_river).
:- \+sportusesequipment(adventure,equipment).
:- \+hasofficeincity(daily_news,los_angeles).
:- \+riveremptiesintoriver(columbia,lake_chelan).
:- \+bookwriter(east,john_steinbeck).
:- \+synonymfor(economic_development_council,board).
:- \+agriculturalproductincludingagriculturalproduct(legumes,alfalfa).
:- \+agriculturalproducttoattractinsect(oils,insects).
:- \+drugpossiblytreatsphysiologicalcondition(nexium,heartburn).
:- \+musicianinmusicartist(robert_plant,zep).
:- \+animalsuchasinvertebrate(roaches,insects).
:- \+teamplayssport(cornhuskers,games).
:- \+fatherofperson(abraham,jesus_christ).
:- \+politicianholdsoffice(bill_clinton,office).
:- \+politicianrepresentslocation(bill_clinton,states).
:- \+politicianusendorsedbypoliticianus(bush,hillary_clinton).
:- \+musicianplaysinstrument(charlie,fiddle).
:- \+musicianplaysinstrument(pat,fiddle).
:- \+politicianusendorsedbypoliticianus(bush_90__,john_mccain).
:- \+musicianinmusicartist(van_halen,sammy_hagar).
:- \+politicianusendorsedbypoliticianus(bush,rush_limbaugh).
:- \+parentofperson(abraham,lord).
:- \+athleteplaysforteam(robinho,brazil).
:- \+politicianusendorsedbypoliticianus(clinton,bush).
:- \+politicianholdsoffice(secretary,vice_president).
:- \+persongraduatedschool(he,auburn_university).
:- \+musicartistgenre(bob_dylan,protest).
:- \+musicartistgenre(the_grateful_dead,jam).
:- \+politicianusendorsedbypoliticianus(clinton,bill).
:- \+musicianinmusicartist(black_sabbath,tony_iommi).
:- \+persongraduatedfromuniversity(president,yale).
:- \+politicianusendorsedbypoliticianus(mitt_romney,clinton).
:- \+personhasresidenceingeopoliticallocation(governor,massachusetts).
:- \+fatherofperson(noah,lord).
:- \+musicianplaysinstrument(barber,violin).
:- \+musicianinmusicartist(john,joan_baez).
:- \+athletehomestadium(ronaldinho,camp_nou).
:- \+actorsuchasactor(theater_actors,raul_julia).
:- \+malemovedtostateorprovince(edwards,new_york).
:- \+subpartof(good_air,system).
:- \+teamwontrophy(dallas_cowboys,three_super_bowls).
:- \+teamplayssport(washington_nationals,games).
:- \+fatherofperson(laban,pharaoh).
:- \+fatherofperson(abraham,yahweh).
:- \+teamplayssport(pittsburgh_steelers,games).
:- \+companyeconomicsector(suez,water).
:- \+bankboughtbank(citi,countrywide).
:- \+producesproduct(toyota,suv).
:- \+acquired(gm,chevrolet).
:- \+producesproduct(honda,toyota_prius).
:- \+automobilemakerdealersincountry(mitsubishi,canada).
:- \+automakerproducesmodel(lincoln,navigator).
:- \+automakerproducesmodel(lincoln,mark_lt).
:- \+teamplaysagainstteam(baltimore_orioles,indians).
:- \+automobilemakerdealersincountry(toyota,deutschland).
:- \+automobilemakerdealersincity(honda,seattle).
:- \+automobilemakercardealersinstateorprovince(honda,arizona).
:- \+itemfoundinroom(sleeper,area).
:- \+agentparticipatedinevent(benefits,result).
:- \+persondiedatage(michael_crichton,66).
:- \+persondiedatage(bernie_mac,50).
:- \+synonymfor(three,executive).
:- \+synonymfor(vice,analysis).
:- \+subpartof(improvements,air).
:- \+subpartof(home,good_air).
:- \+subpartof(center,air).
:- \+producesproduct(sony,nintendo_wii).
:- \+itemfoundinroom(tv,bathroom).
:- \+synonymfor(committee,directors).
:- \+synonymfor(four,residence).
:- \+synonymfor(four,council).
:- \+subpartof(treatment_plant,water).
:- \+itemfoundinroom(private_bathroom,separate_shower).
:- \+itemfoundinroom(tub,bedroom).
:- \+synonymfor(excel,microsoft).
:- \+fooddecreasestheriskofdisease(drops,cancer).
:- \+itemfoundinroom(tub,one_bath).
:- \+agentparticipatedinevent(patient,result).
:- \+companyeconomicsector(discount,insurance).
:- \+agentparticipatedinevent(place,turn).
:- \+persondiedatage(mark,10).
:- \+synonymfor(microsoft,entourage).
:- \+persondiedatage(alex002,3).
:- \+personhasage(barack_obama,47).
:- \+headquarteredin(small_business,london).
:- \+persondiedatage(lord,14).
:- \+hasofficeincity(post,los_angeles).
:- \+athleteinjuredhisbodypart(roy_smith,foot).
:- \+coachesinleague(joey_graham,nba).
:- \+parentofperson(steve_trout,dizzy_trout).
:- \+professionusestool(email,tools).
:- \+agriculturalproductcontainchemical(lactobacillus,caffeine).
:- \+aquariumincity(the_natural_history_museum,london).
:- \+beveragecontainsprotein(family,factor).
:- \+cityliesonriver(jamaica,east).
:- \+sportusesequipment(volleyball,basketball_court).
:- \+musicartistgenre(vibrators,punk).
:- \+languageofcountry(spanish,tucson).
:- \+animalsuchasinvertebrate(midges,insects).
:- \+arthropodandotherarthropod(spiders,black_widow_spiders).
:- \+itemfoundinroom(beds,baths).
:- \+itemfoundinroom(sleeper_sofa,area).
:- \+itemfoundinroom(size_sofa_bed,area).
:- \+itemfoundinroom(bed,porch).
:- \+itemfoundinroom(bed,front_room).
:- \+itemfoundinroom(bed,master).
:- \+itemfoundinroom(size,guest_room).
:- \+bookwriter(advise_and_consent,allen_drury).
:- \+subpartof(training,water).
:- \+personhasresidenceingeopoliticallocation(american,state).
:- \+personhasresidenceingeopoliticallocation(rendell,state).
:- \+buildingfeaturemadefrombuildingmaterial(garage_door,roller).
:- \+istallerthan(connecticut,people).
:- \+animalistypeofanimal(internet_dog,dogs).
:- \+agriculturalproductcontainchemical(root,caffeine).
:- \+countryalsoknownas(ireland,austria).
:- \+countryalsoknownas(indonesia,malaysia).
:- \+countryalsoknownas(congo,indonesia).
:- \+countryalsoknownas(indonesia,congo).
:- \+countryalsoknownas(russia,scandinavia).
:- \+chemicalistypeofchemical(dioxin,chemicals).
:- \+plantincludeplant(maple,hard_woods).
:- \+cityalsoknownas(santa_catarina,rio).
:- \+beveragemadefrombeverage(extra_virgin_olive_oil,juice).
:- \+teamplaysincity(cleveland_indians,boston).
:- \+sportschoolincountry(ski,iraq_worth).
:- \+agriculturalproductcomingfromvertebrate(eggs,ducks).
:- \+attractionmadeofbuildingmaterial(house,fiberglass).
:- \+fooddecreasestheriskofdisease(dairy_products,cancer).
:- \+agentparticipatedinevent(place,amount).
:- \+emotionassociatedwithdisease(shame,cancer).
:- \+animalsuchasinsect(mosquitos,insects).
:- \+agriculturalproducttoattractinsect(herbs,insects).
:- \+visualartistartform(picasso,ceramics).
:- \+automobilemakercardealersinstateorprovince(audi,virginia).
:- \+automobilemakercardealersinstateorprovince(audi,illinois).
:- \+automobilemakerdealersincity(audi,san_diego).
:- \+professionistypeofprofession(specialists,scientists).
:- \+arthropodcalledarthropod(crabs,sand_fleas).
:- \+chemicalistypeofchemical(nitrous_oxide,carbon).
:- \+professionusestool(graduate_students,tools).
:- \+itemfoundinroom(telephone,bathroom).
:- \+astronautssuchasaustronauts(notable_astronauts,alan_shepard).
:- \+politicianusendorsedbypoliticianus(president_elect_barack_obama,bush).
:- \+politicianusholdsoffice(mitt_romney,president).
:- \+agentparticipatedinevent(hit,series).
:- \+countryalsoknownas(slovenia,croatia).
:- \+synonymfor(office,health).
:- \+countryalsoknownas(croatia,macedonia).
:- \+animalsuchasinvertebrate(native_bees,insects).
:- \+persongraduatedschool(he,harvard).
:- \+countrylocatedingeopoliticallocation(hungary,states).
:- \+politicianholdsoffice(ma,president).
:- \+subpartof(workshop,air).
:- \+academicprogramatuniversity(technologies,college).
:- \+persongraduatedfromuniversity(andrea,college).
:- \+chemicalistypeofchemical(charcoal,gas).
:- \+animaleatfood(ants,plant_species).
:- \+plantincludeplant(pine,vegetation).
:- \+riveremptiesintoriver(mississippi_river,ohio_river).
:- \+teammate(world_number_one_rafael_nadal,roddick).
:- \+plantincludeplant(pine,trees).
:- \+sportsgamescore(eastern_conference,3-2).
:- \+teamalsoknownas(toronto_blue_jays,yankees).
:- \+subpartof(engineers,air).
:- \+agriculturalproductincludingagriculturalproduct(whole_grains,barley).
:- \+cityalsoknownas(columbia,district).
:- \+chemicalistypeofchemical(dioxide,acidic_gases).
:- \+academicprogramatuniversity(literature,college).
:- \+teamplayssport(cincinnati,football).
:- \+automobilemakercardealersinstateorprovince(honda,iowa).
:- \+bodypartcontainsbodypart(blood,atria).
:- \+plantincludeplant(junipers,trees).
:- \+animalpreyson(rats,pets).
:- \+istallerthan(main_goal,people).
:- \+teamplayssport(michigan_state,football).
:- \+politicianusendorsedbypoliticianus(huckabee,mccain).
:- \+animalistypeofanimal(pets,tigers).
:- \+hasspouse(scarlett_johansson,jennifer).
:- \+motherofperson(mother,holy_spirit).
:- \+companyeconomicsector(u_s__citizens,insurance).
:- \+itemfoundinroom(possibility,bathroom).
:- \+animalsuchasinsect(carpenter_ants,insects).
:- \+furniturefoundinroom(bed,side).
:- \+riveremptiesintoriver(missouri_river,ohio_river).
:- \+persongraduatedfromuniversity(peter,stanford_university).
:- \+cityalsoknownas(san_francisco,yerba_buena).
:- \+agriculturalproductcookedwithagriculturalproduct(rosemary,pepper).
:- \+bankbankincountry(citizens,united_states).
:- \+drughassideeffect(imipramine,side_effects).
:- \+plantincludeplant(cedars,trees).
:- \+sportusesequipment(golf,skis).
:- \+parentofperson(jesus,virgin).
:- \+politicianrepresentslocation(black,states).
:- \+beveragemadefrombeverage(mixture,cabernet_sauvignon).
:- \+professionistypeofprofession(professionals,health_professionals).
:- \+arterycalledartery(vessels,carotid).
:- \+organizationacronymhasname(anc,african_national_congress).
:- \+istallerthan(objective,people).
:- \+fooddecreasestheriskofdisease(regular_exercise,cancer).
:- \+politicianholdsoffice(ms__palin,president).
:- \+mammalsuchasmammal(sheep,mule_deer).
:- \+furniturefoundinroom(size,apartment).
:- \+politicianholdsoffice(dan_quayle,president).
:- \+hasofficeincountry(japan,european_countries).
:- \+agriculturalproductcutintogeometricshape(red_pepper,dice).
:- \+agriculturalproductincludingagriculturalproduct(plants,sugar).
:- \+bodypartcontainsbodypart(region,body).
:- \+countryalsoknownas(malawi,united_states).
:- \+animaleatfood(animals,berries).
:- \+vehicleistypeofvehicle(police_cars,ambulances).
:- \+musicianplaysinstrument(john,bass).
:- \+countryalsoknownas(japan,india).
:- \+statelocatedincountry(michigan,united_states).
:- \+countryalsoknownas(republic,japan).
:- \+animaleatfood(females,blood).
:- \+countryalsoknownas(republic,poland).
:- \+countryalsoknownas(republic,england).
:- \+teamplaysinleague(college,international).
:- \+statelocatedingeopoliticallocation(states,tanzania).
:- \+statelocatedingeopoliticallocation(states,rwanda).
:- \+lakeinstate(lake_macatawa,michigan).
:- \+sportusesstadium(basketball,new_orleans_arena).
:- \+bookwriter(kidnapped,robert_louis_stevenson).
:- \+organizationhiredperson(houses,republican).
:- \+sportusesequipment(table_tennis,equipment).
:- \+countryalsoknownas(republic,namibia).
:- \+bookwriter(alice_in_wonderland,lewis_carol).
:- \+statelocatedingeopoliticallocation(states,tibet).
:- \+streetincity(place,the_hague).
:- \+countrylocatedingeopoliticallocation(bahamas,states).
:- \+academicfieldsuchasacademicfield(public_health,business).
:- \+teamplaysagainstteam(france,brazil).
:- \+synonymfor(services_department,department).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(world_cup,soccer).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(championships,soccer).
:- \+languageofcountry(persian,kuwait).
:- \+languageofcountry(persian,qatar).
:- \+languageofcountry(persian,oman).
:- \+languagespokenatisland(english,manhattan).
:- \+languageofcountry(german,czechoslovakia).
:- \+languageofcountry(russian,korea).
:- \+languageofuniversity(english,auburn_university).
:- \+languageofcountry(macedonian,republic).
:- \+countrylocatedingeopoliticallocation(eastern_european_countries,countries).
:- \+buildinglocatedincity(braves_field,boston).
:- \+countryalsoknownas(republic,indonesia).
:- \+lakeinstate(manresa_beach,california).
:- \+stateorprovinceisborderedbystateorprovince(states,md).
:- \+countrylocatedingeopoliticallocation(sudan,states).
:- \+sportschoolincountry(ski,china).
:- \+hobbiessuchashobbies(hobbies,antiques).
:- \+animaldevelopdisease(children,sight_problems).
:- \+animalpreyson(cat,pet).
:- \+mammalsuchasmammal(horses,bears).
:- \+animalistypeofanimal(rodents,rats).
:- \+sportsgamedate(world_cup,n2008).
:- \+animalpreyson(creatures,ticks).
:- \+mammalsuchasmammal(bear,lions).
:- \+sportsgamescore(finals,0-2).
:- \+hobbiessuchashobbies(hobbies,ice_hockey).
:- \+plantincludeplant(fan_palms,trees).
:- \+plantincludeplant(apple_trees,trees).
:- \+sportsgamedate(hollywood_bowl,n2005).
:- \+teamplaysagainstteam(san_antonio,los_angeles_lakers).
:- \+personchargedwithcrime(george_w__bush,murder).
:- \+teamplaysincity(usc,columbia).
:- \+plantincludeplant(oleander,trees).
:- \+animalsuchasinsect(shrews,small_mammals).
:- \+animalistypeofanimal(animals,badgers).
:- \+invertebratefeedonfood(larvae,plant_roots).
:- \+animalistypeofanimal(mammals,bats).
:- \+animalistypeofanimal(cougar,animals).
:- \+agentparticipatedinevent(pigs,result).
:- \+subpartof(attic,air).
:- \+plantincludeplant(cherry_trees,trees).
:- \+academicprogramatuniversity(physical_therapy,northeastern_university).
:- \+plantgrowinginplant(bushes,grass).
:- \+organizationheadquarteredinstateorprovince(chicago_cubs,new_york).
:- \+persondiedatage(jason,4).
:- \+plantincludeplant(cypresses,trees).
:- \+countryalsoknownas(india,indonesia).
:- \+plantincludeplant(horse_chestnut,trees).
:- \+arthropodcalledarthropod(insects,mantids).
:- \+arthropodcalledarthropod(insects,parasitic_wasps).
:- \+arthropodcalledarthropod(pests,aphids).
:- \+animaleatfood(chicken,red_wine_sauce).
:- \+animaleatfood(chicken,brie).
:- \+organizationheadquarteredinstateorprovince(orioles,new_york).
:- \+arthropodcalledarthropod(gnats,insects).
:- \+animaleatfood(chicken,pizza).
:- \+plantincludeplant(trees,oleander).
:- \+countryalsoknownas(republic,chile).
:- \+countryalsoknownas(us,pakistan).
:- \+streetincity(north,washington_d_c).
:- \+animalpreyson(dog,furry_friends).
:- \+musicgenressuchasmusicgenres(prog,rock).
:- \+musicgenressuchasmusicgenres(thrash_metal,metal).
:- \+chemicalistypeofchemical(carbondioxide,greenhouse_gases).
:- \+chemicalistypeofchemical(greenhouse_gases,air_pollutants).
:- \+chemicalistypeofchemical(greenhouse_gases,fuels).
:- \+chemicalistypeofchemical(greenhouse_gases,pollutants).
:- \+chemicalistypeofchemical(greenhouse_gases,emissions).
:- \+agentparticipatedinevent(europe,result).
:- \+numberofkilledinbombing(four,car_bomb_hits_shiite_suburb_of_beirut__killing_2).
:- \+numberofinjuredinbombing(n28,blasts_injure_28_protesters_in_bangkok).
:- \+numberofkilledinbombing(nine,n1327689011).
:- \+numberofcasualtiesinearthquake(n7,n2000_nicaragua_earthquake).
:- \+chemicalistypeofchemical(matter,gas).
:- \+personbelongstoorganization(us_president,house).
:- \+synonymfor(cia,america).
:- \+synonymfor(committees,directors).
:- \+softwareisprogrammedinprogramminglanguage(appletviwer,java).
:- \+politicianholdsoffice(president_kennedy,office).
:- \+beveragemadefrombeverage(peaches,juice).
:- \+beveragemadefrombeverage(strawberry,juice).
:- \+personhasresidenceincountry(ehud_barak,israeli).
:- \+beveragemadefrombeverage(apricot,juice).
:- \+sourceofearthquake(central_weather_bureau,magnitude_5_4_earthquake_hits_north_taiwan).
:- \+transportationincity(caltrain,san_francisco).
:- \+athleteplaysinleague(bart_starr,nfl).
:- \+meatcomesfromanimal(chuck,cow).
:- \+furniturefoundinroom(sinks,master).
:- \+meetingeventtitleinofficebuildingroom(robot_futures,rashid_auditorium_4401).
:- \+musicianplaysinstrument(mick_jones,guitar).
:- \+persondiedincity(william_verity,beaufort).
:- \+musicianplaysinstrument(david,accordion).
:- \+professionistypeofprofession(research,nursing).
:- \+meetingeventtitleinbuilding(optimizing_password_composition_policies,gates_and_hillman_centers).
:- \+thinghascolor(moon,orange).
:- \+meetingeventtitlehasmeetingeventtype(robot_futures,scs_author_presentation___booksigning).
:- \+personhasresidenceincountry(theodor_kollek,isreal).
:- \+personhasreligion(andre_carson,islam).
:- \+politicianusholdsoffice(john,next_u_s__president).
:- \+politicianusholdsoffice(barack,next_leader).
:- \+personleadscity(mahmoud_ahmadinejad,tehran).
:- \+personchargedwithcrime(obama,crimes).
:- \+marriedinyear(he,n1995).
:- \+personbelongstoorganization(he,southern_african_development_community).
:- \+politicianusendorsedbypoliticianus(ralph_nader,bush).
:- \+personchargedwithcrime(bush,murder).
:- \+attractionbefallincity(elephant,portland).
:- \+bodypartcontainsbodypart(blood,calf).
:- \+furniturefoundinroom(bed,balcony).
:- \+politicianholdsoffice(bush,senator).
:- \+politicianrepresentslocation(bush,duck).
:- \+personhasage(president,48).
:- \+itemfoundinroom(bed,studio).
:- \+vegetableisproducedatcountry(spinach,china).
:- \+politicianusholdsoffice(bush,secretary).
:- \+politicianrepresentslocation(hillary_rodham_clinton,states).
:- \+furniturefoundinroom(bed,cabins).
:- \+foodcancausedisease(berries,blood_pressure).
:- \+politicianrepresentslocation(obama,region).
:- \+furniturefoundinroom(bed,executive).
:- \+victiminbombing(five_people,beirut_bombing__thurs__blast_in_hezbollah_run_area_of_beirut_claimed_5_lives).
:- \+bombinghaswitness(ali_oleik,beirut_bombing__thurs__blast_in_hezbollah_run_area_of_beirut_claimed_5_lives).
:- \+organizationheadquarteredinstateorprovince(detroit_lions,new_york).
:- \+leaguestadiums(mlb,olympic_stadium).
:- \+companyalsoknownas(caterpillar,cat).
:- \+personchargedwithcrime(bush,treason).
:- \+itemfoundinroom(bed,dining_room).
:- \+attractionofcity(jordan_hall,boston).
:- \+bankboughtbank(citi,wachovia).
:- \+meetingeventtitlehasmeetingeventtype(optimizing_password_composition_policies,theory_lunch_seminar).
:- \+professionusestool(business_professionals,tools).
:- \+directordirectedmovie(sylvester_stallone,rambo).
:- \+agriculturalproductcookedwithagriculturalproduct(oil,chili_pepper).
:- \+organizationterminatedperson(the_boston_public_school_system,i).
:- \+furniturefoundinroom(bed,entry).
:- \+automobilemakerdealersincountry(buick,china).
:- \+personbelongstoorganization(pat,college).
:- \+persondiedatage(benjamin,2).
:- \+politicianholdsoffice(hillary,first_woman_president).
:- \+politicianholdsoffice(hillary,president).
:- \+hasspouse(kidman,cruise).
:- \+personhasjobposition(randy_smith,general_manager).
:- \+meetingeventtitlehasmeetingeventtype(human_powered_data_management,scs_faculty_candidate).
:- \+professionistypeofprofession(jobs,nursing).
:- \+teamplaysinleague(washington_state_university,international).
:- \+istallerthan(summer,friends).
:- \+personleadscity(karl_dean,nashville).
:- \+animalsuchasinvertebrate(mice,prey).
:- \+athletebeatathlete(james_blake,williams).
:- \+automobilemakercardealersinstateorprovince(mitsubishi,virginia).
:- \+agriculturalproductcookedwithagriculturalproduct(oil,lime_juice).
:- \+clothingmadefromplant(jackets,grass).
:- \+attractionofcity(leaning_tower_of_pisa,london_city).
:- \+bankbankincountry(national,malawi).
:- \+organizationacronymhasname(office,united_states).
:- \+meetingeventtitleatdate(human_powered_data_management,april_3__2013).
:- \+touristattractionsuchastouristattraction(aquarium_salt_fresh_water_aquarium,temple_of_the_reclining_buddha).
:- \+politicianusmemberofpoliticalgroup(president_george_w_bush,house).
:- \+bakegoodistypicalincountry(croissant,usa).
:- \+ceoof(ed_colligan,palm).
:- \+bodypartcontainsbodypart(blood,tissue).
:- \+athleteflyouttosportsteamposition(chad_johnson,center).
:- \+beveragemadefrombeverage(maple_syrup,syrup).
:- \+fatherofperson(abraham,jesus).
:- \+personhasjobposition(joe002,king).
:- \+agentcontributedtocreativework(roald_dahl,collected_stories).
:- \+agentcontributedtocreativework(franz_kafka,collected_stories).
:- \+hasfamilymember(master,lord_jesus).
:- \+hasspouse(jean_kasem,casey).
:- \+citycapitalofcountry(amman,jordan).
:- \+persondiedatage(george,2).
:- \+statelocatedingeopoliticallocation(states,albania).
:- \+countryalsoknownas(republic,el_salvador).
:- \+agentcontributedtocreativework(moses,commandments).
:- \+hasfamilymember(moses,yahweh).
:- \+persondiedatage(dad,15).
:- \+riveremptiesintoriver(columbia,kootenay_river).
:- \+cityalsoknownas(columbia,langley).
:- \+persondiedatage(david,10).
:- \+countryalsoknownas(republic,germany).
:- \+persongraduatedfromuniversity(bill,boston_university).
:- \+subpartof(day,air).
:- \+personhasresidenceincity(katrina,new_orleans).
:- \+countrylocatedingeopoliticallocation(new_zealand,countries).
:- \+countrycurrency(hong_kong,dollars).
:- \+countrycurrency(nation,dollars).
:- \+touristattractionsuchastouristattraction(highland_park,temple_of_the_reclining_buddha).
:- \+televisionstationincity(wplg,miami).
:- \+citylocatedinstate(hayward,california).
:- \+personhasage(kobe_bryant,30).
:- \+citylocatedincountry(memphis,egypt).
:- \+organizationalsoknownas(__america,countries).
:- \+countryalsoknownas(__america,scotland).
:- \+statelocatedingeopoliticallocation(states,mid).
:- \+teamplaysincity(san_francisco_state_university,san_francisco).
:- \+teamplayssport(lsu,golf).
:- \+teamplayssport(germany,golf).
:- \+teamplaysinleague(trent_university,international).
:- \+teamplaysincity(humber_college,toronto).
:- \+organizationalsoknownas(__america,eastern_asia).
:- \+organizationdissolvedatdate(winter,june).
:- \+teamplaysincity(jackson_state,jackson).
:- \+citycapitalofcountry(berlin,prussia).
:- \+countryalsoknownas(republic,mexico).
:- \+synonymfor(monitoring,linux).
:- \+aquariumincity(world,vegas).
:- \+synonymfor(hungary,republic).
:- \+countryalsoknownas(republic,iran).
:- \+hasspouse(garden_of_eden,eve).
:- \+personbelongstoorganization(opinion,times).
:- \+animaleatfood(chicken,bleu_cheese).
:- \+animaleatfood(chicken,cheddar).
:- \+animaleatfood(chicken,fontina_cheese).
:- \+animaleatfood(chicken,pepper_jack_cheese).
:- \+teamplaysinleague(edmund_a__walsh_school,international).
:- \+teamhomestadium(marlins,dolphin_stadium).
:- \+timeofearthquake(n3_51am,one_dead__30_injured_in_southern_pakistan_quakes).
:- \+mountaininstate(sugarloaf_mountain,florida).
:- \+bookwriter(collected_stories,jean_stafford).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(nba_finals,basketball).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(championships,basketball).
:- \+plantincludeplant(acacia,tree).
:- \+thinghasshape(hypotenuse,right_triangle).
:- \+emotionassociatedwithdisease(sleep,abnormalities).
:- \+sportsgameteam(match,devils).
:- \+languageofuniversity(slavic,princeton_university).
:- \+sportusesequipment(gymnastics,football).
:- \+sportusesequipment(gymnastics,equipment).
:- \+sportusesequipment(gymnastics,ball).
:- \+awardtrophytournamentisthechampionshipgameofthenationalsport(semifinals,soccer).
:- \+sportusesequipment(outdoor_sports,football).
:- \+mammalsuchasmammal(bear,orca).
:- \+animaldevelopdisease(children,abnormalities).
:- \+animaleatfood(bears,strawberry).
:- \+animalistypeofanimal(large_animals,deer).
:- \+academicfieldsuchasacademicfield(technology,doctoral_degrees).
:- \+teamplaysinleague(oregon_state_university,international).
:- \+sportschoolincountry(successful_sports,__america).
:- \+languageofuniversity(russian,princeton_university).
:- \+languageofcountry(english,iran).
:- \+animalpreyson(animals,calves).
:- \+animalistypeofanimal(animals,calves).
:- \+animaldevelopdisease(child,abnormalities).
:- \+arthropodcalledarthropod(arthropods,ticks).
:- \+academicfieldsuchasacademicfield(technology,international_affairs).
:- \+arachnidiseatenbybird(tarantulas,exotic_birds).
:- \+academicfieldsuchasacademicfield(technology,higher_education).
:- \+academicfieldsuchasacademicfield(technology,electrical_engineer).
:- \+motherofperson(mother,jesus).
:- \+animaldevelopdisease(babies,abnormalities).
:- \+chemicalistypeofchemical(carbon_dioxide_emission,fuels).
:- \+numberofinjuredinprotest(n0,stuha).
:- \+politicsgroupconcernsissue(planned_parenthood,abortion).
:- \+meetingeventtitleinofficebuildingroom(human_powered_data_management,n6115).
:- \+meetingeventtitleinofficebuildingroom(holey_grail___the_mechanism_of_transport_through_the_nuclear_pore_of_cells,conference_room).
:- \+meetingeventtitlehasmeetingeventtype(finding_needles_in_exponential_haystacks,math_colloquium).
:- \+meetingeventtitleatdate(math__monkeys__and_the_developing_brain,april_25__2013).
:- \+professionssuchasprofessions(professions,jobs).
:- \+thinghascolor(eye,grey).
:- \+attractionbefallincity(max,anaheim).
:- \+agriculturalproductcamefromcountry(flowers,new_zealand).
:- \+agriculturalproductcamefromcountry(tea,hong_kong).
:- \+beveragemadefrombeverage(ginger_tea,tea).
:- \+actorstarredinmovie(heath_ledger,batman).
:- \+actorstarredinmovie(christian_bale,batman).
:- \+transportationincity(orient_express,paris).
:- \+teammate(steve_nash,iverson).
:- \+fatherofperson(arphaxad,cainan).
:- \+weaponmadeincountry(nuclear_weapon,korea).
:- \+bodypartcontainsbodypart(blood,blood_vessels).
:- \+agriculturalproductincludingagriculturalproduct(oils,corn).
:- \+objectlookslikeobject(plasma,stand).
:- \+objectlookslikeobject(two,televisions).
:- \+objectlookslikeobject(inch,televisions).
:- \+objectlookslikeobject(plasma,televisions).
:- \+politicsgroupconcernsissue(planned_parenthood,pro_choice).
:- \+directordirectedmovie(christian_bale,batman).
:- \+directordirectedmovie(christopher_nolan,batman).
:- \+personbelongstoorganization(brown,college).
:- \+hassibling(roman,caligula).
:- \+hasbrother(roman,nero).
:- \+agentcontributedtocreativework(raymond_chandler,collected_stories).
:- \+persondiedatage(mike,3).
:- \+clothingtogowithclothing(short_skirts,boots).
:- \+musicianplaysinstrument(mozart,two_pianos).
:- \+diseasemaybecausedbydrug(cancer,acid).
:- \+visualartistartform(claude_monet,collection).
:- \+agentparticipatedinevent(n13_people,result).
:- \+athletewinsawardtrophytournament(chelsea,carling_cup).
:- \+athletewinsawardtrophytournament(chelsea,fa_cup).
:- \+athletewinsawardtrophytournament(chelsea,league_cup).
:- \+personhasage(chelsea,28).
:- \+clothingtogowithclothing(underwear,hat).
:- \+agriculturalproductcamefromcountry(tea,china).
:- \+agriculturalproductcamefromcountry(tea,singapore).
:- \+competeswith(youtube,facebook).
:- \+objectlookslikeobject(two,monitors).
:- \+celebritysuchascelebrity(hollywood_stars,glen_campbell).
:- \+personbelongstoorganization(democratic_candidate,house).
:- \+athleteinjuredhisbodypart(lt__joseph_r__hunt,hands).
:- \+agentparticipatedinevent(young_people,result).
:- \+acquired(pfizer,wyeth).
:- \+actorstarredinmovie(michael_caine,italian_job).
:- \+motherofperson(eve,genesis).
:- \+politicianusendorsedbypoliticianus(oprah_winfrey,clinton).
:- \+subpartof(loops,water).
:- \+ismultipleof(illnesses,young_people).
:- \+musicianinmusicartist(robert_johnson,stones).
:- \+teamplaysinleague(loyola_university_new_orleans,international).
:- \+hasofficeincountry(the_national,china).
