bookwriter(jude_the_obscure,thomas_hardy).
bookwriter(animal_farm,orwell).
bookwriter(animal_farm,george_orwell).
bookwriter(nineteen_eighty_four,orwell).
bookwriter(nineteen_eighty_four,george_orwell).
bookwriter(tess_of_the_d_urbervilles,thomas_hardy).
bookwriter(dune,frank_herbert).
bookwriter(a_farewell_to_arms,ernest_hemingway).
bookwriter(alice_in_wonderland,lewis_carrol).
bookwriter(artemis_fowl,eoin_colfer).
sportsgameteam(world_cup,brazil).
sportusesequipment(skiing,skis).
sportusesequipment(skiing,equipment).
sportusesequipment(sports,skis).
sportusesequipment(ski,skis).
chemicalistypeofchemical(argon,gases).
chemicalistypeofchemical(argon,gas).
chemicalistypeofchemical(carbon_dioxide,gases).
chemicalistypeofchemical(carbon_dioxide,gas).
chemicalistypeofchemical(carbon_dioxide,emissions).
specializationof(osprey,birds).
animalpreyson(orcas,animals).
animalistypeofanimal(scorpions,animals).
professionistypeofprofession(engineers,professionals).
professionistypeofprofession(professionals,employees).
professionistypeofprofession(general_practitioners,staff).
attractionofcity(heineken_music_hall,amsterdam).
statelocatedincountry(ia,usa).
statehascapital(saskatchewan,regina).
airportincity(schiphol_airport,amsterdam).
citylocatedinstate(nyc,new_york).
cityliesonriver(belgrade,sava).
cityliesonriver(belgrade,danube).
musicartistgenre(sex_pistols,british_punk).
musicartistgenre(sex_pistols,punk).
musicartistgenre(sex_pistols,punk_rock).
atlocation(american,nyc).
automakerproducesmodel(nissan,altima).
acquired(volkswagen,bentley).
agentcontributedtocreativework(thomas_hardy,far_from_the_madding_crowd).
agentcreated(thomas_hardy,far_from_the_madding_crowd).
agentcontributedtocreativework(thomas_hardy,jude_the_obscure).
agentcreated(thomas_hardy,jude_the_obscure).
agentcontributedtocreativework(thomas_hardy,the_mayor_of_casterbridge).
agentcreated(thomas_hardy,tess_of_the_d_urbervilles).
actorstarredinmovie(keanu_reeves,matrix).
ceoof(dmx,bloodline_records).
directordirectedmovie(robert_zemeckis,forrest_gump).
directordirectedmovie(robert_zemeckis,beowulf).
politicianusendorsedbypoliticianus(hillary_clinton,gore).
politicianusholdsoffice(mr_bush,president).
musicianinmusicartist(johnny_rotten,sex_pistols).
politicianusendorsedbypoliticianus(bush,george_w___bush).
athleteplayssport(lennox_lewis,boxing).
agentcreated(anonymous,beowulf).
agentcontributedtocreativework(eoin_colfer,artemis_fowl).
agentcreated(eoin_colfer,artemis_fowl).
agentcreated(frank_herbert,dune).
itemfoundinroom(bed,private_master_suite).
furniturefoundinroom(berths,guest_cabin).
itemfoundinroom(sleeper_sofa,family_room).
itemfoundinroom(sleeper_sofa,den).
furniturefoundinroom(beds,open_loft).
furniturefoundinroom(beds,first_floor_bedroom).
furniturefoundinroom(beds,middle_bedroom).
furniturefoundinroom(beds,front_bedroom).
furniturefoundinroom(beds,loft_bedroom).
furniturefoundinroom(beds,second_bedrooms).
furniturefoundinroom(bed,second_double_bedroom).
itemfoundinroom(bed,one_bedroom_apartment).
itemfoundinroom(bed,family_bedroom).
itemfoundinroom(double_bed,master_bedroom).
itemfoundinroom(refrigerator,kitchen).
drughassideeffect(remeron,side_effects).
productinstanceof(windows_2000,systems).
productinstanceof(silver,metal).
agentcreated(jane_austen,emma).
specializationof(home,life).
bookwriter(alice_in_wonderland,lewis_carroll).
countrycurrency(usa,dollars).
politicianholdsoffice(barrack_obama,senators).
animalistypeofanimal(chipmunks,animals).
countrycurrency(libya,dinar).
countrycurrency(switzerland,francs).
restaurantincity(bonaparte_restaurant,montreal).
languageofcountry(arabic,qatar).
companyeconomicsector(morgan_stanley,investment_banking).
producesproduct(apple,pc).
animalistypeofanimal(horse,animals).
bookwriter(harry_potter_and_the_goblet_of_fire,j_k__rowling).
bookwriter(tristram_shandy,laurence_sterne).
bookwriter(ulysses,james_joyce).
bookwriter(ulysses,joyce).
musicianplaysinstrument(elvis_presley,guitar).
musicianinmusicartist(bono,u2).
bookwriter(the_grapes_of_wrath,john_steinbeck).
bookwriter(the_grapes_of_wrath,steinbeck).
animalpreyson(reptiles,vertebrates).
academicprogramatuniversity(engineering,virginia_tech).
animalistypeofanimal(birds,pets).
bookwriter(brave_new_world,aldous_huxley).
synonymfor(department,board).
languageofcountry(english_language,england).
chemicalistypeofchemical(pollution,emissions).
directordirectedmovie(james_cameron,aliens).
actorstarredinmovie(sigourney_weaver,aliens).
actorstarredinmovie(tom_hanks,forrest_gump).
synonymfor(office,division).
bookwriter(the_master_and_margarita,mikhail_bulgakov).
bookwriter(the_master_and_margarita,bulgakov).
bookwriter(the_brothers_karamazov,fyodor_dostoevsky).
bookwriter(the_brothers_karamazov,dostoevsky).
professionistypeofprofession(nurses,services).
animalistypeofanimal(predators,animals).
cityliesonriver(krakow,vistula).
actorstarredinmovie(tom_hanks,castaway).
actorstarredinmovie(tom_hanks,apollo_13).
actorstarredinmovie(tom_hanks,cast_away).
motherofperson(mary,james).
cityalsoknownas(charleston,charleston).
automakerproducesmodel(honda,insight).
statelocatedincountry(ca,usa).
statelocatedincountry(nj,usa).
statelocatedincountry(il,usa).
actorstarredinmovie(john_goodman,big_lebowski).
actorstarredinmovie(jeff_bridges,big_lebowski).
animalpreyson(pets,animals).
chemicalistypeofchemical(water,toxic_chemical).
teamplayssport(milwaukee_brewers,baseball).
acquired(ebay,paypal).
animalpreyson(voles,animals).
citylocatedinstate(elgin,illinois).
bookwriter(chronicles_of_narnia,c_s__lewis).
bookwriter(chronicles_of_narnia,lewis).
bookwriter(chronicles_of_narnia,c___s___lewis).
animalistypeofanimal(pigs,animal_species).
languageofcountry(greek,greece).
countrycurrency(japan,yen).
animalpreyson(predators,invertebrates).
animalistypeofanimal(greyhounds,animals).
agentcontrols(steve_jobs,pixar).
academicprogramatuniversity(architecture,massachusetts_institute_of_technology).
organizationacronymhasname(gao,government_accountability_office).
worksfor(bill_o_reilly,fox_news).
languageofuniversity(english,cleveland_state_university).
languageofuniversity(english,dartmouth_college).
animalistypeofanimal(polar_bear,animals).
acquired(lycos,tripod).
politicianrepresentslocation(president_obama,states).
animalpreyson(cats,pets).
agentcontributedtocreativework(today,world).
animalistypeofanimal(pets,animals).
languageofuniversity(english,emory_university).
animalpreyson(dogs,pets).
animalistypeofanimal(insects,insects).
locationlocatedwithinlocation(athens,greece).
languageofuniversity(english,uc_berkeley).
agentcontributedtocreativework(charlotte_bronte,jane_eyre).
teamplayssport(uconn,basketball).
teamplaysagainstteam(giants,greenbay_packers).
worksfor(steven_levy,newsweek).
academicprogramatuniversity(computer_science,uc_berkeley).
politicianusendorsedbypoliticianus(ronald_reagan,george_bush).
personleadsorganization(chris_anderson,wired).
politicianusendorsedbypoliticianus(ronald_reagan,w___bush).
politicianrepresentslocation(congress,states).
teamhomestadium(la_dodgers,dodger_stadium).
agentcompeteswithagent(search,web).
hasspouse(tom_cruise,katie).
agentcreated(jk_rowling,harry_potter_and_the_goblet_of_fire).
agentcreated(j__k__rowling,harry_potter_and_the_goblet_of_fire).
agentcreated(laurence_sterne,tristram_shandy).
agentcreated(lewis_carroll,alice_in_wonderland).
agentcreated(aldous_huxley,brave_new_world).
agentcontributedtocreativework(aldous_huxley,brave_new_world).
agentcreated(mikhail_bulgakov,the_master_and_margarita).
agentcreated(fyodor_dostoevsky,the_brothers_karamazov).
itemfoundinroom(washbasin,bathroom).
furniturefoundinroom(iron_bed,bedroom).
agentcreated(c_s__lewis,chronicles_of_narnia).
furniturefoundinroom(beds,suite_bedrooms).
productinstanceof(civic,car).
itemfoundinroom(tub,marble_bathrooms).
organizationacronymhasname(mit,massachusetts_institute_of_technology).
countrycurrency(thailand,baht).
atdate(house,friday).
agentinvolvedwithitem(nintendo,wii).
producesproduct(nintendo,wii).
bodypartcontainsbodypart(hand,arteries).
hasofficeincity(easyjet,gatwick).
atlocation(lincoln,nebraska).
locationlocatedwithinlocation(lincoln,nebraska).
agentcontributedtocreativework(frank_herbert,dune).
agentcreated(isaac_asimov,foundation).
agentactsinlocation(american,jackson).
teamplaysinleague(cornell_big_red,ncaa).
agentcreated(help,contact).
agentcontributedtocreativework(john_milton,paradise_lost).
synonymfor(league,board).
specializationof(links,info).
specializationof(links,site).
subpartof(louisville,kentucky).
agentinvolvedwithitem(information,windows).
animalsuchasinvertebrate(insects,butterflies).
statelocatedingeopoliticallocation(states,home).
animaleatfood(baby,breastmilk).
citycapitalofcountry(nassau,bahamas).
agentparticipatedinevent(ideas,result).
foodcancausedisease(junk_food,heart_attacks).
attractionofcity(hallenstadion,zurich).
sportusesequipment(hunting,apparel).
sportfansincountry(rugby,argentina).
sportschoolincountry(ski,the_united_states).
sportschoolincountry(ski,holland).
sportusesequipment(badminton,racquet).
sportschoolincountry(aikido,japan).
sporthassportsteamposition(football,offensive_guard).
sportusesequipment(golf,field).
sportusesequipment(golf,wood).
sportusesequipment(sports,protective_gear).
sportusesequipment(soccer,jersey).
sportschoolincountry(snowboard,switzerland).
sportusesstadium(basketball,united_center).
sportusesequipment(soccer,soccer_accessories).
bookwriter(the_shell_seekers,rosamunde_pilcher).
sportusesstadium(basketball,fedex_forum).
sportusesstadium(basketball,conseco_fieldhouse).
sportusesstadium(basketball,thomas___mack_center).
bookwriter(angels_and_demons,dan_brown).
bookwriter(da_vinci_code,dan_brown).
bookwriter(the_hobbit,tolkien).
sportusesstadium(baseball,shea_stadium).
bookwriter(macbeth,shakespeare).
bookwriter(satanic_verses,rushdie).
sportusesequipment(hockey,clubs).
bookwriter(mein_kampf,adolf_hitler).
bookwriter(time_machine,h_g__wells).
sportusesstadium(baseball,oriole_park).
bookwriter(romeo_and_juliet,shakespeare).
bookwriter(silmarillion,tolkien).
academicprogramatuniversity(computer_science,mit).
academicprogramatuniversity(engineering,auburn_university).
academicfieldsuchasacademicfield(business,finance).
academicprogramatuniversity(accounting,institute).
academicfieldsuchasacademicfield(actuarial_science,accounting).
academicprogramatuniversity(applied_mathematics,institute).
academicfieldsuchasacademicfield(applied_science,engineering).
academicfieldsuchasacademicfield(linguistics,japanese).
academicprogramatuniversity(computer_science,institute).
academicfieldsuchasacademicfield(biology,marine).
academicprogramatuniversity(divinity,mccormick_theological_seminary).
bookwriter(the_catcher_in_the_rye,j_d__salinger).
bookwriter(babbitt,sinclair_lewis).
bookwriter(the_war_of_the_worlds,h__g__wells).
bookwriter(the_war_of_the_worlds,h_g__wells).
bookwriter(fahrenheit_451,ray_bradbury).
bookwriter(dandelion_wine,ray_bradbury).
bookwriter(martian_chronicles,ray_bradbury).
sporthassportsteamposition(baseball,hitter).
academicprogramatuniversity(architecture,institute).
academicprogramatuniversity(architecture,harvard_university_graduate_school_of_design).
academicprogramatuniversity(architecture,cornell_university).
languageofcity(english,toronto).
academicprogramatuniversity(engineering,uc_berkeley).
academicprogramatuniversity(law,emory_university).
languageofcountry(persian,iran).
bookwriter(harry_potter_books,j_k_rowling).
bookwriter(harry_potter_books,j_k__rowling).
languageofcity(english,pittsburgh).
languageofcountry(english,uk__ireland).
bookwriter(the_wapshot_chronicles,john_cheever).
bookwriter(left_behind,tim_lahaye_and_jerry_jenkins).
bookwriter(left_behind,tim_lahaye).
bookwriter(gormenghast,mervyn_peake).
bookwriter(a_suitable_boy,vikram_seth).
bookwriter(a_month_in_the_country,jl_carr).
bookwriter(breakfast_at_tiffany_s,truman_capote).
bookwriter(cyteen,c__j__cherryh).
bookwriter(remains_of_the_day,kazuo_ishiguro).
languageofuniversity(english,dartmouth).
languageofuniversity(english,iowa_state_university).
languageofuniversity(english,victoria_university_of_wellington).
languageofuniversity(english,university_of_florida).
languageofuniversity(english,ohio_university).
languageofuniversity(english,catholic_university).
languageofuniversity(english,carnegie_mellon).
languageofuniversity(english,washington_university).
languageofuniversity(english,indiana_university).
languageofuniversity(english,middlebury).
languageofuniversity(english,university_of_washington).
languageofuniversity(english,loyola_university).
languageofcity(russian,st__petersburg).
languageschoolincity(german_language,freiburg).
languageschoolincity(german_language,regensburg).
languageschoolincity(english_language,adelaide).
languageschoolincity(english_language,vancouver).
languageofcity(spanish,dallas).
languageofcity(spanish,miami).
languageschoolincity(english_language,boston).
languageofcountry(spanish,panama).
languageofcity(spanish,orlando).
languageofcountry(spanish,chile).
languageofcountry(malay,indonesia).
languageofcity(spanish,barcelona).
languageofcountry(spanish,uruguay).
languageofcountry(spanish,guatemala).
emotionassociatedwithdisease(anxiety,asthma).
emotionassociatedwithdisease(depression,memory_problems).
emotionassociatedwithdisease(symptoms,disorders).
emotionassociatedwithdisease(abuse,disorders).
emotionassociatedwithdisease(depression,chronic_fatigue).
languageofcountry(portuguese,portugal).
languageofcountry(portuguese,brazil).
emotionassociatedwithdisease(depression,medications).
emotionassociatedwithdisease(anxiety,anxiety_disorders).
languageofcity(arabic,cairo).
plantrepresentemotion(flowers,love).
plantrepresentemotion(pansies,love).
plantrepresentemotion(roses,love).
plantrepresentemotion(orchids,happiness___joy).
plantincludeplant(trees,coconut_trees).
emotionassociatedwithdisease(phobia,disorder).
sportsgameteam(championship,pittsburgh_steelers).
plantrepresentemotion(flowers,beauty).
emotionassociatedwithdisease(pain,arthritis).
emotionassociatedwithdisease(clinical_depression,disorder).
plantgrowinginplant(foliage,tree).
plantrepresentemotion(flowers,purity).
emotionassociatedwithdisease(panic_attacks,disorder).
plantincludeplant(flowers,carnations).
plantrepresentemotion(gift,grace).
plantincludeplant(plants,blueberries).
sportsgameteam(series,houston_astros).
plantrepresentemotion(roses,romance).
sportsgamewinner(world_cup,italy).
plantincludeplant(bushes,elderberry).
bacteriaisthecausativeagentofphysiologicalcondition(staphylococcus,infections).
sportsgameteam(playoffs,pittsburgh_steelers).
plantrepresentemotion(home,appreciation).
plantincludeplant(trees,palm).
plantincludeplant(plants,hydrangeas).
sportsgameteam(playoffs,houston_rockets).
sportsgameteam(playoffs,eagles).
sportsgameteam(playoffs,phoenix_suns).
sportsgameteam(playoffs,bulls).
sportsgameteam(series,yankees).
bacteriaisthecausativeagentofphysiologicalcondition(s_,endocarditis).
sportsgameloserscore(n2006_sugar_bowl,35).
emotionassociatedwithdisease(fear,ageing).
emotionassociatedwithdisease(fear,aids).
emotionassociatedwithdisease(fear,cancer).
bacteriaisthecausativeagentofphysiologicalcondition(streptococcus,infection).
languageofcountry(english_language,australia).
sportusesstadium(soccer,wembley_stadium).
plantincludeplant(flowers,hydrangeas).
languageofcountry(german,germany).
sportsgamedate(world_cup,n2008).
languageofcountry(azerbaijani,azerbaijan).
languageofuniversity(english,stanford).
sportusesstadium(baseball,new_yankee_stadium).
academicfieldsuchasacademicfield(m_s,engineering).
languageofuniversity(english,long_island_university).
bookwriter(about_a_boy,nick_hornby).
academicfieldsuchasacademicfield(biology,ecology).
haswikipediaurl(legend_of_mana,'//en.wikipedia.org/wiki/Legend%20of%20Mana').
haswikipediaurl(dan_brown,'//en.wikipedia.org/wiki/Dan_Brown').
haswikipediaurl(da_vinci_code,'//en.wikipedia.org/wiki/The_Da_Vinci_Code').
automobilemakerdealersincountry(volkswagen,germany).
countrylocatedingeopoliticallocation(tonga,countries).
sportsgameteam(world_cup,france).
sportsgameteam(world_cup,croatia).
bookwriter(eragon,christopher_paolini).
bookwriter(eragon,paolini).
sportusesequipment(hockey,skate).
languageofcountry(portuguese,brasil).
countrycurrency(united_kingdom,pounds).
sportsgamesport(n2000_world_series,baseball).
bookwriter(brothers_karamazov,fyodor_dostoevsky).
languageofuniversity(english,north_carolina_state_university).
academicfieldsuchasacademicfield(electrical_and_computer_engineering,computer_science).
arthropodcalledarthropod(tarantulas,spiders).
invertebratefeedonfood(larvae,plants).
arthropodandotherarthropod(brown_recluse,spiders).
arthropodcalledarthropod(shrimp,shellfish).
arthropodlookslikeinsect(butterflies,moths).
arthropodcalledarthropod(shrimp,seafood).
arthropodandotherarthropod(recluse,brown_recluse_spider).
animalistypeofanimal(grubs,invertebrates).
arthropodcalledarthropod(lobsters,seafood).
arthropodcalledarthropod(scallops,seafood).
animalthatfeedoninsect(creatures,beetles).
arthropodandotherarthropod(recluse_spiders,brown_recluse).
arthropodcalledarthropod(lobster,seafood).
animaleatfood(birds,foods).
animalistypeofanimal(ocelots,animals).
animalsuchasinsect(parasites,ticks).
animalsuchasinsect(parasites,mosquitoes).
animalsuchasinvertebrate(brown_widow,widow_spider).
arachnidssuchasarachnids(poisonous_arachnids,black_widow_spiders).
arthropodcalledarthropod(black_widow_spiders,spiders).
arthropodandotherarthropod(spiders,black_widow_spiders).
animaleatfood(horses,meal).
animaleatvegetable(livestock,meal).
agriculturalproductincludingagriculturalproduct(livestock,horses).
agriculturalproductincludingagriculturalproduct(livestock,poultry).
animaleatfood(cows,dinner).
animaleatfood(cows,hay).
animaleatfood(dogs,chocolate).
animaldevelopdisease(cats,epilepsy).
animaldevelopdisease(cats,acne).
animaldevelopdisease(cats,seizures).
animaleatfood(dogs,yogurt).
animaldevelopdisease(cats,allergic_reactions).
animaldevelopdisease(dogs,allergy).
animaldevelopdisease(cats,breast_feeding).
animaldevelopdisease(cats,alzheimers).
animaldevelopdisease(wild_animals,rabies).
animalistypeofanimal(bats,wild_animals).
animalistypeofanimal(rabbits,rodents).
animalistypeofanimal(monkeys,creatures).
animalistypeofanimal(bears,carnivores).
animalistypeofanimal(cattle,large_animals).
fishservedwithfood(salmon,horseradish_sauce).
animalthatfeedoninsect(pests,silverfish).
animalsuchasfish(endangered_species,salmon).
animalistypeofanimal(frogs,creatures).
animalistypeofanimal(frogs,predators).
animaldevelopdisease(pet,problems).
fishservedwithfood(trout,rice_pilaf).
fishservedwithfood(tuna,sauce).
fishservedwithfood(trout,sauce).
animalsuchasinvertebrate(filter_feeders,oysters).
animaldevelopdisease(child,mumps).
animaldevelopdisease(child,scabies).
animalsuchasinvertebrate(pests,worms).
animaldevelopdisease(child,disability).
animaldevelopdisease(child,hpv).
animaleatfood(frogs,larvae).
fishservedwithfood(salmon,french_bread).
ismultipleof(herds,bison).
chemicalistypeofchemical(heavy_metals,chemicals).
chemicalistypeofchemical(natural_gas,fossil_fuels).
chemicalistypeofchemical(gas,natural_resources).
chemicalistypeofchemical(oxygen,gas).
chemicalistypeofchemical(oxygen,compound).
chemicalistypeofchemical(radon,gas).
chemicalistypeofchemical(cadmium,pollutants).
chemicalistypeofchemical(dioxide,compound).
chemicalistypeofchemical(nitrogen,gas).
animaldevelopdisease(cats,cancer).
animaldevelopdisease(rabbits,cancer).
fishservedwithfood(linguine,sauce).
animalistypeofanimal(seals,marine_animals).
synonymfor(great_apes,gorillas).
fishservedwithfood(mahimahi,sauce).
chemicalistypeofchemical(mercury,emissions).
chemicalistypeofchemical(petroleum,fuels).
countryalsoknownas(ireland,great_britain).
sportsgameteam(tournament,germany).
sportsgameteam(tournament,brazil).
citylocatedinstate(hayward,california).
cityliesonriver(manhattan,east).
citycapitalofcountry(bucharest,romania).
citylocatedincountry(winnipeg,canada).
citylocatedinstate(gunnison,colorado).
countrycurrency(bahamas,dollars).
statehascapital(utah,salt_lake).
countrycurrency(canada,dollars).
statehascapital(alabama,montgomery).
statehascapital(romania,bucharest).
cityalsoknownas(philadelphia,philly).
countrycurrency(jamaica,dollar).
statehascapital(ne,omaha).
countrycurrency(kuwait,dollars).
statehascapital(wa,seattle).
countrycurrency(taiwan,dollars).
statelocatedingeopoliticallocation(britishcolumbia,canada).
citylocatedinstate(galveston,texas).
citylocatedincountry(tokyo,japan).
citylocatedinstate(hinsdale,illinois).
citylocatedinstate(key_biscayne,florida).
citylocatedincountry(hiroshima,japan).
statehascapital(alberta,edmonton).
citycapitalofcountry(tripoli,libya).
countrylocatedingeopoliticallocation(portugal,europe).
countrycurrency(liberia,dollars).
citylocatedinstate(santa_ana,california).
citycapitalofcountry(rangoon,burma).
citylocatedinstate(glendale,california).
citycapitalofcountry(damascus,syria).
citylocatedincountry(bahia_blanca,argentina).
citylocatedincountry(rio,brazil).
citycapitalofcountry(algiers,algeria).
citylocatedincountry(algiers,algeria).
cityalsoknownas(mumbai,bombay).
cityalsoknownas(bombay,mumbai).
citylocatedinstate(hyderabad,andhra_pradesh).
citylocatedinstate(mumbai,maharashtra).
countryalsoknownas(ethiopia,eritrea).
countryalsoknownas(eritrea,ethiopia).
countryalsoknownas(kenya,ethiopia).
countryalsoknownas(djibouti,ethiopia).
countrycurrency(croatia,kuna).
countrycurrency(bulgaria,lev).
countrycurrency(ethiopia,birr).
countrycurrency(ecuador,sucre).
countrycurrency(estonia,kroon).
countrycurrency(andorra,euro).
countrycurrency(montenegro,euro).
countrycurrency(france,euros).
countrycurrency(greece,euros).
cityliesonriver(cairo,nile).
citylocatedincountry(puerto_iguazu,argentina).
citylocatedinstate(north_chicago,illinois).
cityalsoknownas(los_angeles,l_a_).
citycapitalofcountry(nairobi,kenya).
countryalsoknownas(afghanistan,tajikistan).
countryalsoknownas(tadjikistan,tajikistan).
countryalsoknownas(tajikistan,afghanistan).
statehascapital(northern_ireland,belfast).
citycapitalofcountry(lima,peru).
cityliesonriver(zurich,limmat).
citylocatedincountry(montreux,switzerland).
statehascapital(aargau,aarau).
statelocatedincountry(aargau,switzerland).
citycapitalofcountry(caracas,venezuela).
cityliesonriver(little_falls,mississippi).
citylocatedinstate(lake_tahoe,california).
citylocatedinstate(colorado_city,colorado).
countrylocatedingeopoliticallocation(austria,europe).
citylocatedinstate(calabasas,california).
citycapitalofcountry(dacca,bangladesh).
countrylocatedingeopoliticallocation(brasil,countries).
statelocatedingeopoliticallocation(niedersachsen,germany).
statelocatedincountry(texas,united_state).
subpartof(fishers,indiana).
citylocatedinstate(montrose,colorado).
citylocatedincountry(jena,germany).
statelocatedingeopoliticallocation(illinois,u_s_a).
cityliesonriver(new_york_city,mohawk).
countrycurrency(scotland,pounds).
citylocatedinstate(flower_mound,texas).
statehascapital(united_arab_emirates,abu_dhabi).
cityliesonriver(new_orleans,mississippi).
politicsgroupconcernsissue(democratic_party,liberalism).
politicsgroupconcernsissue(national_rifle_association,gun_control).
athletewinsawardtrophytournament(kim_clijsters,australian_open).
directordirectedmovie(david_fincher,fight_club).
directordirectedmovie(john_mctiernan,die_hard).
motherofperson(mother,child).
politicianusendorsedbypoliticianus(john_mccain,president_bush).
personhasjobposition(cleopatra,queen).
visualartistartform(warhol,exhibits).
actorstarredinmovie(tom_cruise,magnolia).
directordirectedmovie(paul_thomas_anderson,magnolia).
actorstarredinmovie(tom_cruise,jerry_maguire).
actorstarredinmovie(tom_cruise,mission_impossible).
actorstarredinmovie(tom_cruise,minority_report).
actorstarredinmovie(tom_cruise,risky_business).
actorstarredinmovie(jackie_chan,rush_hour).
actorstarredinmovie(jackie_chan,rush_hour_2).
celebritysuchascelebrity(artists,john_denver).
motherofperson(mother,son).
motherofperson(mother,lord).
musicianinmusicartist(ian_astbury,cult).
parentofperson(mary,jesus_christ).
directordirectedmovie(akira_kurosawa,seven_samurai).
directordirectedmovie(akira_kurosawa,rashomon).
visualartistartmovement(leonardo_da_vinci,italian_renaissance).
politicianusmemberofpoliticalgroup(tom_daschle,senate).
personhasjobposition(constantine,emperor).
actorstarredinmovie(mel_gibson,maverick).
motherofperson(mary,jesus_christ).
hashusband(madona,sean_penn).
parentofperson(blessed_virgin_mary,jesus_christ).
directordirectedmovie(paul_haggis,crash).
ceoof(frederick_smith,federal_express).
actorstarredinmovie(bela_lugosi,dracula).
visualartistartmovement(vincent_van_gogh,expressionism).
celebritysuchascelebrity(artists,elvis_presley).
directordirectedmovie(david_lean,doctor_zhivago).
personhasjobposition(frank_walter_steinmeier,foreign_minister).
professionistypeofprofession(research,services).
professionistypeofprofession(orthopedic_surgeons,professionals).
professionistypeofprofession(specialists,doctors).
agriculturalproductcutintogeometricshape(cucumbers,cubes).
agriculturalproductcontainchemical(coffee,caffeine).
agriculturalproductcontainchemical(coffee,antioxidants).
agriculturalproductcontainchemical(yogurt,calcium).
agriculturalproductcamefromcountry(vanilla,comoros).
agriculturalproductcookedwithagriculturalproduct(cream,milk).
agriculturalproductcomingfromvertebrate(beef,cows).
agriculturalproductcontainchemical(beef,cholesterol).
agriculturalproductcamefromcountry(tea,kenya).
fooddecreasestheriskofdisease(green_tea,skin_cancer).
agriculturalproductincludingagriculturalproduct(crops,sugarcane).
vegetableproductioninstateorprovince(tomato,florida).
agriculturalproductcookedwithagriculturalproduct(beans,onions).
agriculturalproductincludingagriculturalproduct(crops,sugar_cane).
agriculturalproductcontainchemical(tea,antioxidant).
beveragemadefrombeverage(mango_juice,juice).
agriculturalproductgrowinginstateorprovince(sugar,mauritius).
vegetableproductioninstateorprovince(spinach,new_mexico).
agriculturalproductcookedwithagriculturalproduct(leek,potatoes).
agriculturalproductcutintogeometricshape(onions,squares).
furniturefoundinroom(beds,smoking_room).
furniturefoundinroom(beds,bunk_bed).
furniturefoundinroom(beds,porch).
furniturefoundinroom(beds,apartment).
drugpossiblytreatsphysiologicalcondition(serevent,asthma).
bakedgoodservedwithbeverage(bagels,juice).
bakedgoodservedwithbeverage(bagels,coffee).
productinstanceof(apple_macintosh,computers).
bakedgoodservedwithbeverage(breakfast,coffee).
bakedgoodservedwithbeverage(breakfast,tea).
bakedgoodservedwithbeverage(biscuit,tea).
bakedgoodservedwithbeverage(cakes,cream).
bakedgoodservedwithbeverage(honey,cream).
buildingfeaturemadefrombuildingmaterial(doors,vinyl).
bakedgoodservedwithbeverage(pie,chocolate).
vegetableproductioninstateorprovince(bean,north_dakota).
bakedgoodservedwithbeverage(marmalade,coffee).
fooddecreasestheriskofdisease(antioxidants,alzheimer).
bakedgoodservedwithbeverage(bun,coffee).
bakedgoodservedwithbeverage(bread,banana).
drugpossiblytreatsphysiologicalcondition(ambien,sleeping).
bakedgoodservedwithbeverage(fresh_fruit,coffee).
foodcancausedisease(sugars,diabetes).
bakedgoodservedwithbeverage(toast,butter).
bakedgoodservedwithbeverage(sandwich,tea).
buildingfeaturemadefrombuildingmaterial(wall,cement).
bakedgoodservedwithbeverage(sandwiches,tea).
beveragemadefrombeverage(cilantro,juice).
bakedgoodservedwithbeverage(fruits,coffee).
buildingfeaturemadefrombuildingmaterial(veneered_doors,veneers).
furniturefoundinroom(home_bar,living_room).
drugworkedonbyagent(metformin,bristol_myers_squibb).
productinstanceof(microsoft_windows,applications).
bakedgoodservedwithbeverage(bread,yoghurt).
drugpossiblytreatsphysiologicalcondition(medications,pain).
buildingfeaturemadefrombuildingmaterial(cabinet,steel).
buildingfeaturemadefrombuildingmaterial(windows,vinyl).
itemfoundinroom(beds,villa).
furniturefoundinroom(bookcase,living_room).
drugworkedonbyagent(paxil,glaxosmithkline).
bakedgoodservedwithbeverage(bread,red_wine).
bakedgoodservedwithbeverage(goodies,coffee).
buildingfeaturemadefrombuildingmaterial(door,screen).
furniturefoundinroom(beds,studio_rooms).
furniturefoundinroom(beds,dorm_room).
bakedgoodservedwithbeverage(cookies,white_chocolate).
bakedgoodservedwithbeverage(preserves,cream).
beveragecontainsprotein(breast_milk,enzyme).
agriculturalproductcontainchemical(tea,acids).
agriculturalproductgrowinginstateorprovince(tobacco,andhra_pradesh).
beveragecontainsprotein(milk,fatty_acid).
agriculturalproductcomingfromvertebrate(dairy_products,cattle).
bakedgoodservedwithbeverage(raspberries,cream).
bakedgoodservedwithbeverage(cookies,beverages).
agriculturalproductcontainchemical(tea,chemicals).
vegetableproductioninstateorprovince(onion,texas).
clothingmadefromplant(skirts,palmtrees).
clothingtogowithclothing(shirts,jackets).
clothingtogowithclothing(hoodie,shirt).
clothingtogowithclothing(sleeve,shirt).
clothingtogowithclothing(leather_jacket,jeans).
clothingtogowithclothing(shorts,cotton_shirts).
itemfoundinroom(hairdryer,private_bathroom).
itemfoundinroom(hairdryer,bathroom).
itemfoundinroom(spa_tub,bath).
furniturefoundinroom(bed,smoking_room).
furniturefoundinroom(accent_chair,living_room).
haswikipediaurl(world_clock,'//en.wikipedia.org/wiki/World%20clock').
clothingtogowithclothing(black_suit,shirt).
furniturefoundinroom(headboard,bedroom).
furniturefoundinroom(ottoman,living_room).
furniturefoundinroom(sectional_sofa,living_room).
furniturefoundinroom(bed,property).
clothingtogowithclothing(pants,polo_shirts).
clothingtogowithclothing(polo_shirts,pants).
clothingtogowithclothing(sport_coat,pants).
clothingtogowithclothing(jersey,pants).
clothingtogowithclothing(top,long_skirt).
clothingtogowithclothing(jersey,shorts).
clothingtogowithclothing(shorts,shoes).
itemfoundinroom(shower,bathroom).
itemfoundinroom(shower,adjacent_bathroom).
itemfoundinroom(shower,one_bathroom).
itemfoundinroom(shower,bathrooms).
itemfoundinroom(shower,large_bathrooms).
haswikipediaurl(enemy_engaged_2,'//en.wikipedia.org/wiki/Enemy%20Engaged%202').
foodcancausedisease(blood_sugar,diabetes).
itemfoundinroom(shower,luxury_bathroom).
agriculturalproductincludingagriculturalproduct(plants,sorghum).
agriculturalproductcookedwithagriculturalproduct(seasonings,chicken).
agriculturalproductincludingagriculturalproduct(fresh_herbs,parsley).
agriculturalproductincludingagriculturalproduct(herbs,parsley).
fooddecreasestheriskofdisease(natural,cancer).
agriculturalproductcamefromcountry(silk,nepal).
clothingtogowithclothing(sweaters,pants).
clothingtogowithclothing(shirt,linen_pants).
clothingtogowithclothing(shirt,bermuda_shorts).
clothingtogowithclothing(golf_shirts,shirts).
clothingtogowithclothing(long_sleeves,shirts).
clothingtogowithclothing(dresses,tops).
clothingtogowithclothing(sweat_shirts,shirts).
weaponmadeincountry(bombs,u_s).
weaponmadeincountry(bombs,pakistan).
agriculturalproductcookedwithagriculturalproduct(potato_soup,onions).
clothingtogowithclothing(red_shirt,shorts).
weaponmadeincountry(nuclear_bombs,iran).
agriculturalproductincludingagriculturalproduct(products,oat).
agriculturalproductincludingagriculturalproduct(products,salt).
agriculturalproductincludingagriculturalproduct(products,barley).
agriculturalproductincludingagriculturalproduct(products,cocoa).
agriculturalproductincludingagriculturalproduct(products,citrus_fruits).
agriculturalproductincludingagriculturalproduct(products,margarine).
weaponmadeincountry(bows,brazil).
clothingtogowithclothing(sweat_shirt,pants).
itemfoundinroom(shower,master_bath).
writerwasbornincity(martin_luther_king_jr__,memphis).
agriculturalproducttoattractinsect(alfalfa,honey_bees).
agriculturalproductincludingagriculturalproduct(crops,alfalfa).
beveragecontainsprotein(breast_milk,proteins).
beveragecontainsprotein(dairy_foods,proteins).
beveragecontainsprotein(beer,proteins).
actorstarredinmovie(mark_hamill,star_wars).
haswikipediaurl(n2001_british_grand_prix,'//en.wikipedia.org/wiki/2001%20British%20Grand%20Prix').
directordirectedmovie(christopher_nolan,the_prestige).
actorstarredinmovie(sacha_baron_cohen,borat).
ceoof(steven_ballmer,microsoft).
celebritysuchascelebrity(film_stars,angelina_jolie).
hashusband(basemath,esau).
haswikipediaurl(basemath,'//en.wikipedia.org/wiki/Basemath').
drugpossiblytreatsphysiologicalcondition(valtrex,genital_herpes).
agriculturalproductcontainchemical(tea_leaves,amino_acid).
vegetableproductioninstateorprovince(corn,kansas).
agriculturalproductcomingfromvertebrate(milk,farms).
ceoof(hank_mckinnell,pfizer).
musicianplaysinstrument(franz_liszt,piano).
politicianusendorsedbypoliticianus(gore,clinton).
politicianusmemberofpoliticalgroup(harry_reid,senate).
politicianusendorsedbypoliticianus(joe_biden,clinton).
musicianplaysinstrument(bono,guitar).
politicianholdsoffice(kennedy,senator).
politicianusendorsedbypoliticianus(w___bush,cheney).
politicianusendorsedbypoliticianus(presidential_candidate_barack_obama,clinton).
personwasborninstateorprovince(monica,california).
personhasresidenceingeopoliticallocation(arnold_schwarzenegger,california).
politicianusmemberofpoliticalgroup(antonin_scalia,supreme_court).
politicianholdsoffice(barak_obama,president).
politicianholdsoffice(barak_obama,senator).
politicianholdsoffice(barak_obama,senators).
countrylocatedingeopoliticallocation(egypt,countries).
directordirectedmovie(steven_spielberg,jaws).
directordirectedmovie(steven_spielberg,jurassic_park).
citylocatedincountry(new_dehli,india).
directordirectedmovie(martin_scorsese,goodfellas).
directordirectedmovie(martin_scorscese,goodfellas).
actorstarredinmovie(joe_pesci,goodfellas).
actorstarredinmovie(ray_liotta,goodfellas).
directordirectedmovie(quentin_tarantino,pulp_fiction).
actorstarredinmovie(john_travolta,pulp_fiction).
buildinglocatedincity(sears_tower,chicago).
attractionofcity(circus_maximus,rome).
hotelincity(quality_suites,toronto).
newspaperincity(the_stranger,seattle).
mountaininstate(mount_whitney,california).
mountaininstate(castro_peak,california).
aquariumincity(vancouver_aquarium,vancouver).
placeofworshippracticesreligion(westminster_abbey,catholicism).
aquariumincity(dallas_aquarium,dallas).
airportincity(istanbul_airport,istanbul).
transportationincity(metro_system,montreal).
hospitalincity(the_vancouver_clinic,vancouver).
hotelincity(omni_chicago_hotel,chicago).
hotelincity(georgia_tech_hotel_and_conference_center,atlanta).
placeofworshippracticesreligion(zen_mountain_monastery,buddhism).
mountaininstate(calico_mountains,california).
attractionofcity(colosseum,rome).
museumincity(toronto_s_historic_museums,toronto).
zooincity(toronto_zoo,toronto).
hospitalincity(toronto_general,toronto).
lakeinstate(lake_tahoe,california).
mountaininstate(death_valley,california).
aquariumincity(gulf_of_maine_research_institute,portland).
mountaininstate(mauna_kea,hawaii).
hospitalincity(vancouver_general_hospital,vancouver).
placeofworshippracticesreligion(the_hurva_synagogue,judaism).
buildinglocatedincity(miami_international_airport,miami).
stadiumlocatedincity(fedex_forum,memphis).
placeofworshippracticesreligion(east_ham_baptist_church,baptist).
organizationacronymhasname(seal,sea).
airportincity(mumbai_airport,mumbai).
placeofworshippracticesreligion(muktinath,hinduism).
placeofworshippracticesreligion(banteay_srei,hinduism).
haswikipediaurl(lindstrom_peak,'//en.wikipedia.org/wiki/Lindstrom%20Peak').
parkincity(south_kensington,london).
airportincity(cairo_international_airport,cairo).
mountaininstate(capitol_peak,colorado).
parkincity(covent_garden,london).
lakeinstate(deep_creek_lake,maryland).
newspaperincity(evening_standard,london).
hotelincity(courtyard_by_marriott_lax,los_angeles).
placeofworshippracticesreligion(sleepy_hollow_presbyterian_church,presbyterianism).
haswikipediaurl(boswell_bay_airport,'//en.wikipedia.org/wiki/Boswell%20Bay%20Airport').
mountaininstate(kilauea_volcano,hawaii).
newspaperincity(toronto_star,toronto).
placeofworshippracticesreligion(the_great_mosque_of_taza,islam).
buildinglocatedincity(three_rivers_stadium,pittsburgh).
airportincity(lester_b__pearson_international_airport,toronto).
airportincity(bwi,baltimore).
mountaininstate(everest,nepal).
synonymfor(executive_officers,board).
buildinglocatedincity(memphis_international,memphis).
airportincity(memphis_international,memphis).
airportincity(miami_international_airport,miami).
airportincity(bristol_airport,bristol).
parkincity(greenwich,london).
museumincity(austin_children_museum,austin).
hotelincity(hotel_57,new_york_city).
haswikipediaurl(hollywood_wax_museum,'//en.wikipedia.org/wiki/Hollywood%20Wax%20Museum').
museumincity(hollywood_wax_museum,los_angeles).
stadiumlocatedincity(ford_field,detroit).
transportationincity(airtrain_light_rail,new_york_city).
hotelincity(the_lombardy,new_york_city).
museumincity(bethesda_fountain,new_york_city).
attractionofcity(kingdome,seattle).
hospitalincity(m_d__anderson,houston).
attractionofcity(quicken_loans_arena,cleveland).
buildinglocatedincity(quicken_loans_arena,cleveland).
placeofworshippracticesreligion(san_francisco_zen_center,buddhism).
personbelongstoorganization(edgar_bronfman_jr_,warner_music).
agriculturalproductincludingagriculturalproduct(legumes,alfalfa).
agriculturalproductincludingagriculturalproduct(beverages,milk).
beveragemadefrombeverage(grapefruit_juice,juice).
productinstanceof(android,systems).
personbelongstoorganization(jeff_greenfield,cnn).
competeswith(google,yahoo_local).
athleteplayssport(john_mcenroe,tennis).
athletebeatathlete(ivan_lendl,john_mcenroe).
athletewinsawardtrophytournament(john_mcenroe,us_open).
leaguestadiums(nfl,soldier_field).
personhasresidenceingeopoliticallocation(bill_clinton,arkansas).
athleteplayssport(sachin_tendulkar,cricket).
musicartistgenre(jewel,pop).
musicartistgenre(roy_orbison,rock).
personattendsschool(tolkien,oxford).
musicartistgenre(lou_reed,rock).
musicartistgenre(ricky_martin,pop).
musicartistgenre(wham,pop).
musicianplaysinstrument(bach,piano).
musicianplaysinstrument(beethoven,piano).
musicianplaysinstrument(emerson_lake_palmer,piano).
politicianusholdsoffice(nancy_pelosi,speaker).
organizationacronymhasname(nba,national_basketball_association).
athleteplayssport(anna_kournikova,tennis).
athleteplayssport(dinara_safina,tennis).
athleteplayssport(lleyton_hewitt,tennis).
athletewinsawardtrophytournament(lleyton_hewitt,us_open).
athleteplayssport(marat_safin,tennis).
athletewinsawardtrophytournament(marat_safin,australian_open).
parentofperson(noah,shem).
actorsuchasactor(western_movie_actors,clint_eastwood).
politicianusendorsedbypoliticianus(bush,dick_cheney).
politicianusmemberofpoliticalgroup(bob_dole,senate).
coachesinleague(doc_rivers,nba).
actorstarredinmovie(chevy_chase,vacation).
politicianusholdsoffice(clinton,presidents).
musicartistgenre(immortal,black_metal).
politicianusendorsedbypoliticianus(sen___barack_obama,clinton).
musicartistgenre(alice_cooper,hard_rock).
politicianusendorsedbypoliticianus(clinton,michael_moore).
politicianusendorsedbypoliticianus(clinton,jimmy_carter).
athletebeatathlete(svetlana_kuznetsova,williams).
musicartistgenre(kylie,pop).
athleteplayssport(annika_sorenstam,golf).
leaguestadiums(mlb,camden_yards).
athleteplayssport(john_daly,golf).
politicianusendorsedbypoliticianus(cheney,bush).
politicianusendorsedbypoliticianus(lieberman,clinton).
athleteplayssport(tommy_haas,tennis).
personleadscity(andrew_young,atlanta).
mlauthorofsoftware(andrew_mccallum,mallet).
musicianplaysinstrument(itzhak_perlman,violin).
musicianplaysinstrument(joshua_bell,violin).
politicianholdsoffice(president_chirac,president).
personhascitizenship(leonardo_boff,brazil).
personhascitizenship(jewel,brazil).
musicianplaysinstrument(james_hetfield,guitar).
leaguestadiums(nba,fedex_forum).
worksfor(balmer,microsoft).
leaguestadiums(nba,conseco_fieldhouse).
leaguestadiums(nba,thomas___mack_center).
athleteplayssport(phil_mickelson,golf).
musicianinmusicartist(jack_bruce,cream).
athleteplayssport(adam_petty,nascar).
athleteplayssport(ryan_newman,car_racing).
leaguestadiums(nascar,bristol_motor_speedway).
leaguestadiums(nascar,bowman_gray_stadium).
leaguestadiums(nascar,auto_club_speedway).
athleteplayssport(carl_edwards,car_racing).
teamplaysinleague(san_francisco_49ers,nfl).
personleadscity(cory_booker,newark).
musicartistgenre(elvis,blues).
politicianholdsoffice(governor_mitt_romney,senator).
politicianusmemberofpoliticalgroup(john_g___roberts,supreme_court).
musicianinmusicartist(the_edge,u2).
musicianplaysinstrument(b_b__king,guitar).
musicianinmusicartist(nicole_scherzinger,pussycat_dolls).
athleteplayssport(mark_allen,triathlon).
marriedinyear(david_selden,n1956).
personhasresidenceingeopoliticallocation(goffredo_marcaccini,mexico).
teamplaysincity(miami_heat,miami).
teamplaysinleague(sixers,nba).
teamplaysinleague(dallas_mavericks,nba).
teamplaysincity(broncos,denver).
teamplaysincity(dallas_mavericks,dallas).
teamhomestadium(indiana_pacers,conseco_fieldhouse).
teamhomestadium(fc_barcelona,camp_nou).
teamplaysincity(astros,houston).
teamplayssport(sooners,games).
athleteplayssport(george_foreman,boxing).
athleteplaysinleague(kurt_warner,nfl).
teamhomestadium(st___louis_cardinals,busch_stadium).
bookwriter(charlotte_s_web,e_b__white).
teamplaysinleague(pittsburgh_steelers,nfl).
teamplaysagainstteam(pittsburgh_steelers,minnesota_vikings).
teamplaysincity(indians,cleveland).
companyalsoknownas(sysco,sysco_corp).
televisionstationincity(kiro,seattle).
companyeconomicsector(british_gas,energy).
companyeconomicsector(exxonmobil,energy).
companyeconomicsector(china_mobile,telecom).
automakerproducesmodel(jeep,jeep_wrangler_unlimited).
automakerproducesmodel(jeep,jeep_grand_cherokee).
automakerproducesmodel(toyota,tundra).
automakerproducesmodel(toyota,camry).
producesproduct(toyota,corolla).
producesproduct(toyota,camry).
automakerproducesmodel(toyota,camry_hybrid).
producesproduct(toyota,toyota_matrix).
automobilemakerdealersincountry(toyota,japan).
producesproduct(pontiac,bonneville).
producesproduct(honda,insight).
automakerproducesmodel(honda,fit).
automakerproducesmodel(honda,honda_civic).
automakerproducesmodel(lincoln,navigator).
companyeconomicsector(audi,auto).
automobilemakercardealersinstateorprovince(kia,missouri).
companyeconomicsector(british_petroleum,oil).
producesproduct(honda,element).
producesproduct(volkswagen,eos).
automakerproducesmodel(volkswagen,eos).
automobilemakerdealersincity(peugeot,london).
automakerproducesmodel(honda,odyssey).
producesproduct(microsoft,xbox).
televisionstationaffiliatedwith(kcit,fox).
companyeconomicsector(geico,insurance).
televisionstationincity(kcnc,denver).
producesproduct(microsoft,microsoft_excel).
automakerproducesmodel(honda,prelude).
bankbankincountry(citibank,australia).
companyeconomicsector(honda,automobile).
companyeconomicsector(shell,energy).
automakerproducesmodel(honda,pilot).
producesproduct(honda,pilot).
itemfoundinroom(toilette,bathroom).
synonymfor(board,committee).
istallerthan(great_pyramid_of_giza,eiffel_tower).
agentparticipatedinevent(impact,injury).
companyeconomicsector(citgo,oil).
itemfoundinroom(bath_tub,bathrooms).
synonymfor(mac,apple_computer).
synonymfor(vice,learning).
haswikipediaurl(super_ninja_boy,'//en.wikipedia.org/wiki/Super%20Ninja%20Boy').
companyalsoknownas(att,at_t).
synonymfor(committee,board).
organizationacronymhasname(nsf,national_science_foundation).
itemfoundinroom(fridge,kitchen).
itemfoundinroom(fridge,kitchenette).
organizationacronymhasname(nsc,national_security_council).
fooddecreasestheriskofdisease(fibre,cancer).
organizationacronymhasname(usps,postal_service).
organizationacronymhasname(cbo,congressional_budget_office).
synonymfor(management_team,board).
organizationacronymhasname(fca,farm_credit_administration).
itemfoundinroom(tub,bath).
itemfoundinroom(tub,home).
itemfoundinroom(tub,ensuite_bathroom).
itemfoundinroom(tub,full_bath).
itemfoundinroom(tub,private_bath).
istallerthan(eiffel_tower,washington_monument).
agentparticipatedinevent(evidence,injury).
agentcontributedtocreativework(mark_twain,adventures_of_tom_sawyer).
agentcontributedtocreativework(mark_twain,adventures_of_huckleberry_finn).
organizationacronymhasname(fda,food_and_drug_administration).
synonymfor(department,ministry).
fooddecreasestheriskofdisease(laxative,cancer).
subpartof(point,air).
subpartof(cleveland,ohio).
synonymfor(windy_city,chicago).
agentparticipatedinevent(changes,part).
animalistypeofanimal(kangaroo,marsupials).
persongraduatedfromuniversity(michelle,princeton_university).
itemfoundinroom(oven,modern_kitchen).
agentcontributedtocreativework(charles_dickens,a_tale_of_two_cities).
agentcontributedtocreativework(jane_austen,pride_and_prejudice).
synonymfor(macintosh,apple_computer).
companyalsoknownas(amd,advanced_micro_devices).
teamplaysagainstteam(florida_marlins,indians).
automakerproducesmodel(ford,edge).
producesproduct(microsoft,explorer).
televisionstationaffiliatedwith(wlov,fox).
subpartof(la_paz,bolivia).
radiostationincity(wfmt,chicago).
haswikipediaurl(arkalyk,'//en.wikipedia.org/wiki/Arkalyk').
haswikipediaurl(mapreduce,'//en.wikipedia.org/wiki/MapReduce').
hasofficeincity(air_jamaica,new_york_city).
headquarteredin(verizon,new_york_city).
athleteplayssportsteamposition(warrick_dunn,running_back).
competeswith(nissan,honda).
haswife(esau,basemath).
bankbankincountry(hsbc,singapore).
leaguestadiums(nfl,invesco_field_at_mile_high).
personhascitizenship(king_ptolemy,egypt).
politicianusholdsoffice(president_obama,president).
musicartistgenre(gentle_giant,rock).
actorstarredinmovie(jackson,pulp_fiction).
agentcontributedtocreativework(mario_puzo,the_godfather).
personhasjobposition(william_the_conqueror,king).
hotelincity(holiday_inn_midtown_57th_street,new_york_city).
haswife(prince_william,kate_middleton).
actorstarredinmovie(kevin_spacey,k_pax).
languageofcountry(english,great_britain).
musicartistgenre(arctic_monkeys,rock).
istallerthan(lebanon,people).
sportschoolincountry(rugby,argentina).
arthropodandotherarthropod(tarantulas,spiders).
citycapitalofcountry(tokyo,japan).
citycapitalofcountry(hiroshima,japan).
itemfoundinroom(beds,smoking_room).
itemfoundinroom(beds,bunk_bed).
itemfoundinroom(beds,porch).
itemfoundinroom(beds,apartment).
itemfoundinroom(beds,studio_rooms).
itemfoundinroom(beds,dorm_room).
itemfoundinroom(bed,smoking_room).
itemfoundinroom(bed,property).
worksfor(steven_ballmer,microsoft).
attractionofcity(three_rivers_stadium,pittsburgh).
personleadsgeopoliticalorganization(andrew_young,atlanta).
personbelongstoorganization(kurt_warner,nfl).
stadiumlocatedincity(kingdome,seattle).
citylocatedinstate(longwood,florida).
haswikipediaurl(chris_gethard,'//en.wikipedia.org/wiki/Chris%20Gethard').
bookwriter(a_fall_of_moondust,arthur_c__clarke).
haswikipediaurl(a_fall_of_moondust,'//en.wikipedia.org/wiki/A%20Fall%20of%20Moondust').
haswikipediaurl(scotland_today,'//en.wikipedia.org/wiki/Scotland%20Today').
haswikipediaurl(long_way_round,'//en.wikipedia.org/wiki/Long%20Way%20Round').
haswikipediaurl(the_venturers,'//en.wikipedia.org/wiki/The%20Venturers').
haswikipediaurl(the_pallisers,'//en.wikipedia.org/wiki/The%20Pallisers').
haswikipediaurl(the_brain_drain,'//en.wikipedia.org/wiki/The%20Brain%20Drain').
haswikipediaurl(the_nfl_today,'//en.wikipedia.org/wiki/The%20NFL%20Today').
haswikipediaurl(the_young_lawyers,'//en.wikipedia.org/wiki/The%20Young%20Lawyers').
haswikipediaurl(the_othersiders,'//en.wikipedia.org/wiki/The%20Othersiders').
sportfansincountry(football,cyprus).
citylocatedinstate(san_dimas,california).
agriculturalproductcookedwithagriculturalproduct(sea_salt,pepper).
emotionassociatedwithdisease(disorder,epilepsy).
citylocatedincountry(palembang,indonesia).
haswikipediaurl(peter_gavin,'//en.wikipedia.org/wiki/Peter%20Gavin%20(Canadian%20politician)').
agriculturalproductcookedwithagriculturalproduct(onion,pepper).
agriculturalproductcutintogeometricshape(tofu,cube).
chemicalistypeofchemical(nitrogen_oxides,gas).
sporthassportsteamposition(football,fan).
bakedgoodservedwithbeverage(cookie,chocolate).
actorstarredinmovie(jamie_lee_curtis,halloween).
languageofuniversity(spanish,state_university).
bookwriter(angels___demons,dan_brown).
furniturefoundinroom(sofabeds,living_room).
animalsuchasmollusk(pelagics,rays).
agentcontributedtocreativework(dan_brown,angels_and_demons).
haswikipediaurl(alan_dargin,'//en.wikipedia.org/wiki/Alan%20Dargin').
agriculturalproductcontainchemical(products,corn_syrup).
animalsuchasinvertebrate(invertebrates,slugs).
sportusesequipment(soccer,nets).
emotionassociatedwithdisease(shame,alcoholism).
emotionassociatedwithdisease(shame,addiction).
haswikipediaurl(joseph_filkowski,'//en.wikipedia.org/wiki/Joseph%20Filkowski').
agriculturalproductcutintogeometricshape(cheeses,cubes).
agriculturalproductcutintogeometricshape(beets,dice).
agriculturalproductcutintogeometricshape(celery,dice).
agriculturalproductcutintogeometricshape(zucchini,dice).
agriculturalproductcutintogeometricshape(pepper,squares).
agriculturalproductcutintogeometricshape(potatoes,squares).
agriculturalproducttoattractinsect(herbs,insects).
haswikipediaurl(macbook_pro,'//en.wikipedia.org/wiki/MacBook%20Pro').
haswikipediaurl(the_atwood_stories,'//en.wikipedia.org/wiki/The%20Atwood%20Stories').
fishservedwithfood(catfish,sauce).
animalsuchasfish(big_fish,catfish).
bookwriter(zorro,isabel_allende).
languageofuniversity(english,providence_college).
streetincity(west_broadway,vancouver).
fishservedwithfood(fish_filet,sauce).
foodcancausedisease(sushi,food_poisoning).
bacteriaisthecausativeagentofphysiologicalcondition(sarcoptes_scabiei,scabies).
musicianplaysinstrument(ray,piano).
agriculturalproductgrowinginstateorprovince(flowers,virginia).
itemfoundinroom(showerhead,bathroom).
competeswith(facebook,amazon_com).
arthropodandotherarthropod(shrimp,arthropods).
haswikipediaurl(brainfuck,'//en.wikipedia.org/wiki/Brainfuck').
citylocatedincountry(trakai,lithuania).
countrycurrency(lithuania,litas).
musicartistgenre(david_bowie,pop).
languageofuniversity(english,concordia_university).
directordirectedmovie(quentin_tarantino,kill_bill).
synonymfor(ministry,department).
agriculturalproductcookedwithagriculturalproduct(lentils,spices).
haswikipediaurl(steve_mandanda,'//en.wikipedia.org/wiki/Steve%20Mandanda').
haswikipediaurl(cathleen_synge_morawetz,'//en.wikipedia.org/wiki/Cathleen%20Synge%20Morawetz').
museumincity(austin_museum_of_art,austin).
musicianinmusicartist(michael_jackson,jackson_five).
itemfoundinroom(cook_top,kitchen).
attractionofcity(key_arena,seattle).
airportincity(san_francisco_international,san_francisco).
musicartistgenre(public_enemy,rap).
newspaperincity(philadelphia_enquirer,philadelphia).
animalistypeofanimal(dogs,indoor_pets).
sportusesequipment(soccer,net).
citycapitalofcountry(doha,qatar).
buildinglocatedincity(louvre,paris).
bookwriter(invisible_man,ralph_ellison).
haswikipediaurl(spreadsheet,'//en.wikipedia.org/wiki/Spreadsheet').
athleteplayssport(matt_hasselbeck,football).
drugpossiblytreatsphysiologicalcondition(zofran,nausea).
sporthassportsteamposition(football,tackle).
professionistypeofprofession(physicians,staff).
politicianusholdsoffice(barack_obama_s,president).
streetincity(peachtree_street,atlanta).
statehascapital(ohio,columbus).
agriculturalproductincludingagriculturalproduct(crops,wheat).
languageofuniversity(english,kansas_state).
furniturefoundinroom(bed,one_bedroom_cottages).
bakedgoodservedwithbeverage(whole_grain_bread,salad).
citylocatedinstate(seattle,washington).
airportincity(denver_international,denver).
agriculturalproductcamefromcountry(flowers,denmark).
agriculturalproductcookedwithagriculturalproduct(pepper,basil).
personhascitizenship(alexander_the_great,macedonia).
mlareaexpert(neural_networks,tom_mitchell).
astronautssuchasaustronauts(american_astronauts,neil_armstrong).
astronautssuchasaustronauts(notable_astronauts,neil_armstrong).
haswikipediaurl(steven_armstrong,'//en.wikipedia.org/wiki/Steven%20Armstrong').
haswikipediaurl(otakon,'//en.wikipedia.org/wiki/Otakon').
haswikipediaurl(tekkoshocon,'//en.wikipedia.org/wiki/Tekkoshocon').
haswikipediaurl(philcon,'//en.wikipedia.org/wiki/Philcon').
animaleatfood(sheep,vegetation).
animaleatfood(grizzly_bears,vegetation).
animaleatfood(bears,vegetation).
academicfieldsuchasacademicfield(biology,genomics).
clothingtogowithclothing(trousers,tie).
bakedgoodservedwithbeverage(chocolate_chip_cookies,chocolate).
statehascapital(kansas,topeka).
hasofficeincity(ryanair,glasgow).
haswikipediaurl(australasian_meat_industry_employees_union,'//en.wikipedia.org/wiki/Australasian%20Meat%20Industry%20Employees%20Union').
sportschoolincountry(badminton,england).
teamplayssport(ohio_state_university,basketball).
acquired(apple,next).
agentcontributedtocreativework(alexandre_dumas,the_count_of_monte_cristo).
sportsgamewinner(eastern_conference,celtics).
haswikipediaurl(anarcho_syndicalism,'//en.wikipedia.org/wiki/Anarcho%2Dsyndicalism').
sportschoolincountry(ju_jitsu,japan).
politicianusendorsedbypoliticianus(richard_nixon,john_f__kennedy).
organizationhiredperson(scottrade,rodger_o__riney).
producesproduct(ford,car).
productinstanceof(accord,car).
bookwriter(catcher_in_the_rye,j_d__salinger).
musicartistgenre(watain,metal).
bakedgoodservedwithbeverage(cookie,cream).
acquired(hp,mercury).
agentcontributedtocreativework(emma_donoghue,hood).
academicfieldsuchasacademicfield(science,aeronautics).
haswife(andrew_upton,cate_blanchett).
ismultipleof(herds,giraffe).
automakerproducesmodel(ford,ford_taurus).
musicianplaysinstrument(lang_lang,piano).
teamplaysincity(atlanta_thrashers,atlanta).
bookwriter(fever_pitch,nick_hornby).
actorstarredinmovie(samuel_l__jackson,pulp_fiction).
actorstarredinmovie(bruce_willis,pulp_fiction).
actorstarredinmovie(uma_thurman,pulp_fiction).
directordirectedmovie(quentin_tarantino,inglourious_basterds).
automakerproducesmodel(chevrolet,caprice).
academicprogramatuniversity(management,college).
companyeconomicsector(ne,insurance).
museumincity(carnegie_museum_of_art,pittsburgh).
competeswith(linkedin,myspace).
politicianrepresentslocation(theodore_roosevelt,states).
statehascapital(uruguay,montevideo).
sportusesequipment(soccer,shin_guards).
politicianusholdsoffice(barack,united_states_presidency).
musicartistgenre(radiohead,british_rock).
agriculturalproductcomingfromvertebrate(milk,livestock).
producesproduct(honda,prelude).
productinstanceof(prelude,car).
citycapitalofcountry(amman,hashemite_kingdom_of_jordan).
ismultipleof(herds,impala).
statehascapital(nevada,carson_city).
musicianinmusicartist(ron_wood,rolling_stones).
personbelongstoorganization(mick_jagger,rolling_stones).
musicartistgenre(rolling_stones,classic_rock).
musicartistgenre(rolling_stones,rock).
musicartistgenre(rolling_stones,british_rock).
musicartistgenre(rolling_stones,pop).
personhasjobposition(czeslaw_milosz,poet).
animaleatfood(birds,juicy_berries).
athletebeatathlete(serena_williams,venus_williams).
animalsuchasinvertebrate(invertebrates,clams).
journalistwritesforpublication(peter_jennings,abc).
sportusesequipment(soccer,goal).
agriculturalproductcamefromcountry(coffee,ethiopia).
haswife(barack_obama,michelle_obama).
musicartistgenre(ozzy_osbourne,rock).
airportincity(washington_dulles,washington).
sportsgamesport(n2003_world_series,baseball).
furniturefoundinroom(beds,one_room_cabin).
restaurantincity(fix,las_cruces).
haswikipediaurl(donald_f__towsley,'//en.wikipedia.org/wiki/Don%20Towsley').
haswikipediaurl(indoor_soccer,'//en.wikipedia.org/wiki/Indoor%20soccer').
organizationacronymhasname(usmc,marine_corps).
hashusband(katie,tom_cruise).
bookwriter(great_gatsby,fitzgerald).
restaurantincity(restaurant_toqu_,montreal).
bookwriter(harry_potter,j_k__rowling).
bookwriter(mere_christianity,c__s__lewis).
buildingbelongstoorganization(wean_hall,cmu).
timeofbombing(april_14,n70_killed_in_nigeria_bus_blasts).
locationofearthquake(taiwan,magnitude_5_4_earthquake_hits_north_taiwan).
bookwriter(the_great_gatsby,f_scott_fitzgerald).
bookwriter(the_great_gatsby,f__scott_fitzgerald).
bookwriter(the_great_gatsby,f___scott_fitzgerald).
hashusband(jolie,brad_pitt).
bookwriter(cat_s_cradle,kurt_vonnegut).
statehascapital(manitoba,winnipeg).
agentcontributedtocreativework(ayn_rand,anthem).
bookwriter(atlas_shrugged,ayn_rand).
bookwriter(fountainhead,ayn_rand).
bookwriter(the_fountainhead,ayn_rand).
persondiedatage(elvis_presley,42).
academicprogramatuniversity(engineering,lehigh).
academicprogramatuniversity(engineering,princeton).
timeofprotest(night,kiev_protesters_attack_building_with_police_inside).
damagedinearthquake(houses,n2000_nicaragua_earthquake).
damagedinbombing(houses,n1327689011).
streetincity(piedmont_road,atlanta).
hasfamilymember(joseph,jesus).
moviessuchasmovies(action_movies,die_hard).
moviessuchasmovies(action_movies,godzilla).
moviessuchasmovies(action_movies,the_karate_kid).
sportusesequipment(table_tennis,balls).
sportusesequipment(table_tennis,rackets).
sportusesequipment(table_tennis,ball).
haswikipediaurl(epee,'//en.wikipedia.org/wiki/%C3%89p%C3%A9e').
academicfieldconcernssubject(mathematics,proofs).
personinacademicfield(blaise_pascal,mathematics).
academicfieldsuchasacademicfield(mathematics,geometry).
riveremptiesintoriver(ganges,bay_of_bengal).
cityliesonriver(varanasi,ganges).
cityliesonriver(bangladesh,ganges).
cityliesonriver(calcutta,ganges).
mountainatgeopoliticallocation(mount_logan,north_america).
agentcontributedtocreativework(lord,commandments).
bookwriter(anna_karenina,tolstoy).
bookwriter(anna_karenina,leo_tolstoy).
agentparticipatedinevent(team,championship).
televisionshowssuchastelevisionshows(televisionshows,anne_of_green_gables).
agentcontributedtocreativework(sophocles,oedipus).
bookwriter(oedipus,sophocles).
riveremptiesintoriver(illinois_river,mississippi_river).
riveremptiesintoriver(missouri_river,mississippi_river).
countryalsoknownas(republic,argentina).
citylocatedincountry(ushuaia,argentina).
citylocatedincountry(el_calafate,argentina).
countryisthehomeofsportsteam(brazil,corinthians).
agentparticipatedinevent(eagles,games).
sportschoolincountry(skiing,china).
thinghascolor(chocolate,brown).
sportusesstadium(football,heinz_field).
bookwriter(great_gatsby,f__scott_fitzgerald).
citycapitalofcountry(budapest,hungary).
sportfansincountry(soccer,__france).
bookwriter(screwtape_letters,lewis).
academicfieldconcernssubject(sociology,behavior).
sportfansincountry(rugby,__france).
countrycurrency(u_s_a_,dollars).
buildinglocatedincity(detroit_metro,detroit).
airportincity(detroit_metro,detroit).
citylocatedinstate(st_charles,illinois).
bookwriter(blackwood_farm,anne_rice).
writerwasbornincity(voltaire,paris).
academicprogramatuniversity(political_science,ohio_state).
academicprogramatuniversity(medicine,ohio_state).
bookwriter(tender_is_the_night,f__scott_fitzgerald).
countrycurrency(great_britain,pounds).
airportincity(lax,la).
teamplaysincity(hawks,atlanta).
academicprogramatuniversity(fine_arts,ohio_state).
sportfansincountry(soccer,brazil).
academicprogramatuniversity(arts,ohio_state).
statehascapital(iowa,des_moines).
haswikipediaurl(all_the_things_you_are,'//en.wikipedia.org/wiki/All%20the%20Things%20You%20Are').
haswikipediaurl(angus_l__macdonald_bridge,'//en.wikipedia.org/wiki/Angus%20L%2E%20Macdonald%20Bridge').
locationofbombing(beirut,beirut_bombing__thurs__blast_in_hezbollah_run_area_of_beirut_claimed_5_lives).
bookwriter(tractatus_logico_philosophicus,ludwig_wittgenstein).
citylocatedinstate(white_pigeon,michigan).
languageofuniversity(english,barnard_college).
languageschoolincity(english_language,san_francisco).
languageofuniversity(english,georgia_state).
languageofcountry(french,__france).
academicprogramatuniversity(education,memorial_university).
languageofuniversity(latin,harvard).
languageofuniversity(english,miami_university).
languageschoolincity(russian_language,moscow).
academicfieldconcernssubject(astronomy,stars).
academicfieldhassubfield(astronomy,observational_astronomy).
academicfieldhassubfield(astronomy,theoretical_astromony).
countriessuchascountries(countries,brazil).
museumincity(the_andy_warhol_museum,pittsburgh).
citylocatedinstate(anchorage,alaska).
airportincity(louis_armstrong_new_orleans_international_airport,new_orleans).
statehascapital(nebraska,lincoln).
statehascapital(bc,victoria).
agentcontributedtocreativework(stanley_kubrick,the_shining).
bookwriter(sherlock_holmes,arthur_conan_doyle).
bookwriter(sherlock_holmes,sir_arthur_conan_doyle).
citycapitalofcountry(paris,__france).
thinghascolor(ocean,blue).
haswikipediaurl(david_miscavige,'//en.wikipedia.org/wiki/David%20Miscavige').
buildinglocatedincity(bolshoi_theatre,moscow).
bookwriter(and_then_there_were_none,agatha_christie).
citylocatedingeopoliticallocation(krakow,poland).
emotionassociatedwithdisease(sleep,condition).
animalistypeofanimal(pigs,animals).
thinghascolor(foliage,maroon).
sportsgamedate(all_star_game,n2006).
videogamessuchasvideogames(action_games,assassin_s_creed_2).
videogamessuchasvideogames(action_games,dynasty_warriors_6).
sportsgameteam(series,falcons).
sportsgameteam(match,brazil).
sportsgameteam(match,man_united).
emotionassociatedwithdisease(nausea,symptoms).
sportsgamesport(n2004_world_series,baseball).
haswikipediaurl(sierra_del_tontal_chinchilla_rat,'//en.wikipedia.org/wiki/Sierra%20del%20Tontal%20Chinchilla%20Rat').
sportsgameteam(finals,blackhawks).
videogamessuchasvideogames(rts_games,age_of_empires_2).
animaldevelopdisease(children,terminal_illnesses).
haswikipediaurl(armored_core_2,'//en.wikipedia.org/wiki/Armored%20Core%202').
emotionassociatedwithdisease(anger,disorders).
emotionassociatedwithdisease(anger,symptoms).
agriculturalproductcomingfromvertebrate(cattle,herds).
animaleatvegetable(cattle,corn).
animalistypeofanimal(cattle,ruminants).
haswikipediaurl(doom_4,'//en.wikipedia.org/wiki/Doom%204').
haswikipediaurl(mario_kart_64,'//en.wikipedia.org/wiki/Mario%20Kart%2064').
haswikipediaurl(boreal_toad,'//en.wikipedia.org/wiki/Boreal%20Toad').
animalistypeofanimal(bowhead_whales,marine_mammals).
hobbiessuchashobbies(hobbies,horse_riding).
sportsgamewinner(n1998_world_series,yankees).
sportsgamesport(n2003_british_open,golf).
emotionassociatedwithdisease(irritability,disorder).
hobbiessuchashobbies(hobbies,racquetball).
sportsgamewinner(n2009_world_series,yankees).
sportsgamesport(n1966_world_series,baseball).
sportsgamewinner(world_cup,brazil).
animalistypeofanimal(sperm_whales,cetaceans).
bacteriaisthecausativeagentofphysiologicalcondition(tb,infections).
thinghascolor(sky,blue).
plantincludeplant(trees,apple_trees).
plantincludeplant(trees,evergreens).
plantincludeplant(trees,fir).
sportsgamewinner(n1962_world_series,yankees).
sportsgamesport(n1995_world_series,baseball).
personwrittenaboutinpublication(steven,the_new_york_times).
aquariumincity(new_england_aquarium,boston).
animalistypeofanimal(black_widow,spider).
fishservedwithfood(bass,sauce).
fishservedwithfood(salmon,cream_cheese).
fishservedwithfood(swordfish,butter).
fishservedwithfood(trout,chips).
fishservedwithfood(trout,salsa).
haswikipediaurl(moxico,'//en.wikipedia.org/wiki/Moxico%20Province').
animaleatvegetable(pigs,corn).
academicprogramatuniversity(journalism,stanford).
attackerinbombing(unknown,aleppo_university_bombings).
damagedinbombing(aleppo_university,aleppo_university_bombings).
animalpreyson(hornets,insects).
teamplayssport(san_francisco_49ers,football).
airportincity(george_bush_intercontinental,houston).
organizationhiredperson(kansas,self).
mammaleatsinsect(aardvark,ant).
mammaleatsinsect(aardvark,termite).
sportsgamesport(n1958_world_series,baseball).
sportfansincountry(squash,new_zealand).
citycapitalofcountry(ankara,turkey).
citylocatedincountry(ankara,turkey).
plantincludeplant(trees,horse_chestnut).
sportschoolincountry(golf,england).
countriessuchascountries(countries,israel).
hobbiessuchashobbies(hobbies,bicycling).
haswikipediaurl(zoea,'//en.wikipedia.org/wiki/Crustacean%20larvae').
animalistypeofanimal(dragons,beasts).
agentcontributedtocreativework(h__g__wells,the_island_of_doctor_moreau).
cityalsoknownas(st_louis,st__louis).
colorassociatedwithvisualizableattribute(blue,cloud).
colorassociatedwithvisualizableattribute(blue,flesh).
timeofearthquake(n5_18,big_earthquake_shakes_tokyo__17_injured).
epicenterofearthquake(izu_oshima_island_southwest,big_earthquake_shakes_tokyo__17_injured).
magnitudeofearthquaque(n5_8,big_earthquake_shakes_tokyo__17_injured).
victiminearthquake(n17_people,big_earthquake_shakes_tokyo__17_injured).
musicianinmusicartist(paul,the_beatles).
haswikipediaurl(hard_house,'//en.wikipedia.org/wiki/UK%20hard%20house').
numberofkilledinbombing(three,three_killed_in_lebanese_suicide_bombing).
drugpossiblytreatsphysiologicalcondition(aspirin,headache).
chemicalistypeofchemical(acetic_acid,acid).
numberofcasualtiesinroadaccident(n1,chappaquiddick_incident).
numberofcasualtiesinearthquake(n15981,n2011_t_hoku_earthquake_and_tsunami).
explosivesinbombing(missiles,aleppo_university_bombings).
numberofinjuredinbombing(n160,aleppo_university_bombings).
chemicalistypeofchemical(hexane,carbon).
numberofinjuredinbombing(n70,bomb_kills_20_at_pakistan_vegetable_market).
animalsuchasinvertebrate(molluscs,snails).
statehascapital(nm,albuquerque).
synonymfor(committees,boards).
competeswith(fox,times).
jobpositionusesacademicfield(licensed_doctor,medicine).
haswikipediaurl(cricket_at_the_olympics,'//en.wikipedia.org/wiki/Cricket%20at%20the%201900%20Summer%20Olympics').
agriculturalproductincludingagriculturalproduct(crops,soybeans).
bakedgoodservedwithbeverage(dinner,tea).
softwareisprogrammedinprogramminglanguage(rtext,java).
softwareisprogrammedinprogramminglanguage(bioclipse,java).
softwareisprogrammedinprogramminglanguage(opera_mini,java).
organizationacronymhasname(darpa,defense_advanced_research_projects_agency).
agentcontributedtocreativework(yahweh,commandments).
bakedgoodservedwithbeverage(breakfast,milk).
haswikipediaurl(plymouth_cambridge,'//en.wikipedia.org/wiki/Plymouth%20Cambridge').
clothingtogowithclothing(blouse,sweater).
clothingtogowithclothing(gloves,sweater).
clothingtogowithclothing(hat,sweater).
clothingtogowithclothing(jeans,sweater).
agentcontributedtocreativework(c__s__lewis,the_chronicles_of_narnia).
actorofprotest(civilians,anti_austerity_movement).
locationofprotest(europe,anti_austerity_movement).
actorstarredinmovie(jamie_foxx,collateral).
agentcontributedtocreativework(chaim_potok,my_name_is_asher_lev).
athleteplaysforteam(miroslav_klose,germany).
productinstanceof(old_spice,deodorant).
itemfoundinroom(corner_shower,bathroom).
actorsuchasactor(talented_actors,tobey_maguire).
directordirectedmovie(kenneth_branagh,hamlet).
actorstarredinmovie(frances_mcdormand,fargo).
politicsgroupconcernsissue(planned_parenthood,abortion).
agriculturalproductcamefromcountry(tea,hong_kong).
agriculturalproductcomingfromvertebrate(dairy,cow).
meatcomesfromanimal(beef,cow).
musclelocatedinbodypart(biceps,upper_arm).
itemfoundinroom(bed,lounge).
haswikipediaurl(belgian_grand_prix,'//en.wikipedia.org/wiki/Belgian%20Grand%20Prix').
fatherofperson(zeus,athene).
athletecanbethesameasactor(bob_uecker,bob_uecker).
directordirectedmovie(alfred_hitchcock,notorious).
actorstarredinmovie(brad_pitt,fight_club).
haswikipediaurl(election_of_1852,'//en.wikipedia.org/wiki/United%20States%20presidential%20election,%201852').
drugpossiblytreatsphysiologicalcondition(advil,headache).
drugpossiblytreatsphysiologicalcondition(tylenol,headache).
directordirectedmovie(tim_burton,charlie_and_the_chocolate_factory).
musicianinmusicartist(jimmy_page,zep).
jobpositionusesacademicfield(cryptoanalyist,mathematics).
persondiedatage(pope_john_paul_ii,84).
meetingeventtitleinbuilding(optimizing_password_composition_policies,gates_and_hillman_centers).
aquariumincity(cameron_park_zoo,waco).
aquariumincity(national_aquarium__baltimore,baltimore).
zooincity(calgery_zoo,calgery).
haswikipediaurl(asian_cycling_championships,'//en.wikipedia.org/wiki/Asian%20Cycling%20Championships').
itemfoundinroom(vanity,master).
hasspouse(barack_obama,michelle_obama).
hasspouse(actress_nicole_kidman,keith_urban).
itemfoundinroom(bed,guestrooms).
itemfoundinroom(bed,accessible_rooms).
itemfoundinroom(bed,accommodations).
itemfoundinroom(bed,air_conditioned_bedrooms).
itemfoundinroom(bed,air_conditioned_room).
itemfoundinroom(bed,den).
directordirectedmovie(alfred_hitchcock,north_by_northwest).
agriculturalproductcamefromcountry(flowers,korea).
itemfoundinroom(bed,master_suite).
itemfoundinroom(bed,master_bedroom).
professionistypeofprofession(local_doctors,professionals).
zooincity(belfast_zoo,belfast).
injuredinbombing(n35_people,car_bomb_hits_shiite_suburb_of_beirut__killing_2).
attackerinbombing(al_nusra_front,car_bomb_hits_shiite_suburb_of_beirut__killing_2).
musicianplaysinstrument(yngwie_malmsteen,guitar).
hasspouse(president,laura_bush).
personbelongstoorganization(president,house).
personchargedwithcrime(president,crimes).
personchargedwithcrime(president,war_crimes).
personhasjobposition(beaverbrook,lord).
writerwasbornincity(fitzgerald,boston).
personhasreligion(abdul_jalil_jan,islam).
visualartistartform(ansel_adams,prints).
motherofperson(mary,christ_child).
politicianusholdsoffice(john_mccain,united_states_senator).
hasspouse(sue,brian).
politicianusendorsedbypoliticianus(president_elect_barack,clinton).
companyproducesvideogamesystem(sega,dreamcast).
topmemberoforganization(alfred_p__sloan,gm).
personbelongstoorganization(obama,house).
personbirthdate(obama,n1961).
persongraduatedfromuniversity(obama,harvard).
ceoof(elon_musk,tesla).
hashusband(kidman,keith_urban).
commentatorofbombing(lebanese_red_cross,car_bomb_hits_shiite_suburb_of_beirut__killing_2).
politicianusendorsedbypoliticianus(george_w,bush).
motherofperson(mary,child_jesus).
agriculturalproductcamefromcountry(green_tea,china).
newpaperhaswebsite(la_times,www_latimes_com).
agenthaswebsite(youtube,youtubecom).
clothingtogowithclothing(tie,blue_suit).
politicianusendorsedbypoliticianus(president_ronald_reagan,bush).
parentofperson(blessed_virgin_mary,jesus).
personhasage(levi_johnston,18).
commentatorofbombing(barack_obama,boston_marathon_bombings).
fatherofperson(barack_obama,malia).
motherofperson(michelle_obama,malia).
musclelocatedinbodypart(gastrocnemius,calf).
musclelocatedinbodypart(calf,leg).
musclelocatedinbodypart(calf,lower_leg).
haswikipediaurl(libertarian_party_of_maine,'//en.wikipedia.org/wiki/Libertarian%20Party%20of%20Maine').
haswikipediaurl(siege_of_mount_hiei,'//en.wikipedia.org/wiki/Siege%20of%20Mount%20Hiei').
persondeathdate(franklin_d___roosevelt,n1945).
itemfoundinroom(bed,rooms).
motherofperson(mary,lord_jesus).
visualartistartform(raphael,pictures).
bakedgoodservedwithbeverage(cookies,dozen_chocolate).
agriculturalproductcomingfromvertebrate(eggs,young_hens).
visualartistartmovement(vincent_van_gogh,impressionism).
furniturefoundinroom(bed,rooms).
clothingtogowithclothing(blue_suit,tie).
furniturefoundinroom(bed,decor).
agriculturalproductcookedwithagriculturalproduct(oil,mashed_potatoes).
visualartistartmovement(vincent_van_gogh,postimpressionism).
clothingtogowithclothing(starched_white_shirt,tie).
eventdate(hurricane_agnes,june_1972).
criminalarrestedincountry(fernandinho_beira_mar,brazil).
criminalarrestedincountry(jose_do_telhado,portugal).
foodcancausedisease(beer,blood_pressure).
furniturefoundinroom(bed,suites).
itemfoundinroom(bed,suite).
beveragecontainsprotein(squash,ingredients).
objectfoundinscene(telescope,observatory).
producesproduct(activision,guitar_hero).
automakerproducesmodel(kia,optima).
hasofficeincity(ryanair,birmingham).
personhasjobposition(jesus,lord).
leaguestadiums(mlb,citi_field).
companyeconomicsector(chase,investment).
musicartistgenre(bob_marley,reggae).
musicartistgenre(beatles,classic_pop).
musicartistgenre(beatles,pop).
musicartistgenre(beatles,rock).
musicartistgenre(beatles,classic_rock).
hasofficeincity(cctv,beijing).
hasfamilymember(jesus,mary).
companyalsoknownas(konica_minolta,konica_minolta_holding_inc).
personhasresidenceingeopoliticallocation(sarah,alaska).
musicartistgenre(daft_punk,electronica).
leaguestadiums(nascar,indianapolis_raceway_park).
producesproduct(hyundai,hyundai_accent).
haswife(jay_z,beyonce).
musicartistgenre(michael_jackson,pop).
agriculturalproductcamefromcountry(silk,china).
automobilemakercardealersinstateorprovince(dodge,massachusetts).
directordirectedmovie(martin_scorsese,the_departed).
directordirectedmovie(sylvester_stallone,rambo).
politicianusendorsedbypoliticianus(sarah_palin,bush).
producesproduct(subaru,subaru_impreza).
musicianinmusicartist(george_harrison,the_beatles).
musicianplaysinstrument(george_harrison,guitar).
actorstarredinmovie(bruce_willis,die_hard).
actorstarredinmovie(bruce_willis,armageddon).
haswikipediaurl(ashanti_mythology,'//en.wikipedia.org/wiki/Ashanti%20mythology').
musicianplaysinstrument(steve_vai,guitar).
producesproduct(dodge,dodge_ram).
haswikipediaurl(audi_r8,'//en.wikipedia.org/wiki/Audi%20R8%20(road%20car)').
productproducedincountry(computers,china).
attackerinbombing(female_suicide_bomber,n16_killed_in_suicide_bombing_in_russia_s_south).
motherofperson(mary,infant).
animalistypeofanimal(shellfish,creatures).
ceoof(franklin_raines,fannie_mae).
televisionstationaffiliatedwith(wncf_tv,abc).
istallerthan(life,immigrants).
automobilemakercardealersinstateorprovince(mitsubishi,virginia).
politicianrepresentslocation(kennedy,american).
companyeconomicsector(goldman,investment).
bankchiefexecutiveceo(goldman,lloyd_blankfein).
automobilemakerdealersincity(nissan,indianapolis).
astronautwasonamissionwithastronaut(neil_armstrong,buzz_aldrin).
transportationincity(bus,portland).
agriculturalproductcamefromcountry(beer,japan).
haswikipediaurl(aagenaes_syndrome,'//en.wikipedia.org/wiki/Aagenaes%20syndrome').
personleadscity(mark_l__mallory,cincinnati).
weaponssuchasweapons(several_weapons,nuclear_missile).
weaponssuchasweapons(weapon_arsenals,nuclear_missile).
organizationheadquarteredincountry(ups,usa).
fatherofperson(isaac,esau).
agriculturalproductcomingfromvertebrate(eggs,chicken).
politicianusmemberofpoliticalgroup(bill_clinton,house).
companyproducesvideogamesystem(sega,playstation).
producesproduct(nissan,n240sx).
hashusband(linda_hogan,hulk_hogan).
motherofperson(linda_hogan,nick_hogan).
personalsoknownas(linda_hogan,linda_marie_bollea).
personhasage(linda_hogan,46).
bookwriter(naked_lunch,william_burroughs).
sportfansincountry(cricket,uk).
sporthassportsteamposition(baseball,shortstop).
sporthassportsteamposition(team,shortstop).
languageschoolincity(english_language,cape_town).
animalistypeofanimal(shrimp,crustaceans).
athleteplaysforteam(chad_johnson,bengals).
agriculturalproductcamefromcountry(coffee,us).
animalsuchasinvertebrate(creatures,crustaceans).
agriculturalproductincludingagriculturalproduct(vegetable_oils,canola_oil).
aquariumincity(georgia_aquarium,atlanta).
countrylocatedingeopoliticallocation(india,asia).
haswikipediaurl(braunstone_gate_bridge,'//en.wikipedia.org/wiki/Braunstone%20Gate%20Bridge').
shoppingmallincity(west_edmonton_mall,edmonton).
citylocatedinstate(bakersfield,california).
cityliesonriver(st___petersburg,grand).
hasspouse(michelle_phillips,john002).
organizationheadquarteredinstateorprovince(ossetia,georgia).
synonymfor(republic,bolivia).
cityalsoknownas(columbia,new_brunswick).
haswikipediaurl(gamelan_outside_indonesia,'//en.wikipedia.org/wiki/Gamelan%20outside%20Indonesia').
organizationacronymhasname(dod,department_of_defense).
organizationacronymhasname(dod,defense_department).
citycapitalofcountry(kingston,jamaica).
statelocatedincountry(west_virginia,usa).
lakeinstate(lake_almanor,california).
statelocatedincountry(virginia,usa).
citylocatedinstate(corvallis,oregon).
countryalsoknownas(republic,russia).
airportincity(san_francisco_international_airport,san_francisco).
statelocatedingeopoliticallocation(states,nation).
citylocatedincountry(veracruz,mexico).
statelocatedincountry(florida,usa).
organizationacronymhasname(fhwa,federal_highway_administration).
museumincity(boston_science_museum,boston).
parkincity(lower_haight,san_francisco).
subpartof(wten,abc).
citycapitalofcountry(hamilton,bermuda).
hasspouse(heidi_klum,seal).
lakeinstate(manistee_lake,michigan).
hospitalincity(jackson_memorial,miami).
haswife(ice_t,coco).
lakeinstate(baldwin_lake,michigan).
haswikipediaurl(my_little_pony__friendship_is_magic,'//en.wikipedia.org/wiki/My%20Little%20Pony%3A%20Friendship%20Is%20Magic').
citylocatedinstate(pasadena,california).
countryalsoknownas(republic,germany).
citylocatedinstate(lawrence,massachusetts).
citylocatedingeopoliticallocation(east_setauket,new_york).
haswikipediaurl(solr,'//en.wikipedia.org/wiki/Apache%20Solr').
personhasjobposition(mother_teresa,nun).
aquariumincity(texas_state_aquarium,corpus_christi).
zooincity(taronga_zoo,sydney).
hospitalincity(abbott_northwestern_hospital,minneapolis).
countrylocatedingeopoliticallocation(the_philippines,southeast_asia).
countrycurrency(barbados,dollars).
animalistypeofanimal(animal_companions,pet).
citylocatedinstate(cleveland,ohio).
citylocatedingeopoliticallocation(arequipa,peru).
statehascapital(andhra_pradesh,hyderabad).
citylocatedinstate(stafford,virginia).
cityliesonriver(nyc_,columbia).
statehascapital(new_york,albany).
parkincity(little_italy,cleveland).
countriessuchascountries(countries,__america).
citylocatedinstate(williamsport,pennsylvania).
teamplaysagainstteam(devils,pittsburgh_penguins).
teamhomestadium(los_angeles_lakers,staples_center).
citylocatedincountry(buenos_aires,argentina).
airportincity(sfo,san_francisco).
agentparticipatedinevent(first_place,standings).
teamplaysincity(new_orleans_hornets,new_orleans).
countrycurrency(moldova,leu).
countrylocatedingeopoliticallocation(__america,countries).
statehascapital(alaska,juneau).
persondiedatage(john,2).
placeofworshippracticesreligion(westminster_abbey,christianity).
haswikipediaurl(potenza,'//en.wikipedia.org/wiki/Potenza').
buildinglocatedincity(miami_international,miami).
airportincity(miami_airport,miami).
cityliesonriver(abbeville,somme).
haswikipediaurl(arnaud_montebourg,'//en.wikipedia.org/wiki/Arnaud%20Montebourg').
statelocatedingeopoliticallocation(indiana,u_s_).
lakeinstate(hamilton_lake,indiana).
citycapitalofcountry(berlin,germany).
istallerthan(home,children).
countryalsoknownas(singapore,republic).
countryalsoknownas(republic,singapore).
countrycurrency(singapore,dollars).
hasofficeincountry(hsbc,singapore).
teamwontrophy(toronto_blue_jays,world_series).
teamplayssport(miami_university,football).
sportfansincountry(football,usa).
teamplayssport(bucs,football).
mountaininstate(mount_katahdin,maine).
haswikipediaurl(ambient_intelligence,'//en.wikipedia.org/wiki/Ambient%20intelligence').
bookwriter(a_prayer_for_owen_meany,john_irving).
bookwriter(barnaby_rudge,charles_dickens).
televisionshowisbasedonmovie(beetlejuice,beetlejuice).
bookwriter(a_confederacy_of_dunces,john_kennedy_toole).
sportsgamescore(finals,0-2).
languageofuniversity(english,new_york_university).
academicprogramatuniversity(engineering,john_hopkins_university).
academicfieldsuchasacademicfield(education,arts).
sportsgamedate(n2006_world_series,october_2006).
hobbiessuchashobbies(activities,fishing).
hobbiessuchashobbies(hobbies,fishing).
hobbiessuchashobbies(pastimes,fishing).
hobbiessuchashobbies(recreational_activities,fishing).
languageofcountry(english,the_united_kingdom).
sportsgamesport(n1939_world_series,baseball).
sportsgamesport(n1984_world_series,baseball).
sportsgamewinner(n2006_world_cup,italy).
haswikipediaurl(kindness,'//en.wikipedia.org/wiki/Kindness').
sportschoolincountry(golf,new_zealand).
sportschoolincountry(ski,germany).
sportsgamesport(alcs,baseball).
languageofuniversity(english,luther_college).
languageofuniversity(latin,indiana_university).
sportsgamesport(n1918_world_series,baseball).
organizationheadquarteredincity(kalw,san_francisco).
sportsgamescore(season_opener,0-1).
sportschoolincountry(football,britain).
sportschoolincountry(football,turkey).
hobbiessuchashobbies(summer_activities,fishing).
sportsgamesport(first_world_series,baseball).
bookwriter(redwall,brian_jacques).
drughassideeffect(sorafenib,side_effects).
languageofuniversity(french,la_sorbonne).
languageschoolincity(latin,jerusalem).
awardtrophytournamentisthechampionshipgameofthenationalsport(medals,gymnastics).
sportusesequipment(handball,ball).
sportusesequipment(ice_hockey,skates).
sportfansincountry(ice_hockey,__america).
languageofuniversity(spanish,california_state_university).
languageofuniversity(english,manchester_metropolitan_university).
bookwriter(a_study_in_scarlet,arthur_conan_doyle).
bookwriter(eldest,christopher_paolini).
languageofuniversity(english,tufts).
hobbiessuchashobbies(activities,hiking).
hobbiessuchashobbies(activities,skiing).
hobbiessuchashobbies(activities,golfing).
plantrepresentemotion(roses,deep_love).
haswikipediaurl(how_to_read_a_book,'//en.wikipedia.org/wiki/How%20to%20Read%20a%20Book').
sportusesequipment(outdoor_sports,football).
bookwriter(the_colour_of_magic,terry_pratchett).
bookwriter(against_the_day,thomas_pynchon).
bookwriter(a_christmas_carol,charles_dickens).
bookwriter(a_tale_of_two_cities,charles_dickens).
bookwriter(christmas_carol,charles_dickens).
sportfansincountry(rugby,england).
languageofuniversity(english,stanford_university).
hobbiessuchashobbies(adventure_activities,rafting).
academicfieldsuchasacademicfield(art,literature).
academicfieldsuchasacademicfield(art,graphic_design).
academicprogramatuniversity(art,college).
academicfieldconcernssubject(history,the_past).
academicfieldhassubfield(history,cultural_history).
academicfieldhassubfield(history,military_history).
academicfieldsuchasacademicfield(biology,environment).
politicsbillconcernsissue(climate_stewardship_act,environment).
mountaininstate(mount_davis,pennsylvania).
languageofuniversity(english,american_university).
animalpreyson(leopards,animals).
animalistypeofanimal(whales,sea_mammals).
amphibiansuchasamphibian(salamanders,california_tiger_salamander).
animaldevelopdisease(children,life_limiting_illness).
animalsuchasinvertebrate(marine_life,clams).
animalistypeofanimal(calves,animals).
animalistypeofanimal(dog,pet).
animalistypeofanimal(bulls,pets).
haswikipediaurl(canadian_football,'//en.wikipedia.org/wiki/Canadian%20football').
emotionassociatedwithdisease(sadness,symptoms).
emotionassociatedwithdisease(sadness,depression).
emotionassociatedwithdisease(sadness,disorder).
haswikipediaurl(latent_semantic_analysis,'//en.wikipedia.org/wiki/Latent%20semantic%20analysis').
languageofcountry(portugese,brazil).
languageofcity(german,oberwesel).
sportsgamesport(n1998_world_series,baseball).
bacteriaisthecausativeagentofphysiologicalcondition(mycobacterium,mycobacterium_tuberculosis).
animalpreyson(arthropods,ticks).
animalsuchasinsect(mollusks,invertebrates).
animalistypeofanimal(koalas,animals).
animalistypeofanimal(snakes,vertebrates).
languageofcity(spanish,madrid).
languageofcountry(spanish,costa_rica).
languageofcountry(spanish,el_salvador).
haswikipediaurl(logistic_regression,'//en.wikipedia.org/wiki/Logistic%20regression').
sportschoolincountry(tennis,__america).
animalsuchasinsect(prey,grasshoppers).
languageofcountry(hebrew_language,israel).
sportsgamewinner(bcs_national_championship_game,florida_gators).
hobbiessuchashobbies(activities,bike_riding).
academicprogramatuniversity(engineering,uc_davis).
academicprogramatuniversity(law,washington_university).
sportfansincountry(futsal,brazil).
subpartof(orange_county,california).
meetingeventtitleinbuilding(human_powered_data_management,gates___hillman_centers).
haswikipediaurl(roskilde_festival,'//en.wikipedia.org/wiki/Roskilde%20Festival').
meetingeventtitlehasspeakingperson(brain_maps_to_mechanisms__neural_circuit_molecular_architecture,stephen_j___smith).
meetingeventtitleinbuilding(brain_maps_to_mechanisms__neural_circuit_molecular_architecture,biomedical_science_tower).
meetingeventtitleatdate(brain_maps_to_mechanisms__neural_circuit_molecular_architecture,april_16__2013).
numberofcasualtiesinearthquake(n185,n2011_christchurch_earthquake).
productlauchvenue(rolls_royce_launches_ghost_series_ii,south_india).
haswikipediaurl(omnism,'//en.wikipedia.org/wiki/Omnism').
diseasecausesphysiologicalcondition(dysfunction,incontinence).
clothingtogowithclothing(sweater,t_shirt).
musicianinmusicartist(eddie_van_halen,van_halen).
hasfamilymember(jesus_christ,mary).
actorstarredinmovie(cary_grant,north_by_northwest).
personbirthdate(emile_lahoud,n1936).
musicianplaysinstrument(david,accordion).
actorstarredinmovie(arnold_schwarzeneggar,true_lies).
personhasresidenceingeopoliticallocation(arnold_schwarzeneggar,california).
actorstarredinmovie(ron_livingston,office_space).
itemfoundinroom(closet,master_bathroom).
haswife(deryck_whibley,avril_lavigne).
actorstarredinmovie(clint_eastwood,dirty_harry).
clothingtogowithclothing(white_t_shirt,jacket).
productproducedincountry(cars,germany).
aquariumincity(the_waikiki_aquarium,honolulu).
personhascitizenship(queen,the_united_kingdom).
agriculturalproductcamefromcountry(tea,the_united_kingdom).
musicianplaysinstrument(herbie_hancock,piano).
itemfoundinroom(brass_bed,master_bedroom).
weaponmadeincountry(missle,korea).
furniturefoundinroom(sofa,family).
agriculturalproductcookedwithagriculturalproduct(pepper,lime_juice).
clothingtogowithclothing(tie,black_suit).
aquariumincity(waikiki_aquarium,honolulu).
actorstarredinmovie(sigourney_weaver,alien).
politicsgroupconcernsissue(moveon_org,liberalism).
politicsgroupconcernsissue(republican_party,conservatism).
politicsgroupconcernsissue(greenpeace,environment).
politicsgroupconcernsissue(aclu,human_rights).
athletewinsawardtrophytournament(greg_norman,masters).
organizationhasofficialwebsite(wordpress,wordpress_com).
directordirectedmovie(woody_allen,annie_hall).
directordirectedmovie(alfred_hitchcock,psycho).
directordirectedmovie(alfred_hitchcock,vertigo).
directordirectedmovie(jj_abrams,star_trek).
athletewinsawardtrophytournament(tiger_woods,us_open).
athleteplayssportsteamposition(edgerrin_james,running_back).
athletebeatathlete(lindsay_davenport,serena_williams).
writerwasbornincity(luke,boston).
athleteplayssport(ian_woosnam,golf).
agentcontributedtocreativework(raymond_chandler,collected_stories).
personhasresidenceingeopoliticallocation(george_clinton,new_york).
athleteplaysinleague(stan_musial,nfl).
organizationhasofficialwebsite(youtube,youtube_com).
clothingtogowithclothing(uniform,boots).
athletewinsawardtrophytournament(novak_djokovic,us_open).
chemicalistypeofchemical(sulphur,compounds).
agriculturalproductcookedwithagriculturalproduct(oil,mussels).
motherofperson(virgin_mary,lord_jesus).
athletebeatathlete(mauresmo,williams).
visualartistartform(brancusi,sculptures).
personbirthdate(rembrandt,n1606).
hasspouse(rebecca,isaac).
celebritysuchascelebrity(cultural_icons,deepak_chopra).
personalsoknownas(the_donald,donald_trump).
journalistwritesforpublication(greta_van_susteren,fox).
journalistwritesforpublication(joe_mcguff,kansas_city_star).
agriculturalproductcookedwithagriculturalproduct(mango,salt).
athleteplayssport(brock_lesnar,wrestling).
athleteplayssport(big_show,wrestling).
athleteplayssport(bret_hart,wrestling).
athleteplayssport(jeff_hardy,wrestling).
politicianusholdsoffice(george_w__bush,governor).
personwrittenaboutinpublication(barack_obama,economist).
musicianplaysinstrument(jimi_hendrix,guitar).
meatcomesfromanimal(pork_belly,pig).
agentparticipatedinevent(driver,championship).
musicianplaysinstrument(buddy_guy,guitar).
musicianplaysinstrument(john,accordion).
directordirectedmovie(julie_taymor,frida).
agentcontributedtocreativework(jk_rowling,harry_potter_and_the_chamber_of_secrets).
personleadscity(mahmoud_ahmadinejad,tehran).
haswikipediaurl(bridges_academy,'//en.wikipedia.org/wiki/Bridges%20Academy').
persondeathdate(fdr,n1945).
persongraduatedfromuniversity(obama,law_school).
personbirthdate(randall_forsberg,n1943).
haswikipediaurl(david_gandy,'//en.wikipedia.org/wiki/David%20Gandy').
ceoof(satoru_iwata,nintendo).
ceoof(mark_zuckerberg,facebook).
organizationheadquarteredincountry(u_s__immigration_and_naturalization_service,u_s_).
ceoof(chad_hurley,youtube).
furniturefoundinroom(chairs,dinning_area).
musicianplaysinstrument(brahms,piano).
musicianplaysinstrument(chopin,piano).
chemicalistypeofchemical(nitrogen,monoxide).
athletehomestadium(ron_santo,wrigley_field).
organizationalsoknownas(fbi,federal_bureau_of_investigation).
personbornincity(hillary,york).
politicianholdsoffice(hillary,us_president).
politicianholdsoffice(hillary,member).
weaponmadeincountry(bomb,iran).
furniturefoundinroom(chairs,kitchen_area).
companyeconomicsector(enron_corp,energy).
jobpositionusesacademicfield(accountant,economics).
jobpositionusesacademicfield(doctor,surgery).
jobpositionusesacademicfield(plastic_surgeon,surgery).
jobpositionusesacademicfield(surgeon,surgery).
jobpositionusesacademicfield(physician,surgery).
coachesinleague(mike_tomlin,nfl).
actorstarredinmovie(jeff_bridges,king_kong).
musicianinmusicartist(mick_jagger,rolling_stones).
itemfoundinroom(tub,luxurious_master_suite).
itemfoundinroom(bed,luxurious_master_suite).
furniturefoundinroom(bed,luxurious_master_suite).
politicianholdsoffice(jacques_chirac,president).
automakerproducesmodel(mitsubishi,lancer).
automobilemakercardealersinstateorprovince(volvo,virginia).
fatherofperson(father_abraham,isaac).
agentcontributedtocreativework(audrey_niffenegger,the_time_traveler_s_wife).
televisionstationincity(wfor,miami).
producesproduct(toyota,toyota_avalon).
automakerproducesmodel(volkswagen,jetta).
producesproduct(nissan,n300zx).
hasofficeincity(klm_royal_dutch_airlines,amsterdam).
automobilemakerdealersincity(toyota,tucson).
automobilemakerdealersincity(honda,orlando).
leaguestadiums(nba,rose_garden).
musicartistgenre(eminem,hip_hop).
producesproduct(volkswagen,beetle).
automakerproducesmodel(toyota,toyota_sienna).
bankbankincountry(j_p__morgan,__america).
agentcontributedtocreativework(annie_proulx,the_shipping_news).
agentcontributedtocreativework(e__annie_proulx,the_shipping_news).
animalpreyson(bowhead_whales,marine_mammals).
haswikipediaurl(anachronox,'//en.wikipedia.org/wiki/Anachronox').
haswikipediaurl(virtua_fighter_animation,'//en.wikipedia.org/wiki/Virtua%20Fighter%20Animation').
haswikipediaurl(chuck_rock,'//en.wikipedia.org/wiki/Chuck%20Rock').
haswikipediaurl(colony_wars__red_sun,'//en.wikipedia.org/wiki/Colony%20Wars%3A%20Red%20Sun').
haswikipediaurl(ultima_iv,'//en.wikipedia.org/wiki/Ultima%20IV%3A%20Quest%20of%20the%20Avatar').
